### ISSUE TITLE
Minify Razor Output

### ISSUE THREAD

**Issue by nikmd23** [aspnet/Mvc#1110]
As covered by @madskristensen in [his recent blog post](http://madskristensen.net/post/effects-of-gzipping-vs-minifying-html-files), minifying HTML, in addition to GZipping, can provide significant file size reductions. 

Getting HTML to the client as quickly as possible is the first step towards a speedy experience, and #1048 provides one way to do this.

If Razor provided a configuration option to minify the HTML it was generating, we'd have another. 

[JSON.NET has a setting](http://james.newtonking.com/json/help/index.html?topic=html/T_Newtonsoft_Json_Formatting.htm) for minifying the JSON it produces. A similar switch in Razor configuration would be awesome.

Of course, there are lots of things this switch _could_ do. Here's a few things I'd expect, but this certainly isn't an exhaustive list:
1. Collapse whitespace
2. Collapse Boolean HTML attributes (e.g. `<... disabled="disabled">` → `<... disabled>`) 
3. Remove empty attributes (e.g. `<... class="">` → `<...>`) 
4. No need to remove HTML comments. Authors can use Razor comments if they don't want HTML comments to appear.
5. Remove default values. _This might be dangerous?_ (e.g. `<form method="get">` → `<form>`) 

I'd expect Razor to operate the way it does today by default, but for this to be an opt-in setting so as to not break any JavaScript that is explicitly dependent on the HTML currently generated.

---

_NOTE: [Dean Hume does have an open source .NET HTML Minifier](http://deanhume.com/home/blogpost/a-simple-html-minifier-for-asp-net/2097). But he admits to its simplicity and something better could be done._

**Comment by GuardRex** [comment]
For those who are following this issue but not the other one, you can hack up changes to the Razor `MarkupChunkGenerator` that will minify markup at compile-time: [aspnet/Razor #444](https://github.com/aspnet/Razor/issues/444#issuecomment-138828582). It's rough and I did it at 3am last night, but it seems to work ok. Something like that could be provided now (with an MVC options switch so that devs would be opting-in if they want it) even if it doesn't hit all of the edge cases, then the team could address it properly next year.

I'm still hoping this issue will be moved off the backlog. The bandwidth savings are huge; and as @DamianEdwards pointed out on yesterday's [Community Standup (9/8)](https://youtu.be/tQC7P6n3pqk?t=1700), Razor has gone through several generations now without this much-needed capability. Think of the :deciduous_tree: :palm_tree: :evergreen_tree: that can be saved by doing this now.
