### ISSUE TITLE
Parse errors in Razor need to be mapped to the cshtml file as part of diagnostics

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#1195]
Related to https://github.com/aspnet/Mvc/issues/872 - we need to be able to parse errors to diagnostic pages during runtime compilation and give enough details for hosts to interpret them during pre-compilation.

**Comment by yishaigalatzer** [comment]
@pranavkm this seems closely related to #1968

**Comment by danroth27** [comment]
@NTaylorMullen Can you please provide some details on what the work involved here is?

**Comment by NTaylorMullen** [comment]
@danroth27 I'm honestly not sure. We only map parser errors to cshtml so that's all diagnostics should be getting from Razor. Not to mention all errors are exposed as a final result of generating code via the Razor.

@pranavkm what'd you have in mind here? Is this issue that we map errors incorrectly on occasion?

**Comment by pranavkm** [comment]
This was addressed as part of #872 and works for Helios + error page middleware
![capture](https://cloud.githubusercontent.com/assets/174281/6785004/3e898b46-d140-11e4-965b-4c71a69de9ed.PNG)
