### ISSUE TITLE
Static files in MVC areas and wwwroot

### ISSUE THREAD

**Issue by kichalla** [aspnet/Mvc#1357]
Today we expect all static content to be placed under `wwwroot` folder. We have seen users developing pluggable components with MVC areas that one can install in their applications. 
These areas could be having static files within them and so this issue is to keep track onto how would they fit into the `wwwroot` system.

Example: Web API's HelpPage has a HelpPage.css file
![image](https://cloud.githubusercontent.com/assets/6559784/4638424/52a1ff00-53fa-11e4-8868-a1c393561ede.png)

**Comment by kowsheek** [comment]
Is there an update on how this is being approached (not just for areas)?

There are several things that I didn't want in my `wwwroot` folder (such as TypeScript and SCSS files). For reasons such as being compiled or processed via grunt. Also, I didn't want lib to be committed to the repo but rather installed via bower. While that's something I added to my gruntfile, other templates/generators like angular-fullstack have these features in its vanilla installation. 

Also, depending on the library, custom copy methods are needed (since bower support for that sucks). 

```` javascript
      copy: {
          scripts: {
              expand: true,
              cwd: "Scripts",
              src: ["**/*.js"],
              dest: "wwwroot/scripts/"
          },
          ionrangeslider: {
              expand: true,
              cwd: "bower_components/ionrangeslider",
              src: ["img/sprite-skin-flat.png"],
              dest: "wwwroot/lib/"
          }
      }
````

**Comment by Eilon** [comment]
Closing because we have no plans to support this. The new "ASP.NET Core Modules" concept will likely have some solution to this instead.
