### ISSUE TITLE
Need a way to specify required action parameters

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#1410]
We should have some sort of built-in action constraint to opt into required action parameters that influence action selection.

**Comment by yishaigalatzer** [comment]
@rynowak moving out to RC, ping me if you have feedback

**Comment by rynowak** [comment]
@yishaigalatzer no objection here.

**Comment by yishaigalatzer** [comment]
I believe @loudej strongly objects to have this kind of behavior because
1. It means model binding has to run before action selection (at least in some cases), webapi got around it by allowing only value providers based data (Url & Query).
2. It leads to user confusion because some parameters can work this way and some cannot.
3. Model binding should not run before authorization happens.

So I recommend won't fix for this. @danroth27 if you agree please close the issue, and if not lets talk about it.
