### ISSUE TITLE
Cleanup: Consider removing GetDefaultServices

### ISSUE THREAD

**Issue by HaoK** [aspnet/Mvc#1634]
I tried to minimize changes when making the TryAdd fixes, so I just made it internal instead of removing it.  Eventually I think most of the other repos are going to remove their GetDefaultServices and just TryAdd their services inside of AddXyz().

Identity's Add looks like this: https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNet.Identity/IdentityServiceCollectionExtensions.cs

**Comment by Eilon** [comment]
@kichalla can you take a look and see what other framework components are doing here? Do we need to make any changes in order to be consistent? BTW @davidfowl is out for ~1wk but might be on email.

**Comment by kichalla** [comment]
Sure...I am looking into it now...

**Comment by kichalla** [comment]
I found `GetDefaultServices` being used in following components:
- [EncoderServices](https://github.com/aspnet/HttpAbstractions/blob/04707ccaa00c31967208aa076a7a59aac45e3283/src/Microsoft.Framework.WebEncoders/EncoderServices.cs) used by `AddWebEncoders` extension
- [DataProtectionServices](https://github.com/aspnet/DataProtection/blob/e8cc1106d88710ce643104bb7aa6aebd4e7ceb3b/src/Microsoft.AspNet.DataProtection/DataProtectionServices.cs) used by `AddDataProtection` extension

While going through this exercise, I noticed that following extensions do not use `TryAdd` instead. We should ideally use `TryAdd` in order to prevent replacing any user registered service earlier?
- [AddCaching](https://github.com/aspnet/Caching/blob/be3f8c0befe1b557aac2f2446071662a987384e8/src/Microsoft.Framework.Caching.Distributed/CachingServicesExtensions.cs#L14)
- [AddAuthorization](https://github.com/aspnet/Security/blob/14d1b467c69dd6f836f5683b6e1545b7f3f859ee/src/Microsoft.AspNet.Authorization/ServiceCollectionExtensions.cs#L26)
- [AddCors](https://github.com/aspnet/CORS/blob/da6a4f2ab7cf75b99391a1f93dcbb161d45109d8/src/Microsoft.AspNet.Cors.Core/CorsServiceCollectionExtensions.cs#L38)

**Comment by HaoK** [comment]
Yes all of the framework AddXyz methods should be using try add. Shame on me for missing that in my own AddAuthZ hah

**Comment by HaoK** [comment]
Never mind on add auth. I looked at the code and it's not using try add because it's registering multiple policy handlers for ienumerable resolution

**Comment by kichalla** [comment]
commit 284c8992333d5eeede4bfd9b34974994606e5c8b
