### ISSUE TITLE
URL Extention mapping to media types

### ISSUE THREAD

**Issue by kulmugdha** [aspnet/Mvc#1673]
We should be able to add file extension in the URL to specify the response format, like user.json or user.html.

**Comment by danroth27** [comment]
You can use content negotiation, but the URL extension approach is convenient for adhoc testing from a browser where you can't control the Accept header and it can simplify your caching strategy (i.e. no need to mess around with the Vary header). The feature will also by default, so if you don't want it you can just leave it disabled.

**Comment by nvivo** [comment]
I completely agree with @satish860 that this will lead users to the wrong path.

I like the idea of being able to force content negotiation based on an extension if needed, but in reality most people will always publish and use their APIs with ".json" in the end because that shows the result they expect in the browser. Just look at [how Twitter publishes all APIs in their documentation with ".json"](https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline)  to compensate this rails behavior.

The idea is nice, but extension mapping to media typed + XmlFormatter by default is definitely not the pit of success.

**Comment by kulmugdha** [comment]
514460b8018ff84158196e6421652538297fa10c
