### ISSUE TITLE
Support conversions on [FromHeader]

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#1680]
Consider supporting conversion on the `[FromHeader]` binder to our built-in strongly typed headers, as well as an extensible pattern based on a `Parse(string)` method or something similar.

```
public Book UpdateBook([FromHeader] Guid transactionId, Book book)
{
}
```

When we do this, we should consider what refactoring can be done to commonize code with CollectionModelBinder. Right now there's some similar logic around selecting what kind of collection to create.

**Comment by bluemmc** [comment]
Yes, please! 
My use case is a method like the one below where "unmodifiedSince" should be passed as a DateTimeOffset. This does unfortunately not work in RC1. Works only if I change the type of unmodifiedSince to a string which is ugly.
```
[HttpPut]
public IActionResult UpdateEmployee(uint employeeId, [FromBody] Employee employee, [FromHeader(Name="If-Unmodified-Since")] DateTimeOffset unmodifiedSince)
```

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

**Comment by Yves57** [comment]
@rynowak Why is the Header binding done with a specific `IModelBinder` implementation (the class `HeaderModelBinder`) and not with a `IBindingSourceValueProvider` implementation like `QueryStringValueProvider` for example?
I tried to remove `HeaderModelBinderProvider` from the `ModelBinderProviders` list and I have added a new `HeaderValueProviderFactory` in `ValueProviderFactories`. And it seems to work fine (with type conversion!).

**Comment by Yves57** [comment]
@rynowak Found the problem with a `IBindingSourceValueProvider` implementation for the header: it concerns the collections management, because header values are stored as a single value in the header.
So when `CollectionModelBinder.BindSimpleCollection()` analyzes the values, it sees only one single value.

I tried a POF that has an additional property `ValueProviderResult.ValuesForCollection` that allows a `ValueProviderResult` to know if the value is get for simple binding or for a collection binding.

So no change in the public interfaces, and the magic 😃 :
![image](https://cloud.githubusercontent.com/assets/11701094/23822516/5f9f29f4-064e-11e7-97a1-fcb76fd8e73b.png)

I don't know if you are interested to discuss on a PR ?

**Comment by rynowak** [comment]
It's done this way because **all** value provider data is generally available for **all** model binding - unless you opt-out with a `[FromXyz]` attribute. We think the header model binder has narrow enough usage that it should be opt-in.
