### ISSUE TITLE
Constructor of StreamWriter(string path) throws compiler error

### ISSUE THREAD

**Issue by Azrann** [aspnet/Mvc#1757]
Please look at this StackOverflow question for more details and a code example on how to reproduce it.

http://stackoverflow.com/questions/27735447/vnext-argument-1-cannot-convert-from-string-to-system-io-stream

**Comment by davidfowl** [comment]
Thats because it's not available on CoreCLR

**Comment by Azrann** [comment]
Hi David

Thanks for your quick response. For future reference where can I check if a function is available or not? I am sorry I am starting with vnext and I am struggling to know where to get the references from.

Cheers,
Alberto

**Comment by davidfowl** [comment]
File issues on the https://github.com/dotnet/corefx repository. They will be able to clarify why things are missing in the new framework. I believe the reason this particular overload was removed was because of layering issues between the new packages.

The assembly that contains StreamWriter shouldn't be directly referencing FileStream:

`new StreamReader(path)` actually does new `StreamReader(new FileStream(path, options))`.
