### ISSUE TITLE
Grunt interaction with razor views (example: HTMLMIN). Is it possible ?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#1793]
Right now, (i think) we can't use ```grunt-contrib-htmlmin```  in the compilation pipeline.

Can we expect to have this kind of feature or it's already there and I'm missing something ?

**Comment by yishaigalatzer** [comment]
You can't minify the html during compilation mostly because there is no HTML generated at compilation time. We are not planning to add support for this. I have heard some folks looking into building something like that along the lines of minifying the .cshtml file upfront and modifying the view engine to serve from the minified location.

I chatted with @avanderhoorn @nikmd23 on this issue some time ago, not sure if they made any progress.

@DamianEdwards

**Comment by danroth27** [comment]
No plans to support this.

**Comment by nikmd23** [comment]
We have not made any progress on this - though I would like to see something like this implemented, somehow, someway, by someone one day. :wink:

**Comment by Bartmax** [comment]
@nikmd23 I'm sure this is not the best solution but just you said you would like to see something like this implemented somehow, this works for me at least as a start: https://github.com/Bartmax/HtmlMinifier
