### ISSUE TITLE
Cache tag helper - manually delete cache

### ISSUE THREAD

**Issue by nfplee** [aspnet/Mvc#1808]
I'd like to be able to manually remove the cache from the cache tag helper. For example I'd imagine adding an extension method to IMemoryCache which allows me to remove all cache entries which begin with a particular key. Therefore the change I'm requesting is to add a key prefix property to the cache tag helper.

**Comment by yishaigalatzer** [comment]
@nfplee since the feature is not yet in, it's probably better to just comment on the PR first

**Comment by pranavkm** [comment]
@nfplee the current API for the tag helper doesn't have a way to iterate \ remove keys by prefixes. There's an API for adding additional expiration triggers, but it requires using a helper and isn't particularly intuitive. I'll work on adding a sample to the TagHelpersSample.Web application on what usage for this looks like.

**Comment by nfplee** [comment]
@pranavkm I would remove the cache by adding an extension method to IMemoryCache such as void RemoveAll(this IMemoryCache cache, string prefix) to handle the removal of the cache. I would just like a way to set a prefix for the key that the cache tag helper would use.

By doing a prefix I could say something like:

```
<cache asp-cache-key-prefix="Widget_1" ...>...</cache>
<cache asp-cache-key-prefix="Widget_2" ...>...</cache>
```

Now I could call my extension method to delete an individual item with a prefix of "Widget_1" or the entire cache with a prefix of "Widget".

As a side note (maybe this should be another issue) but it would be great if the OutputCache / ResponseCache attribute also supported this.

**Comment by pranavkm** [comment]
@nfplee, you might want to file a work item for your requirement at - https://github.com/aspnet/Caching. That said

1) This API doesn't exist so any prefix requirement is predicated on the feature existing to start with.
2) The sample added as part of https://github.com/aspnet/Mvc/commit/6c21b40894ef93d8f97072991426a42ed324c074 demonstrates the usage of triggers to expire cached content. This API works today, so perhaps you could redesign your application to use this feature to evict items rather than prefixes.

**Comment by yishaigalatzer** [comment]
We are tracking a potential improvement to make it easier to write this type of trigger #1873

**Comment by blakepell** [comment]
If the dictionary of keys were exposed on the caching class it would be trivial to implement a delete all from cache or by pattern (I know the arguments against getting an iterator on the keys).  I posted an issue in the cache project because I can't see a way to inspect the contents of the cache for diagnostics (the MemoryCache class exposes the Count from the underlying dictionary with a comment of "for diagnostics" but nothing else).
