### ISSUE TITLE
Async IModelValidator

### ISSUE THREAD

**Issue by ThoughtHaven** [aspnet/Mvc#1884]
The Validate method on Microsoft.AspNet.Mvc.ModelBinding.IModelValidator should be ValidateAsync. Sure, validating DataAnnotations, etc. are sync. However, some validation is not.

One simple example is checking the availability of a UserName during user registration. This usually involves some query of a data store, which is clearly async work. But since the interface does not allow for this, this validation will have to be done at some different time in the pipeline. The framework comes up short in this case. Not ideal.

To validate synchronously with ValidateAsync, return Task.FromResult(errors). No problem. And if you do need to query a data store, async work is enabled.

**Comment by yishaigalatzer** [comment]
We don't think this is a common scenario enough to worry about. We have discussed this in detail and decided it is not useful enough to make the validation pipeline async considering that making one thing async is a viral change all the way up the stack from it.

For the scenario described above:
When you validate a user in views you use a remote attribute.
You can validate the business decision in the action itself rather than in a validation rule for the object.

**Comment by ThoughtHaven** [comment]
I  understand this decision and knew you would have talked about this. Unfortunately for me though, my company's core validation cannot be ported over the use Mvc's model binding now. For good reason, our model validation implementation is async all the way up our stack. And we can't provably call our async code in Mvc's sync interfaces without deadlock issues (or always enforce ConfigureAsync(false)).

So we'll need to keep throwing typed exceptions in our Mvc apps and catch them in filters. Not ideal but I do understand why the masses wouldn't need async model validation 90% of the time. Oh well.

Thanks for the reply.

**Comment by yishaigalatzer** [comment]
The good news is that filters are async so you can do the work in global action filter and not throw

-----Original Message-----
