### ISSUE TITLE
@Url.Action does not remove "index" from url

### ISSUE THREAD

**Issue by Boglen** [aspnet/Mvc#2029]
In last builds when i generate url by @Url.Action and pass default action = index, i get the following link:
\somecontroller\index\1. But \somecontroller\1 be better

**Comment by Eilon** [comment]
What routes have you defined? If the route has `{controller}` before `{id}` then if the id is required (because it's not empty), the controller is also required. This has always worked this way since the first version of routing several years ago. If you have code that reproduces this issue please reopen the issue.

**Comment by Boglen** [comment]
Let i'm try to explane the idea.
1) I have entity with controller,action, parameters fields. Controller and action is a string fields, and parameters = Dictionary&lt;string,object&gt;() {}
2) In view i have @Url.Action(item.Action, item.Controller, item.Parameters)
3) Routes:

                   routes.MapRoute(
                        name: "default",
                        template: "{controller}/{action}/{id?}",
                        defaults: new { controller = "Page", action = "Index", id = 2 },
                        constraints: new { id = @"\d+" }
                        );

                   routes.MapRoute(
                         name: "defaultWithoutAction",
                         template: "{controller}/{id?}",
                         defaults: new { action = "Index" },
                         constraints: new { id = @"\d+" }
                       );

1. In first case i have Controller = "Page", Action = "Index", Parameters = new {id = 1}.
@Url.Action generates "/Page/Index/1"

2. In second case i have Controller = "Page", Action = String.Empty, Parameters = new {id = 1}.
@Url.Action duplicate all patameters from current page

3. In the third case  i have Controller = "Page", Action = null, Parameters = new {id = 1}.
From http://localhost/Page/Index/5 site page @Url.Action generates "/Page/Index/1"
From http://localhost/Page/AwesomePage/5 @Url.Action generates "/Page/AwesomePage/1"


It would be nice if the second and third case, the helper has generated such lines:

 "/Page/1" - if we have route with default action defined.(This link works, by the way.)
"/Page/Index/1" - This result is also nice, but looks a little less beautiful.

**Comment by Eilon** [comment]
@rynowak in case he has thoughts.

I still think this is by design because there is a valid way to generate a URL for the first route. The "ambient values" of the current URL and matching route are factors in determining which URL to generate. You can use named routes to use a specific route when generating a URL and that avoids the linear matching algorithm whereby the system tries to match each route in order.

**Comment by rynowak** [comment]
:100: what @Eilon said. The "ambient values" are part of the system - they always apply. 

Fortunately, all of this is highly tuneable, you can get the results your want with a little more work.

1). You can change the order of your routes. It sounds like you prefer `{controller}/{id}` over `{controller}/{action}/{id}`. So then consider adding `{controller}/{id}` first so it's tried first. Anything that can't match/link with `{controller}/{id}` will fall back to your other routes.

Just be aware if you do this that the constraint on `id` is important.

2). You can use named routes. That would look like: `@Url.RouteUrl("defaultWithoutAction", new { controller = "Page", action = "Index" });` Using named routes will go directly to the route with that name instead of trying them in order.

If you end up using this heavily you could define your own extension methods for `IUrlHelper` that keep it DRY.

3). You can just use attribute routes. If you want to really fine-tune the routing experience for your app then this is the most straightforward way.

If you don't like using attributes directly in your code, you can also write a convention to apply routes to your actions and controllers using any logic you want. https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.CustomRoutingConvention
