### ISSUE TITLE
Mark IControllerFactory methods in DefaultControllerFactory as virtual

### ISSUE THREAD

**Issue by milutinovici** [aspnet/Mvc#2095]
Methods I'm referring to are CreateController and ReleaseController. These extension points are sorely needed.

**Comment by kichalla** [comment]
@milutinovici : I am going to work on fixing this but was curious to know what are the scenarios where you needed this?

**Comment by milutinovici** [comment]
Well, this class was one of several I had to modify, to enable generic controllers.

**Comment by rynowak** [comment]
@milutinovici sounds cool! We'd love to see examples if you get it working. Please keep the feedback coming if you run into more issues.

**Comment by milutinovici** [comment]
I got it working several times, but it keeps breaking, cause i'm building against a moving target :)
I could make a gist of the current iteration, if you want.

**Comment by milutinovici** [comment]
https://gist.github.com/milutinovici/9bc3c22fc962175c8084

This of course isn't production quality, but it works. At least is works with some version :)
I removed some of the code that I just copied from base classes, that isn't exposed.

**Comment by kichalla** [comment]
great...thanks...this is helpful...

**Comment by rynowak** [comment]
Pretty cool stuff Ivan, thanks for sharing.

A few thoughts from looking at the sample. My assumption of course is that you can compute at startup-time what entity types you have in your app. If this isn't the case, then obviously what I'm suggesting doesn't apply.

If you wanted to, you could generate one `ControllerModel` for each `controller X entity` combination that you want to support. So if you have `PetStoreController<T>` and `Dog`, `Cat`, and `Fish` - you'd have a 3 descriptors. Then it would be simpler to attach the actual type `PetStoreController<Dog>` and actual method `PetStoreController<Dog>.BuyFood()` to the action descriptor. 

Now since the descriptor has the actual type and actual method you want, there's no need for a custom descriptor type - `ControllerActionDescriptor` would work fine.

But we still have to address action selection - because we need to find the *right* controller instead of finding all of them. To do that, add to `ControllerModel.RouteConstraints` -- these are like key-value pairs that have to make the data coming from routing. `controller : <controllername>` and `action : <actionname>` will be added for you. So to do this, create a new class that derives from `RouteConstraintAttribute` and sets the key to `type` and value to the type of the entity matching that controller.

I think if you try this out you'll only need to customize controller discovery.

**Comment by rynowak** [comment]
I want to also mention that the above `RouteConstraintAttribute` is how areas are implemented in MVC. So if you read the docs about that, that's gist of what it does. The difference in the new system you can build arbitrary levels of hierarchies.

**Comment by milutinovici** [comment]
You are right in your assumption, and your suggestions are really helpful. Gotta love the open source.
