### ISSUE TITLE
Add TagHelperContent.AppendFormat

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#2123]
Let's add the following methods to `TagHelperContent`:

``` C#
public TagHelperContent AppendFormat(string format, params object[] args);
public TagHelperContent AppendFormat(IFormatProvider provider, string format, params object[] args);
```

For now, it can just turn around and call `String.Format` before adding the result to the collection, but eventually we could optimize this so that the format doesn't result in an allocation at all but rather writes directly to the underlying writer.

We should update the `LinkTagHelper` and `ScriptTagHelper` to use this new method.

**Comment by sornaks** [comment]
I think we should just call `string.Format` directly and not optimize because we would end up rewriting the code for validating the content format string, handling alignment of the string, format of the type passed in, escaping etc. (https://msdn.microsoft.com/en-us/library/txafckwd(v=vs.110).aspx) While this is possible, I think this would open up a wider area for issues. We could try to optimize for arguments of type `TagHelperContent` but we would end up allocating the string as well as iterating through our buffer either ways - so there should be no difference in performance. What do you think @DamianEdwards @NTaylorMullen ?

**Comment by NTaylorMullen** [comment]
@sornaks the initial implementation of this will not be a true optimization (under the covers it'll just call `string.Format`). Ultimately its nice to have to make code easier to write/understand. 

If we want to make true performance optimizations later on we have that option.

**Comment by sornaks** [comment]
Checked in - https://github.com/aspnet/Razor/commit/585002baf8b6ef5239f66257ba565cdf71ed3b4d
