### ISSUE TITLE
Transition MVC TagHelpers to use TargetElementAttributes attribute targeting.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2195]
Now that `TagHelper`s can target attributes we should transition our existing `TagHelper`s to utilize this new "required" attributes functionality.

One example: `ValidationSummaryTagHelper` shouldn't target "div" elements then no-op if the attribute doesn't exist: It should target the `asp-validation-summary` attribute on any HTML element.

This should also enable us to no longer have ambiguity between "should I be a tag helper" for all of our tag helpers.

**Comment by dougbu** [comment]
it's likely views would perform better if tag helpers were not created only to no-op.  however we should measure things to confirm this is worthwhile since the MVC tag helpers are doing simple checks that work today.

specifically:
> ValidationSummaryTagHelper shouldn't target "div" elements then no-op if the attribute doesn't exist: It should target the asp-validation-summary attribute on any HTML element.

"any" is too broad.  we likely want to target `<div>` and `<span>` and that's about it.  in any case, we should strive to preserve the chosen behaviour and limit work on this issue to the implementation choice.  deal with reevaluating the behaviours separately.

> This should also enable us to no longer have ambiguity between "should I be a tag helper" ...

could you clarify this statement?  is this another point about changing the current MVC tag helper behaviours?

**Comment by danroth27** [comment]
@DamianEdwards Let us know if you think we need to pull this back into the current milestone.

**Comment by DamianEdwards** [comment]
We should do this now

**Comment by NTaylorMullen** [comment]
@dougbu The ambiguity bit I mentioned will drastically improve `TagHelper` tooling. For instance, today in the pre-bits for `TagHelper` tooling every `div` tag is highlighted because of the validation summary maybe being a `TagHelper` on div elements. Same thing goes for all other `TagHelper`s.

**Comment by dougbu** [comment]
@NTaylorMullen thanks, that was much clearer

**Comment by ajaybhargavb** [comment]
Part 1 - https://github.com/aspnet/Mvc/commit/bfdeda797df054a4ae8a6fa9250e65f07cd63a1e
Part 2 - https://github.com/aspnet/Mvc/commit/e2058905ec30facdf41d1eca2360be3c4b6b7314
Part 3 - https://github.com/aspnet/Mvc/commit/fd5e07dd0323812263b9fc0160ad56be3a4f3f6c
