### ISSUE TITLE
Consider using `DisplayAttribute.GroupName` to determine `SelectListItem`'s Group

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#2292]
`IHtmlHelper.GetEnumSelectList` picks up `DisplayAttribute.Name` to determine an enum field's display name. It seems appropriate for it also pick up `DispayAttribute.GroupName` to group these enum values. 

That said, this might have pretty narrow scope - there aren't too many scenarios I can think of where the values used to produce `SelectListItem` are annotated to start with.

**Comment by dougbu** [comment]
low priority, I agree.  but we pay attention to `[Display(Name=x)]`, so why not `[Display[GroupName=y)]` as well?

**Comment by heathyates** [comment]
@danroth27 @henkmollema Is this issue closed?

**Comment by henkmollema** [comment]
@heathyates nope, my commit is just some try-out which got pushed accidentally.

**Comment by stebet** [comment]
So. I have this working pretty well on my fork. It displays groups depending on the GroupName in the DisplayAttribute, by default groups and non-groups are just displayed in the order they are reflected form the Attribute (no sorting by group name or item name by default, thought that could rather be done manually since the Html.GetEnumSelectList returns an IEnumerable). Here is a small screenshot:
![capture](https://cloud.githubusercontent.com/assets/661658/10103041/61227396-6391-11e5-849b-294658c0f53b.PNG)
![capture2](https://cloud.githubusercontent.com/assets/661658/10103042/612ab574-6391-11e5-8e3c-c53c223aea96.PNG)

Anything else that needs to be added or changed before I send in a pull request?

**Comment by pranavkm** [comment]
Looks good to me.

**Comment by stebet** [comment]
I'll send in the pull request so we can continue the discussion from a code perspective then :)

**Comment by dougbu** [comment]
@Eilon wanna have this in Beta 8? @stebet is wrapping up #3201 as we speak.

**Comment by Eilon** [comment]
Beta8 is closed. For RC this will be fine.

**Comment by dougbu** [comment]
:ok: self-assigning since I've been working with @stebet on #3201

**Comment by dougbu** [comment]
13af6f8

**Comment by dougbu** [comment]
Thanks @stebet !
