### ISSUE TITLE
Model binding in view component

### ISSUE THREAD

**Issue by marcuslindblom** [aspnet/Mvc#2339]
I have a simple `ViewComponent` which contains a form, The `ViewComponent` is placed inside the `_Layout` view and displayed on all views, `Home`, `Article` and so on. Now I wish to handle the posted data inside my `ViewComponent` and that works pretty good if I use `Request.Form` to receive my data from the `Form` collection. I have tried to add the `[FromForm]` attribute on the `InvokeAsync` method but that does not work. How can I bind the `Form` data to my `Comment` object if it's not possible to bind the data in the `InvokeAsync` method?

This is my form:

```
@model Foo.Models.Comment
@using (Html.BeginForm())
{
    @Html.EditorForModel()
    <input type="submit" value="Comment" />
}

```

And this is my `ViewComponent`:

```
public class FormComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync([FromForm] Comment comment)
    {
        if (Request.HasFormContentType)
        {
            // Handle posted data
        }
        return View(new Comment());
    }
}
```

**Comment by danroth27** [comment]
I believe the behavior you are seeing is by design. The Invoke method for ViewComponents does not use model binding. It only uses the specific parameters that were passed when the ViewComponent was invoked. 

Handling a form post also isn't really a good use case for ViewComponents. ViewComponents are designed to handle rendering of complex data, not handling request data. Instead you should have your form POST to a specific controller action (ex for POST'ing the comment) and then from that action redirect back to the previous action ([POST/Redirect/GET](http://en.wikipedia.org/wiki/Post/Redirect/Get)).
