### ISSUE TITLE
Data Annotations consistency.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Mvc#2370]
Right now, for data annotations to work properly in a sample login form we annotate like this:

```
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

```

But if we annotate like this :
```
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
```

The DataType EmailAddress does not trigger the email validation.

I think mvc should always use DataType(DataType ...) and have 'helpers' when seems appropiate like [EmailAddress] that internally uses the DataType(DataType.EmailAddress).

**Comment by Eilon** [comment]
Hmm not sure I fully understand. The `[DataType]` attribute just specifies the data type - that affects the display and processing of the field. It is *not* a validation attribute (despite its base class). On the other hand, the `[EmailAddress]` attribute is a proper validation attribute that checks for `email@example.com` formats.

Even though these two attributes are in the same namespace and even have the same base class, their purposes are quite different.

It's interesting you just brought this up because just the other day I was talking to some other folks on the MVC team and we discussed how it is crucial for MVC to treat the Data Annotations attributes *as they were designed* and to make sure that MVC doesn't add/change any of these behaviors. Every time we've changed the behavior in the past (either on purpose or by accident) it came back to cause issues.

**Comment by Bartmax** [comment]
I see, wow! I have like 4+ years doing mvc and this is the first time that this DataType vs other attributes does make some sense.

 What I think is confusing is this:
```[DataType]``` affects display and processing
```[EmailAddress]``` is a validation attribute.

but ```[EmailAddress]``` does also affects display and processing. (```<input type="email" ...>```)

It was never clear to me what DataType exactly does and that the others are validators (like required, EmailAddress, etc).

While now is more clear, I still think it's confusing, but can be just me.

**Comment by Bartmax** [comment]
I did some more 'testing' and what looks to be inconsistent is that the Validation attribute does not honor the DataType attribute

```
[Required]
[EmailAddress]
[DataType(DataType.Text)]
public string Email { get; set; }
```
the input is still rendered as ```<input type="email" ...>```

**Comment by dougbu** [comment]
@Bartmax the last sample you've shared includes conflicting `[DataType]` instances.  given the model itself is inconsistent, what exactly would you suggest change?

> `[EmailAddress]` does also affects display and processing

yes, `[EmailAddress]` is a subclass of `[DataType]`.

**Comment by Bartmax** [comment]
I think it's confusing from an api point of view, and can be only me.

If any, the only think that I suggest is to make more clearly that EmailAddress subclasses DataType.EmailAddress (hence provide presentation and validation) and that DataType does not do any validation but presentation. 

maybe via documentation (summary).

**Comment by dougbu** [comment]
[MSDN](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.emailaddressattribute.aspx) makes the relationship between the classes clear.
