### ISSUE TITLE
Transition Script/Link TagHelper to utilize Pre/Post Element properties on TagHelperOutput.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2382]
With the completion of aspnet/Razor#341 there is now `PreElement` and `PostElement` properties on `TagHelperOutput`. Today we rebuild our `ScriptTagHelper` and `LinkTagHelper` contents to give the appearance of `PostElement` behavior; we should refactor this to use the new `TagHelperOutput` properties.

**Comment by NTaylorMullen** [comment]
Why is this a bug?

**Comment by dougbu** [comment]
aspnet/Razor#225 includes a [comment](https://github.com/aspnet/Razor/issues/225#issuecomment-95979090) that mentions complete support for maintaining the original attribute order involves that fix (done), #2639, completing this task (#2382), as well as
- use `PostElement` for `type="checkbox"` case in `<input/>` tag helper and merge added attributes for original element

My comment is incorrect because attribute order will be maintained correctly as soon as #2639 is done. But we have agreed `PostContent` avoids lots of special-case code in the `<link>` and `<script>` tag helpers. So why not the `<input>` tag helper as well?

Question for @Triage: Should we do the `checkbox` task as part of #2382 (this issue) or in another issue?
