### ISSUE TITLE
[Mvc 5.0 Compat] Null values returned by value providers/model binders for value type properties should not create a model state error.

### ISSUE THREAD

**Issue by harshgMSFT** [aspnet/Mvc#2423]
Mvc 5.0 behavior is to use the default value, however in mvc 6.0 we add the following error:
`A value is required.`

For example :
```c#
public class Person
{
     [FromBody]
     public int SSN { get; set; }
}

public void Action(Person p)
{
}
```
Request body is empty.
There would be an error in model state in MVC 6.0 and  no one for a comparable scenario in MVC 5.0 (where a value provider returns a null for the key SSN ).

**Comment by dougbu** [comment]
@harshgMSFT could you please check if de63075 (which removed the `[Required]` special case for JSON inputs) also fixed this compat issue?

**Comment by Bartmax** [comment]
just so you can take into consideration, I hope `[Required]` (and similar) still makes a `ModelState` error on this same scenario, even while on mvc5 it will not. I see this as an enhancement of a bad design on mvc5 that can be fixed (it is already) on mvc6. Just please, don't go backwards with this one.

Specially, 
```
[Required]
public int Amount {get; set;}
```

this won't ever trigger a required error in mvc5, you need to change `int` to `int?` because it's defaulting to 0 (default value). in mvc6 this does triggers and error and it's great!.

I know this is about `[FromBody]` attribute, but just in case.

**Comment by yishaigalatzer** [comment]
MVC never supported `[FromBody]` this should probably be compatible with WebAPI rather than MVC

**Comment by harshgMSFT** [comment]
@Bartmax The reason for not logging an error is that '[Required]' means that the value should be not null. In case of value types it can never be null. So instead of overloading Required to mean not present in the request we are going with what it is supposed to mean (not null).

**Comment by Bartmax** [comment]
@harshgMSFT I understand how it works, but I think it's a bad design (I may be wrong). I created a specific issue for this https://github.com/aspnet/Mvc/issues/2615

**Comment by yishaigalatzer** [comment]
Agree with @bartmax

**Comment by borgdylan** [comment]
I think that even without [Required], the model should be invalid if a value is not given for a valuetype. Nullable<T> should be used to indicate that a value is not by force required to be present.

**Comment by Eilon** [comment]
Closing this. To specify that a value must be on the wire, use `[BindRequired]` on the property. The `[Required]` attribute means only what Data Annotations says it means, which is that the current value of the property is not-null, when applicable. Because value types can't be null, the `[Required]` attribute will by-design not do anything.
