### ISSUE TITLE
Shouldn't AllowAnonymous come first?

### ISSUE THREAD

**Issue by aggieben** [aspnet/Mvc#2475]
I was reading through the source of [`AuthorizeFilter`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/Filters/AuthorizeFilter.cs#L51), and noticed that in `OnAuthorizeAsync`, the `AllowAnonymous` attribute isn't checked until after active auth schemes are authenticated and claims added to the principal. 

```
// use active auth schemes to get claims and populate new ClaimsPrincipal

// Allow Anonymous skips all authorization
if (context.Filters.Any(item => item is IAllowAnonymous))
{
    return;
}

// do authz, issues challenge result if necessary
```

Shouldn't the middle part go first?  Why do the claims stuff if an `AllowAnonymous` attribute is present?

**Comment by blowdart** [comment]
Regardless of what authorization you select authentication is always going to happen first, because you can't authorize without authenticating.

If have allow anonymous on a controller or method and an optional identity is sent I'd want that identity created regardless so I could, for example, show or hide parts of my UI.
