### ISSUE TITLE
What happened to DataAnnotationsModelMetadataProvider?

### ISSUE THREAD

**Issue by mrchief** [aspnet/Mvc#2522]
I tried searching for it in this repo but can't find any references to it. There is no word as to what happened to this - is it in the works or is there a new way of doing this?

I'm trying to use [HumanizerMetadataProvider](https://github.com/MehdiK/Humanizer#mix-this-into-your-framework-to-simplify-your-life) which derives from `DataAnnotationsModelMetadataProvider` to weave its magic.

**Comment by dougbu** [comment]
The `ModelMetadata` and `IModelMetadataProvider` extensibility story is significantly different in MVC 6. You would need a `HumanizerMetadataProvider` which implements `IDisplayMetadataProvider`. Then update the `ModelMetadataDetailsProviders` collection in `MvcOptions` to add that humanizer at the end (see `MvcOptionsSetup` for the base).

**Comment by mrchief** [comment]
I suspected as much. I found `DefaultModelMetadataProvider` and was attempting this:

```csharp
public class HumanizerMetadataProvider : DefaultModelMetadataProvider
{
	protected override ModelMetadata CreateModelMetadata(DefaultMetadataDetailsCache entry)
	{
	    var propertyAttributes = entry.Attributes;
	    var modelMetadata = entry.DisplayMetadata;

        if (IsTransformRequired(modelMetadata, propertyAttributes))
            modelMetadata.DisplayName = modelMetadata.SimpleDisplayProperty.Humanize().Transform(To.TitleCase);

        return base.CreateModelMetadata(entry);
	}


	private static bool IsTransformRequired(DisplayMetadata modelMetadata, IReadOnlyList<object> propertyAttributes)
	{
		if (string.IsNullOrEmpty(modelMetadata.SimpleDisplayProperty))
			return false;

		if (propertyAttributes.OfType<DisplayNameAttribute>().Any())
			return false;

		if (propertyAttributes.OfType<DisplayAttribute>().Any())
			return false;

		return true;
	}

	public HumanizerMetadataProvider(ICompositeMetadataDetailsProvider detailsProvider) : base(detailsProvider)
	{
	}
}
```

Is this an acceptable way to go?

I also found `DataAnnotationsMetadataProvider`. Is this same as `DataAnnotationsModelMetadataProvider` (minus the Model in the name)?

If not, do I need to remove it from default options before plugging the Humanizer Provider?

Finally, if I implement  `IDisplayMetadataProvider ` how can I still hitch back on the default `DataAnnotationsMetadataProvider`? `DataAnnotationsMetadataProvider` seems to be doing a lot and I'm not sure what I would be leaving out if I roll my own.

**Comment by rynowak** [comment]
@mrchief - the new extensibility model is based on adding your own provider to a list, not based on subclassing or replacing a provider. Providers run in the order you put them in (in options) and each one can see and modify the results of the previous providers.

Think of `DefaultModelMetadataProvider` as the factory for `DefaultModelMetadata` - subclassing it allows you to change what class is returned. I wouldn't recommend that approach for what you're tying to do.

If you do what @dougbu is suggesting - implement `IDisplayMetadataProvider` - add it to options. Then your provider will run **after** the `DataAnnotationsMetadataProvider`. You can make you modifications to `DisplayName` without impacting anything else that `DataAnnotationsMetadataProvider` normally does.

**Comment by mrchief** [comment]
This totally makes sense and I like this approach even more! :ok_hand:

Thanks for the quick responses @rynowak @dougbu !

**Comment by rynowak** [comment]
Cool, this is exactly the kind of scenario that new extensibility was intended to support, so we're glad to see that it helps you.

**Comment by mrchief** [comment]
Being able to talk to the core team and get questions answered is a bigger help! 

This clears one of the hurdles I was facing while migrating an existing MVC 5 project to vNext. I'll soon post an updated code for posterity's sake.

**Comment by mrchief** [comment]
Here's the updated code:

```csharp
public class HumanizerMetadataProvider : IDisplayMetadataProvider
{
  private static bool IsTransformRequired(DisplayMetadata modelMetadata, IReadOnlyList<object> propertyAttributes)
  {
      if (string.IsNullOrEmpty(modelMetadata.SimpleDisplayProperty))
          return false;

      if (propertyAttributes.OfType<DisplayNameAttribute>().Any())
          return false;

      if (propertyAttributes.OfType<DisplayAttribute>().Any())
          return false;

      return true;
  }

  /// <summary>
  /// Gets the values for properties of <see cref="T:Microsoft.AspNet.Mvc.ModelBinding.Metadata.DisplayMetadata"/>. 
  /// </summary>
  /// <param name="context">The <see cref="T:Microsoft.AspNet.Mvc.ModelBinding.Metadata.DisplayMetadataProviderContext"/>.</param>
  public void GetDisplayMetadata(DisplayMetadataProviderContext context)
  {
      var propertyAttributes = context.Attributes;
      var modelMetadata = context.DisplayMetadata;

      if (IsTransformRequired(modelMetadata, propertyAttributes))
          modelMetadata.DisplayName = modelMetadata.SimpleDisplayProperty.Humanize().Transform(To.TitleCase);
  }
}
```

**Comment by toddtsic** [comment]
Concerning:
"If you do what @dougbu is suggesting - implement IDisplayMetadataProvider - add it to options. Then your provider will run after the DataAnnotationsMetadataProvider. You can make you modifications to DisplayName without impacting anything else that DataAnnotationsMetadataProvider normally does."

How exactly is "public class HumanizerMetadataProvider : IDisplayMetadataProvider" added to options.  Assuming this is in startup.cs...

**Comment by mrchief** [comment]
@toddtsic Yes, you'd configure it in `Startup.cs`, like so:

```csharp
// This method gets called by the runtime. Use this method to add services to the container.
public void ConfigureServices(IServiceCollection services)
{
    ...

    // Add MVC services to the services container.
    services.AddMvc()
        .Configure<MvcOptions>(options => options.ModelMetadataDetailsProviders.Add(new HumanizerMetadataProvider()));
    ;

    ...
}   
```

**Comment by toddtsic** [comment]
Thanks Hrusikesh,

I actually was able to figure this out, but have hit a wall since.  Would
you mind my asking a couple of questions?  I totally understand if you are
too busy...

I'm trying to capture the moment when mvc accesses dataannotations and edit
a model's annotations depending on values in a database.  (I write sports
software, so when registering a player using a certain model, one club may
want to ask "Jersey Size", a different club may not, etc, and I really
don't want to create separate models for each club)

I was able to do this easily with MVC3 but am stuck with MVC6.

I seem to be able to capture in my CustomModelMetadataProvider

services.ConfigureMvc(config =>
            {
                config.ModelMetadataDetailsProviders.Add(new
CustomModelMetadataProvider());
            });

But I have noticed


   1. mvc will only fire my CustomModelMetadataProvider with first time
   access of each model (MVC appears to be caching the information), and I
   can't figure out how to force access every time
   2. I can't seem to figure out how to inject my db connection into my
   CustomModelMetadataProvider as MVC 6 seems only to support controller
   injection.


If you had a second, and either of these problems seamed simply to you and
you could point me in the right direction, I'd be grateful.

Todd

**Comment by mrchief** [comment]
> I was able to do this easily with MVC3 but am stuck with MVC6.

That is a statement that is very true and you're going to be muttering it quite often till your transition (to vNext) completes! :smile: 

The first issue would need some R&D since I haven't really had such need so far.
The second however seems straightforward unless I'm missing something:

```csharp
services.ConfigureMvc(config =>
            {
                config.ModelMetadataDetailsProviders.Add(new
CustomModelMetadataProvider(_container.GetInstance<ServiceType>()));
            });
```

**Comment by toddtsic** [comment]
Thanks, very much for the tip on DI into CustomModelMetadataProvider...

If I learn anything about caching of dataannotations and how to override,
I'll be sure to pass it on.

Todd

**Comment by mrchief** [comment]
Taking a glance at the source, I think they are stored in `DisplayMetadataProviderContext` and the `CustomModelMetadataProvider` is only called if the keys are missing. Since reflection is a costly business, I guess caching makes sense. 

Instead of disabling caching, and thus sacrificing performance, I would advise an alternate approach such as extending `LabelFor` or `DisplayFor` or whatever you use to render the label. This way, you can hook up your dynamic provider selectively in places where you need them and still leverage the default behavior in rest of the places without losing any performance.

**Comment by toddtsic** [comment]
Hrusikesh,

Thanks for your response, all makes sense.  I agree totally with the
approach to maximize performance.

Here's another head-scratcher (just ignore if you are busy):

Trying to add a player (read: valid ApplicationUser) to a table of family
players (multiple kids in a family)

I pass a username/password of the valid ApplicationUser, then simply
validate the credentials then add to table.

In prior mvc's you could validate with Membership.ValidateUser, but no
more, so I tried UserManager.CheckPasswordAsync.

------start failing code block-----
*                        bool bCorrectPassword = await
UserManager.CheckPasswordAsync(user,
model.New_Player_Detail.TSIC_Password);*
*                        if (bCorrectPassword)*
*                        {*
*                            Family_Members record = new Family_Members()*
*                            {*
*                                Family_UserId =
model.Family_Details.Family_UserId,*
*                                Family_Member_UserId = user.Id,*
*                                modified = DateTime.Now,*
*                                lebUserID =
model.Family_Details.Family_UserId*
*                            };*

*                            db.Family_Members.Add(record);*
*                            await db.SaveChangesAsync();*
*                            return RedirectToAction("EditFamilyAccount",
new { StatusMessage = String.Format("Player: {0} has been added to your
family account.", model.New_Player_Detail.TSIC_Username) });*
*                        }*
*                        else*
*                        {*
*                            return RedirectToAction("EditFamilyAccount",
new { StatusMessage = "Credentials for new player were not valid." });*
*                        }*

------end failing code block------

UserManager.CheckPasswordAsync returns correct results (true if true, false
if any non-matching combination of username/password), however:

The await db.SaveChangesAsync() will fail with:

A database operation failed while processing the request.

*DbUpdateConcurrencyException: Database operation expected to affect 1
row(s) but actually affected 0 row(s). Data may have been modified or
deleted since entities were loaded.  *

Now simply comment out the UserManager.CheckPasswordAsync and it works
fine.  Somehow UserManger.CheckPasswordAsync is holding the account
record... can't be sure, very difficult to debug.  Try Catch doesn't add
anything beyond the DbUpdateConcurrencyException.

------start successful code block-----
*                        //bool bCorrectPassword = await
UserManager.CheckPasswordAsync(user,
model.New_Player_Detail.TSIC_Password);*
*                        //if (bCorrectPassword)*
*                        //{*
*                            Family_Members record = new Family_Members()*
*                            {*
*                                Family_UserId =
model.Family_Details.Family_UserId,*
*                                Family_Member_UserId = user.Id,*
*                                modified = DateTime.Now,*
*                                lebUserID =
model.Family_Details.Family_UserId*
*                            };*

*                            db.Family_Members.Add(record);*
*                            await db.SaveChangesAsync();*
*                            return RedirectToAction("EditFamilyAccount",
new { StatusMessage = String.Format("Player: {0} has been added to your
family account.", model.New_Player_Detail.TSIC_Username) });*
*                        //}*
*                        //else*
*                        //{*
*                        //    return RedirectToAction("EditFamilyAccount",
new { StatusMessage = "Credentials for new player were not valid." });*
*                        //}*

------end successful code block------

**Comment by mrchief** [comment]
[CheckPasswordAsync](https://github.com/aspnet/Identity/blob/e80853a4cf665d73e7e5cdcb652d3d51cd456068/src/Microsoft.AspNet.Identity/UserManager.cs#L514) doesn't update anything unless there is a need to rehash. My best guess would be that between the call to CheckPasswordAsync and the next continuation block, your context undergoes a change (most likely the user property changes). 

I would advise posting this in a Q&A forum such as stackoverflow or asp.net lists. You'll reach a greater audience and this thread can stay focused on DataAnnotationModelProvider issues.

**Comment by toddtsic** [comment]
Will do, thanks
