### ISSUE TITLE
BodyModelBinder converts what should be a 415 error into a Model error with no clean way to resurface as a 415

### ISSUE THREAD

**Issue by darrelmiller** [aspnet/Mvc#2612]
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ModelBinding/BodyModelBinder.cs#L44

By converting this to a Model error with just a string error message how can the action detect this and return a 415?

Why not just return a 415 in the first place?   On a related note, if this was to happen we would need an similar attribute to the Produces attribute for declaring which inputformatters are valid for the particular action.

**Comment by harshgMSFT** [comment]
@darrelmiller - 
You hit the nail on its head 
> On a related note, if this was to happen we would need an similar attribute to the Produces attribute for declaring which inputformatters are valid for the particular action.

Yes we do have an attribute which lets you specify which content type is supported for an action . 
Its called `Consumes`. 
example

```c#
        [Consumes("application/json", "text/json")]
        public Product CreateProduct([FromBody] Product_Json jsonInput)
        {
            return jsonInput;
        }
```
The above code will return a `UnsupportedMediaTypeResult` which means its a 415 if there are no formatters which support  application/json or text/json.

Now coming back to `how can an action detect this`

Since there can only be one and only one parameter (or property) which is bound from body the model state can be looked up to see if there is an error and return a 415. (Please note that there is no strongly typed way to detect that the error was due to a missing input formatter, so use consumes for your scenario.).

HTH

**Comment by darrelmiller** [comment]
Excellent.  Thanks.
