### ISSUE TITLE
Invalid model type validation

### ISSUE THREAD

**Issue by anfomin** [aspnet/Mvc#2614]
I've two view components. Each has it's own model type. If *view* renders *component 1* which renders *component 2*, exception occurs:
**The model item passed into the ViewDataDictionary is of type 'Model2', but this ViewDataDictionary instance requires a model item of type 'Model1'.**

**Comment by dougbu** [comment]
@anfomin are you calling `Component2` directly from `Component1`? If yes, this is somewhat similar to calling one action method directly from another: It may work in some cases but is not recommended.

View components are designed to be invoked from views. The implementation does such things as setting up `ViewContext` and `ViewData` correctly prior to the actual call.

**Comment by anfomin** [comment]
@dougbu it can be useful to render one view component from another. And there is no problems except one I mentioned before.

I can describe why we do this. We've created `WidgetViewComponent` in our project. `WidgetComponent` is `ViewComponent` with custom options. It can be rendered via:

1. Razor: `@Component.Invoke<WidgetViewComponent>(options)`
2. Database entries with JSON serialized options.

For the second way we have created `WidgetPlaceViewComponent` which loads widgets information from database and renders `WidgetViewComponent` in specific HTML markup. So different pages can just invoke `@Component.Invoke<WidgetPlaceViewComponent>()` to render all components registered in database.

**Comment by dougbu** [comment]
@anfomin your scenario makes sense but making direct calls from one view component to another is not something MVC provides out-of-the-box. Either use another framework for managing your loaded widgets or ensure the inner component (`component2`) is configured correctly before calling `Invoke()` or `InvokeAsync()`.

In current Beta 5 bits, "configured correctly" involves creating a `ViewComponentContext` instance containing a new `ViewContext` (liked to that of the parent `ViewComponent`) and `ViewDataDictionary<TModel>`. Assign that instance to the `ViewComponentContext` property if you have derived from the `ViewComponent` base class. Otherwise set the correct property or properties in your POCO view component.

**Comment by rynowak** [comment]
@anfomin can you share your code?
