### ISSUE TITLE
我在使用MVC4时发现一个bug（I found a bug when using MVC4）

### ISSUE THREAD

**Issue by liuww111** [aspnet/Mvc#2650]
原文我写在了博客里面：http://www.cnblogs.com/RainbowInTheSky/p/4550066.html
我使用form传递参数的时候，想把参数转化成对象，结果使用了对象变量名“action”，结果得到的值是null。当我改变这个变量名为model的时候，是可以得到值的。请问，这个是不是一个错误？
I use the “form” transfer parameters, want to convert the parameters into the object, the results of the use of the object variable name "action", the results get the value is null. When I change the name of the variable named “model”, it can be obtained.. Excuse me, is this a mistake?

**Comment by rynowak** [comment]
If you're using conventional routing (which it appears that you are) - then the values `action` and `controller` will be bound from the URL by the route.

It's interfering with model binding because the system is trying to find a match for the parameter name. Since it find a route value for `action` then it tries to convert that value into your model.

A few suggestions for how you could avoid this (choose any):
- Use attribute routing
- Avoid using parameters named `action` or `controller` with conventional routing
- Use `[ModelBinder(Name = "")]` to force model binding to ignore the value for `action`
- Provide a prefix when you generate the form use generate keys with the prefix `action.ActionName`, `action.ActionParam`, etc.

**Comment by liuww111** [comment]
thanks

**Comment by supermancahcah** [comment]
oh,no , too many dogs.

**Comment by dougbu** [comment]
No such thing as too many dogs.

**Comment by pranavkm** [comment]
:joy_cat:
