### ISSUE TITLE
Mvc samples not working

### ISSUE THREAD

**Issue by sujitdmello** [aspnet/Mvc#2689]
Just pulled dev branch and got latest DNX runtime bits (Unstable branch) and ran *DNU restore* for the samples. Running the MvcSample and Taghelper samples are giving compilation errors:

MvcSample - HttpContext missing
TagHelper - IServiceCollection missing

I figure some of the packages in the project.json files are wrong but I can't seem to get the right combination.

**Comment by ajaybhargavb** [comment]
Looked at this issue. This occurs if the sample is restored and built without building the Mvc source. This looks like some design quirk of how dnx resolves dependencies for projects referenced through global.json.
There are two workarounds to this problem.
1. Run `dnu restore` on the entire Mvc source (the `src` folder)
2. Move the sample out of the Mvc folder so that it does not reference the project through global.json.

Please reopen the issue if none of these workarounds fix it.
