### ISSUE TITLE
TagHelperSample.Web not working

### ISSUE THREAD

**Issue by back5576** [aspnet/Mvc#2731]
When I run the sample with "dnx . web" I get console output 
info    : [Microsoft.Net.Http.Server.WebListener] Start
info    : [Microsoft.Net.Http.Server.WebListener] Listening on prefix: http://localhost:5001/taghelpers/
Started
Q: why does this sample have /taghelpers in URL
Anyway, here's what I find. When I try to open the URL, the web server process locks up, the browser gets no response, and the command window where it was run becomes unresponsive. I assume I'm correct in how I'm trying to run this sample. Or am I doing it wrong?

**Comment by back5576** [comment]
MvcMinimalSample.Web and MvcSample.Web work fine

**Comment by danroth27** [comment]
Thanks for reporting this issue. What version of DNX are you using?

**Comment by back5576** [comment]
dnvm use 1.0.0-beta6-12114 -r clr -arch x64

After restarting this computer, I am getting a different result. I get an error popup that I hadn't seen before. It says

"Embedded resource missing. Ensure 'prebuild' script has run."

![Uploading taghelper_error.png…]()

**Comment by danroth27** [comment]
@dougbu Can you do a quick check to make sure this sample is actually working? Is it already part of our automation?

**Comment by dougbu** [comment]
@back5576, @danroth27 this sample is used in a number of functional tests and those tests are not failing. However there's a few prerequisites that `.\build.cmd initialize` (the first step in almost any build) provides for free:
1. Use the [`volatile`](https://www.myget.org/F/aspnetvolatile/api/v2) feed. Breaking changes have gone in since our `dev` (aka `vnext`) feed was last updated. Hopefully this is a short-term issue.
2. Run `dnu restore` from the solution root, not just for the sample project. Sample does not work unless packages for other projects have been restored. Some build-time requirements aren't satisfied otherwise.
3. Run `npm install` and `grunt` in the `src\Microsoft.AspNet.Mvc.TagHelpers` project. Need to set resources for that project up.

FYI `dnx . kestrel` behaves similarly for this sample. The main difference is that command listens at [http://localhost:5000/](http://localhost:5000/) and not [http://localhost:5001/taghelpers](http://localhost:5001/taghelpers).

**Comment by back5576** [comment]
>Run npm install and grunt in the src\Microsoft.AspNet.Mvc.TagHelpers project. 
That did the trick! Thanks.
I think having a readme in these sample  folders would be a good idea

**Comment by dougbu** [comment]
4d56046
