### ISSUE TITLE
Discuss adding server side validation to value type model properties by default.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#2776]
Today in MVC6 having the following model:
```C#
public class Person
{
    public int Id { get; set; }
}
```
Will result in client side validation with 0 server side validation (unless specifying `BindingBehaviorAttribute` with `BindingBehavior.Required`). 

This differs from what happened in MVC5; model state would be invalid due to server side validation opting in `ValueType` properties. However, in WebAPI not providing a value for a `ValueType` property when model binding was 100% ok and did not result in any `ModelState` errors. 

Given the different behavior in the old MVC/WebAPI systems we should discuss the right approach for this in MVC6.

Related conversation that spurred this: https://github.com/aspnet/Mvc/issues/2720#issuecomment-117339050

/cc @rynowak @Eilon @dougbu

**Comment by rynowak** [comment]
Decision here is to bring back the implicit `[BindRequired]` for value-types. If you need to make something optional, it can be customized:
- using `[BindingBehavior(BindingBehavior.Optional)]`
- a custom MMP
- using a nullable type (`int?`)

**Comment by rynowak** [comment]
We've done more investigation here, and the data above isn't correct about MVC 5's behavior.

In MVC 5 the absence of a field **does not** result in a validation error for a value type property. You only get the validation error if you submit an empty value.

This is critical for compatibility because Create views that scaffolding generates will omit the `Id` for the model. With the fix in a6ce9ab - you'll see an error in this very common scenario.

**Comment by rynowak** [comment]
07fabde92ab4b6dd26016097a0ca297c467fb4ff
