### ISSUE TITLE
Decide if newlines in Razor tests need to be normalized to '\r\n' or '\n'

### ISSUE THREAD

**Issue by sornaks** [aspnet/Mvc#2779]

**Comment by danroth27** [comment]
@sornaks Why? What is the actual issue here?

**Comment by sornaks** [comment]
Two reasons:
1. Razor normalizes it to '\r\n' in its tests. - https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNet.Razor.Test/CodeGenerators/RazorChunkGeneratorTest.cs#L87
2. We might end up coding test cases to handle '\n' (*nix) cases that we actually miss some cases relating to '\r\n' (Windows) - This scenario is remote but possible. So normalizing to '\r\n' would always ensure working tests in Windows :)

/cc: @NTaylorMullen @dougbu

**Comment by dougbu** [comment]
Due to core.autocrlf, neither `\n` nor `\r\n` is consistently correct on Windows. Razor repo unfortunately normalizes to the less-common `\r\n`, matching only the default Windows setup. MVC repo normalizes files to contain `\n` on read but only when it matters due to for example calculation of source locations. In either case, need `ignoreLineEndings` in assertions due to additions of `Environment.NewLine`s in generated HTML.

**Comment by Eilon** [comment]
Let's go with `\r\n` as the default in the tests across our repos because it seems like it'll be easier for us to deal with. We'll quickly catch any non-Windows issues on CI runs anyway.

**Comment by sornaks** [comment]
https://github.com/aspnet/Mvc/issues/2779
