### ISSUE TITLE
Throw `InvalidOperationException` if `ViewLocalizer._localizer` is used before Contextualize method is called?

### ISSUE THREAD

**Issue by kirthik** [aspnet/Mvc#2816]
This is purely a discussion bug. This came up in PR - https://github.com/aspnet/Mvc/pull/2701. Currently `localizer` in `ViewLocalizer` and `HtmlLocalizer` classes can be null if they are accessed before `Contextualize` method is called. One option is to throw an `InvalidOperationException` in the getter just like we currently do in `HtmlHelpers`.

**Comment by dougbu** [comment]
Updated subject. The discussion is not Localization-specific since `DefaultViewComponentHelper` and `HtmlHelper` are already inconsistent `ICanHasViewContext` implementations. Question is about which `Exception` (`NullReferenceException` or `InvalidOperationException`) should be thrown in this unusual scenario.

Specific discussion is found [here](https://github.com/aspnet/Mvc/pull/2701#discussion-diff-34403174).

**Comment by Eilon** [comment]
Closing because this doesn't seem particularly important. 99.9% of the time the framework takes care of everything and there's no error.
