### ISSUE TITLE
Resolving dependency without using constructor and property

### ISSUE THREAD

**Issue by mbharodia** [aspnet/Mvc#2822]
What is equivalent of the following to resolve dependency? The following is valid in previous version of MVC.
GlobalConfiguration.Configuration.DependencyResolver.GetService

Thanks a lot for your help.

**Comment by danroth27** [comment]
We don't recommend accessing the service provider statically. Can you tell us more about what you are trying to do?

**Comment by mbharodia** [comment]
Hi Daniel,

Thanks a lot for the reply. I have several helper classes.

One of them is a custom implementation of ILogger and ILoggerProvider. I wanted to provide configuration value to ILogger such as file path to log values. I wanted to inject IOption<AppSetting>.

My custom ILogger is created by my custom ILoggerProvider. If I do constructor injection then I need to pass in this dependency all the way up to ILoggerProvider.

So thought to use [FromServices] right in ILogger. When I used [FromServices] on a property, it did not resolve the dependency.

Additionally I have other helper classes, which I do not register but they still need services registered in the context. So I thought to use [FromServices]. This does not work in my case.

I have also custom implementation of UserManager. UserManager depends on IdetityService. This is a class with various methods, which I use to override UserManager methods. I create IdentityService object in the constructor of my custom UserManger.

IdentityService uses objects of repository implemented in another project: ILoginReposritory and IUserRepository. I register ILoginRepository and IUserRepository in StartUP.cs. Concrete implementation of these are LoginRepository and Userrepository. Basically they are in a separate project. They use EntityFramework 6.

I thought to use [FromServices] in IdentityService too. I do not register IdentityService in Startup.cs. That does not work either. If I use constructor then it works. But I really do not want to do it as I need to create a chain changes all the way up to custom UserManager.

I have looked into MvcMusic store to learn how [FromServices] work there but the same set up just does not work for me. So I thought to figure out some other means of resolving the dependency. In my case using property injection looks much cleaner and requires no changes to default constructors.

I really appreciate if you can provide me some feedback.

**Comment by danroth27** [comment]
As you have seen `[FromServices]` is only used by model binding in MVC. It is not a general DI concept in ASP.NET 5. It really only works in MVC controllers when model binding request data.

You can use property injection with ASP.NET 5, but not using the default container. Instead you can configure a 3rd party container (ex [AutoFac](http://alexmg.com/autofac-4-0-alpha-1-for-asp-net-5-0-beta-3/)) that supports property injection.

We should probably have the logging discussion in the Logging repo. Opened https://github.com/aspnet/Logging/issues/220 to track it.

For the Identity and DI issue, could you please open an issue on the https://github.com/aspnet/identity repo with your `UserManager` code so that folks can take a look?
