### ISSUE TITLE
Unexpected Url.Action output

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#2859]
Given routing in beta5:
```C#
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "DefaultDouble",
        template: "{custom}/{controller}/{action}/{id?}",
        defaults: new { controller = "Home", action = "Index" },
        constraints: new { custom = "Double" });

    routes.MapRoute(
        name: "DefaultSingle",
        template: "{controller}/{action}/{id?}",
        defaults: new { custom = "Single", controller = "Home", action = "Index" },
        constraints: new { custom = "Single" });
});
```
And calling this from NotHome controller view
```C#
@Url.Action("Index", new { custom = "Double" })
```
results in
```HTTP
/Double
```
while expected output is
```HTTP
/Double/NotHome
```
Repro
https://github.com/Muchiachio/ActionUrlSample

**Comment by dougbu** [comment]
@Muchiachio is there a typo in your sample? If not where would "NotHome" come from?

**Comment by Muchiachio** [comment]
No, I just didn't want to write "Broken" in the issue :smile:

**Comment by dougbu** [comment]
@Muchiachio my point was the `controller` value defaults to "Home" in both routes. No route will choose the other controller.

**Comment by Muchiachio** [comment]
Hmm, but you didn't need to specify other controllers in MVC5 routing, right?
```C#
@Url.Action("Index", new { custom = "Double" })
```
would mean, form an url for current controller and area + add custom route value/query parameter?
So if I am currently in controller's "NotHome" view, Url.Action for index should still be generated for "NotHome" controller? It seems like you need to re-specify current route values then forming an url action.
```C#
@Url.Action("Index", new { controller = ViewContext.RouteData.Values["controller"], custom = "Double" })
```

**Comment by rynowak** [comment]
> Hmm, but you didn't need to specify other controllers in MVC5 routing, right?

That depends on the current value of `custom`. Both old and new routing codebases have a feature that invalidates route-values when a route-value to the left (lexically, in the template) has a new value.

Ex: - using route:

routes.MapRoute(
        name: "DefaultDouble",
        template: "{custom}/{controller}/{action}/{id?}",
        defaults: new { controller = "Home", action = "Index" });

Current Values: `{ custom = "Double", controller = "NotHome", action = "Index" }`
`@Url.Action("Index", "Home", new { custom = "Double" })` should generate `/Double/NotHome/Index`

In this case, the current (or 'ambient') value of `controller` is valid, because `custom` has not changed.

Current Values: `{ custom = "Single", controller = "NotHome", action = "Index" }`
`@Url.Action("Index", new { custom = "Double" })` should generate `/Double`

In this case, the current (or 'ambient') value of `controller` is not valid, because `custom` has changed.

**Comment by Muchiachio** [comment]
Does that mean that there are changes in routing in MVC6?
Because this works just fine in MVC5.

**Comment by Eilon** [comment]
The same routing logic should be in MVC5 and MVC6 with respect to this...

**Comment by Muchiachio** [comment]
I have a project in MVC5 which works differently, I will try to reproduce the same different behavior in small MVC5 project and will get back to you.

**Comment by Muchiachio** [comment]
[Here's](https://github.com/Muchiachio/UrlActionSample5) a MVC5 repro project with the same configuration.
You can run both projects side by side and see different results :?

**Comment by rynowak** [comment]
The only **intended** behavior difference between MVC 5 and MVC 6 is that MVC 6 won't generate a link to something that doesn't exist. I'll take a look at the samples.

**Comment by rynowak** [comment]
I can confirm that this is behaving differently on MVC6. Currently trying to root cause why. Thanks for the report and the helpful repos :+1:

**Comment by rynowak** [comment]
Found the issue here. There's a piece of code in `UrlHelper` in MVC5 that will explicitly add the ambient values for `action` and `controller` to the 'specified values' dictionary. 

In effect, if you call `Url.Action(...)` - you're never relying on route-value-invalidation for the 'typical' MVC route tokens of `action` and `controller`. `area` doesn't have any special behavior in this regard.

**Comment by Eilon** [comment]
Ah yes I vaguely recall that.

**Comment by rynowak** [comment]
7aa5967cd40ea6659d7084c4f34e0bc901109b6f
