### ISSUE TITLE
Logs from routing

### ISSUE THREAD

**Issue by jbfp** [aspnet/Mvc#2860]
When using the `Microsoft.Framework.Logging.ILoggerFactory` and DI, is it possible to get MVC routing to be a little more quiet? I use `LogLevel.Information` quite a bit myself, but so does MVC routing apparently.
Specifically the lines where it logs (at level 'Information') when it matches a route:
https://github.com/aspnet/Mvc/blob/5632a330986b4e915ba351e57e477062d81a58fd/src/Microsoft.AspNet.Mvc.Core/Routing/InnerAttributeRoute.cs#L136-L139

Perhaps this log is more 'verbose' than 'information'?

**Comment by davidfowl** [comment]
Are you using beta5?

**Comment by jbfp** [comment]
Yep

**Comment by Eilon** [comment]
We recently updated that log levels of most log events so that the `Information` level should be very quiet - at most a few log entries per "normal" request.

Can you try with the latest build? I took a quick look and the only LogInformation that I saw was the one you pointed out. We're contemplating removing even that one, but we're not sure if we want to remove *all* the Information logs from the request...

**Comment by jbfp** [comment]
The latest builds are from the aspnetvnext MyGet feed, which is the "dev" branch, right? The dev branch still has that one specific ``Information`` log and it didn't make a difference in the log amount. It's not a big deal when it's just me testing, but I made the mistake of using 'wrk' (http load testing tool) with logging on and, well, the logs now tell me that MVC did in fact find the correct route a couple thousand times 😉

**Comment by Eilon** [comment]
Yes, the `dev` branch is the most recent code and has that one Information log. Do you feel that even just that one log is too noisy? Most log systems have ways of filtering out events - all the Microsoft ones have event names that start with `Microsoft...` if you want to filter them all out.

**Comment by danroth27** [comment]
@lodejard @rynowak @Eilon  We think at the Information level there should really only be one log event _per request_ from the framework - that a request happened.This should probably be done in hosting instead of in routing. All the other details about what happened for that request should probably be at the Verbose level.

**Comment by rynowak** [comment]
Fixed the attribute routing part: e61ebca
