### ISSUE TITLE
Any Plans to Implement VaryByParam?

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#2894]
Are there any plans to implement the MVC 5 VaryByParam property on ResponseCache and CacheProfile? Is there an alternative approach?

**Comment by Daniel15** [comment]
`ResponseCache` doesn't need `VaryByParam`. `ResponseCache` is purely client-side caching, and client-side caching is always based on the full URL including querystring parameters.

**Comment by RehanSaeed** [comment]
Ok, let me ask this in another way. Are there any plans on implementing a server side caching attribute that works similarly to the OutputCacheAttribute?

**Comment by tinchou** [comment]
It's been a year since @RehanSaeed asked the question. It looks like you guys had plans to implement it in the beta, then in the rc, then moved it to the backlog again...

Could you share any details about when server-side caching attributes will be available? I'm planning on using `IMemoryCache`, but it would be great to have this as an attribute!

Also, I see `CacheTagHelper` uses `IMemoryCache` and we can use that from Razor, but I don't think I'll be able to use that from a Controller. Maybe we could reuse that code?

Thanks!

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/responsecaching

**Comment by Tratcher** [comment]
@JunTaoLuo
