### ISSUE TITLE
DOM elements navigation in TagHelpers

### ISSUE THREAD

**Issue by sergeyzwezdin** [aspnet/Mvc#2940]
It would be very useful to be able to navigate parent DOM elements in TagHelper, not just current element.

For example:

```html
<form name="FormName">
   <input asp-some-tag-helper="test"/>
</form>
```

In this example it would be useful to have access to form's attributes from `asp-some-tag-helper`.

It seems pretty common scenario for Tag Helpers.

**Comment by Eilon** [comment]
You might have to arm-wrestle @DamianEdwards to get that feature :smile:

**Comment by sergeyzwezdin** [comment]
Is it already reported somewhere? :-)

**Comment by Eilon** [comment]
Not that I recall...

**Comment by DamianEdwards** [comment]
Very unlikely this will ever happen as a 1st class Tag Helper feature as we really don't want a DOM on the server. However, it should be possible to add it yourself by defining a Tag Helper for the parent elements you care about then adding the instance (or some other crafted structure) to the `Items` dictionary so that child Tag Helpers can pull it out again. You could even implement a full DOM that way if you wanted, if that's your prerogative :smile:

**Comment by sergeyzwezdin** [comment]
@DamianEdwards Could you show simple example of working with `Items`? It seems does not work.
