### ISSUE TITLE
UrlHelper throws NullReference when trying to manually render a page (to string)

### ISSUE THREAD

**Issue by promontis** [aspnet/Mvc#2949]
I'm trying to implement IViewService (https://github.com/IdentityServer/IdentityServer3/blob/master/source%2FCore%2FServices%2FIViewService.cs) in IdentityServer3 to get customized views. Note that every method returns a stream.

Currently, I'm trying to render a view using the aspnet5 stack to a string and return that as the stream. I stumbled upon this SO post: http://stackoverflow.com/questions/30362156/render-razor-view-to-string-in-asp-net-5

```
private async Task<string> RenderView(string path, ViewDataDictionary viewDataDictionary)
{
    using (var sw = new System.IO.StringWriter())
    {
        var viewResult = viewEngine.FindView(actionContext, path);

        var viewContext = new ViewContext(actionContext, viewResult.View, viewDataDictionary, new TempDataDictionary(httpContextAccessor, tempDataProvider), sw);

        await viewResult.View.RenderAsync(viewContext);
        sw.Flush();

        if (viewContext.ViewData != viewDataDictionary)
        {
            var keys = viewContext.ViewData.Keys.ToArray();
            foreach (var key in keys)
            {
                viewDataDictionary[key] = viewContext.ViewData[key];
            }
        }

        return sw.ToString();
    }
}
```

While that code works in an aspnet5 controller, it does not in IdentityServer3. I get a null reference exception in Microsoft.AspNet.Mvc.UrlHelper..ctor. Basically, the first parameter, IScopedInstance<ActionContext> contextAccessor, has a property value which is null.

So the question is: how to resolve that. How to get an 'active' ActionContext? I already tried to create a DefaultHttpContext instead of injecting the HttpContext via httpContextAccessor, but that throws an error that other services.

So I tried adding those services using...

```
var serviceCollection = new ServiceCollection();
serviceCollection.AddMvc();
serviceCollection.AddLogging();
var requestServices = serviceCollection.BuildServiceProvider();
                
var httpContext = new DefaultHttpContext
{ RequestServices = requestServices };
```

but eventually resulted in the same null reference exception in Microsoft.AspNet.Mvc.UrlHelper..ctor
Could you please help me out?

**Comment by rynowak** [comment]
A bunch of stuff in the stack (including `IUrlHelper`) DI's services which can be used to access the 'current context' for the scope. 

For instance in Razor the `IUrlHelper` will use the current context to access route values and use those to generate links. I'd suggest replacing the `IUrlHelper` with your own implementation since none of the data structures you'll need are available.

If you really need to fake 'current context', you can fake this by adding your own instance of `HttpContextAccessor` and `ScopedInstance<ActionContext>`. 

**But, beware! You're treading new ground here. The team hasn't spent much (or any) trying to make this kind of usage viable**.
