### ISSUE TITLE
Consider adding `IViewEngine` during `services.AddMvc()`

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#2960]
I ended up digging through locals to see that an `ICompositeViewEngine` was registered. I had tried at first to just depend on `IViewEngine`. For ease of accessing the view engine, would you consider adding an entry as `IViewEngine`, or is there some other thing I should have been injecting to get the current view engine?

**Comment by pranavkm** [comment]
* `ICompositeViewEngine` gives you access to all the potential view engines the application is configured to use (also accessible via `MvcViewOptions.ViewEngines`).
* `IRazorViewEngine` gives you access to default instance of the `RazorViewEngine`

> injecting to get the current view engine
If you're inside of a `RazorView` there're potential ways to access the view engine that created out. Outside of one, the notion of a current view engine instance doesn't make sense, since you have to query all the registered view engines to get to the view. The `ICompositeViewEngine` abstracts this for you.

**Comment by tuespetre** [comment]
Ah, thanks @pranavkm. I did try `IRazorViewEngine` but that had failed. Anyways, I found out that what I was trying to do was unnecessary. Thanks for your help!
