### ISSUE TITLE
Add data-main to ~ tag helper

### ISSUE THREAD

**Issue by Alexander-Taran** [aspnet/Mvc#2977]
For us to be able to point require js to starting point using ~url 
as in `<script src="~/lib/require.js" data-main="~/app/startup.js">`

**Comment by NTaylorMullen** [comment]
Razor tends to avoid consuming or modifying any `data-*` attributes. For instance you cannot bind any `TagHelper` attributes to `data-` (we restrict it). Reason behind this decision is due to the `data-` [spec](http://www.w3.org/html/wg/drafts/html/master/dom.html#embedding-custom-non-visible-data-with-the-data-*-attributes).

As an alternative you can do the following: `<script src="~/lib/require.js" data-main='@Url.Content("~/app/startup.js")'></script>`
