### ISSUE TITLE
How to remove Tag helpers for all the views?

### ISSUE THREAD

**Issue by NeelBhatt** [aspnet/Mvc#2999]
I have used below code for  `_ViewImports.cshtml`: 
```
@using MyNewMvc.Web
@using Microsoft.Framework.OptionsModel
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```
And as `_ViewImports.cshtml` provides namespaces which can be used by all other views.

I got to know that there is something like `@removeTagHelper "*` which is used to remove tag helpers.

But i guess it is for single page and does not work for `_ViewImports.cshtml`?

It might be because of below line?

`@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"`

As tag helpers is assigned for all the views and if we remove from `_ViewImports.cshtml` it means it is removed before even assigned!

This might be already resolved or might not be issue but just curious to ask.

**Comment by NTaylorMullen** [comment]
`@removeTagHelper` works in `_ViewImports.cshtml`.

If you have:

```
approot
- /Views
- - /About
- -  Index.cshtml
- - /Home
- -  _ViewImport.cshtml  // "Home"
- -  Index.cshtml
- - /Shared
- -  _ViewImport.cshtml // "Shared"
```

`/Shared/_ViewImport.cshtml`:
```
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```

`/Home/_ViewImport.cshtml`:
```
@removeTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
```

Your views will then have the following `TagHelper`s libs enabled:

`/Home/Index.cshtml`: No `TagHelper`s enabled.
`/About/Index.cshtml`: `Microsoft.AspNet.Mvc.TagHelpers` are enabled.

Are you seeing otherwise?

**Comment by NeelBhatt** [comment]
:+1: I was confused but now i am all clear! thanks for the response!

**Comment by NTaylorMullen** [comment]
Awesome! Glad I could help.
