### ISSUE TITLE
Rename `ModelMetadata.IsCollectionType`; perhaps provide real `IsCollectionType` as well??

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3022]
The `ModelMetadata.IsCollectionType` property actually checks whether `ModelType` implements `IEnumerable`.  Since this property is new in MVC 6, we could rename it to match the actual meaning -- `IsEnumerableType`.

Product code uses `ClosedGenericMatcher.ExtractGenericInterface()` to find `T` for `ICollection<T>` in a few places where `ModelMetadata` is available. These cases could be handled using `ModelMetadata.ElementMetadata` and a "real" `ModelMetadata.IsCollectionType` or `ModelMetadata.IsGenericCollectionType`.

Final step along these lines would be to add `ModelMetadata.TaskTypeParameter` or `ModelMetadata.TaskTypeParameterMetadata`. This could replace uses of `ClosedGenericMatcher.ExtractGenericInterface()` to find `T` for `Task<T>` -- another repeated gesture.

These changes would make `ModelMetadata` more usable and broadly useful. Would also avoid lower-level helper methods and repeated code -- in our code and in customer code.

**Comment by rynowak** [comment]
I think it would be fine to pivot on `IEnumerable` vs `ICollection` and have both. I'd say if this particular change is good cleanup, go ahead and do it.

Overall though, I'm skeptical about our ability to remove all uses of `ClosedGenericMatcher` or to move them "behind the scenes". The suggested changes for `Task<T>` seem like a bad fit in general because tasks are rarely used as/in model types.

**Comment by dougbu** [comment]
d8d0a1a
