### ISSUE TITLE
Discussion: Support model binding controller properties hidden using `new`?

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3028]
Separating a [discussion](https://github.com/aspnet/Mvc/pull/3023#discussion-diff-37700278) from PR #3023. Skipping a few details, here's the top-level comments:

@rynowak's [commented](https://github.com/aspnet/Mvc/pull/3023#discussion_r37765625)
> It should be totally viable to use `new` in a controller to hide services used by the `Controller` class itself.

@dougbu [commented](https://github.com/aspnet/Mvc/pull/3023#discussion_r37712297)
> Sounds like a lot of complication, especially given issues [potential incorrect settings] when `base.Property` would be properly initialized as-is.

**Comment by Eilon** [comment]
Shouldn't model binding on the controller at least roughly work like the rest of model binding anywhere else, and thus use model metadata? I agree it's a bit weird, but maybe that's just because we didn't consider those scenarios 5+ years ago when model metadata was invented.

But either way, hiding stuff with `new` is at least *slightly* esoteric, no?

**Comment by danroth27** [comment]
We don't think there is a real scenario that is blocked here. We can revisit this based on customer feedback.
