### ISSUE TITLE
DirectRouteProvider removed for Asp.Net MVC 6?

### ISSUE THREAD

**Issue by Dresel** [aspnet/Mvc#3107]
With Asp.Net 5.2 it was finally possible to hook into the attribute routing process for MVC and WebAPI with a DirectRouteProvider.

Correct me if I'm wrong, but it seemed that you removed that for 6.0?

How are we able to hook into the attribute routing process now? I would like to proxy generated attribute routes with my own routes for [localization support](https://github.com/Dresel/RouteLocalization/).

**Comment by rynowak** [comment]
Hi @Dresel 

We've changed the model for extending attribute routes in vNext. We don't expose the details of how the framework implements attribute routing so that we can evolve it in the future.

We've moved away from smaller extensibility points like `IDirectRouteProvider` to a larger metadata driven system that's customizable via conventions. Example: https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs

I think there's a way to do what you want - it's a little roundabout, but you'll be leveraging more of the built-in system and will benefit from any improvements we make in this area in the future.

You'd need a **filter** and a **convention** for this.

The convention will modify the set of actions to include all of your localized route templates (one-per-action) - that means duplicating actions where necessary. For each action, you will set the route template to a specific translation and then add the culture string to `ActionModel.RouteConstraints`. The simplest way to describe this is that it's a route value that you get when the attribute route for the action matches.

Your filter will implement `IResourceFilter` and apply to all actions. When it runs it will look for a route value 'culture' and set the request culture appropriately.

Pseudocode:
```
public class LocalizedRouteConvention : IApplicationConvention
{
    public void Apply(ApplicationModel application)
    {
        var controllersToAdd = new List<ControllerModel>();
        var controllersToRemove = new List<ControllerModel>();

        foreach (var controller in application.Controllers)
        {
            if (controller.Attributes.OfType<LocalizedRoute>().Any())
            {
                // Localized routes found at the controller level, create a copy for each translation and
                // remove the original.
                controllersToRemove.Add(controller);

                foreach (var translation in GetTranslations())
                {
                    var newController = new ControllerModel(controller);
                    newController.RouteContraints.Add(new RouteContraintAttribute("culture", translation.Culture");
                    newController.AttributeRoutes.Clear();
                    foreach (var route in controller.AttributeRoutes)
                    {
                        newController.AttributeRoutes.Add(route);
                    }

                    controllersToAdd.Add(newController);
                }
            }
        }

        foreach (var controller in controllersToRemove)
        {
            application.Controllers.Remove(controller);
        }

        foreach (var controller in controllersToAdd)
        {
            application.Controllers.Add(controller);
        }

        // Now iterate over the list of actions and do the same process. Take into account that if you
        // have a localized route on the controller, the action-level routes need to match that translation
        ...
    }
}

public class LocalizationFilter : IResourceFilter
{
    public void OnResourceExecuting(ResourceExecutingContext context)
    {
        #if DNX451
            Thread.CurrentThread.CurrentCulture = requestCulture.Culture;
            Thread.CurrentThread.CurrentUICulture = requestCulture.UICulture;
        #else
            CultureInfo.CurrentCulture = requestCulture.Culture;
            CultureInfo.CurrentUICulture = requestCulture.UICulture;
        #endif
    }
}
```
