### ISSUE TITLE
ViewComponents should respect the global @inherits declaration in _ViewImports

### ISSUE THREAD

**Issue by muratcakir** [aspnet/Mvc#3121]
At the moment this declaration does not seem to be applied to a ViewComponent

**Comment by Eilon** [comment]
@dougbu @pranavkm do you know if this is deliberate? This sounds like a bug to me.

**Comment by pranavkm** [comment]
It's not deliberate - they're treated as any other partial.

**Comment by dougbu** [comment]
On first glance, a view invoked from `ViewComponent.View()` should respect `_ViewImports.cshtml`. However we probably didn't implement this because view component views do not and (probably, think we have an issue open on this) should not respect `_Layout.cshtml`. Respecting `_ViewImports.cshtml` would introduce a new case where some of that file would be ignored or cause errors.

**Comment by Eilon** [comment]
But `_ViewImports` is different from `_ViewStart`. I agree they shouldn't run `_ViewStart`.

**Comment by rynowak** [comment]
Agree with @Eilon - all of this work was done before we had the separation. This needs to be updated.

**Comment by ajaybhargavb** [comment]
This seems to work fine for ViewComponents without the `@model` declaration. This issue could be related to https://github.com/aspnet/Mvc/issues/3144.

**Comment by ajaybhargavb** [comment]
Tracked by https://github.com/aspnet/Mvc/issues/3144. Closing this.
