### ISSUE TITLE
TempData support for Enum types

### ISSUE THREAD

**Issue by anfomin** [aspnet/Mvc#3141]
`SessionStateTempDataProvider` does not support `Enum` types but enums always can be converted to the underlying type and serialized to JSON. May be temp data provider should support enums?

**Comment by Eilon** [comment]
@pranavkm can you see if this is straightforward to add? If it's crazy complex or something then we should push out. Not sure how well enums will roundtrip in this scenario.

**Comment by Krusen** [comment]
I actually had a look at this a few weeks ago.

The only "issue" seems to be getting the value back. The `BsonReader` in Json.NET casts the value to `long` even though it knows it is an `int`. This means you can't do this:

```C#
MyEnum myEnum = (MyEnum) TempData["myEnum"];
```

Instead you will have to do either of these:

```C#
myEnum = (MyEnum)(long) TempData["myEnum"];
myEnum = Enum.Parse(typeof(MyEnum), TempData["myEnum"].ToString());
```

As far as I remember this is actually also currently the same when just storing and `int` in TempData because of boxing - `(int)(object)1L` doesn't compile.

I couldn't see any good reason why `BsonReader` does this and I was going to raise an issue about it but never got around to it.

**Comment by pranavkm** [comment]
@Krusen I filed a bug in Json.Net for the `BsonReader` behavior - https://github.com/JamesNK/Newtonsoft.Json/issues/692. For now, I was hoping to fix it by attempting to cast short-`long`s to `int`s since it also affects round tripping for regular int values.
