### ISSUE TITLE
Taghelper: Razor populated attribute value not accesible in taghelper but shows "Microsoft.AspNet.Razor.Runtime.TagHelpers.DefaultTagHelperContent"

### ISSUE THREAD

**Issue by IRooc** [aspnet/Mvc#3189]
When I have a razor template with
```HTML
<div mytag-demo="@Model.Title">
@Model.Title
</div>
```

and create a taghelper targeting "mytag-demo" the value in the taghelper is not the Title of the model object but "Microsoft.AspNet.Razor.Runtime.TagHelpers.DefaultTagHelperContent".

Taghelper demo:
```C#
	[HtmlTargetElement(Attributes = "mytag-demo")]
	public class MyTagDemoTagHelper : TagHelper
	{
		[HtmlAttributeName("mytag-demo")]
		public string MyTag { get; set; }

		public override void Process(TagHelperContext context, TagHelperOutput output)
		{
			output.Attributes.Add("data-mytagvalue", MyTag);
		}
	}

```
now it outputs

```HTML
<div data-mytagvalue="Microsoft.AspNet.Razor.Runtime.TagHelpers.DefaultTagHelperContent">
The Model Title
</div>
```

This behaviour was introduced in ```1.0.0-beta8-15653 ``` in the previous release ```1.0.0-beta8-15618``` it worked fine. Am I missing something or is this a bug?

**Comment by pranavkm** [comment]
Seems related to this - https://github.com/aspnet/Razor/commit/323befaaf10a4c3bf90f73153065b331a5e8ace0

cc @rynowak

**Comment by NTaylorMullen** [comment]
@rynowak Looks like we have a test gap in MVC for generic `TagHelper` cases that have attribute values intermixed with `@value`. 

https://github.com/aspnet/Mvc/blob/d8d0a1ab89d61713fe60ec4b5a2994b7907646a9/src/Microsoft.AspNet.Mvc.Razor/RazorPage.cs#L253

Is `ToString`d at codegen [here](https://github.com/aspnet/Razor/blob/dev/test/Microsoft.AspNet.Razor.Test/TestFiles/CodeGenerator/Output/ComplexTagHelpers.cs#L126) when a user intermingles `@`s.

I knew we had it for a reason :smile:. The right fix for this will probably be a code generation change to use `GetContent` rather than re-adding `ToString`

**Comment by NTaylorMullen** [comment]
Waitttt there's no test gap. The build fails.

**Comment by NTaylorMullen** [comment]
Thanks for the report. @rynowak has been fixed this via:
https://github.com/aspnet/Razor/commit/c9341ee3d7c75bc97ef0f825bac25b48bd74134b
https://github.com/aspnet/Mvc/commit/80add92de8ad839e26dba236c873f51ef039740d
