### ISSUE TITLE
Telemetry Source View resolution events feedback/thoughts

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Mvc#3203]
**Searched locations for `ViewResultViewFound` event**
In the `ViewResultViewFound` Telemetry Source event, I would like to know what locations it searched. Currently I only know this in the failure case.

**Scope around actual view execution**
Currently we have no `Before`/`After` which we can used to isolate how long the actual view took to execute. The current scope (`BeforeActionResult`/`AfterActionResult`) will include the resolution lookup time as well. @rynowak and co might be able to indicate if this difference would every be something other than trivial. If it is always going to be trivial then I'm cool with what we have, but if it could be something that could have perf issues, then it would be good to know the difference.

**Comment by rynowak** [comment]
Self assigning because I'm working on some parts of this:


> Searched locations for ViewResultViewFound event

I can't say that this is something we'll ever be able to do without some lateral thinking. We're moving away from the idea that that each request results in a 'search' for a view. The process of actually performing the search is very expensive. We need to think more about what the real scenario here is and see what can be done to solve it.


> Scope around actual view execution

Currently working on this as we're now in a position to provide it. This will also provide access to the `ViewContext` which was previously asked for.

**Comment by rynowak** [comment]
306776ff635d9cb0c0337650d30031403f35c63c for the scope around view execution

**Comment by Eilon** [comment]
Moving this to backlog for the rest of the work.

**Comment by danroth27** [comment]
@avanderhoorn Anything still need to be done here? Can this issue be closed?

**Comment by avanderhoorn** [comment]
I think this is all done. Thanks
