### ISSUE TITLE
IApplicationEnvironment returns NULL

### ISSUE THREAD

**Issue by alansangeeth** [aspnet/Mvc#3262]
I created a class library project and to read a file i used IApplicationEnvironment to get rootpath but it always returns NULL

    namespace TestLibrary{
        public Class TestClass{
                 IApplicationEnvironment _appEnvironment;
                 public void GetFile(){
                        File.OpenRead(_appEnvironment.ApplicationBasePath + "Content/tahoma.ttf");
                 }
         }
    }

Here _appEnvironment returns NULL

**Comment by rynowak** [comment]
There's no code here that would initialize `_appEnvironment`, its always going to be null.

If you want to access the app environment:
- write a class that takes it as a constructor argument
- register that class in DI
- inject it somewhere in your application so that the DI container creates it

If you want to provide a little more information about what you're trying to accomplish we can help.
