### ISSUE TITLE
Support JSON from body and form URL encoded at the same time

### ISSUE THREAD

**Issue by filipw** [aspnet/Mvc#3264]
In Web API there was a `FormUrlEncodedMediaTypeFormatter` so things just worked out of the box.

However, in MVC 6, where we have the concept of `BindingInfo` and `BindingSource`, using something like `BindingSource.Body` on a parameter seemingly prevents any attempts from trying to support FormUrlEncoded.

What is the correct approach in MVC 6?

**Comment by danroth27** [comment]
We don't have a form data based formatter in the box for MVC 6 because you can use the MVC model binding system to handle form data. 

> using something like  BindingSource.Body  on a parameter seemingly prevents any attempts from trying to support FormUrlEncoded.

You should be able to provide your own form data based formatter. Or you could just have two actions. How important is it in your scenarios to support both form data and other formats from the same action?

**Comment by paulsperanza** [comment]
So am I correct in assuming that an API controller in MVC 6 will always have a null value when applying a FromBody attribute to a parameter when the content-type is application/x-www-form-urlencoded for a post? This works in Web API and as far as I know the application/x-www-form-urlencoded is the recommended approach.

**Comment by Eilon** [comment]
Moving to backlog.

**Comment by danroth27** [comment]
No plans to provide a formatter that supports form data.
