### ISSUE TITLE
PhysicalFileResult should allow not rooted paths

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#3290]
We have a check in `PhysicalFileResult` that causes us to throw for non rooted paths. We should instead let the underlying filesystem \ working directory determine this without performing any checks.

**Comment by Eilon** [comment]
I believe we did this because the concept of a relative path is completely different between *nix and Windows. Whereas on Windows it's perhaps a bit easier to know what's a relative path and what isn't, on *nix they can look identical. We decided to avoid any confusion and just require/assume that the path provided is rooted.

**Comment by pranavkm** [comment]
Could we change it to not throw a FileNotFoundException? Maybe a `NotSupportedException` or the ever popuar `InvalidOperationException`? It was confusing since I thought I had the path specified incorrectly in my sample

**Comment by Eilon** [comment]
The question is, how would we know, in an OS-independent way? The idea for what we have currently is to say in the doc comment what you need to pass in, assume you got it right, and then let the underlying implementation from BCL talk to the OS and do whatever it wants.
