### ISSUE TITLE
Can't build source code.

### ISSUE THREAD

**Issue by SimonConrad** [aspnet/Mvc#3297]
Hi,
I'm quite new to asp.net5. I try to build mvc6 source code. I'm doing steps as in instruction https://github.com/aspnet/Mvc/wiki/Building-MVC. But when doing build from cmd I've got erros like below:

   Unable to resolve dependency System.Dynamic.Runtime 4.0.0
   Unable to resolve dependency System.Globalization.Calendars 4.0.0
   ...

   C:\Dev\Sandbox\ASP.NET5\mvc\src\Microsoft.AspNet.JsonPatch\project.json(0,0): error NU1002: The dependency System.Dynamic.Runtime 4.0.0 in project Microsoft.AspNet.JsonPatch does not support framework DNXCore,Version=v5.0.
   C:\Dev\Sandbox\ASP.NET5\mvc\src\Microsoft.AspNet.JsonPatch\project.json(0,0): error NU1002: The dependency System.Globalization.Calendars 4.0.0 in project Microsoft.AspNet.JsonPatch does not support framework DNXCore,Version=v5.0.
...

Could you please point my to the right direction how to build source code?

**Comment by Eilon** [comment]
That wiki page is incorrect so I deleted it.

In general all you need to do is clone the repo and run `build` from the root of the repo.

Do you see anywhere in the build output which NuGet feeds were used?

**Comment by SimonConrad** [comment]
Yes in the build output I've got:
Feeds used:
    https://nuget.org/api/v2/
    https://www.myget.org/F/aspnetmaster/api/v2/

Do you need anything more from the build output?

**Comment by BillKrat** [comment]
http://www.global-webnet.com/Adventures/post/ASPNET-VNext-how-to-setup-for-using-source-codeEnter-a-post-title

**Comment by SimonConrad** [comment]
@BillKrat this article does not make me any closer to build successfully the source. As I wrote I just pulled branch master from repo and run build.cmd. I suppose this build should end up successfully without even starting visual studio and running any any dnx commands...

**Comment by BillKrat** [comment]
Type in the following:

dnvm list

If it shows beta 5 is the default .net runtime then it won't build unless your environment is in sync.  The blog I wrote covers all the pieces I had to understand to build the source successfully.

**Comment by BillKrat** [comment]
The videos I reference on the link were instrumental in understanding how to work with code.

**Comment by pranavkm** [comment]
@BillKrat, could you try specifying `set BUILDCMD_RELEASE=beta7` prior to running build? Admittedly this isn't documented or pretty.

**Comment by BillKrat** [comment]
Very nice, I will try it and update my blog when  I get back (been on the road for last three weeks) and heading back home

This environment variable would be consistent with what we would expect for a multi-platform dev environment, so pretty would be relative and documentation understandably futile at this stage as things are in constant flux (judging by email traffic for my subscriptions).  

Excited about where things are going!

**Comment by SimonConrad** [comment]
The build.cmd is setting newer dnvm then beta7 that build crash against as wriiten in my first comment. So after setting BUILDCMD_RELEASE=beta7 it's actually better but I still have error:

C:\Dev\Sandbox\ASP.NET5\mvc\src\Microsoft.AspNet.Mvc.Formatters.Xml\SerializableErrorWrapper.cs(16,52): DNXCore,Version=v5.0 error CS0246: The type or namespace name 'IXmlSerializable' could not be found (are you missing a using directive or an assembly reference?)

when Building Microsoft.AspNet.Mvc.Formatters.Xml for DNXCore,Version=v5.0

**Comment by SimonConrad** [comment]
When simple get source code by downlad zip and run build I've got following:
Restoring packages for C:\Dev\Sandbox\ASP.NET5\Mvc-dev\test\WebSites\FormatterWebSite\pro
Unable to locate Dependency runtime.win7.System.Private.Uri >= 4.0.1-beta-23406
Unable to locate Dependency runtime.win7.System.Diagnostics.Debug >= 4.0.11-beta-23406
Unable to locate Dependency runtime.win7.System.Runtime.Extensions >= 4.0.11-beta-23406
Unable to locate Dependency runtime.win7.System.IO.FileSystem >= 4.0.1-beta-23406
Unable to locate Dependency runtime.win7.System.Globalization.Extensions >= 4.0.1-beta-23
Unable to locate Dependency runtime.win7.System.Net.Primitives >= 4.0.11-beta-23406
Unable to locate Dependency runtime.win7.System.Security.Cryptography.Algorithms >= 4.0.0
Unable to locate Dependency runtime.win7.System.Security.Cryptography.Encoding >= 4.0.0-b
Unable to locate Dependency runtime.win7.System.Security.Cryptography.X509Certificates >=
Unable to locate Dependency runtime.win7.System.IO.FileSystem.Watcher >= 4.0.0-beta-23406
Unable to locate Dependency runtime.win7.System.Console >= 4.0.0-beta-23406
Unable to locate Dependency runtime.win7.System.Net.Http >= 4.0.1-beta-23409

**Comment by SimonConrad** [comment]
Help anyone :) ??

**Comment by BillKrat** [comment]
Try the steps outlined in the following link for building the MVC project.  It will highlight the steps to insure DNVM, DNX, DNU and  GIT are in sync.

I have found that failed builds corrupt so you'll want to do a dnu restore --no-cache (ref following link) to ensure everything is correct.  Patience mau be required.

http://www.global-webnet.com/Adventures/post/ASPNET-MVC-The-design-time-host-build-failed…

**Comment by BillKrat** [comment]
I suggest using clone versus .zip so that once you build successful you can easily access from solution.

**Comment by SimonConrad** [comment]
As I wrote I clonned I'm on 2 day-ago comitt at branch dev/origin.

**Comment by BillKrat** [comment]
"When I just get source code by 'downlad zip' or be on 2 day-ago comitt at branch dev/origin and run build I've got following"

**Comment by SimonConrad** [comment]
@BillKrat thanks to step-by-step link. However I've got still questions.
1. On which branch are you? On dev and on master I cannot see tag 1.0.0-beta7 I can only see 6.0.0-beta7.
2. What do you men by cd ..\Hosting // Change to hosting folder ?
3. Is adding path to src needed in json ( "projects": [ "src", "test", "e:/github/mvc/src"],)? Can I just run .\build as in setps descriped and open solution in VS?

**Comment by BillKrat** [comment]
1.  I'm using GitShell which was installed in Step 3 of [THIS BLOG] (http://www.global-webnet.com/Adventures/post/ASPNET-VNext-how-to-setup-for-using-source-codeEnter-a-post-title).  If you reference figure 1 below you'll see that it is available and how I select it ([*more info on Step 4*](http://www.global-webnet.com/Adventures/post/ASPNET-VNext-how-to-setup-for-using-source-codeEnter-a-post-title))
2. I have two projects: MVC and Hosting.   The problem was that when I ran into issues (as you have) I corrupted more than just the MVC assemblies.   Now that I was fixing MVC it wouldn't build because it had dependencies on Hosting which was also corrupted.  I had to change to Hosting, fix it, and then switch back to MVC to rebuild it.
3. This is only needed when you want to create a new ASP.NET website and step through the source code.   As I ran into issues I found it helpful to step through [Dependency Injection](http://www.global-webnet.com/blog/post/2015/08/24/Dependency-Injection-in-ASPNET-vNext-(adding-Unity-container).aspx), [Configuration](http://www.global-webnet.com/Adventures/post/ASPNET-MVC-how-to-get-configjson-settings-(beta7)), [Hosting](http://www.global-webnet.com/Adventures/post/ASPNET-MVC-ServerMapPath), and [others](http://www.global-webnet.com/Adventures/post/ASPNET-MVC-RenderViewToString-in-MVC-6)

![gitshell](https://cloud.githubusercontent.com/assets/10552946/10436752/f6f98468-70ed-11e5-831f-93fb0fc2f0a5.png)
Figure 1

**Comment by BillKrat** [comment]
"Could you be so nice and please try to build branch dev tag 6.0.0-beta7? I see that every build has diffrent errors and it will be very helpful to me if we have same scenario..."

I am working on a project for a client that has to be done by the 15th - it is nose to the grindstone until then (burning the midnight oil).  I'll be on schedule but I promised my son dinner and a movie on Thursday night... After that I should be free to dig in and help you :)

**Comment by BillKrat** [comment]
BTW, the steps on the first blog link I sent you were done step-by-step for beta 7 ;)

**Comment by SimonConrad** [comment]
I have done build successfully :). However I succeded partially cause it was done against 1.0.0-beta5 runtime, still there're errors while building against 1.0.0-beta7 runtime.
Steps to reporoduce:
- Chose 1.0.0-beta5 runtime  // dnvm use 1.0.0-beta5 -r clr -arch x86 -p
- Being on dev branch choose 6.0.0-beta5 tag // git checkout 6.0.0-beta5
- Build // .\build
![dnvm](https://cloud.githubusercontent.com/assets/5357204/10475992/f4df306c-7249-11e5-8ed1-ecfbc2801be1.png)

**Comment by BillKrat** [comment]
Congrats!  Looks like you are good to go :) 

As for the build failing for Beta 7 - I duplicated build / DNU restore errors and documented them on the following link:

[GitHub MVC issue #3323] (https://github.com/aspnet/Mvc/issues/3323)

Note: you'll probably want to do the following:

   **DNVM alias default 1.0.0-beta5**

so that your active and **default** are referencing the same runtime.
