### ISSUE TITLE
Sample without dnx451

### ISSUE THREAD

**Issue by ShaneCourtrille** [aspnet/Mvc#3298]
Anyone coming from a non-Microsoft background (NodeJs, etc) or looking at developing a solution that can be deployed anywhere is likely going to want a pure dnxcore50 setup.  It would be helpful to see a sample that didn't include dnx451 to help work through issues via a known good setup.

**Comment by Eilon** [comment]
@ShaneCourtrille many of the samples work on both DNX451 and DNXCORE50, so it's just a matter of deleting the parts of the sample you don't want and you'll have a sample for either system. E.g. in https://github.com/aspnet/Mvc/tree/dev/samples/MvcSample.Web you can edit the `project.json` file to remove the `dnx451` target, as well as delete any part of the source code that mention it, and it should be a 100% functioning sample for dnxcore50. We don't intend to create any samples that necessarily target just one or the other target because most things work the same on both.
