### ISSUE TITLE
View renders incorrect values for model's indexed collection properties

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#3320]
I'm working on a line-of-business application where, on a certain 'edit' page, the user needs to be able to add and remove items to a grid and later click 'save'. 

For each row of the grid, I am looping through the items with a `for` loop to make use of the items' indices when posting back. The model binding itself seems to work appropriately. When stepping through the controller action, everything appears to be correct. I have even put a breakpoint on the `for` loop in the view to examine the immediate values of the model expressions and they seem correct... but the HTML that I get is errant:

1. When adding an item, the last item in the list is duplicated and the new item does not appear
2. When removing an item, the last item in the list is removed

Now, I am sorting the grid items in the controller action, and when I remove the sort, the new items are appropriately added to the end of the list, but removal is still errant.

I have tried:

1. The `@Html` helper syntax
2. The `asp-for="SomeProperty[i].SomeProperty"` syntax
3. The `asp-for="@Model.SomeProperty[i].SomeProperty"` syntax (my preferred, due to intellisense)

No matter which I use, the issue persists. It seems like the model data that gets bound from POST is being cached somewhere, so while the immediate values in the debugger show correctly, the model expressions in the view are translated into string keys and actually rendering out of the cache, and this view is only pulling from the 'real' model values (i.e. those passed in by the controller) when it can't find that key in the cache.

#### The View

```csharp
<form method="post">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Community</th>
                <th>Amount</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <select class="form-control"
                            asp-for="@Model.NewCommunity.CommunityId"
                            asp-items="@Model.CommunityOptions"></select>
                </td>
                <td>
                    <input type="text" class="form-control" asp-for="@Model.NewCommunity.Amount" />
                </td>
                <td style="text-align: center; vertical-align: middle">
                    <button type="submit"
                            class="btn btn-xs btn-success"
                            name="AddCommunity"
                            value="True">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </td>
            </tr>
            @for (var i = 0; i < Model.Communities.Count; i++)
            {
                <tr>
                    <td>
                        <input type="hidden" asp-for="@Model.Communities[i].CommunityId" />
                        <input type="hidden" asp-for="@Model.Communities[i].CommunityName" />
                        <input type="text" class="form-control" disabled
                               asp-for="@Model.Communities[i].CommunityName" />
                    </td>
                    <td>
                        <input type="text" class="form-control"
                               asp-for="@Model.Communities[i].Amount" />
                    </td>
                    <td style="text-align: center; vertical-align: middle">
                        <button type="submit"
                                name="RemoveCommunity"
                                value="@Model.Communities[i].CommunityId"
                                class="btn btn-xs btn-danger">
                            <span class="glyphicon glyphicon-remove"></span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>
```

#### The Model

```csharp
public class MyCompanyEditModel
{
    public CommunityItemViewModel NewCommunity { get; set; }

    public bool AddCommunity { get; set; }

    public Guid? RemoveCommunity { get; set; }

    public IList<CommunityItemViewModel> Communities { get; set; } = new List<CommunityItemViewModel>();

    public IList<SelectListItem> CommunityOptions { get; set; } = new List<SelectListItem>();
}

public class CommunityItemViewModel
{
    public Guid CommunityId { get; set; }

    public string CommunityName { get; set; }

    public decimal Amount { get; set; }
}
```

#### The Controller

```csharp
[AcceptVerbs("GET", "POST"), Route("{id}/Edit")]
public IActionResult Edit(int id, [FromForm]MyCompanyEditModel model)
{
    var entity = Database.Set<MyCompanyEntity>().Include(x => x.Communities).FirstOrDefault(x => x.Id == id);

    if (entity == null)
    {
        return HttpNotFound();
    }
    else if (Request.Method == "GET")
    {
        // GET logic removed for brevity
    }
    else if (Request.Method == "POST")
    {
        ModelState.Remove("NewCommunity.Amount");

        if (model.Save && ModelState.IsValid)
        {
            // "Save" logic removed for brevity
        }
        else if (model.AddCommunity)
        {
            model.Communities.Add(new CommunityItemViewModel
            {
                Amount = model.NewCommunity.Amount,
                CommunityId = model.NewCommunity.CommunityId,
                CommunityName = Enumerable.SingleOrDefault
                (
                    from c in Database.Communities
                    where c.Id == model.NewCommunity.CommunityId
                    select c.Name   
                )
            });

            model.Communities = model.Communities.OrderBy(c => c.CommunityName).ToList();

            model.NewCommunity = null;
        }
        else if (model.RemoveCommunity.HasValue)
        {
            model.Communities = model.Communities.Where(c => c.CommunityId != model.RemoveCommunity).ToList();
        }
    }

    model.CommunityOptions = Enumerable.ToList
    (
        from c in Database.Communities.ToList()
        where c.Active
        join f in model.Communities on c.Id equals f.CommunityId into lf
        where lf.Count() == 0
        orderby c.Name
        select new SelectListItem
        {
            Text = c.Name,
            Value = c.Id.ToString()
        }
    );

    return View(model);
}
```

**Comment by Eilon** [comment]
@tuespetre I suspect the issue is that there are model state entries for the list in the *original* sort order, and that's what gets displayed, regardless of any additional sorting that takes place.

So, let's say the data at first is in the order `A, B, C, D, E`, and the form is rendered in that order. Upon doing a POST, a model state entry will be created with `0=A, 1=B, 2=C, 3=D, 4=E`. During the same POST, the data is sorted to a different ordering, let's say `E, D, C, B, A`. Then the view is rendered. All the HTML helpers (both HTML helpers such as `@Html.TextBox(...)` and tag helpers such as `<input type="text" asp-for="..." />`) always prefer using a model state value, if it is available. So, despite the *data* being `E, D, C, B, A`, the HTML helpers will prefer reading the model state values for the keys `0, 1, 2, 3, 4`, which have the *original* sort order, which was `A, B, C, D, E`. The new *data* values are completely ignored.

I have some suggestions on how to address this:

1. Clear all the "communities" related model state. This will cause the HTML helpers to use the "live" Model data instead of the saved model state. The `ModelState` property has several helper methods on it to quickly clear out a set of model state.

2. If possible, do the sorting via a GET (which won't post any data), thus there won't be any model state. Depending on your app, this might be a bigger change. However, depending on the type of UI experience you want to deliver, that might work better.

3. Do the sorting on the client side. This avoids posting any data to the server. Ultimately, the server doesn't care about the layout of items in the HTML, so by doing all the sorting using JavaScript, the problem is avoided.

**Comment by tuespetre** [comment]
Even without sorting, the removal of items from the beginning or middle of the list does not work as expected. I would expect that, when I pass a model into a view, the view is going to use a model state dictionary created for the model I just passed in, not the one that came in from the `POST` request. I also would not like to have to use client-side scripting to solve what is fundamentally an undesirable server-side behavior.

**Comment by Eilon** [comment]
@tuespetre another thing I just thought of is to use a *stable* item index instead of using `i`, which has a different meaning on each request. Fundamentally the issue is that `@Model.Communities[i].CommunityId` has a completely different meaning on every request. Whether it's an insert/delete/sort, the item with index `i` will change. If you use a *stable* index such as the community id itself, I think you'll be fine. Ultimately I believe the model binder doesn't care a whole lot about what the index is, as long as it's consistent.

**Comment by tuespetre** [comment]
That makes a ton of sense, especially when considering that validation messages would need to be somehow associated with a given item in the list and maintain that association during rendering.

Thanks for your direction. I have now switched to using a dictionary and it is working perfectly:

```csharp
@foreach (var entry in Model.Communities)
{
    <tr>
        <td>
            <input type="hidden" 
                   asp-for="@Model.Communities[entry.Key].CommunityId" />
            <input type="hidden" 
                   asp-for="@Model.Communities[entry.Key].CommunityName" />
            <input type="text" class="form-control" disabled 
                   value="@Model.Communities[entry.Key].CommunityName" />
        </td>
        <td>
            <input type="text" class="form-control"
                   asp-for="@Model.Communities[entry.Key].Amount" />
        </td>
        <td style="text-align: center; vertical-align: middle">
            <button type="submit"
                    name="RemoveCommunity"
                    value="@Model.Communities[entry.Key].CommunityId"
                    class="btn btn-xs btn-danger">
                <span class="glyphicon glyphicon-remove"></span>
            </button>
        </td>
    </tr>
}
```

**Comment by Eilon** [comment]
Nice!
