### ISSUE TITLE
TagHelper and non-TagHelper select tags in a form don't work well together.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#3347]
If you have:
```HTML
<form asp-action="...">
    <select asp-for="...">
        ...
    </select>
    <select>
        <option value="...">...</option>
    </select>
</form>
```

The `<option>` tags in the second select will think that they're running under the first `<select asp-for="...">`. This can be fixed by transitioning the `SelectTagHelper` to properly use `TagHelperContext.Items` instead of relying on `ViewContext.FormContext.FormData`.

**Comment by Eilon** [comment]
Wow, call that OOPS!

@NTaylorMullen any idea if other tag helpers suffer from cross-talk like this?

**Comment by dougbu** [comment]
@Eilon this is a to-do item we've had since we added the `Items` property bag -- which came after the `<select>` and `<option>` tag helpers. The problem is a corner case related to lifetime of the information relative to `FormContext`. And the new `<form>` tag helper for rendering at the end is the only other one that communicates to children but that one is definitely using the correct mechanism (`FormContext`). So, no chance of similar issues elsewhere.

**Comment by Eilon** [comment]
@dougbu thanks, good to know.

**Comment by NTaylorMullen** [comment]
911dfc57b0a40b8feb415e9afcc90a9845d0ba5b
