### ISSUE TITLE
Writing "Raw" IHtmlContent

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3355]
As you know `IHtmlContent` always takes `IHtmlEncoder` as it's parameter.
There is a default `HtmlEncoder` implementation which is great and all.

But let's say I am 3rd party library maker, users passes a lot of `IHtmlContent`'s which I process, some of them have to be encoded while others not. How should I go about returning a "raw" html back to the user?

Implementing `IHtmlEncoder` which does nothing sounds kind of meeh :confused:
Wouldn't having a `IHtmlContent.WriteTo(TextWriter)` be more natural?
Or at least having a "raw" html encoder provided by the framework?

It is partially related to #3341, I now have a gist of why `HtmlString` overrides `ToString`, because it does not encode a value, even though it requires not null `IHtmlEncoder` :smiley:

**Comment by rynowak** [comment]
>  users passes a lot of IHtmlContent's which I process, some of them have to be encoded while others not. How should I go about returning a "raw" html back to the user?

That's the opposite of how this works. An `IHtmlContent` instance decides its own encoding behavior.

**Comment by Muchiachio** [comment]
So there will be no way to reuse default html helpers like `Html.InputFor`, `Html.CheckBoxFor` and so on?

**Comment by dougbu** [comment]
@Muchiachio methods such as `Html.InputFor()` return an `IHtmlContent` implementation that can be written to a `TextWriter` multiple times, perhaps with different encoder implementations. Could you show a sample of what you're trying to achieve?

Separately note the `writer` passed to `WriteTo()` will often get encoded content no matter what the passed `encoder` does. For example one use of a non-encoding `IHtmlContent` implementation is for HTML content from a Razor file. In that case the original text must be correctly encoded or the Razor parser will reject it.

> it does not encode a value, even though it requires not null `IHtmlEncoder`

That's by design and ensures the caller is correct. No `IHtmlContent.WriteTo()` method should ever be `null` values for either parameter.

**Comment by Muchiachio** [comment]
@dougbu one of the examples is to use html helper methods to write inputs, check boxes and any other not encoded stuff to typed grids. [Here's (MVC5)](http://mvc-grid.azurewebsites.net/Column/Encoding) one of the examples from the community.

In MVC5 `Html.CheckBox("Person_" + model.Id).ToString()` works, but how would you go about rendering `IHtmlContent` in MVC6, if it chooses how to be encoded by itself?

**Comment by dougbu** [comment]
In MVC 6, write the elements within `<pre>` tags. Avoid `ToString()` because we don't guarantee what that method returns. At best we implemented `ToString()` because we were too lazy to use `[DebuggerDisplay(...)]` :smiling_imp:
