### ISSUE TITLE
Pre-Compiling Razor Views

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Mvc#3369]
The default project template used to come with the following class commented out:

    public class RazorPreCompilation : RazorPreCompileModule
    {
        public RazorPreCompilation(IServiceProvider provider) : base(provider)
        {
            this.GenerateSymbols = true;
        }
    }

Jason on [StackOverflow](https://stackoverflow.com/questions/31156081/asp-net-5-application-deployment/31992843?noredirect=1#comment54302736_31992843) has highlighted the code below in one of the ASP.NET sample projects but there is no information on how or why it can be used.

    public void ConfigureServices(IServiceCollection services)
    {
        // Add MVC services to the services container
        services
            .AddMvc()
            .AddPrecompiledRazorViews(GetType().GetTypeInfo().Assembly);
    }

Is the `AddPrecompiledRazorViews` method required along side the above class or is it only for adding pre-compiled views in other satellite assemblies?

**Comment by pranavkm** [comment]
The first piece of code is the build step that produces precompiled views. It's changed a bit in beta8 so that you no longer need to pass the `IServiceProvider` in: https://github.com/aspnet/Mvc/blob/dev/samples/TagHelperSample.Web/compiler/preprocess/RazorPreCompilation.cs. Simply having this piece of code is equivalent to having the `MvcBuildViews` property from Mvc 5 projects on.

The piece of code in Startup tells the view engine to use precompiled views for rendering.
