### ISSUE TITLE
Use IsDefined over GetCustomAttribute<T> where possible

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#3416]
Consider using `Type.IsDefined` over `Type.GetCustomAttribute<T>`, where attribute instance is used only to check if attribute is defined. `Type.IsDefined` is ~2-3 times faster.

**Comment by pranavkm** [comment]
Seems to check out: http://stackoverflow.com/a/14719740 for desktop. Does this continue to be the case in CoreCLR?

**Comment by Muchiachio** [comment]
Did a quick test, seems to be about the same on CoreCLR.
I guess it still boils down to creating attribute instance vs not doing that.

**Comment by Eilon** [comment]
@rynowak any thoughts on this? Not sure if these even shows up on profiles. Do we call this much on a per-request basis or do we probably cache all the results of reflection anyway?

**Comment by rynowak** [comment]
> Do we call this much on a per-request basis or do we probably cache all the results of reflection anyway?

I'm not going to use a big scary word like *never*... but I'm not aware of any uncached reflection that doesn't have a bug tracking it. Doing a quick search turns up 1-2 cases that should be looked at.

 We don't in general spend time on these kind of micro-optimizations unless data tells us that it matters. However, I'm not opposed to this idea in general since it's an improvement in clarity as well.
