### ISSUE TITLE
ViewComponent with omitted optional argument(s) throws `InvalidOperationException`

### ISSUE THREAD

**Issue by dealdiane** [aspnet/Mvc#3473]
Suppose we have this view component in beta8:

    public class ExampleViewComponent
    {
        public Task<string> InvokeAsync(int id = 0)
        {
            return Task.FromResult("lorem ipsum");
        }
    }

Using this view component in a razor file by calling the method below:

    @await Component.InvokeAsync("Example")

will throw:

    InvalidOperationException: Could not find an 'Invoke' or 'InvokeAsync' method matching the parameters.

**Comment by dougbu** [comment]
@opiants to confirm the exact symptoms, that's the `Exception` thrown when you call `Component.InvokeAsync(23)` or something else without a type mismatch?

**Comment by dougbu** [comment]
Ah, thanx for updating the view component code so quickly :smiley_cat:

**Comment by dougbu** [comment]
Oops, looked like an update. Question remains.

**Comment by opiants** [comment]
@dougbu  Yep, that's the exception that's thrown when you call `Component.InvokeAsync("Example")`. It won't throw if you supply the correct argument though `Component.InvokeAsync("Example", 23)`. 

I didn't include the full stack trace because it was almost useless. They were just thread jumps. I could put it in if you think that it'll make a difference.

**Comment by dougbu** [comment]
@opiants in that case the `Exception` is correct and its `Message` describes a real issue in your `.cshtml`. Are you suggesting it's messy that the arguments to `InvokeAsync()` are not correctly-typed -- and the editor didn't highlight the issue? If so, that's a known restriction of the current view component system.

Separately the title of this issue seems incorrect. The type mismatch is caught in the same way (at runtime) for required parameters.

**Comment by opiants** [comment]
@dougbu I don't understand how that can be correct though. It shouldn't throw an error and should just pass in the default value of the **optional** parameter. It would defeat the purpose of having optional parameters if I have to pass it all the time.

**Comment by dougbu** [comment]
@opiants you're not leaving the value out, you're providing an argument of the wrong type.

**Comment by dougbu** [comment]
Oh, wait. My comment was wrong.

**Comment by dougbu** [comment]
Sorry, my test project had an overload hiding the issue here. Looks like our method lookups cannot handle omitted arguments.

One workaround is to switch from optional parameters to multiple overloads. E.g.
``` c#
    public Task<string> InvokeAsync()
    {
        return Task.FromResult("lorem ipsum");
    }
    public Task<string> InvokeAsync(int id)
    {
        return Task.FromResult("lorem ipsum" + id);
    }
```

**Comment by opiants** [comment]
@dougbu Yes, that does work. That is an acceptable workaround but should this be tagged as bug though?

**Comment by dougbu** [comment]
Perhaps but we generally leave feature / enhancement / bug determinations to the triage team.

**Comment by rynowak** [comment]
> That is an acceptable workaround but should this be tagged as bug though?

@opiants - we're considering a fresh take on this API altogether. Something that looks more like your code just calling into your code. That design change will address a number of points of confusion and limitations of the current design.

#612 is probably the best representation of our current thinking

**Comment by opiants** [comment]
Awesome. Yes, I do think the proposed methods there are better that what it is currently. Any guestimate on when rc2 might roll out? Are we talking about sometime in Dec?

**Comment by dougbu** [comment]
The public [roadmap](https://github.com/aspnet/Home/wiki/Roadmap) has not been updated recently. Expect some news soon.

**Comment by danroth27** [comment]
See #612
