### ISSUE TITLE
Expose DefaultHtmlGenerator internal methods to deriving types

### ISSUE THREAD

**Issue by klesniewski** [aspnet/Mvc#3520]
I am developing custom tag helpers, which in API will be similar to built-in tag helpers. I found, that a lot of code, which could be reused, is implemented in `DefaultHtmlGenerator` as `internal` methods and therefore not available for reuse in deriving classes. Adding `protected` keyword could make it also available for reuse, but on the other hand would form a contract, on which people will depend.

Is it a good idea to mark `internal` methods as `protected` and expose them for reuse, or should I rather create my own generator and copy the internal functionality I need?

**Comment by dougbu** [comment]
`protected` won't work because the methods are not intended just for `DefaultHtmlGenerator` and its subclasses. They're used in the implementation of some `protected virtual` methods in `DefaultHtmlGenerator` and elsewhere. Further, all `internal` methods in `DefaultHtmlGenerator` are also `static` and some are referenced from code that does not have an available `IHtmlGenerator`.

If these methods need to be `public`, we'd extend both `IHtmlGenerator` (to include the methods) and `IHtmlHelper` (to include an `IHtmlGenerator` property or wrappers for the new `IHtmlGenerator` methods).

Could you provide more information on your scenario and the exact method or methods you need to call?

**Comment by klesniewski** [comment]
According to MSDN documentation and [these StackOverflow answers](http://stackoverflow.com/q/585859/1537441) marking method as `protected internal` makes it accessible in the same assembly **plus** in derived classes. There would be no need to make them `public`, since they would preserve their current accessibility level plus if someone would like to take advantage of `DefaultHtmlGenerator` it would be possible through derivation.

I am building a tag helper to display an orderable table, where given list of items table is generated (headers are inferred from items array). The table supports ordering items using drag and drop, where table can be part of a larger form and be submitted on pressing save rather than on element drop.

Since I am using something like `asp-for` with `ModelExpression` and I need to retrieve name of the field to be used I use the `GetFullHtmlFieldName` method. I also did use `GetValidationAttributes` method, since validation support will be also helpful for my element. Since `GetValidationAttributes` uses `GetClientValidationRules` method, which is public, I added dependency on `IHtmlGenerator` (the method has further dependency on `IClientModelValidatorProvider` and I didn't want to go that deep into details).

**Comment by klesniewski** [comment]
I looked into `GetValidationAttributes` and it actually doesn't apply to my case, since I do not have any client side validation for ordering items in tables. In the end I am using only `GetFullHtmlFieldName`, which is one-liner. Looks like after all I do not need `DefaultHtmlGenerator` private methods. Not sure if it wouldn't be beneficial in other cases though.

**Comment by danroth27** [comment]
Looks like there is no direct ask to make these methods public. We can reevaluate as requirements arise.
