### ISSUE TITLE
RangeAttribute should be localized with 3 parameters

### ISSUE THREAD

**Issue by Anderman** [aspnet/Mvc#3537]
RangeAttribute has 3 paramaters and should be localized like

_stringLocalizer[Attribute.ErrorMessage,displayName, min,max]

**Comment by Eilon** [comment]
@Anderman can you explain what the problem is? The string localizer just needs to get a resource string. The formatting of the resource string is done by Data Annotations, so there's no need for the string localizer to do it itself. In fact, I don't think it *can* do it because the information isn't even available.

**Comment by Eilon** [comment]
I chatted with @kirthik and @dougbu and I understand this now, and I agree it's a bug - sorry for the confusion.

Apparently @DamianEdwards had a solution to this here: https://github.com/DamianEdwards/i18nStarterWeb/blob/master/src/Microsoft.AspNet.Mvc.Localization/ValidationAttributeLocalizerOfT.cs

So we need to bring that behavior back in.

**Comment by Anderman** [comment]
@Eilon No problem, Sorry for the unclear issue description. I just created my Json implementation of the <IStringLocalizer> and did some testing

**Comment by Eilon** [comment]
@Anderman cool, thanks!

**Comment by ryanbrandenburg** [comment]
Closed in #3649
