### ISSUE TITLE
JSON serialization performance investigation

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#3542]
Hi @DamianEdwards + MVC devs working on performance

I'm going to do some more work on json.net perf and allocations and I'd like to get a discussion going about optimizing json.net performance in MVC when serializing and deserializing. We can pool knowledge and figure out what hotspots you can see and what each side can change to eliminate them.

An MVC dev at MVP Summit (sorry I've forgotten your name, please say hi) mentioned the buffer that the reader/writers allocates as something to look at. I wrote some code to potentially handle that but I'd like to hear more about what you are seeing.

Damian have you found anything when profiling the JSON serialization benchmark at https://github.com/aspnet/benchmarks? Has anyone else of the MVC team seen anything that was slowing down MVC's JSON serialization?

**Comment by JamesNK** [comment]
Work in progress API for Json.NET to utilize a buffer pool - https://github.com/JamesNK/Newtonsoft.Json/commit/ac1a46bd146438da79f2550f031d7b903186682f

**Comment by rynowak** [comment]
Hi James,

It was I that brought up buffer pooling. Let me grab some data really quick based on the current state of things.

**Comment by rynowak** [comment]
Here's some data for allocations. I'm using this sample, and doing 3000 requests. 

```
        [HttpPost]
        public IActionResult AddPet([FromBody] Pet pet)
        {
            if (!ModelState.IsValid)
            {
                return new BadRequestObjectResult(ModelState);
            }

            Repository.AddPet(pet); // Does nothing

            return new CreatedAtRouteResult("FindPetById", new { id = pet.Id }, pet);
        }
```
https://github.com/rynowak/mvc-sandbox/blob/master/workloads/MediumApi/Controllers/PetController.cs#L43

The posted data looks like this:
```
{
  "category" : {
    "id" : 2,
    "name" : "Cats"
  },
  "name" : "fluffy",
  "status" : "available"
}
```

This includes both serialization and deserialization, but is pretty close to an e2e for an API. The only thing missing is actually doing something with the data :laughing: This is absolutely a 'tiny' sample of serialization, deserialization. We can get to larger samples at some point which might be more interesting, but this is one I've been iterating on.

For this exercise, I bumped up `Newtonsoft.Json` to `8.0.1`. I also made a private build of Kestrel with workarounds for aspnet/KestrelHttpServer#334 and aspnet/KestrelHttpServer#371

This is the high-level view. I'm happy to say that almost everything here that's 'above the fold' is actively being worked on.

![image](https://cloud.githubusercontent.com/assets/1430011/11124519/514e15ca-891a-11e5-82e6-88a4db8a59a9.png)

Our total allocation in bytes here is is 63.7mb. Kestrel's memory pool grew by 3.8mb during this benchmark (shows up under `byte[]`) which is a variable factor based on server load. So let's fudge the numbers and say that 60mb is our 'working' number.

Drilling down into `char[]` - this is what we discussed at MVP summit:
![image](https://cloud.githubusercontent.com/assets/1430011/11124750/54eb4a30-891b-11e5-8284-e90e0ad1fe85.png)

So, the buffers that get allocated by `JsonTextReader` in this case are worth about 10% of the total allocated bytes. @sokket - this is another place where we will plug in your memory pool :+1: 

The buffers used by `JsonTextWriter` in this case don't really amount to much for this case.

Regarding `JsonSerializer` - what can we do to mitigate these allocations. Generally `JsonSerializerSettings` aren't mutated after startup. Can we pool these? Is sharing a single instance per-settings safe?

The other item that jumps out at me is `JsonPosition[]` at 456,000 bytes (`JsonReader.ctor()`/`JsonWriter.ctor()`). Looking at the code, I'm not sure much can be done.


Looking at `Linq` there's one boxed enumerator allocated by Json.NET:
![image](https://cloud.githubusercontent.com/assets/1430011/11125230/a4a608f6-891d-11e5-89f5-ea1dc7a5f014.png)

![image](https://cloud.githubusercontent.com/assets/1430011/11125247/bb793cf6-891d-11e5-9b32-a9b48da60329.png)

It's not a critical source of allocations, but it could easily be turned into a `for` over `this.Items` to avoid the boxing. It's about 0.6% of the total bytes, so worth doing if the fix is simple.
```
foreach (JsonProperty current in this)
{
    if (string.Equals(propertyName, current.PropertyName, comparisonType))
    {
        return current;
    }
}
```

Here's all allocations with `Json` in the name. Let me know if anything else jumps out at you as being something we could improve:
![image](https://cloud.githubusercontent.com/assets/1430011/11125383/81818d90-891e-11e5-81e8-4148579942a3.png)

**Comment by rynowak** [comment]
Give me a min to reload, and I'll be back with sampling data.

**Comment by rynowak** [comment]
Ok, so here's sampling data for the same sample and input.

Looking at the call-tree overall would be pretty hard to do over github, so here's a high-level picture via table. In this data all the code that runs once we reach routing represents 100%. I'm ignoring everything the server does to get us into middleware, and everything the server does once we finish writing to the stream.

| Feature                            | Feature Area | Inclusive % |
|------------------------------------|--------------|------------:|
| Routing                            | Dispatching  |       4.45% |
| Request Services Creation          | Dispatching  |       3.45% |
| Action Selection                   | Dispatching  |       6.89% |
| Controller Factory                 | Invoker      |       3.45% |
| Misc Invoker Overhead              | Invoker      |      12.06% |
| Input Conneg                       | Input        |       3.45% |
| JsonSerializer.DeserializeInternal | Input        |      12.07% |
| Validation                         | Input        |       18,97 |
| Misc ModelBinding Overhead         | Input        |       5.17% |
| Read Form/Query                    | Input        |       3.45% |
| JsonSerializer.SerializeInternal   | Output       |       1.72% |
| Flush                              | Output       |       6.90% |
| Link Generation                    | Output       |      10.34% |
| Output Conneg                      | Output       |      10.35% |

**A few takeaways from this:**

We still have a lot of framework overhead around model binding. We've done a little here, but not nearly enough. Validation is too expensive. We're looking to make it much better. I call out these areas specifically because their cost will scale up with the size of the input data. Most of the other feature areas here are fixed costs and have very nice scaling (or no scaling) as your app grows.

Output conneg and link generation are pigs for what they do.

Flush issue is tracked: #3501

It would be nice to see reading Json go faster. Output seems plenty fast. We should try bigger workloads to verify that.

Zoomed in to `JsonSerializer.DeserializeInternal`
![image](https://cloud.githubusercontent.com/assets/1430011/11126352/54bf779a-8923-11e5-9483-7f19a9c0f2d2.png)

@JamesNK - hopeful you can help us here with background or guidance for more investigation. I haven't done a deep dive into this yet. I just wanted to put the numbers into context and help you see what I'm seeing.

Zoomed in to `JsonSerializer.SerializeInternal`
![image](https://cloud.githubusercontent.com/assets/1430011/11126376/7963cf2e-8923-11e5-9d1e-24d42f333394.png)

**Comment by sokket** [comment]
Fantastic write up @rynowak, this is really interesting! I made some changes to the BufferPool yesterday that might help...there's now a Shared instance on the ManagedBufferPool that might make it easier to plug into the pipeline here.

**Comment by JamesNK** [comment]
Hey Ryan, perfect, this is just what I was thinking of

> So, the buffers that get allocated by JsonTextReader in this case are worth about 10% of the total allocated bytes. @sokket - this is another place where we will plug in your memory pool :+1:

> The buffers used by JsonTextWriter in this case don't really amount to much for this case.

The writer buffer starts out very small, `new char[32]` off the top of my head. It will grow if you have large strings with escaped characters (eg, new line). It would be worth looking have a benchmark with larger data.

> Regarding JsonSerializer - what can we do to mitigate these allocations. Generally JsonSerializerSettings aren't mutated after startup. Can we pool these? Is sharing a single instance per-settings safe?

JsonSerializer is thread safe. @DamianEdwards is already reusing it in his benchmark. You could have a single instance but you would need to know when to recreate it if JsonSerializerSettings changes. It is exposed publicly and there is no event to say that it has been modified.

> The other item that jumps out at me is JsonPosition[] at 456,000 bytes (JsonReader.ctor()/JsonWriter.ctor()). Looking at the code, I'm not sure much can be done.

If you want to get crazy with pooling, you could do something where you pool JsonTextReaders/JsonTextWriters. They don't allow you to change the underlying TextReader/TextWriter, but if you have your own TextReader/TextWriter that you can reset and point to a new input/output stream then you could reuse them.

> Looking at Linq there's one boxed enumerator allocated by Json.NET:

That happens when the JSON property name case doesn't match the .NET class property name case. I've not benchmarked that before. Looks simple enough to fix.

> It would be nice to see reading Json go faster.

It would be great to have someone other than me - whether it is the ASP.NET team or CoreFX team - look and comes up with suggestions. I've done most of what I can think of.

**Comment by rynowak** [comment]
> It would be great to have someone other than me - whether it is the ASP.NET team or CoreFX team - look and comes up with suggestions. I've done most of what I can think of.

I spent a little time this morning - will look more later.

**A few thoughts:**

------------------------

We don't have a sync implementation of `Read` in Kestrel right now. There's some friction here because of this. I know you've closed issues in the past that request an `async` implementation of JSON.NET. We might find that one of these two things need to budge if we look at bigger data-sets. 

For now, a bespoke `Read()` implementation in Kestrel would be an improvement. We pay the cost of all of the async goop without getting any benefit. /cc @DamianEdwards @lodejard 

------------------------

Does it make sense in JSON.NET to enable and a "fast-path" for things like `int` and `string` where no converters or other types of extensibility are involved? Thinking in psuedocode something like "if the next token is a string, I can just set the property directly".

As you said, the code here has been extensively profiled and analyzed. If there's any gains to be had it's going to come from *doing less*. The idea here is to optimize a few common cases where extensibility isn't in use.

For context, I'm looking at `JsonSerializerInternalReader.PopulateObject` where you the code is looping through properties. The idea would be to skip over looking up a converter, calling `ReadForType` and skip over the bulk of stuff in `SetPropertyValue`

**Comment by JamesNK** [comment]
You don't know whether to just go ahead and set the property until you've checked that there is no customization going on, and there are a lot of places where customization could come from.

However I have thought about this in the past. There is already caching in contracts but it is denormalized. As you can see in CalculatePropertyDetails and GetConverter, there is a lot of checking in different places for the same setting.

e.g.
1. Is a converter defined on the property?
2. Is a converter defined on the class for members?
3. Is a converter defined on the property of the class for members?
4. Is a converter defined against the property type?
5. Has a converter been passed in?

Steps 1-4 could be squished together into a single check by having a more normalized cache. That cache could then be hit repeatedly for the half-dozen (dozen?) settings used.

**Comment by JamesNK** [comment]
> I know you've closed issues in the past that request an async implementation of JSON.NET.

Adding async to Json.NET would be a huge amount of work.

**Comment by rynowak** [comment]
> If an optimized version of Read in Kestrel is easy then do that. 

We need this as well for the XML formatters if we care about their perf because they don't go async.

I realize that it would be a huge amount of work to create an async parser. One middle-ground might be an optimized experience for when we can read the request body in a single shot.

That would look like:
```
var byteBuffer = _pool.Take(...);
var charBuffer = _pool.Take(...);

var encoder = Encoding.CreateEncoder();

var contentLength = int.Parse(request.Headers.ContentLength);
var read = await _stream.Read(byteBuffer.Array, byteBuffer.Offset, contentLength);

encoding.GetChars(....);

var jsonReader = new CustomJsonTextReader(charBuffer);
return _serializer.Deserialize(reader, type);

```

This is obviously for a special/limited case, but it's a very common one.

If I find some time today I'll try it out. I need to talk with people who understand Kestrel better about all of these issues.

**Comment by sokket** [comment]
@rynowak The managed buffer pool (currently) only lets you Rent a primitive array (ie ```byte[]``` or ```char[]```); do you need it to be able to rent Span<T> (per your example) or are arrays fine?

The NativeBufferPool rents ```Span<T>``` since it assumes the buffers will be used for PInvoke calls that require Pointers.

**Comment by rynowak** [comment]
This is all psuedocode :+1: I only need arrays.

**I still need the ability to rent non-primitive arrays.** But let's have that discussion offline and not pollute this thread.

**Comment by JamesNK** [comment]
> This is obviously for a special/limited case, but it's a very common one.

You wouldn't need a custom JsonReader to do that, you could implement your own TextReader that preloads characters and use it if the content length is sub N characters. JsonTextReader doesn't care how TextReader gets its data.

**Comment by JamesNK** [comment]
Oh, and as bonus you could now simply pool the JsonTextReaders that are over the top of your simple TextReader. Reset the position, over write the buffer and you are good to go. That would save creating a new StreamReader, JsonTextReader, List<JsonPosition> and JsonPosition[] for each request.

**Comment by rynowak** [comment]
Sounds promising. Now I'm excited to try this :+1:

**Comment by JamesNK** [comment]
I've uploaded a new beta of 8.0.1 that includes the buffer pooling API and fixes the foreach allocation:
https://www.nuget.org/packages/Newtonsoft.Json/8.0.1-beta2

**Comment by rynowak** [comment]
Awesome! Thanks @JamesNK :fireworks: 

@sokket and I have been working on a spike to integrate the CoreFX buffer pooling work here. Hopefully we'll see these two converge sometime in RC2. https://github.com/sokket/Mvc/commit/9c9bd8fced172434b70ca10c194560007a9cbc23

**Comment by rynowak** [comment]
@JamesNK - any thoughts on reducing `JsonSerializer` allocations here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Formatters.Json/JsonInputFormatter.cs#L83

Obviously we could use pooling here, and detach the event handler before returning the serializer to the pool. Ideally we'd have a pool of 1 :laughing:

**Comment by JamesNK** [comment]
Is there an abstraction for getting the current InputFormatterContext? You could have a single instance with an event attached that uses that abstraction to get the context. As far as I can tell that is the only state that event cares about.

**Comment by rynowak** [comment]
> Is there an abstraction for getting the current InputFormatterContext?

Nope :laughing: That would be `InputFormatterContext.Current`. 

We'd need a 'state' parameter to be plumbed through to the `ErrorEventArgs` to be able to do this. It's not good enough to close over something in a lambda, because we could be called with errors from another thread.

We might have to do traditional object pooling here.

**Comment by davidfowl** [comment]
@JamesNK that's a pretty common pattern to avoid allocating closures for delegates. It would be great if we could add something like that.

**Comment by JamesNK** [comment]
There is already a Context property on JsonSerializer that can be used to pass around state while serializing and deserializing. I'm afraid you can't have your cake (single JsonSerializer instance) and eat it too (state). I think you will have to pool.

**Comment by davidfowl** [comment]
I could be part of the call instead of being attached to the instance

**Comment by JamesNK** [comment]
JsonSerializer is already there for state. It doesn't make sense to have state on the serializer and to have to pass it in.

**Comment by ArunBhusal** [comment]
Awesome article.Thank you.

**Comment by rynowak** [comment]
For anyone watching this thread, we're in a bit of a holding pattern on integrating `System.Buffers` while they lock down the last few aspects of that API.

https://github.com/dotnet/corefx/issues/4547

We've made progress on many other smaller items that affect API sites in the meantime. I'm really happy to report that the 63mb allocations number that was quoted above is now down to 44mb on desktop for that scenario, or a lean 38mb :scream: on CoreCLR. 

**Desktop**
![image](https://cloud.githubusercontent.com/assets/1430011/11661471/ea6ab328-9d86-11e5-98b0-11a884caa30f.png)

**CoreCLR**
![image](https://cloud.githubusercontent.com/assets/1430011/11661509/19e4b202-9d87-11e5-8dfb-bcf1b2d24de9.png)


Some of these improvements come from measuring in a more accurately and many of them from the work being done on Kestrel. Work is ongoing on the most of these things at the top of the list.

**Comment by JamesNK** [comment]
Newtonsoft.Json 8.0.1 is out and has a hook for `System.Buffers`. Is there anything else to do on the json.net side?

**Comment by rynowak** [comment]
Here's the same benchmark, about a month later. We're in the midst of a deep-dive on content-type/content-negotiation right now so you can expect a reduction in allocations along the lines of another 2mb or so.

Notable improvements:
- Buffer pooling (`char[]`)
- Enumerator not getting boxed (`Enumerator<JsonProperty`)
- Using the correct contract resolver (`string`)
- Various routing improvements (`string`, `StringBuilder` `Dictionary<string, object>`, `RouteValueDictionary`)

**Only CoreCLR this time**

**Memory**
![image](https://cloud.githubusercontent.com/assets/1430011/12126356/98fab6b6-b3a5-11e5-9e22-a09847f599e1.png)


**CPU Time**

(I don't have access to dotTrace at the moment). Will add when I do.

**Comment by rynowak** [comment]
> Is there anything else to do on the json.net side?

I'm not aware of anything right now. If anything jumps out from the CPU profile, I'll let you know.

**Comment by rynowak** [comment]
Updated here with some CPU profiles. I don't have anything else from a JSON.NET point of view. For this benchmark, a 2% improvement in JSON.NET's straight line performance would go completely unnoticed in the vast ocean of MVC.

We need to finish our tracked work for this scenario more than anything.

**Comment by JamesNK** [comment]
Ok, looks good to me. There are a couple of minor bugs in 8.0.1 (deserializing a bool as a string, serializing objects with events using the Newtonsoft.Json PCL259 dll). Few people will hit them but it breaks those that do so I'm going to release 8.0.2 with fixes in a week. I'll post here when I do.

**Comment by rynowak** [comment]
OK thanks for the heads up. It's no trouble for us to update to 8.0.2 when that's available.

**Comment by rynowak** [comment]
Going to close this issue for now. Reopen if you think there's more to do/discuss.

**Comment by sokket** [comment]
@JamesNK - did you have any trouble incorporating the System.Buffers code into JSON.NET? I'd love to hear your feedback about how easy / difficult it was to use and if there are any features you would like to see in it.

**Comment by JamesNK** [comment]
It was fine. I think the only thing I was a little unsure about was documentation for best practices around Dispose/Finalize of objects that own rented buffers.

i.e. should all classes that use a buffer in a class field implement dispose and/or Finalize to return the buffer.

I settled on ensuring the buffer was returned in Dispose but I'm curious whether a Finalize is also recommended.

**Comment by sokket** [comment]
Hmm good feedback. I'm working on documentation now so I'll some recommendations around that. Thanks for the feedback! If you think of any more feedback, feel free to shoot me an email

**Comment by rynowak** [comment]
> I settled on ensuring the buffer was returned in Dispose but I'm curious whether a finalizer is also recommended.

I wouldn't use a finalizer. There's no native resource being managed, and it's not an error to 'forget' pooled memory, just suboptimal. By that I mean that if you fail to return pooled memory it's not actually leaked.

**Comment by JamesNK** [comment]
It's it leaked though? The array will never be returned to the pool and won't be usable again. Eventually the pool will be filled up with unreturned arrays.

**Comment by rynowak** [comment]
The `System.Buffers` pool holds **returned** items, not **checked out** items.

**Comment by sokket** [comment]
@rynowak That is an implementation detail that is hidden...any array that is Rented **must** be returned otherwise it is a leak; while it may not be the typical kind of memory leak, it is still a leak. Things that utilize the Pool should use the Dispose pattern (ideally)

**Comment by JamesNK** [comment]
@rynowak I didn't know that. Clever.

@sokket Should a Finalizer be added to ensure arrays from objects that weren't explicitly disposed are returned?

**Comment by sokket** [comment]
@JamesNK I would follow the Dispose pattern instead of relying on a finalizer; finalizers add GC overhead and might not be run in a timely manor

**Comment by rynowak** [comment]
Despite being an implementation detail, this is the kind of thing that traditionally can't be changed in a future version without also adding some guardrails (like leak tracking and automated cleanup). People will code and ship working (but non-optimal) apps -- you will break them by turning this into an unrecoverable leak.

> I would follow the Dispose pattern instead of relying on a finalizer; finalizers add GC overhead and might not be run in a timely manor

Finalizers are used all over the framework to return avoid leaking native resources when a disposable type isn't handled correctly. If the memory returned from the buffer pool can leak, that makes it a native resource.

**Comment by JamesNK** [comment]
Properly disposed objects won't ever run the finalizer because of `GC.SuppressFinalize` in the dispose, and running a finalizer seems preferable to me over a possible memory leak when the user forgets to dispose.

**Comment by sokket** [comment]
@rynowak I'll let @KrzysztofCwalina speak more to the Dispose vs Finalizer issue, he knows much more about that than I do.

The reason I recommend using the Dispose pattern for the buffers is because we want to eventually be able to use native memory to back a pool; by setting the precedent that you **must** return Rented arrays, it will help avoid unmanaged leaks when we add a native pool since the usage pattern will already be set.

**Comment by KrzysztofCwalina** [comment]
Any type that holds rented buffers needs to be Disposable. I think we are in agreement here, correct?

As to the finalizer, I think components should add it, because pooled memory is a manually managed resources, just like native memory, opened handles, etc. Finalizers are for manually managed lifetimes, not just for "native memory". 

Separatelly, I think we should consider tracing from the finalizers to warn people that they should rather dispose (to avoid finalization cost).

**Comment by JamesNK** [comment]
@rynowak https://github.com/JamesNK/Newtonsoft.Json/releases/tag/8.0.2 https://www.nuget.org/packages/Newtonsoft.Json/

**Comment by pranavkm** [comment]
Picked up the 8.0.2 version as part of https://github.com/aspnet/JsonPatch/commit/9ad62d796332572a5ddc4601b87687b08488c474
