### ISSUE TITLE
HttpMethod case sensitivity 

### ISSUE THREAD

**Issue by malekpour** [aspnet/Mvc#3551]
`HttpMethodConstraint` is case sensitive when comparing HTTP methods. Also ~~`HttpContext.Request.Method`~~ `Microsoft.AspNet.Http.Internal.DefaultHttpRequest` case is same as what passed by the client which could cause inconsistency in some cases.

*I am not sure, but I guess http.sys was changing it to upper case, but Kestrel preserve.*

**Comment by Eilon** [comment]
It's worth noting that the HTTP method per [RFC 7231](http://tools.ietf.org/html/rfc7231#section-4) is case sensitive (emphasis mine):

>    HTTP was originally designed to be usable as an interface to
   distributed object systems.  The request method was envisioned as
   applying semantics to a target resource in much the same way as
   invoking a defined method on an identified object would apply
   semantics.  **The method token is case-sensitive** because it might be
   used as a gateway to object-based systems with case-sensitive method
   names.

@Tratcher any thoughts on this?

**Comment by Tratcher** [comment]
Hmm, even RFC 2616 says they're case sensitive. 7231 also says "By convention, standardized methods are defined in all-uppercase US-ASCII letters." so that's a good rule for clients to follow.

That said, I have not ever seen methods intentionally treated as case sensitive. Even System.Net.Http (which is usually very strict) has HttpMethod which uses OrdinalIgnoreCase. I think it's up to the consumer to decide how strict they want to be. Our general guideline is to be strict on what you send, but forgiving on what you accept.  Note the request path is also case sensitive but most of our components do not treat it as such.

**Comment by Eilon** [comment]
Yeah I would generally prefer to have our check be case-insensitive. So I'm fine treating this as a bug.
