### ISSUE TITLE
CacheTagHelper cache invalidation outside view

### ISSUE THREAD

**Issue by mguinness** [aspnet/Mvc#3573]
While we're still in beta, I wanted to ask if there will be a way to manually remove items from the cache like the old RemoveOutputCacheItem method.  Although the question below is related to OutputCache it does show how frustrating it can be to invalidate a cache without knowning the key.

http://stackoverflow.com/questions/5326230/mvc3-outputcache-removeoutputcacheitem-renderaction

In Mvc/src/Microsoft.AspNet.Mvc.TagHelpers/CacheTagHelper.cs I see that context.UniqueId is used for part of the key, but it's created at view compilation time.  Would it be possible to allow a custom key to be provided as an optional attribute which could be used instead?

It may not be necessary as there may be workarounds, but I wanted to float the idea in case this scenario had not already been considered.

**Comment by NTaylorMullen** [comment]
Hmm, interesting. I remember when building it we talked about pluggability to account for custom expiration options. After looking through the code again (it's been a while) [MemoryCache](https://github.com/aspnet/Mvc/blob/94a4c8e3f4018d6357754e0877b7f6beffae2f59/src/Microsoft.AspNet.Mvc.TagHelpers/CacheTagHelper.cs#L63) being protected is probably the manifestation of that idea. Although super heavy handed.

It's an interesting thought. I like it. Were you thinking of an `asp-key` attribute?

**Comment by pranavkm** [comment]
We have an example that shows how you could use expiration tokens to delete cached entries:

* https://github.com/aspnet/Mvc/blob/dev/test/WebSites/HtmlGenerationWebSite/Views/Catalog_CacheTagHelper/ListCategories.cshtml#L3 sets up a `cache` tag and invokes the `ProductsViewComponent`
* `ProductsViewComponent` creates a cache entry at https://github.com/aspnet/Mvc/blob/dev/test/WebSites/HtmlGenerationWebSite/Components/ProductsViewComponent.cs#L29 which adds a custom expiration trigger. Since the creation of this entry happens as part of creating the cache entry for the `CacheTagHelper`, expiring it also also causes the `CacheTagHelper` entry to expire.

The view component is optional and you should be able to do in the body of the `cache` tag using a C# code block. There was work item we discussed at some point which was having the ability to specify `asp-expiration-triggers` as an attribute on the tag helper in case it was something you could specify as part of the tag helper.

tl,dr; `IMemoryCache` the backing store for CacheTagHelper does not have a remove method and might not have it. We recommend using expiration tokens instead.

**Comment by mguinness** [comment]
@pranavkm - thanks for the example using the view component.  But let's say you update products via a Web API controller, how do you expire the cache then?  This would be a common use case I would imagine.  If you have a technique that would work in a similar fashion I would be interested to learn.

**Comment by Eilon** [comment]
@pranavkm there's an `IMemoryCache.Remove()` method: https://github.com/aspnet/Caching/blob/dev/src/Microsoft.Extensions.Caching.Abstractions/IMemoryCache.cs#L37

**Comment by pranavkm** [comment]
Huh, didn't realize that. Guess that's new. I spoke to @lodejard about this and his recommendation was to use expiration tokens + service to get you tokens by named. So you essentially get the same behavior as specifying keys. I was planning on updating the test we have to better reflect this model.

**Comment by danroth27** [comment]
@pranavkm Please update the tests.
