### ISSUE TITLE
How to unit test a view?

### ISSUE THREAD

**Issue by nojaf** [aspnet/Mvc#3606]
Is it possible to render a view to string (html) inside a unit test and then assert whether the html contains the expected tags.

Something like
```csharp
		[Fact]
		public void GivenControllerShouldReturnIndexView(){
			HomeController controller = new HomeController();
			ViewResult result = controller.Index() as ViewResult;
		    string html = result.RenderAsString();
			Assert.True(html.Contains("<h1>My h1 text</h1>"));
		}
```

**Comment by Eilon** [comment]
@nojaf there's no built-in way of doing exactly that because it would generally work in only the simplest cases, in which case you wouldn't need a test to begin with :smile: 

However, with ASP.NET 5 and MVC 6 it's quite easy to use an in-memory server to make requests to an app in the form of a functional test or integration test.

You can check out MVC's functional tests for many examples of this, for example, https://github.com/aspnet/Mvc/blob/eef6c3883a7e27b8387b0925f0b6a88df0a484c5/test/Microsoft.AspNet.Mvc.FunctionalTests/CustomRouteTest.cs

Part of the key to these tests is the MVC test fixture: https://github.com/aspnet/Mvc/blob/f25aab8df7ef935a6d4c67a0ba112de6621ad29d/test/Microsoft.AspNet.Mvc.FunctionalTests/MvcTestFixture.cs

**Comment by nojaf** [comment]
Thanks, this looks very promising for end 2 end scenarios.
