### ISSUE TITLE
Input Taghelper generates invalid value

### ISSUE THREAD

**Issue by mguinness** [aspnet/Mvc#3610]
Using ASP.NET 5 RC1

Model member:
`public DateTime CreatedDate { get; set; }`

Razor content:
`<input asp-for="CreatedDate" type="datetime-local" value="@DateTime.Now" />`

Expected output
`<input type="datetime-local" value="2015-11-21T20:55:17" data-val="true" id="CreatedDate" name="CreatedDate">`

Actual output
`<input type="datetime-local" value="11/21/2015 8:55:17 PM" data-val="true" id="CreatedDate" name="CreatedDate">`

I also tried using `asp-format="{0:s}"` but that had no effect either.  However, that does work when no value specified.

-- http://www.w3.org/TR/html-markup/input.datetime-local.html#input.datetime-local.attrs.value

**Comment by dougbu** [comment]
@mguinness this behaviour is expected: Unless the `value` attribute is left `null`, the `InputTagHelper` does not perform formatting. Few if any of the MVC tag helpers override attributes explicitly provided in the `.cshtml` files.

Suggest removing the `value` attribute entirely. If the `DateTime.Now` expression is intended as a default for `CreatedDate`, move that setting elsewhere e.g. into the model type's constructor or the action.

**Comment by mguinness** [comment]
@dougbu - thanks for explaining and solution.  I ended up setting value attribute to `@DateTime.Now.ToString("s")` for now.

**Comment by dougbu** [comment]
@mguinness that'll work when a `Create.cshtml` view is initially loaded but doesn't make sense in any view where the model is not initially `null`. For example, that expression will not reuse the first value when reloading the view due to a validation error.

Please close this issue if the concern is resolved.

**Comment by mguinness** [comment]
@dougbu - I just tried this in view Edit.cshtml where an initialized model is passed, but it's not working as expected.

Date is not formatted correctly with `<input asp-for="CreatedDate" type="datetime-local" />` and it has to be overridden with `<input asp-for="CreatedDate" type="datetime-local" asp-format="{0:s}" />`.

I understand your point about explicitly specifying the value attribute, but an issue exists when it's omitted (unless I'm missing something obvious) - it should be easy to repro.

**Comment by dougbu** [comment]
@mguinness `InputTagHelper` special cases `datetime-local` but only when `ViewContext.Html5DateRenderingMode == Html5DateRenderingMode.Rfc3339` (see [line 356](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.TagHelpers/InputTagHelper.cs#L356)). Otherwise the helper performs the default conversion to `string`. So, now that you've got `value` out of the way, you need to either specify `asp-format` or use `Html5DateRenderingMode.Rfc3339`.

**Comment by mguinness** [comment]
@dougbu - Ah, didn't know about that enumeration.  Thanks!
