### ISSUE TITLE
Possible Threading Problem in ASP.NET 5 RC

### ISSUE THREAD

**Issue by TLHamilton** [aspnet/Mvc#3630]
I seem to be experiencing a possible threading problem in ASP.NET5 RC.  There seems to be two identical controller/action threads when I startup a new project.

You should be able to see the two identical threads if you create a new ASP.NET 5 RC project, go to the Index action in the HomeController, add a few dummy lines of code, set a break point on the first dummy line, start debugging, and when the controller breaks, display the Window Threads, and then press F10 to move forward.

**Comment by rynowak** [comment]
Does this sound like your issue? https://github.com/aspnet/Mvc/issues/3585

**Comment by TLHamilton** [comment]
It sounds like it might be.  I noticed that issue #3585 is closed.  Is it going to be worked on?  The reason I am asking is because I only noticed this problem because I have been having intermittent failures while trying to add items to an IConfiguration object.  I thought the fact that two identical threads were running might be causing the failures.

**Comment by rynowak** [comment]
Sorry that bug was bounced to https://github.com/aspnet/Tooling/issues/261 which **is** open. 

Are you modifying configuration during a request? This sounds like something that would have issues regardless of the tooling/debugger issue. Can you share a code sample of what you're doing and maybe I can help?

**Comment by TLHamilton** [comment]
It is the IConfigurationSection in TemplateController that is failing sometimes.  The idea is to take the input parameters and place them in the Configuration object so they can be shared by View Components.  The View Components do find them in the Configuration objects passed into their Constructors
[TemplateController.txt](https://github.com/aspnet/Mvc/files/43021/TemplateController.txt)
[TreeMenuViewComponent.txt](https://github.com/aspnet/Mvc/files/43024/TreeMenuViewComponent.txt)

.

**Comment by rynowak** [comment]
Configuration objects are not thread-safe for simultaneous reading and writing, so your problem is really independent of aspnet/Tooling#261. As soon as you have multiple simultaneous users, you have this issue.

The configuration system is really meant for mapping multiple configuration sources to a coherent key-value store for settings. It's not meant to be a keystone of your site's architecture.

I'd recommend the following

- use the (options pattern)[http://www.kotancode.com/2015/11/23/configuration-options-and-di-with-asp-net-5/] for values that are truly part of your site's configuration (environment, site name).
- rather than doing explicit lookups of configuration values based on ASPNET_ENV - use the built in support to load different configuration sources based on environment (see linked post)

- Pass values that are per-request like ItemId, DocumentName, etc from the controller to the view as part of a strongly typed model class 
- Pass these values as parameters to the view component

- Abstract away your access to the configuration system behind a repository pattern, so if you end up using another data source in the future, you're not tied to configuration.

**Comment by TLHamilton** [comment]
Thanks very much for the help.  I will review all of your suggestions and make adjustments!
