### ISSUE TITLE
Decouple ModelBinding from MVC, and make it a simple Middleware

### ISSUE THREAD

**Issue by prasannavl** [aspnet/Mvc#3663]
Just like `Routing`, model binding also has its uses as a standalone middleware. And many extremely simple projects that are tuned for high performance need not go through the entire MVC pipeline for `ModelBinding`, if it that's all the feature that's required. 

Doesn't separating it out, as a middleware with a separate package instead make more sense?

**Comment by Eilon** [comment]
In its current design, model binding depends on a whole lot of MVC concepts, including the existing of actions, value providers, model state dictionary, model metadata, formatters, and much more.

While it might seem simple at first to separate the two (and it's certainly possible in theory), it would likely make writing model binders more difficult (because they won't have direct access to MVC-specific concepts anymore).

As such, we have no plans to separate model binding away from MVC.

(Routing on the other hand is quite a different case because it runs *before* MVC, so it can't easily depend on MVC even if it wants to.)
