### ISSUE TITLE
Url not generating URLs for named routes

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Mvc#3703]
I'm having an issue trying to generate a URL pointing to a route I've defined:

```
				router.MapRoute("upload", "upload",
					new {
						controller = "Home",
						action = "Upload"
					},
					new {
						httpMethod = "post"
					}
				);
```

I'm my template, all I'm trying to do is this:

```
		<form action="@Url.Action("upload")" method="post" enctype="multipart/form-data">
			<input type="file" name="thing" />
			<button>Upload</button>
		</form>
```

Unfortunately, all I end up with is:

```
		<form method="post" enctype="multipart/form-data">
			<input type="file" name="thing" />
			<button>Upload</button>
		</form>
```

Am I missing something?

**Comment by Eilon** [comment]
Yes, you're missing a feature that we apparently forgot to add when porting the old routing code!

What's missing here is the `HttpMethodRouteConstraint`, which would do what you want. The way your route is specified there's a constraint that says that there must be an `httpMethod` parameter specified and its value must be `post`, which is presumably not what you want. With `HttpMethodRouteConstraint` you can specify that for incoming requests the request's HTTP method must be some particular value, and that when generating URLs to ignore the constraint in general.

We'll add the feature back in https://github.com/aspnet/Routing/issues/248

Closing this bug out because it's just due to a missing feature.
