### ISSUE TITLE
Consider AuthorizeFilter ctor that accepts policy name

### ISSUE THREAD

**Issue by brockallen** [aspnet/Mvc#3708]
Instead of `AuthorizationPolicy` instance. This would make it easier to configure global policies, e.g.:

```
services.AddMvc(config =>
{
   config.Filters.Add(new AuthorizeFilter("RequireAuthentication"))
});
```

**Comment by danroth27** [comment]
@blowdart Thoughts?

**Comment by brockallen** [comment]
To flesh this out some more, it feels odd that if in `AddAuthorization` you're setting up most of your policies, but then you want a global policy you have to define a policy in a different place. It just strikes me as odd/inconvenient/inconsistent.

**Comment by blowdart** [comment]
You can already override the default policy property in the authorization options.

This is different though, right? You want to have multiple filters at some point?

**Comment by blowdart** [comment]
@HaoK

**Comment by brockallen** [comment]
> You can already override the default policy property in the authorization options.
> This is different though, right? You want to have multiple filters at some point?

But this default policy is not automatically applied without an `[Authorize]` and I'd rather just set one global filter/policy without touching all my controllers.

**Comment by blowdart** [comment]
That makes sense. @HaoK is this possible?

**Comment by HaoK** [comment]
As things stand today, the Filter expects all the funny business of resolving policies/requirements to already have been done.  The thing that's missing right now all up is an easy way to resolve policy names => AuthorizationPolicies.  The problem here is even if we had one of those services, you wouldn't be able to use it inside of AddMvc easily since configuring options happens during service configuration as well.  

I think the best option might be a slightly dirty one.

```
// ConfigureServices
var globalPolicy = CreateMyPolicy();
services.AddAuthorization(options => options.AddPolicy("Wut", globalPolicy));
services.AddMvc(options => options.Filters.Add(new AuthorizeFilter(globalPolicy));
```

Is that acceptable?

**Comment by brockallen** [comment]
Well, that's in essence what I've been doing up to now. Yea, I'm ok letting this one pass. Don't sweat it.

Thx.
