### ISSUE TITLE
Add support for HTML5 HTML Helpers in ASP.NET MVC

### ISSUE THREAD

**Issue by rustd** [aspnet/Mvc#3725]
Feedback from UserVoice site: https://aspnet.uservoice.com/forums/41201-asp-net-mvc/suggestions/6599921-add-support-for-html5-html-helpers-in-asp-net-mvc

Copying the contents below.
t would be great if you had the ability to use HTML5 together with the built in HTML Helpers in ASP.NET MVC. Being able to use code such as:

@Html.TextBoxFor(model => model.EmailAddress, InputType.Email, "Placeholder goes here")

or:

@Html.Html5Range(1, 100 , 0, 23, null)

There is currently an external open source project maintained on Codeplex (http://mvchtml5.codeplex.com/) that does this, however it would be great to have this functionality available in Visual Studio by default.

Being able to support HTML5 elements such as input types and video/audio elements would be great.
- Color 
- Email 
- Search 
- Time 
- Tel 
- File 
- Range & Number 
- Audio & Video

**Comment by ehsansajjad465** [comment]
yes it could be nice if  it is done.

**Comment by Eilon** [comment]
BTW `Html.EditorFor()` supports the HTML5 input types.

**Comment by khalidabuhakmeh** [comment]
Do you know about [HtmlTags](https://github.com/HtmlTags/htmltags)?

HtmlTags is composable through a fluent interface. The ASP.NET MVC team could still support the current set of extension methods in addition to allowing MVC developers to build their own more easily.

I would be weary about trying to support specific input types (because there is always going to be more), but instead make it easier to build any input type more easily.

**Comment by Eilon** [comment]
We will take another look at HTML5 improvements in helpers in the next release.

**Comment by rynowak** [comment]
These kinds of things work super will with the `<input .. />` tag helper. 

I don't believe we have any plans to add features to HTML helpers. Suggest closing /cc @DamianEdwards @Eilon

**Comment by DamianEdwards** [comment]
Agreed, I'd recommend ppl use Tag Helpers to get the best experience here.
