### ISSUE TITLE
Make framework registrations singleton by default

### ISSUE THREAD

**Issue by dotnetjunkie** [aspnet/Mvc#3728]
Many of the registrations that MVC makes to the new DI abstractions are with the Transient or Scoped lifestyle. If you take a look at the implementations and their dependencies, you'll see that there is often no reason for them to be transient. A transient component forces all depending components to be transient as well. Failing to make a depending components with a registration equal or less than the dependency can cause all sorts of ugly bugs. This problem is commonly referred to as [Captive Dependencies](http://blog.ploeh.dk/2014/06/02/captive-dependency/).

There is obviously no problem when transient framework components (with their dependencies) are stateless, because it doesn't really makes any difference whether those components are made captive by a consuming component. But problems will start to appear if that framework component starts to have state in a future release. Since that framework component is registered as transient or scoped, it is -in a strict sense- allowed to get state in a future version of the framework. But if a singleton consumer already depended on that component in v1 (and note that this consumer could both be a 3rd party library component or an end-user component), the application will suddenly break when the user upgrades to the next version. These types of problems are usually pretty hard to track down and are therefore very costly to fix. So although transient components seem to communicate to the world that the component has state, adding state to a framework component in the future can still cause applications to break. So in reality, framework components can never get state if they didn't have that in the initial version.

To mitigate this, framework components should always be registered as singleton and force their dependencies to be singleton as well. This results in a much simpler mental model, because this can model can be communicated clearly to everybody; the rules are much simpler. Problems are much easier to spot, because the rule now is that a component itself can't have any state. If it needs state, it should either request that from another component, or query some cache. In case users replace components with their own and make those components transient/scoped, their application will break much sooner.

**Comment by ploeh** [comment]
This problem is real; it would be much easier to manage (or perhaps wouldn't exist at all) if the framework didn't insist on providing a [Conforming Container](http://blog.ploeh.dk/2014/05/19/conforming-container); as I [described in a follow-up](http://blog.ploeh.dk/2014/06/03/compile-time-lifetime-matching) to the Captive Dependency article, lifetime mismatches are much clearer to developers when using [Pure DI](http://blog.ploeh.dk/2014/06/10/pure-di). Client developers wouldn't have to *learn* about the framework's lifetime model, but could instead rely on writing normal code that they already understand.

That said, it's not that objects with Singleton lifetime can't have state; they can, but if they have *mutable* state, they must be thread-safe.

**Comment by dotnetjunkie** [comment]
> but if they have mutable state, they must be thread-safe.

Obviously, @ploeh is right about this.

**Comment by Eilon** [comment]
At this time though we feel there are merits to this philosophy, we feel the value of making such a change is minimal. Many MVC services are already singleton, or otherwise behave as if they are singleton.

**Comment by khellang** [comment]
So this is something you "wontfix", ever? What about leaving it open with an "up-for-grabs" (or similar) label on it? Maybe someone would look at it?

**Comment by Eilon** [comment]
@khellang changing the lifetime of a service to be broader (e.g. transient -> singleton) would be a breaking change because this would affect *all* implementations of the service (not just the built-in implementation).

So, at this time there are no plans to change this even in a future release. Of course, we can always change our mind later (and even make a breaking change if it is deemed worthwhile), but at this time we are going with the current implementation and design.

**Comment by dotnetjunkie** [comment]
> changing the lifetime of a service to be broader (e.g. transient -> singleton) would be a breaking change 

Every change in lifetime of a framework's service would be a breaking change. This not only holds when the lifestyle is increased (broadened), but also when it is decreased. Decreasing a service's lifestyle (from singleton to transient for instance) is a breaking change, because its consumers will cause the service to become a captive dependency.

The only change that is safe to make, is increasing a lifestyle of a component that has no dependencies of its own.

> we can always change our mind later (and even make a breaking change if it is deemed worthwhile)

I sincerely hope you won't change your mind, because you will break people’s code.

Do note that if you fix this issue, you will immediately also have fixed issue #3739 as well.

**Comment by Eilon** [comment]
@dotnetjunkie it's unlikely we'd ever change the existing lifetimes, but we could possible in the future introduce a new "replacement" service, e.g. `IBetterFoo` that has an improved lifetime, and is used unless someone explicitly registered an implementation the "old" way (with "bad" lifetime).
