### ISSUE TITLE
asp.net 5 doesn't support request validation

### ISSUE THREAD

**Issue by zibzib** [aspnet/Mvc#3808]
I was surprised to see that requestion validation is not turned on by default in asp.net 5.
On a closer look, it seems like it's not supported at all.
https://msdn.microsoft.com/en-us/library/hh882339(v=vs.110).aspx

What's the guideline on prevent XSS attacks?

Thanks!

**Comment by Eilon** [comment]
@blowdart FYI

Request validation was never a substitute for properly securing an application. In reality, an application always had to validate inputs and ensure that all outputs were properly encoded. The same is true in ASP.NET 5.

My *personal* experience with request validation was that it never protected me against anything (because ASP.NET and EF do a superb job at automatically encoding whatever needs to be encoded), and it quite often got in the way of valid requests (e.g. posting HTML-like content to the server). I, for one, am glad to see it gone :smile:

**Comment by blowdart** [comment]
The guidance is encode all output. That's pretty much the only XSS mitigation technique.

Request Validation has been deprecated for quite a few years, we've been saying this in public. So bringing over a technology that we don't consider a security barrier is wasted effort.
