### ISSUE TITLE
Is there any possibility to call View-components  between areas.

### ISSUE THREAD

**Issue by B-Esmaili** [aspnet/Mvc#3814]
When i attempt to call  a `ViewComponent` from different area , view engine searches the calling area not the area the `ViewComponent` resides in.is this expected behavior or something is wrong with my code?
thanks.

**Comment by rynowak** [comment]
Do you mean the view that's being rendered by a view component? The error message that you get should include the search paths that were used to look for views.

The view lookup logic is the same as for normal views. It will look inside the folder of the controller first, then the shared folder for the area (if the current controller/view is in an area), then the shared folder for the app.

> the calling area not the area the ViewComponent resides in

There's no interaction between view components and areas. view components are neither in, nor out of an area, the features don't overlap.

**Comment by Eilon** [comment]
Indeed, the "area" is chosen based on the route/controller that was selected, and that choice is made only once. One the controller is running the "current area" never changes.

**Comment by ToddThomson** [comment]
@Eilon By design is fine, but I don't understand the reasoning for this. 

Given that I have 2 core libraries, each with its own components ( controllers, embedded views, etc ). If I start a request to an area route handled by a controller in library A, and the view invokes a view component in library B then the view for the component cannot be found.

Shouldn't views for components live in the same area as the component code by default? If not found then the request area would then be searched. And so on...

This is a block for me as I made use of Html.RenderAction() in MVC5.

Can the view component have an area attribute to aide in the search?

**Comment by Eilon** [comment]
@ToddGrun I think the issue here is that the *request* ends up being for an area, and *controllers* can have associated areas, but *view components* do not. Ultimately it's only the "top level action" that handles the request that determines the area *for the entire request*. So, if the request came into `MyApp.AdminArea.Controllers.AdminController` then the area is `admin`, and all views by default (no matter whether they're layouts, partials, for view components, editor/display templates, etc.) will come from that area's folders (and then fall back to the "default" area).

I think in this particular case perhaps we didn't consider the possibility of having view components be associated with areas, but I think that's the feature you'd need to make this work. Of course, I'm not entirely certain *how* that would work...

**Comment by javiercn** [comment]
@Eilon Maybe you wanted to mention @ToddThomson?

**Comment by Eilon** [comment]
Obviously 😄 Todd1 and Todd2 😉

**Comment by ToddThomson** [comment]
@Eilon I am hoping to make this work with an attribute or convention and a view location expander. I just have to figure out how to get the AreaViewComponent name into the action context so that it can be picked up by the view expander.

**Comment by ToddThomson** [comment]
@Eilon I got this to work by:
```
1. registering the IHttpContextAccessor service.
2. Using a [ViewComponentArea( "areaName" )] Attribute which obtains the HttpContext from 1) and adds the areaName to the HttpContext.Items["viewComponentArea"]
3. Using an IViewLocationExpander class to look for the component view starting with the view component areaName obtained from HttpContext.Items.
```
