### ISSUE TITLE
Should FormTagHelper include an antiforgery token when action is specified

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#3869]
Currently the `<form>` tag helper isn't active for cases like
```
<form action="">
</form>
```

Which is a post back to the same URL. 

The reason I mention it is that it's pretty similar to `.BeginForm()` - which would include a token.

Of course when you test your app, you will see that an antiforgery token wasn't included. So you'd need to add `asp-antiforgery="true"`.

**Comment by NTaylorMullen** [comment]
I'd say no, if a `<form>` tag has an `action` then the only other server side attribute you can add is `asp-antiforgery`. 

When we first wrote `FormTagHelper` it applied to every `form` tag and added antiforgery tokens by default. We then went back on the idea because many users weren't trying to use `TagHelper` based `form` tags but were auto-opted into them. Also resulted in lots of purple form tags :smile:

**Comment by Eilon** [comment]
Yeah don't think we need this.
