### ISSUE TITLE
[Question] Need Guide for TagHelper Designs

### ISSUE THREAD

**Issue by sgjsakura** [aspnet/Mvc#3872]
Dear all,

I'm now working on ASP.NET 5 projects and planning to provide some new tag helpers for my application. Durnig the development I found a problem but cannot find any guide. Here I posted my idea any cound anyone give me some advise?

The problem is that I want to add a TagHelper that generate a checkbox for detecting a certain enum flag is set. e.g. for the following type:
```C#
[Flags]
public enum MyOptions
{
  Item1 = 0x1,
  Item2 = 0x2
}
```
I want the generated checkbox be checked or non-checked according to whether the actual model value contains the Item1 flag. The ideal HTML code I want will be similar with:
```HTML
<input type="checkbox" asp-for="CurrentOptions" asp-flag="MyOptions.Item1" />
```
Since all default ASP.NET TagHelper use `asp-for` for model expression bindings, I do not want to change this design. However when I write the new TagHelper class, the ASP.NET runtime reports *"asp-for" for checkbox only accept boolean values*. This error is caused by the default InputTagHelper still injected during the page executing. If I change the attribute name as follows:
```HTML
<input type="checkbox" asp-enum-for="CurrentOptions" asp-enum-flags="MyOptions.Item1" />
```
Then the page will run correctly. However, the user must use 2 new attributes for this feature.

Here my questions are:
- Is there any design guide for TagHelpers?
- Is it recommended to use the same name for some general tag helper purpose (e.g. `asp-for` for model binding) ?
- If I want to add a new TagHelper with partial funtional overlap with the other TagHelper, which manner is recommended for designing new TagHelpers? Should I create a derived type or introduce a internal helper, or create the new one individually?
- How can I solve the above problem (may cancelling the executing of the original tag helper or using any other manner), or I have to force users to use new attribute names?

This is my question and thank you all for replying~

**Comment by Eilon** [comment]
@dougbu @NTaylorMullen can either of you answer this?

**Comment by Eilon** [comment]
@DamianEdwards FYI as well.

**Comment by NTaylorMullen** [comment]
> Is there any design guide for TagHelpers?

There is not currently a design-guide per say. However, there are docs that showcase MVC and `TagHelper` features [here](https://docs.asp.net/projects/mvc/en/latest/).


> Is it recommended to use the same name for some general tag helper purpose (e.g. asp-for for model binding) ?

If you'd like to use the same `Type`d attribute you can use the same name. When you expect a different `Type` then you are required to provide a different name. You can also take the route of disabling existing `TagHelper`s on a page by using `@removeTagHelper` (it has the same syntax as `addTagHelper` but is used for removing, see next response below).


> If I want to add a new TagHelper with partial funtional overlap with the other TagHelper, which manner is recommended for designing new TagHelpers? Should I create a derived type or introduce a internal helper, or create the new one individually?

If you're truly trying to add functionality to a `TagHelper` (in this case the `InputTagHelper`) it'd be best to derive your own type and remove the existing. So for your proposed case where you want to add functionality to the `InputTagHelper`, I'd recommend making your own `CustomInputTagHelper` that derives from `InputTagHelper` and then doing the following:

```
@addTagHelper "MyNamespace.CustomInputTagHelper, MyAssembly"
@removeTagHelper "Microsoft.AspNet.Mvc.TagHelpers.InputTagHelper, Microsoft.Aspnet.Mvc.TagHelpers"
```

This way, you remove the default MVC `InputTagHelper` and add your own. This way your process method can detect if it should apply its own logic (if so do it); otherwise call through to the base `Process`.


> How can I solve the above problem (may cancelling the executing of the original tag helper or using any other manner), or I have to force users to use new attribute names?

Answered in the above bullet points.

Hopefully this all helps, if anything is unclear i'll be happy to clarify.

**Comment by sgjsakura** [comment]
@NTaylorMullen HI, Thank you for your reply. In your answer you use the `@removeTagHelper` to cancel the original InputTagHelper, however it requires users to add this detective manually in views. Is there any manner to controller the execution of a TagHelper in another one for TagHelper designers? 

Thank you~~

**Comment by NTaylorMullen** [comment]
@sgjsakura The closest you can get to controlling the execution of an existing `TagHelper` is to utilize [TagHelperInitializer](https://github.com/aspnet/Mvc/blob/32d15186a01c1d9542c15045ebb2603653b03d8b/src/Microsoft.AspNet.Mvc.Razor/TagHelperInitializerOfT.cs)s. You can see an example [here](https://github.com/aspnet/Mvc/blob/aa7ebb343a49d77bf680f85ad8f9ad81498b7624/test/WebSites/HtmlGenerationWebSite/Startup.cs#L18).

**Comment by Eilon** [comment]
Closing as it seems all the specific questions have been answered. For any new questions please log a new issue.
