### ISSUE TITLE
Where is @Html.Action() in RC 1?

### ISSUE THREAD

**Issue by gkochanowsky** [aspnet/Mvc#3888]
Is @Html.Action() supposed to be in RC1?

**Comment by pranavkm** [comment]
Child actions, which is the feature `Html.Action` surfaced, aren't being brought forward in Mvc 6. View Components are a replacement for them but work a bit differently. http://www.davepaquette.com/archive/2016/01/02/goodbye-child-actions-hello-view-components.aspx has a write up about the differences and the usage.

**Comment by gkochanowsky** [comment]
Thanks Pranav. Perhaps this discussion has already taken place and I missed
it. For that I apologize. But View Components are not a replacement. A
kludge can be made but it is less elegant and powerful than the original
@Html.Action. Is there some reason why both can't be implemented?

**Comment by pranavkm** [comment]
I can't find the relevant design notes for why child actions were dropped, but it's unlikely we would revive it. What would be valuable feedback is if you could list specific scenarios that don't work with view components.

**Comment by gkochanowsky** [comment]
I've got a modal SCRUD scaffolder I've been using with MVC4 which I would
like to move to MVC6. This scaffolder creates views with code for multiple
scenarios, where I subtract the code I don't need, since it is much easier
to delete code than it is to write code. Especially if the scaffolder uses
all the correct types. But at the same time I'm trying to keep the code as
DRY as I can. I only want to access the actions if the user is
authenticated and authorized. A sample scenario would be a view that is
used for a modal search crud interface, but the same view could appear in
the index itself as a partial view. The view generation does not need more
than few parameters such as dialog ID and and post refresh function to call.

@Html.Action() is perfect for this. Compared to just the one line, I've
implemented a far more verbose and contorted solution using a view
component, but it seems like reaching around my head to scratch my nose. If
you would like some code let me know. I can try to get you the nuget
package for the MVC4 scaffolder.

>

**Comment by danroth27** [comment]
@gkochanowsky Yes, please show us the code you are trying to migrate to MVC 6 and we will take a look.

**Comment by gkochanowsky** [comment]
I have an example of how I'm trying to work around the issue with MVC 6 - [https://github.com/gkochanowsky/SCRUD].

Do you need to see an example of how it's implemented in MVC4 using @Html.Action()?

**Comment by davidfowl** [comment]
> Do you need to see an example of how it's implemented in MVC4 using @Html.Action()?

Yes

**Comment by gkochanowsky** [comment]
@davidfowl you can find a freshly scaffolded version @ [https://github.com/gkochanowsky/SCRUD_MVC4].

You will need to attach the mdb file to your local instance of SQL Server and fix the connection string.

**Comment by danroth27** [comment]
The code you have should be fairly easy to convert to use view components by first converting your child actions to be view components and then calling `@Component.InvokeAsync` instead of `@Html.Action`. For any child actions that you still want to still be accessible as public endpoints you can refactor them to call into your view components using the `ViewComponent()` helper method on `Controller`. The nice thing about this model is that local calls don't have to fake any HTTP-isms and your public endpoints are explicit.

**Comment by gkochanowsky** [comment]
I've already done it, Please see the SCRUD codebase [https://github.com/gkochanowsky/SCRUD]. 

There are several concerns with this approach. First, it's a lot more lines of code. Second, the view component context is not the same as the controller contexts, for example the Identity components are not the same. Third, the view component as far as I can tell does not support cross cutting concerns such as security in the same manner as controllers. It is a mess if one is trying to keep the code DRY. Very good at solving the problems it was meant to solve, but does not replace @Html.Action.

**Comment by danroth27** [comment]
What kinds of things are you trying to do in your view component that you need the controller context for?

I looked at the updated code, but it looks like the controller actions are not calling your view component (by calling the `ViewComponent()` helper method). The controller actions still duplicate the view component code, which I think you can avoid by calling the view component from your actions.

Security as a cross cutting concern should only be relevant for your public endpoints. You can implement your public endpoints using your view components (by calling `ViewComponent()`) and then use all the standard controller infrastructure for handling these cross cutting concerns.

**Comment by gkochanowsky** [comment]
In MVC 4 I could do things like line [20](https://github.com/gkochanowsky/SCRUD_MVC4/blob/master/src/SCRUD_MVC4/Views/Person/Index.cshtml#L20). A single line to call an action at line [39](https://github.com/gkochanowsky/SCRUD_MVC4/blob/master/src/SCRUD_MVC4/Controllers/PersonController.cs#L39). Just one line of code to generate the action HTML.

To do the same thing in MVC6 I've had to write all of the following: [view component](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/ViewComponents/SearchPersonViewComponent.cs), [view component view](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/Views/People/Components/SearchPerson/default.cshtml), [common interface](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/Models/Repositories/IControllerContext.cs). All of this to use the same [search view](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/Views/People/Search.cshtml) and same [search linq](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/Models/Repositories/Repository_Person.cs#L53)

In the first case I can implement the security for that action in one place. In the second case I've got to do it twice.

If you have a better way of doing this in MVC 6 please show me in code. Because that is a lot of trouble to go through in MVC 6 for something that was done easily with one line of code in MVC 4.

**Comment by tuespetre** [comment]
@gkochanowsky:

> In MVC 4 I could do things like line 20. A single line to call an action at line 39. Just one line of code to generate and insert into a view, with no model, the action HTML.

This has not changed: you would just write `@Component.Invoke("MyComponent")` as opposed to `@Html.Action("MyAction")`.

> To do the same thing in MVC6 I've had to write all of the following: call to view component, view component, view component view, common interface. All of this to use the same search view and same search linq

Instead of calling `@Html.Partial("Search")` in your view component view, your `Search.cshtml` view should actually _become_ the view component view. Then, everywhere you have been calling `@Html.Partial("Search")`, you would instead call `@Component.Invoke("Search")`.

As for the 'common interface' thing, why not set up your `Repository_Person` so that it gets injected into controllers and components with everything it needs? I believe you can get `ModelState` one way or another through DI and I know you can get the `HttpContext` to get the `IPrincipal` from it. This seems orthogonal to the issue of child actions versus view components.

> In the first case I can implement the security for that action in one place. In the second case I've got to do it twice.

You should only need to implement it once: in the view component.

I believe @danroth27 explained it fairly well, but I know sometimes I learn better with a visual, so here is a tabular comparison between MVC5 child actions and MVC6 view components:

MVC5 | MVC6
------- | -------
Declare a model class for the partial view to use | Declare a model class for the view component view to use
Put your logic into a controller action | Put your logic into a view component
Put your `Search.cshtml` view into the `Views/Shared` folder | Put your `Search.cshtml` view into the `Views/Shared/Components` folder
Invoke the child action from a view with `@Html.Action("MyAction")` | Invoke the view component from a view with `@Component.Invoke("MyComponent")`
Decorate the controller action with `[ChildActionOnly]` if you **don't** want to expose the action | Return a `ViewComponentResult` from a 'thin' controller action if you **do** want to expose the view component

**Comment by gkochanowsky** [comment]
A code example please that implements SCRUD as demonstrated in the code I made available implemented as you suggest.

**Comment by tuespetre** [comment]
I don't mean to be rude, it's just that we've told you exactly what changes need to be made and where. While they are few, it is your code base and I don't think I will find the time to work on it though I cannot speak for anyone else.

A quick, final bit of advice based on the code you posted:

- Your problem is that you still have calls to the Search.cshtml partial.
- Copy/paste the contents of Search.cshtml into your component's view file
- Ditch Search.cshtml
- Change any Html.Partial and PartialView calls for the Search partial Into Component.Invoke and ViewComponent calls for the view component
- You may need to move some of your other partials into the Shared folder

**Comment by gkochanowsky** [comment]
Sorry if I was rude. I only thought that since I supplied code quickly upon request there might be some reciprocation. So I will make the changes as you recommend. 

You allude to the ability to get ModelState through DI. Can you point me to exactly how I would do this. And does the app have only one instance of ModelState, or are they created per instance of controller or component view? If they are created per instance of controller/component view exactly how would DI work when adding an error to a particular controller instance? 

I am new to DI. And percolating errors up to the controller/component views from lower levels is important functionality.

**Comment by gkochanowsky** [comment]
I've tried to apply security to a view component, but it doesn't appear to be working. Is it not yet implemented?

**Comment by tuespetre** [comment]
I think you may be able to get ModelState from the ActionContext (try ScopedInstance<ActionContext> from DI or something like that, you can also poke around in the debugger inspector tooltip to browse what's available.)

As for security, what is the scenario you are trying to accomplish and what have you tried that is not working?

**Comment by gkochanowsky** [comment]
@tuespetre , I've already retrieved ModelState. You described it as "the 'common interface' thing". I was particularly interested in your comment ("I believe you can get ModelState one way or another through DI"). So I was wondering if you could point me in the right direction on how to do that.

Right now I'm trying to implement Windows Authentication. If I decorate the controller and the view component with the [Authorize] attribute it seems to work, since I am an authenticated user on my local domain. However when I try to add a role [Authorize(Roles = "role-i-am-in")] then I get a 403. Not the result I was expecting.

**Comment by gkochanowsky** [comment]
@tuespetre, I've updated the SCRUD project with my attempt to get Windows Authentication using AD groups working. The changes to [project.json](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/project.json#L11), [Startup](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/Startup.cs#L36), [View Component Decoration](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/ViewComponents/SearchPersonViewComponent.cs#L17), [Person Controller Decoration](https://github.com/gkochanowsky/SCRUD/blob/master/src/SCRUD/Controllers/PeopleController.cs#L16).

**Comment by tuespetre** [comment]
I see. I don't know that the `AuthorizeAttribute` is truly applied to `ViewComponent`s. If you think about it, the only way to get to a `ViewComponent` is through some controller action anyways, so it is kind of redundant. Now, within a `ViewComponent` one might make use of the request's current identity to shape behaviors or conditionally render controls and so forth.

As for the 403 you are now getting, I believe that is to be expected with ASP.NET 5. If you have the `AuthorizeAttribute` applied to a controller action (via global-, controller-, or action-level decoration) and the attribute detects an authorization failure, it calls `Challenge` on your configured authentication provider. That can result in a 403 if you are authenticated but do not meet the criteria of the specified policy or role, which is a bit different than in MVC5, where the attribute just seemed to automatically redirect to the login page regardless of the fact that the user may already be logged in.

I prefer this new behavior, although like yourself, I spent a little time picking up on the differences in operation.

**Comment by tuespetre** [comment]
Hmmm... looking over the rest of your code, it seems you are applying your authorization policy globally in the `Startup` class as well. So any request will need to be authenticated, which may not be what you intended.

I also recommend checking out this question on StackOverflow: http://stackoverflow.com/questions/28542141/windows-authentication-in-asp-net-5

**Comment by gkochanowsky** [comment]
As @tuespetre stated:

>I don't know that the AuthorizeAttribute is truly applied to ViewComponents. If you think about it, the only way to get to a ViewComponent is through some controller action anyways, so it is kind of redundant. Now, within a ViewComponent one might make use of the request's current identity to shape behaviors or conditionally render controls and so forth.

So am I correct in assuming that a view component is not on the same level as a controller action? So is there an implicit call to a controller? Other than the placement of the component view, how is that determined? Do I loose action level security by using view components?

**Comment by gkochanowsky** [comment]
Thank you @tuespetre for the link to the [StackOverflow](http://stackoverflow.com/questions/28542141/windows-authentication-in-asp-net-5) post. Are future versions of NET5 going to make that less painful?

**Comment by tuespetre** [comment]
@gkochanowsky:

> So am I correct in assuming that a view component is not on the same level as a controller action? So is there an implicit call to a controller? Other than the placement of the component view, how is that determined? Do I lose action level security by using view components?

Looking again at [the table I posted earlier](https://github.com/aspnet/Mvc/issues/3888#issuecomment-172291499), I will answer your questions like so:

1. Correct, a view component is not the same as a controller action. A view component receives the benefits of dependency injection and can run some developer-defined code and logic before returning what is essentially a partial view.
2. There is no implicit call to a controller involved. When you invoke `Component.Invoke` from a view or `return ViewComponent("MyComponent")` from a controller action, you're basically saying the same thing as `Html.Partial` or `return PartialView("MyPartial")`, except the arguments you pass in get run through the view component's code, which then produces the partial.
3. See (2).
4. No. In your case, you would have one controller action that returns a view, which in turn invokes the view component, and another controller action that directly invokes the view component. In both scenarios you would apply the 'action-level security' to these controller actions, just like when they invoked 'plain old partial views' instead of view components.

So it may help if you tell yourself, "View components are basically partials with a little layer of code on top of them." The layers of security have not changed.

@gkochanowsky:

> Thank you @tuespetre for the link to the StackOverflow post. Are future versions of NET5 going to make that less painful?

The ASP.NET team has been working hard on tightening up the IIS-hosted story and whatever else related to it. Some big changes are yet to come in February with the dotnet-cli per my understanding, plus it sounds like a new version of HttpPlatformHandler is going to come out to address some of the bumps that were hit after beta8 was released.

Just so we're clear, too, let me explicitly state that I'm not a part of the ASP.NET team or Microsoft at all, I'm just personally invested in the community and helping the team answer questions on GitHub because I want them to have more time to focus on their work :stuck_out_tongue:

**Comment by Eilon** [comment]
It seems that the big questions here have been answered so I'm closing this.

If there are further questions please log new issues on them.

**Comment by gkochanowsky** [comment]
On Jun 23, 2016 7:02 AM, "LinkedIn" <news-noreply@linkedin.com> wrote:
>
>
> Your connections are in the news! Aurelia vs Angular — a Feature by
Feature Comparisonh
>
>y
> Connections In The News
>
>
>
> Rob Eisenberg
> sitepoint.com · 15 hours ago
> Aurelia vs Angular — a Feature by Feature Comparison
> Primarily created by Rob Eisenberg of Durandal Inc., Aurelia targets the
same problem space as AngularJS. However, Aurelia uses a modern approach to
ease development and solve a lot of the problems that plagued AngularJS. In
this article, we’ll take a detailed look at AngularJS and ...
> Message Rob
> ·
> Share
> ·
> Wrong Person?
> You are receiving Connections in the News emails. Learn more about this
feature. Unsubscribe.
>
> This email was intended for Gene Kochanowsky (DBA, Data Analyst, FSU
College of Medicine, Claude Pepper Datauh Center). Learn why we included
this.
> If you need assistance or have questions, please contact LinkedIn
Customer Service.
>
> © 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA
9404hu3. LinkedIn and the LinkedIn logo are registered trademarks of
LinkedIn.
>
>
> LinkedIn does not guarantee that news articles are accurate or about the
correct person.

**Comment by rsimmermon** [comment]
Did you ever totally resolve this issue?  ViewCOmponents are not made to process requests and do model binding.  I need the ability to execute an action with the sames results that Html.Action did.

I'm not sure I understand how ViewComponents are helpful with this.  I have used ViewComponents in several places now, though, but this type of use doesn't apply.

Example:
I have a site where the same controller and action is loaded on every page of this site, but based on the requested page, different view components are loaded.
One of these viewcompoents is a form.  I need to be able to submit the form to the same controller/action, but the view component loaded should be the results of submitting the form.  (i.e. a search page and search results)
A viewcomponent is not ideal for this as that is not what it's designed to do.

**Comment by gkochanowsky** [comment]
rsimmermon, not really. But I haven't been doing any core development for
awhile. Still working in classic .NET. It does what I need.
