### ISSUE TITLE
IHtmlGenerator.GenerateSelect is not generating the correct html when a value is specified

### ISSUE THREAD

**Issue by SimplerSoftware** [aspnet/Mvc#3889]
When providing either a collection of custom objects and specifying which value should already be selected, or providing a collection of SelectListItem with one item having the 'Selected' value set to true, when the select renders, no value is pre-selected. Inspecting the HTML shows that the 'selected' attribute is not applied to the 'option' that was specified as the value.

**Comment by dougbu** [comment]
If the expression has a value, `Selected` properties in the passed `IEnumerable<SelectListItem>` are overwritten. This is by design since otherwise the `<select>` will not have the `<option>` matching the value selected.

Are you seeing something different? If so, please provide more information about your scenario. A GitHub repo containing a small repo would be ideal.
