### ISSUE TITLE
Returning void in a Controller causing 500 error, should throw

### ISSUE THREAD

**Issue by ljfolino** [aspnet/Mvc#3901]
I have a simple controller that is using async await.  When the return type is void I receive a 500 error.  The action itself completed without error and is not throwing any exceptions.  This seems to be with the way that the controller handles void.  I know that the return type should be a 204 which would sometimes work.  I have switched my controllers to instead return Task<IActionResult> and return Created("",object) for posts and return new HttpStatusCodeResult(204) for puts.  Being that there is a work around I wanted to file the bug incase others have this issue.

**Comment by rynowak** [comment]
Are you using the `DeveloperExceptionPage`? Can you include a call stack so we can investigate?

**Comment by ljfolino** [comment]
That is also the strange thing.  I enabled the `DeveloperExceptionPage`  to try and debug what was going on and one was not produced.  I would only receive a 500 return with no data.

**Comment by rynowak** [comment]
@pranavkm just pointed out to me that you're using `async void`. You should **never** use async void with MVC, and avoid it in general.

http://haacked.com/archive/2014/11/11/async-void-methods/

@Eilon / @danroth27 - should we try and throw if you declare something `async void`?

**Comment by ljfolino** [comment]
It is a little misleading that this should be avoided.  What I do not understand is why the 500 was being thrown.  I will convert all my code to return `Task<IActionResult>`, but shouldn't the MVC pipeline handle this, or as you said throw an exception of some sort.  At least a warning in the compiler to handle this sort of thing.

**Comment by rynowak** [comment]
`async void` was added to the language to support cases where you need to start async work, but can't return `Task`. What happens when you use it in MVC is that we 'unwind' and start to do the rest of the work we do after your controller is supposed to be finished. Without the task, *we can't know* when your controller is finished. What's the likely cause the 500 is something corrupting internal state of the server or response object by accessing it concurrently.

We can throw in this case, but there's nothing first-class in the reflection API that tells us a method is async. We'd be relying on the current behavior of the compiler, and if that behavior were to change this check would no longer function.

**Comment by benaadams** [comment]
@ljfolino a thrown Exception in an `async void` method is likely to bring down the entire server https://github.com/dotnet/coreclr/issues/2144

**Comment by Eilon** [comment]
Closing because we have no plans to support this.
