### ISSUE TITLE
`SelectListItem` manipulation is quite expensive

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#3953]
`SelectListItem`, `List<SelectListItem>` and related allocations quickly overwhelm any scenario using `Html.ListBox()`, `<select asp-for="...">` or similar helpers with a non-empty `IEnumerable<SelectListItem>` argument or `asp-items` attribute value. For example `SelectListItem`s rise to be the fourth-most allocated type in a scenario involving ten `Html.ListBoxFor()` calls per request despite 50 `Html.LabelFor()` and 40 `Html.IdFor()` calls per request (see #3918).

Very little of the relevant code has changed since MVC 5. It definitely hasn't been optimized. Example perf issues:
- Extensive Linq use (including Linq syntax though a `foreach` would have been clearer) when enumerating items in a `MultiSelectList.
- Extensive Linq use (e.g. `GroupBy()`) in `DefaultHtmlGenerator.GenerateGroupsAndOptions()`.
- Defensive deep copies of `IEnumerable<SelectListItem>` values passed to `DefaultHtmlGenerator.UpdateSelectListItemsWithDefaultValue()`. Could avoid updating user's collection other ways e.g. tracking selection in a bit vector or using `currentValues.Contains(value)` directly in `GenerateOption()`.

**Comment by dougbu** [comment]
@Eilon another one for the backlog?

**Comment by dougbu** [comment]
Overall:
![overall](https://cloud.githubusercontent.com/assets/6431421/12433909/83336896-beb8-11e5-9f90-a44b82226e4a.png)

Directly `SelectListItem`-related:
![selectlistitem](https://cloud.githubusercontent.com/assets/6431421/12433912/859c854a-beb8-11e5-8153-4aff33edf548.png)

**Comment by dougbu** [comment]
Should have mentioned: The directly `SelectListItem`-related allocations are worth more than 12% of the memory used in this scenario.

**Comment by rynowak** [comment]
> Should have mentioned: The directly SelectListItem-related allocations are worth more than 12% of the memory used in this scenario.

To add to this, the benchmark is creating and caching the items up-front, it's already the most optimized usage a user can get with this helper.

**Comment by tuespetre** [comment]
I noticed major improvements somewhere between beta7 and rc1 in a page I have with a very large amount of `<select>` elements. I would be interested in trying this out; can you point me in the right direction as far as running the performance tests and getting their results, or is this something that stays internal?

**Comment by dougbu** [comment]
> somewhere between beta7 and rc1

@tuespetre that's a large window :smiley_cat: I suspect past improvements came from a few broad performance improvements in the Razor and MVC infrastructure. We haven't focused specifically on the `SelectTagHelper` or anything unique to it.

> running the performance tests

We have a public `Performance` [repo](https://github.com/aspnet/Performance) but that's more about the future. Generally we
- Come up with scenarios based on the expected real world -- as opposed to over-emphasizing a particular code path.
- Implement the site and check it in somewhere, allowing later comparisons and double-checks.
- Send 3000 requests to a single URL using a load testing client while collecting information from the site.

I grabbed the tables above using JetBrains' dotMemory 10 and the Windows Snipping Tool.

**Comment by rynowak** [comment]
@tuespetre - we've done a bunch perf work on Razor since then :+1: We're continuing to push onwards with scenarios for larger pages.

*Apologies as this was my own little secret repo for benchmarking things, and it's grown organically as more people have needed to look into perf. We're planning to have a more 'official' set of scenarios take over at some future point.*

The scenario we're iterating on for this item is here: https://github.com/rynowak/mvc-sandbox/tree/master/workloads/BigViews

The scripts that are here use an NPM module called loadtest (`npm install -g loadtest`). We mainly do memory profiling, and so all of these scripts are set to throttle at a stable RPS we can use with the profiler on.

As far as **results**... that's a bit more complicated. If you want to do load testing (Requests Per Second), I'd recommend using a linux VM to hit the server with [wrk](https://github.com/wg/wrk). This is what we use in the smurflab (aspnet/Benchmarks).

Feel free to play with this and let us know any interesting findings or suggestions that you have, just be aware that this isn't our *official* perf setup, which we'll build up later.

**Comment by dougbu** [comment]
Nice @rynowak the intersection between our responses is minimal but we didn't conflict :smile:

**Comment by Eilon** [comment]
Yup, Backlog.

**Comment by rynowak** [comment]
@mnltejaswini - please work with @dougbu on how to get started on this one.
