### ISSUE TITLE
RequireAttribute ignored

### ISSUE THREAD

**Issue by divega** [aspnet/Mvc#3971]
_From @ducalai on November 25, 2015 10:35_

I have a class with an integer property decorated with [Required] attribute. When I use it within an ASP.NET 5 application MVC controller as a parameter in a Post method accepting json, RequiredAttribute seemed to be ignored when property is not contained in JSON. Model deserialized in controller method contains UserId with default property value 0 for an Int32 and is therefore valid.

If the RequiredAttribute was not ignored, model should not be deserialized and should be null, right?

I am using ASP.NET 5 RC1

Here is my code:

JSON:
```
{
     "Token" : "abcd" 
}
```

Model:
```
[DataContract]
public class MyClass
{
     [Required]
     [DataMember]
     public int UserId { get; set; }
 
     [DataMember]
     public string Token { get; set; }
}
```
MVC Controller:
```
[HttpPost]
public async Task MyMethod([FromBody][Required] MyClass model)
{
     if (!ModelState.IsValid || model == null)
          throw new HttpResponseException(400);
     
     await ...
}
```
Thanks for your help
Alain

_Copied from original issue: dotnet/corefx#4669_

**Comment by dougbu** [comment]
> an integer property decorated with `[Required]` attribute

An `int` can't be `null` so the attribute will be ignored by both Json.NET and MVC. You may wish to change your model to include `public int UserId { get; set; } = -1;` and add a validator for the containing class.

If you weren't using `[FromBody]`, MVC's `[BindRequired]` attribute would give you the behaviour you want.

**Comment by rynowak** [comment]
And you can also use `[DataMember(IsRequired = true)]` to have the serializer enforce this behavior.

**Comment by Ciantic** [comment]
This design decision makes using FromBody cumbersome, it enforces nullness to the value, when literally all API calls that uses FromBody require the value. Thus I find this implementation backwards. When one decorates a parameter with [FromBody], what would be the reason for it to be null?

If I were to choose the behavior it would be this:

This would mean the FromBody parameter model is required:
```
public async Task MyMethod([FromBody] MyClass model)
```

This would mean it's optional:
```
public async Task MyMethod([FromBody] MyClass model = null)
```

But now there is no good solution to even make it required with attribute, because this is ignored:

```
public async Task MyMethod([FromBody][Required] MyClass model = null)
```

My beatiful API: 
```
        public async Task<IActionResult> GetById([FromBody] GetByIdAction byId)
        {
            return new OkObjectResult(await thingies.FindByIdAsync(byId.Id));
        }
```

Must be littered with null checks on each and every API call that uses FromBody (which in my case is entire API).

**Comment by PinpointTownes** [comment]
Not being able to decorate an action parameter with `[Required]` when it comes from the request body seems a bit weird IMHO... and a terrible trap.
