### ISSUE TITLE
Remove JsonViewComponentResult

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#3992]
I noticed that `JsonHelper` reuses `JsonOutputFormatter` for writing JSON but `JsonViewComponentResult` doesn't. It misses out from array pooling that is managed by the output formatter.

Should JsonViewComponentResult use JsonOutputFormatter?

**Comment by danroth27** [comment]
@rynowak Is the JsonHelper supposed to be using the `JsonOutputFormatter`? I thought we had separated output formatting from all the other JSON use cases.

**Comment by Eilon** [comment]
Looks like we have a variety of behaviors depending on how you do serialization:

- `JsonOutputFormatter`/`JsonInputFormatter`: Get the shared `JsonSerializerSettings` from the service container.
- `JsonHelper` (used in view pages): Creates its own `JsonOutputFormatter`. Can pass in custom `JsonSerializerSettings`. Never uses shared settings from the service container.
- `JsonViewComponentResult`: Creates its own `JsonSerializer`. Can pass in custom `JsonSerializerSettings`, but if none specified, gets the shared `JsonSerializerSettings` from `MvcJsonOptions` from the service container.
- `JsonResult`: The work is done through the `JsonResultExecutor`, which is retrieved from the service container, and uses the specified `JsonSerializerSettings`, but if none specified, gets the shared `JsonSerializerSettings` from `MvcJsonOptions` from the service container.

**Comment by JamesNK** [comment]
Only JsonOutputFormatter/JsonInputFormatter are using array pooling.

**Comment by rynowak** [comment]
This has been rehashed like 15 times, and every time it's discussed my suggestion is to remove `JsonViewComponentResult`. So I'll suggest it again, let's remove `JsonViewComponentResult`.

If we're still not willing to remove this, let's make it go through one of the other code paths.

----------------------

> JsonHelper (used in view pages): Creates its own JsonOutputFormatter. Can pass in custom JsonSerializerSettings. Never uses shared settings from the service container.

This is not true. No code in `JsonHelper` instantiates a `JsonOutputFormatter`. This instance that gets injected by DI [is configured to use the shared settings](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/DependencyInjection/MvcViewFeaturesMvcCoreBuilderExtensions.cs#L115)

Let's add the above to the docs in `JsonHelper` so that it doesn't get asked again.

**Comment by Eilon** [comment]
We've decided to fix the inconsistencies here by removing `JsonViewComponentResult` because there are no known strong scenarios for it. There are already plenty of ways to write JSON to the result stream and we don't need this one.

**Comment by ryanbrandenburg** [comment]
Fixed in #4263
