### ISSUE TITLE
If TagHelperAttribute is now immutable, can it be a struct?

### ISSUE THREAD

**Issue by benaadams** [aspnet/Mvc#4057]
Raising question?

Or would that cause boxing (via interface, via object) or does it need inheritance?

**Comment by dougbu** [comment]
@benaadams @NTaylorMullen tried it out and found making it a `struct` actually reduced throughput. Though I don't think we tested it, the switch would likely also increase memory consumption because `TagHelperAttribute`s are almost-always stored in a `List<T>`. Same number of larger arrays would be created as those lists grow.

**Comment by rynowak** [comment]
@benaadams - we did some basic testing on it. I think there's some more thinking to be done.

What seems more promising is to preallocate `THA`s statically. Since Razor is generated code we have a lot of bandwidth to do things like that.

**Comment by Eilon** [comment]
@rynowak parking on your plate until you guys come to a conclusion on this.

**Comment by Eilon** [comment]
Not planning on making any further changes here.

**Comment by dougbu** [comment]
@Eilon doubt this should be both closed and ready. How 'bout "will not fix"?
