### ISSUE TITLE
System.Buffers + Json.NET everywhere

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Mvc#4092]
The JSON input and output formatters use array pooling from System.Buffers.

Other places to add System.Buffers:
* JsonViewComponentResult - https://github.com/aspnet/Mvc/blob/25eb50120eceb62fd24ab5404210428fcdf0c400/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewComponents/JsonViewComponentResult.cs#L75
* JsonResultExecutor - https://github.com/aspnet/Mvc/blob/8b1bd343ba56152d2a7e677cf041dc9d62b4033f/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/JsonResultExecutor.cs#L114

**Comment by Eilon** [comment]
Will discuss tomorrow with a few folks. Sorta kinda related to the mess described in https://github.com/aspnet/Mvc/issues/3992.

**Comment by Eilon** [comment]
Discussed with @dougbu and @rynowak (The Outlaw):

In #3992 we decided to remove `JsonViewComponentResult`, so that's not an issue here.

For `JsonResultExecutor` we took a look at the code and it already uses pooling by virtue of `IHttpResponseStreamWriterFactory`, which in its implementation uses the pooling feature.

**Comment by JamesNK** [comment]
Json.NET doesn't automatically use pooling for its internal buffer because of IHttpResponseStreamWriterFactory.

From JsonOutputFormatter: https://github.com/aspnet/Mvc/blob/4123d83d26e528fe09c870cc92d4aecf0e80d3f7/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonOutputFormatter.cs#L120

**Comment by rynowak** [comment]
Ah ok yeah, you're right. We should do this.
