### ISSUE TITLE
Html.EditorFor can't generate Div contains 'Label' and 'Select'(DropdownList) with Ajax in MVC 6 

### ISSUE THREAD

**Issue by sdluhaibing** [aspnet/Mvc#4104]
It works like below in MVC 5:
`@Html.EditorFor(model => model.Type_Id, new { Id = "Type_Id",  Label = "Broadcast Type", Key = "Id" , Value = "Description", Ajax = "http://localhost:5000/types" })`

The model key field Type_Id already has attribute [DataType("DropDownList")] from System.ComponentModel.DataAnnotations

But MVC 6. it will only generate the 'input' element..

**Comment by dougbu** [comment]
`EditorFor()` in MVC 5 will not honour the `[DataType("DropDownList")]` unless you have a template named `DropDownList.cshtml` somewhere which contains the HTML you expect. Does that file exist in both the MVC 5 and 6 test projects?

If yes, we need more information to understand the issue. Ideal if you create a GitHub repo containing the failing MVC 6 project.

**Comment by sdluhaibing** [comment]
Yes, I missed the template file. Sorry for not understand the logic here fully.

Just tested in MVC6 project, it can generate the template what I want. And also set the <select> attribute "data-ajax" correctly. but this http Uri did not get executed when the page loading.

Do I miss any other logic? It works fine in my MVC 5 project. I checked the reference js , did not find any difference.

**Comment by dougbu** [comment]
> Do I miss any other logic?

I suspect you'll find what's missing reviewing the differences between the two. Might focus on the JavaScript in your views given your intuition of where the problem lies.

If you find a problem, don't hesitate to create a new issue. We'd appreciate a minimal repro, ideally hosted in a GitHub repo.

Closing this issue since you have resolved the described problem.
