### ISSUE TITLE
Errors when Serializing to JSON

### ISSUE THREAD

**Issue by capesean** [aspnet/Mvc#4160]
I am hitting an error that I can't quite pinpoint. If you can tell me how to debug it better I'll gladly provide the details. This was working fine with EF7 **before** the change to EntityFrameworkCore 1.0, but now I'm getting these two types of errors. I don't think it's an EF issue because the data gets returned from the database fine, it seems to error when it gets serialized in the WebApi. Although maybe it's an issue with Json.Net.

I have an EF model of clients that have projects. A project has a Project Manager, a Project Type, (etc) as related entities.

When I query the API endpoint to list the projects, I run this code:

`````
return Ok(
    DbContext.Projects
        .Include(p => p.Client)
        .Include(p => p.ProjectManager)
        .Include(p => p.ProjectType)
    );
`````

I get the error:

`````
HTTP Error 502.3 - Bad Gateway
The specified CGI application encountered an error and the server terminated the process.

Most likely causes:
The CGI application did not return a valid set of HTTP errors.
A server acting as a proxy or gateway was unable to process the request due to an error in a parent gateway.
`````

If I remove the line `.Include(p => p.Client)` then I get a different issue: the json gets truncated after about 259 projects. If I put a `.Take(258)` in there, then it works fine.

It looks like 2 different issues - the CGI error and the truncating error. As mentioned, this worked a few days ago before I upgraded to AspNetCore and EntityFrameworkCore. 

I'm not sure how to get more error information out but if direct me I'll do it.

**Comment by capesean** [comment]
This appears to be an issue with Entity Framework.

**Comment by capesean** [comment]
It's not entirely an EF issue. Yes, there is a circular reference issue in EF, but if I do `JsonConvert.SerializeObject` on the EF result and then send that string back, it works fine. But if I just do `Ok(queryresults)` then the result is truncated.

**Comment by gdoron** [comment]
I had something similar, try setting this in the `Configuration` method in the `Startup` class:
```
services.AddMvc().AddJsonOptions(options => {
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            });
```

**Comment by gdoron** [comment]
@Eilon shouldn't the default needs to be changed?
Since if the default value comes into play, it will throw an exception...

**Comment by Eilon** [comment]
I think the default value of *not* ignoring reference loops is correct because you want to avoid serializing things that have loops to begin with. Changing the default would likely mask problems with the data being serialized, no?

**Comment by JamesNK** [comment]
Erroring when a loop is encountered is standard behavour for serializers.

**Comment by OlegKi** [comment]
@Eilon: I find changing of default for the best way. The usage of `.Include` is *the standard way* which suggest Entity Framework. The most people just follow the way and then spend a lot of his time in finding the origin of "HTTP Error 502.3 - Bad Gateway" error.

@JamesNK : I could agree with you if the initial model were oriented on serialization. The developer want just include some field which could be get by INNER JOIN and so he uses `.Include`. As the result he get "HTTP Error 502.3 - Bad Gateway" error, which gives absolutely no information about the origin of the problem.

Thus, in *my personal opinion*, changing of defaults would be make Entity Framework more user friendly, especially for newcomers and especially if one unable to report the error with the exact reason on the problem.

**Comment by gdoron** [comment]
@Eilon I agree that if you pass an entity with reference loop to a view you're doing something wrong because you're not using ViewModel/DTO.
But unfortunately from the places I worked at (and from Stackoverflow questions) most developers do not use DTOs, and in matter of fact even the scaffolding provided by MS for creating new Controller do not use DTOs...

**Comment by Eilon** [comment]
Using view models and DTOs is definitely recommended. It's really not a goal for MVC to allow general serialization of EF data models. The reality is that there's effectively a bug in the app, and the bug needs to be fixed, not ignored.

Completely ignoring reference loops is a Very Bad Idea<sup>TM</sup> because it just means the serialized data is *missing stuff* and you can't predict *where*. That's not good.

**Comment by gdoron** [comment]
@Eilon I agree, but the scaffolding and templates should be adjusted to use DTOs (_AutoMapper_ is probably a good idea).
And if possible, changing the error message you get if you if you pass a model with a _reference loop_ from _HTTP Error 502.3 - Bad Gateway_ to something a little bit more reasonable, otherwise once ASP.NET Core will go public, it will be the most asked question on Stack Overflow... :laughing:

**Comment by Eilon** [comment]
@gdoron issues with the templates can be logged here: https://github.com/aspnet/Templates/

However, one thing that's been a constant challenge for us when making the templates is balancing out how easy it is to understand vs. how "real world" something is. Using view models, binding models, and serialization models is definitely more powerful, but it's a large maintenance cost for an app, and more difficult for someone starting to understand (e.g. "how come when I add/change a property in my model I have to do it in 4 places??").

Regarding the Bad Gateway error that's a really tough one: the problem is that you can't know about the error until it's too late, unless you buffer the *entire* response (which could be several GB or more!).

**Comment by datumgeek** [comment]
***The fix (ignore loops) worked great for me***

## my scenario: Web API with EF Core - Returning child data along with parent (via Include)
> quite common, i'm guessing...

Ran into the issue described above.  Didn't get an error, just no response from the web api.

Happened to stumble upon this thread.

Added the fix (ignore loops).

Worked like a champ !!!

**Comment by alexlomba87** [comment]
I agree with @Eilon, but this bug is still unresolved as to date, and two years have passed. 
As a beginner to ASP.Core, it took me several hours to understand what was the problem, even though I literally followed Microsoft Tutorials. This should not happen.

**Comment by alexlomba87** [comment]
I agree with @Eilon, but this **bug** is still unresolved as to date, and two years have passed.
The issue happens even when literally following Microsoft's own tutorials for ASP Core beginners. This should not happen. I myself, learning ASP from scratch, I have lost several hours to understand what was the issue and then come here. The "fix" (ignore loops) worked for me, but I agree it cannot be regarded as a long term solution.

**Comment by alexlomba87** [comment]
I agree with @Eilon, but this [bug](https://github.com/aspnet/Mvc/issues/4160#issuecomment-193023570) is still unresolved as to date, and two years have passed.
The issue happens even when literally following Microsoft's own tutorials for ASP Core beginners. This should not happen. I myself, learning ASP from scratch, I have lost several hours to understand what was the issue and then come here. The "fix" (ignore loops) worked for me, but I agree it cannot be regarded as a long term solution.

**Comment by IssamTechs** [comment]
referencing problem
for example : 
employee {
                  .... ,
                 customer
                 }
customer {
                 .... ,
                employee
                }
usually when you face certain scenarios of  reference  problem you can solve it either:
1)adding Json configuration to bypass this error like
`services.AddMvc().AddJsonOptions(options => {
                options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            });`
2) make use of view models or DTO (data transfer object) to hold the field that doesn't actually have any referencing problem.
