### ISSUE TITLE
project moved to second dev machine fails to start with error 404.15

### ISSUE THREAD

**Issue by bdelaney** [aspnet/Mvc#4166]
Using Azure AD for authentication/authorization. Followed the asp.net web app project template and used 'school/work' authentication option. Project has been working well locally, IIS Express, and deployed to Azure.
But when I moved to a second dev machine and cloned project from repo, will no longer start in localhost https port. Immediately results in error 404.15, query string is too long, and indeed the detail area shows a requested URL that is about a page long.
Tried resetting project settings, turning off anonymous, then back on. Tried matching ports by setting in /Properties/launchSettings.json, all to no avail. Issue persists. Will move to another dev machine today and try to clone again.

**Comment by Eilon** [comment]
Is the 404.15 coming from your own server or from a request to Azure AD?

cc @Tratcher

**Comment by bdelaney** [comment]
Sorry, believe it is coming from the callback to Azure (how would I know?).
To get past it, I commented out the authentication code in startup.cs in order to proceed on laptop dev machine. Then checked in changes, returned to regular work PC, uncommented that auth code, build, run, and all is well. The laptop I had an issue on was a straight clone from git repo (VS team services) and I was running on same network plus two remote networks and always had the same issue.
If you want, I can run the project again on the laptop to determine source of 404.15
Don't have time today, but willing to try reproducing with clean project template using 'work/school' auth and set up another Azure application.

**Comment by Tratcher** [comment]
https://www.iis.net/configreference/system.webserver/security/requestfiltering/requestlimits
I'd guess it's a question of having request limits installed or configured differently on the two machines. Are they the same OS / IIS version? Is it different in IIS vs IIS Express?

**Comment by ArieJones** [comment]
@Thratcher I don't think that this is a matter of request limits as I have travelled down that route a bit and it will just continue to loop until it breaks..... 

I actually have 2 developers that are experiencing the same issue. These are Windows 10 builds. The problem seems to let us log in through Azure but then we get sent into a loop where it is breaking down at our HomeController with the [Authorize] tag..... it fails gets sent back through Azure AD... goes through since you logged in already...back to HomeController and on and on... 

Our Startup.cs is pretty straightforward right now ... 

```C#
 app.UseCookieAuthentication(options =>
            {
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;
                options.ExpireTimeSpan = new System.TimeSpan(0,10,0);
                options.SlidingExpiration = true;


            });`

app.UseOpenIdConnectAuthentication(options =>
            {
                options.AutomaticChallenge = true;
                options.ClientId = Configuration["Authentication:AzureAd:ClientId"];
                options.Authority = Configuration["Authentication:AzureAd:AADInstance"] + Configuration["Authentication:AzureAd:TenantId"];
                options.PostLogoutRedirectUri = Configuration["Authentication:AzureAd:PostLogoutRedirectUri"];
                options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.Events = new CarepilotAuthenticationEvents(loggerFactory);
            });
```

The devs in question have already tried to clear cookies in their respective browsers. It's very puzzling because we have also had one other end user(tester) experience the same issue on one of her laptops and then when switching to a different one she is fine. This is with the site deployed to Azure. We get a slightly different log output here... 

`warn: Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware[27]
      => RequestId:0HKPP4E9FV2EG RequestPath:/signin-oidc
      .AspNet.OpenIdConnect.State.ENQPD3-yDttk3HZgzRKu4o71cmYy-fZOUSXKcHiRKRI cookie not found.
info: Microsoft.AspNet.Authentication.OpenIdConnect.OpenIdConnectMiddleware[0]
      => RequestId:0HKPP4E9FV2EG RequestPath:/signin-oidc
      Error from RemoteAuthentication: Correlation failed.
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]`

Currently we are pegged at RC1 Update 1 until RC2 becomes a bit more stabilized. We are running on IIS Express locally and I would assume IIS in Azure.  So if someone could throw us a direction to solve here that would be helpful.

**Comment by Tratcher** [comment]
"Correlation failed" is a mismatch between the correlation cookie and the state field in the request.
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectHandler.cs#L398

Delete all the cookies and then take a fiddler trace of the login flow.

Side note: You should only have AutomaticChallenge enabled on a single middleware, not both. I think you want it on OIDC in this scenario.

What do you do in CarepilotAuthenticationEvents?

**Comment by ArieJones** [comment]
I will try to have them install fiddler and trace the login flow.... thanks for the heads up on the Automatic Challenge piece. 

The CarepilotAutheticationEvents was just an attempt to hook into the Failed event to see if we could catch some kind of extra tidbit of information.
