### ISSUE TITLE
RouteAttributes do not combine on inherited classes

### ISSUE THREAD

**Issue by glatzert** [aspnet/Mvc#4194]
I'd suggest (and after a hint where to start, I'd also plege to implement it as PR), that RouteAttributes from subclasses should be combined:

```c#
[Route("v1")]
public class Version1BaseController : Controller { }

[Route("some")]
public class SomeOtherBaseController : Version1BaseController { }

[Route("[Controller]"]
public class FooController : SomeOtherBaseController {
    public string Bar() { return "Hello World" }
}
```

Now I'd expect the Action to be here: http://localhost/v1/some/foo/bar,
but actual it is here: http://localhost/foo/bar

Would you consider to allow that in AttributeBased Routing? 
Is it already allowed and I'm just not able to see how?

If not: Is there advice how to accomplish that?

**Comment by Eilon** [comment]
@rynowak / @lodejard I thought we did this on purpose, but I can't recall why. Do you happen to remember?

**Comment by glatzert** [comment]
Btw - your code does support overwriting the whole route in the combineAttributeRoutes Method, by checking for startswith `/` or `~/` - so opting-out is easy, but opting-in is not possible. But I'd be happy to hear the reasoning behind that

**Comment by rynowak** [comment]
It seems odd to create a base class to prepend something to the path. What if I want to inherit from a class, but I don't want to follow the same routing pattern?

Inheritance or route attributes is supported (in my mind at least) for the cases where you have a group of controllers fulfilling a common role (`MyApiController`) with a common routing pattern, and usually also a set of common base functionality. It's also a convenience that was carried over from previous versions (this time with `[controller]` syntax instead of genuine conventional routing). 

Usually if you're doing this, you have a common base-class for the **whole** app, or one for APIs and one for Browser-based actions.

We also didn't want to make routing too strongly tied to class identity, which is why we only use attribute routes on the most derived class to define any - in other words, routes on a controller class have overriding behavior.

----------------------

@glatzert - have you thought about implementing this using namespaces and something like https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs

Attribute routing is already meta-programmable to a complete extent. I'd rather not add more default behaviors if there's not a strong reason why it's relevant to most users.

**Comment by glatzert** [comment]
@rynowak thanks for the clearification. If I understood you right, I could also do something like:

```c#
[Route("v1/some/[Controller]")]
public class SomeOtherBaseController : Controller { }

public class FooController : SomeOtherBaseController {
    public string Bar() { return "Hello World" }
}
```
And would archieve more or less, what I wanted?

But I'll also take a look into the custom conventions - that seems reasonable.
Thank you

**Comment by rynowak** [comment]
Yes, that example would work
