### ISSUE TITLE
Can release the asp.net core 1.0 rc2 before build 2016

### ISSUE THREAD

**Issue by BruinY** [aspnet/Mvc#4275]
Can release the asp.net core 1.0 rc2 before build 2016,Please release as soon as possible, in order to upgrade the migration project

**Comment by Eilon** [comment]
The roadmap for ASP.NET Core is listed here: https://github.com/aspnet/Home/wiki/Roadmap

At this time, there is no announced date for the RC2 release, but we are working as quickly as possible.

**Comment by LeandroPT** [comment]
> At this time, there is no announced date for the RC2 release, but we are working as quickly as possible.

What does this mean? The current project has been started with asp.net 5 on the premise the dates would be respected in some extent. RC1 in Q1 and RC2 on Q2 and RTM on Q3...

So you guys now decide in a comfortable meeting to reset the naming, the dates, localization, etc... 

The bottom line is, what the hell should be done now? since MSFT for the 1st time in .Net history has decided no to keep dates.

You guys are starting to look like Oracle... Complicated!

Thanks

**Comment by Eilon** [comment]
@LeandroPT and others: the [linked blog post](https://blogs.msdn.microsoft.com/webdev/2016/02/01/an-update-on-asp-net-core-and-net-core/) describes why we are doing what we're doing.

If we could give a more refined date, we certainly would. When we have a higher confidence date, we expect to announce it publicly.

In the meantime I recommend trying out the latest nightly builds, providing feedback as appropriate, and staying up-to-date with the latest developments. The product is getting closer and closer to where we want it to be, but there are still enough unknowns at this time that we are not confident in providing a date.

**Comment by miloush** [comment]
@Eilon Maybe there are couple of tasks that need to be done and sharing those without timelines might still be useful?

**Comment by LeandroPT** [comment]
@Eilon All is good and great, i understand and like the reasons, what i do not like is the time frame.

I have been around since Beta 1 of .net 1.0, so i consider myself not exactly a newbie... 
I dunno why, but i was used to RC being Production ready, buggy but no major rework would happen, essentially a project would be used as a guinea pig, and things would be controlled on tests and production takeoff., users would not cry that much.

I am not used to see this kind of replies.... "use the nightly build and provide feedback".... WTF? are you kidding me? I work for MSFT now?

So, if for instance the deadline of my project were to be in 2 months. Would perfectly fall into RC2/RTM back in November '15...

I read your words, and think that in around Q3 the RC2 will be available, RTM in Q1 '17.

So a choice must be done. (trusty) ASP.net 4 + MVC 5, and forget asp.net vnext, 5, core, whatever. Or wait in a act of faith for a better date than those i forecast.

Like i said... you guys just brought hell to my project, and by the way... this is a LOB web app, on Azure with EF7... so, all issues i see should be be on RC1... Not only MVC has a problem.. EF7 is now focusing in retargeting, other then bug fixing...

Never Again... for now on.. Start on RTM... !!!

**Comment by Eilon** [comment]
@LeandroPT we honestly don't have any more to share about dates at this time. This is a difficult situation for everyone, but we think we're getting close to seeing the end in sight. The switch from DNX to .NET CLI was (and *still is*) a huge change and we're not done with it. That's by far the biggest change, though it involves many other semi-related changes as well, such as the change to the TFMs (`dnx451`/`dnxcore50` to `netstandard` etc.). Making this change after the RC1 milestone was a difficult decision to make but we felt it was for the best. These products live for decades, so getting it right before we ship is more important than breaking an RC.

Lastly, using RTM products is always the safest bet - no doubt about it. But it also provides a more difficult avenue for feedback in case someone runs into issues. The early adopters have a huge amount of influence on the product and we very much appreciate all the discussions, issues that were filed, PRs sent, blog posts, NuGet packages, and everything else.

**Comment by BruinY** [comment]
I already have a project in the use of asp.net 5.0 rc1, and when you release the go live.
Now is adjusted for the core asp.net, this is not a simple name change, give me the project has brought the very big pressure, and unpredictable risk.
I hope to release as soon as possible asp.net core rc2, can help my project as soon as possible from the uncontrollable risks.
I think the release status, too much pursuit of perfection, making the pioneer of asp.net 5.0 has suffered huge irreversible and control risk.
Do you have a responsibility to help us out of this bad situation as soon as possible

**Comment by Eilon** [comment]
@BruinY we are working on detailed upgrade guidance from RC1 to RC2, which should help make the transition a lot smoother.

**Comment by Supratentorial** [comment]
I think the sense of entitlement displayed by some, coupled with the lack of appreciation for what the Asp.Net Core team have achieved in such a short time, is very disappointing. I appreciate the work done by @Eilon and others. I think some people need to remember that Asp.Net core is very much new technology. If your project requires a stable development framework, then perhaps you should consider using MVC5/Entity Framework 6.

**Comment by LeandroPT** [comment]
@Supratentorial ...

Dude... Praising the lord does not get things done. RC = RC... deadlines are deadlines... Plans are plans.

**Comment by TrainedApe** [comment]
I am excited by (ASP).NET Core and am appreciative of the massive amount of work done so far; however, not having any kind of time frame to show prevents me from pushing it for new projects with a projected release at the end of 2016.  It's been a couple of months now since the original RC2 date was nullified and to not even have a new preliminary schedule in that time is something I usually associate with projects that have a very death-marchy feel to them.  To clarify, I don't believe that is the case with (ASP).NET Core, but I don't think it's premature to ask for more information either.

So, with many thanks and the deepest respect, I submit that the natives are getting restless, and it's time for the (ASP).NET Core management team to suck it up and make some time frame commitments.

**Comment by miloush** [comment]
@TrainedApe I would recommend Accomplishments section at  https://blogs.msdn.microsoft.com/webdev/2016/04/06/notes-from-the-asp-net-community-standup-april-5-2016/

**Comment by TrainedApe** [comment]
@miloush Thank you that does give some more insight.  To summarize they hope for April  so hopefully that means RC2 will be no later than sometime in May.
