### ISSUE TITLE
@addTagHelpers doesn't work on linux CoreClr

### ISSUE THREAD

**Issue by paulvanbladel** [aspnet/Mvc#4306]
When The running assembly contains taghelpers registered in _ViewImports.cshtml, this all works on windows system but not on linux coreclr (I run in docker instance)

```
verb: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[2]
      Executed action method Host.UI.Home.HomeController.Index, returned result Microsoft.AspNet.Mvc.ViewResult.'
fail: Microsoft.AspNet.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
      Microsoft.AspNet.Mvc.Razor.Compilation.CompilationFailedException: One or more compilation failures occurred:
      Error @ (87:1,36)(4) - [Cannot resolve TagHelper containing assembly 'Host'. Error: Could not load file or assembly 'Host, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
      ] (1,36) Cannot resolve TagHelper containing assembly 'Host'. Error: Could not load file or assembly 'Host, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

```

**Comment by Eilon** [comment]
@NTaylorMullen any idea what's happening here?

**Comment by NTaylorMullen** [comment]
No clue, i'll have to take a look.

**Comment by NTaylorMullen** [comment]
@paulvanbladel Could you provide your docker file, and the commands you're running to build the image?

Aka a repro I could poke around in.

**Comment by paulvanbladel** [comment]
Sure:
Here is the dockerfile: 
https://github.com/paulvanbladel/aurelia-identityserver-aspnetcore/blob/master/BasicSetup/src/IdSvrHost/Dockerfile

I'm doing from the /src/IdSvrHost folder :
```
sudo docker build -t ids . 
sudo docker run -it -p 22530:22530 ids
```
The file _ViewImports.cshtml refers to taghelpers inside the mvc project:
```
@using IdSvrHost
@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
@addTagHelper "*, IdSvrHost"
```

**Comment by NTaylorMullen** [comment]
@paulvanbladel in your dockerfile you're copying the application into a `/app` folder. In the new world the name of your folder defines the name of your application. Therefore, since you were doing all your work locally in the `/src/IdSvrHost` folder it made sense to do `@addTagHelper "*, IdSvrHost"` because that matched the folder/app name. 

If you change the folder from `/app` [here](https://github.com/paulvanbladel/aurelia-identityserver-aspnetcore/blob/master/BasicSetup/src/IdSvrHost/Dockerfile#L42-L43) to `IdSvrHost` your bits should light up.

I haven't given this a shot myself but from a high level that's what seems to be your problem. Let me know if it doesn't resolve your issue and I can take a closer look.

**Comment by paulvanbladel** [comment]
Ok, the new world is challenging :)
But, sounds reasonable, I'll give it a try asap and keep you posted. Thanks for the prompt feedback.

**Comment by paulvanbladel** [comment]
Works like a charm now.
All microsoft aspnet docker examples rely on following code (also yeoman generator-aspnet I believe)
```
COPY . /app/
WORKDIR /app
```
See e.g. https://github.com/aspnet/Home/blob/dev/samples/1.0.0-rc1-update1/HelloMvc/Dockerfile
So, maybe that docker approach is 'suboptimal'. I can imagine that other stuff (apart from this taghelper functionality) depends also on the "assembly name" (so, in our new world: the parent folder name)
