### ISSUE TITLE
Redirect middleware not working as expected

### ISSUE THREAD

**Issue by pantonis** [aspnet/Mvc#4312]
Hi,

I have an asp.net 5 MVC6/Angular2 web application.
I have followed the following example
[Angular 2 Routing with ASP.NET Core 1](http://benjii.me/2016/01/angular2-routing-with-asp-net-core-1/)

to overcome 404 when refresh (F5) is hit.
For client routes that have no params it works fine (http://localost:3049/clients). Fiddler shows that it requests  http://localost:3049/app/core-angular.boot.js

However when I am in a client route that contains a parameter (http://localost:3049/client/2) it does not redirect back to home.
Fiddler shows that it requests http://localost:3049/client/app/core-angular.boot.js

Any idea why it does not redirect to correct path?

**Comment by pantonis** [comment]
Anyone?

**Comment by danroth27** [comment]
@pantonis Can you share a simplified project with us that reproduces the issue so we can take a look?

**Comment by pantonis** [comment]
You can find a simplified project here:

[Angular2Seed](https://github.com/pantonis/Angular2Seed.git)

Go to http://locahost.../clients and press F5. You can see that the page reloads witout any problem.
Then click on the "Click here to go to client 1". You will be redirected to http://locahost.../client/1 . Press F5 there and you will encounter the problem. If you open up fiddler you will see that it requests "/client/app/boot.js" instead of "app/boot.js".

**Comment by pantonis** [comment]
@danroth27  Did you have a look at it?

**Comment by danroth27** [comment]
Sorry, not yet. Just got back from a crazy week at the [BUILD](https://channel9.msdn.com/Events/Build/2016) conference. We'll take a look this week.

**Comment by pantonis** [comment]
crazy but really really exciting!!!

**Comment by pantonis** [comment]
any workaround?

**Comment by Eilon** [comment]
@SteveSandersonMS is this related to some of the other investigations you've recently done?

**Comment by SteveSandersonMS** [comment]
This is a problem with your client-side SystemJS configuration. It's not a problem with your server-side routing middleware (which is working fine).

The reason that SystemJS tries to load `/client/app/boot.js` instead of `app/boot.js` is because, by default, it resolves modules relative to your current URL. So when you're at `/client/1`, it gets resolved relative to `/client`, whereas when you're at `/client`, it gets resolved relative to `/`.

To fix this, check the SystemJS docs. You probably want to specify a `baseURL` with value `'/'`. I don't know whether that alone will be enough - it depends on other details of how your client-side loader is configured, but either way it's not an ASP.NET MVC issue.

For a complete working starting point for an Angular 2 app on ASP.NET Core MVC (using Webpack rather than SystemJS), see [here](https://github.com/aspnet/JavaScriptServices/tree/master/templates/Angular2Spa).

**Comment by pantonis** [comment]
Setting the baseUr:'/' on systemjs did the trick.

Thanks Steve.

**Comment by shimozurdo** [comment]
Could you give me more details about your solution please? I got the same issue :( but I don't sure how I can solve it

**Comment by shimozurdo** [comment]
![image](https://cloud.githubusercontent.com/assets/4074823/17375149/7475e2d6-5975-11e6-8ab6-e203ede2c837.png)

I found it.
