### ISSUE TITLE
How can this possibly be?

### ISSUE THREAD

**Issue by gzak** [aspnet/Mvc#4315]
If I expand the `Model` in the debugger, it definitely has a `Leads` property. But if I expand it in the Watch window, it doesn't. Furthermore, when I execute the current line in the debugger, it crashes saying that 'object' doesn't have a 'Leads' property. How can this possibly be?

![bug](https://cloud.githubusercontent.com/assets/817765/13895617/a516b712-ed32-11e5-82fd-a77f4d541e1f.png)

The action method in question is very simple:
```
var leadsTask = GetLeadsTask(); // Task<string>
var dealsTask = GetDealsTask(); // Task<string>
await Task.WhenAll(leadsTask, dealsTask); // resolve both tasks to completion in parallel

return View(new { Leads = leadsTask.Result, Deals = dealsTask.Result });
```

(Don't worry those `Guid`'s are fake)

**Comment by ciel** [comment]
I know this isn't at all related to your query, but would you mind telling me what the font you're using for the environment stuff is? Like the menu ("FILE" "EDIT" "VIEW" "PROJECT" etc)

At first I thought it was all default, but at closer inspection that just looks so much cleaner than mine. 

I know this isn't likely an appropriate comment to put here, since this is about an actual product issue... though I'm unsure how to ask the question otherwise. Feel free to chastise me as necessary! (but do please leave the font name as well!)

**Comment by pranavkm** [comment]
@gzak, this is essentially the same issue as the one reported in https://github.com/aspnet/Mvc/issues/645 \ https://github.com/aspnet/Mvc/issues/1484. Anonymous types generate internal properties and `dynamic` doesn't reflect over non-public properties. The fix here would be to return a view model type.

**Comment by gzak** [comment]
Makes total sense now, and I suppose one could argue that it forces better practices :-)

I'll fix it on our end.
