### ISSUE TITLE
Authentication type on Authorize attribute

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#432]
| 221 | 10504 | Reported By: Yishai Galatzer |

**Comment by HaoK** [comment]
Short summary of the current iteration of authorize + authZ:
```
Authorize("policyName")

// Add auth services, and policy via DI (options pattern)
services.AddAuthorization(options => options.AddPolicy(new AuthenticationPolicyBuilder("authType1", "authType2").RequireClaim("Type", "AllowedValue1", "AllowedValue2"))

**Comment by PinpointTownes** [comment]
@HaoK what if I want a specific authentication type being applied without enforcing any authorization policy?

**Comment by HaoK** [comment]
you mean filtering the httpContext.User identities?  That currently isn't addressed as the changes are specific to the auth service, and authorize attribute only so far

**Comment by HaoK** [comment]
But if you want to enforce a specific authentication type as your authZ policy, without any additional rules, you can probably do:
` new AuthorizationPolicyBuilder("requiredAuthType").RequireAuthenticatedUser() or RequireClaim(<somerequiredclaim like NameIdentifier>)`

**Comment by PinpointTownes** [comment]
@Haok filtering is probably not the right word. Basically, what I'm looking for is a filter that sets `Context.User` using the authentication handler corresponding to the `AuthenticationType` defined by the attribute (i.e an `HostAuthenticationFilter` equivalent, but that would concat identities in `Context.User` instead of defining a new principal each time).

You'd use it like that:

```csharp
[Authenticate("APIKey")]
[Authenticate("Bearer")]
[Route("/profiles/{profileID}")]
public IActionResult Get(int profileID) {
    if (Context.User.Identities.Any(identity => identity.AuthenticationType == "Bearer")) {
        // When the profile is requested using an access token representing the associated user, return the whole entity.
    }

    else if (Context.User.Identities.Any(identity => identity.AuthenticationType == "APIKey")) {
        // When the profile is requested using a simple API key representing an application, return a limited entity.
    }

    // When the request is unauthenticated, return a very limited entity.
}

**Comment by HaoK** [comment]
Yeah that is more Authentication, I don't think we want to do that as part of Authorization, but at least for now, that is not supported yet.  We do swap out httpContext.User to the ActiveAuthenticationTypes in the policy while we are authorizing, but we revert it back to the old user (which contains the 'active' auth types) after we are done authorizing.

**Comment by PinpointTownes** [comment]
That's indeed definitely more an authentication concern. That's why I'm not sure it should be `AuthorizationService`'s concern to call `AuthenticateAsync` (https://github.com/aspnet/Security/commit/4a635835af1049679103fdca97716e814408addc#diff-1e9e57ee7433d6630e3e3cb634a0e8e4R44). Instead, `context.User` should be filled by an authentication filter and the authorization service should just have to check `context.User.Identities` to determine whether the mandatory authentication types are there or not.

**Comment by HaoK** [comment]
yeah that part is definitely still in flux, we will keep this in mind for the next iteration, as I agree with you it feels weird that we need to pull all of the authentication types.  But as it stands now, its up to the policy to say what authTypes it cares about, so there's no way to know in advance which authTypes the AuthZ service needs until its invoked.

**Comment by PinpointTownes** [comment]
The question is: does it need to know that? That's not really an authorization concern (while enforcing that `Context.User` has specific authentication types would be).

IMHO, to respect a clear separation between authentication and authorization, `ActiveAuthenticationTypes` should be removed from the authorization server and replaced by authentication filters, that would be combined with authentication handlers configured with the `Active` mode. The authorization service should just check the `Context.User` property, nothing more.

**Comment by HaoK** [comment]
Reopening since this part of the design is once again in flux

**Comment by HaoK** [comment]
Closing this out, tracking AuthZ/AuthN issues in security, this issue deals with AuthN filtering https://github.com/aspnet/Security/issues/159
