### ISSUE TITLE
Ability to change log levels of MVC log entries

### ISSUE THREAD

**Issue by veccsolutions** [aspnet/Mvc#4393]
I would like to change the log levels of the MVC log entries so that we don't get spammed in our logs by MVC while still enabling application wide log levels. I've modified the values in appsettings.json/Logging:LogLevels and set them to Debug, but I still see 5 log entries logged at the Information level.

**Comment by Eilon** [comment]
@veccsolutions to silence log messages you can filter by both log level *and* by category. And categories tend to be hierarchical because they are structured around namespace and type names. So, you could easily silence all logs that start with `Microsoft.AspNetCore.Mvc` and you won't see *any* MVC logs.
