### ISSUE TITLE
Passing complex objects to controller actions through route data

### ISSUE THREAD

**Issue by Antaris** [aspnet/Mvc#4410]
Hi Team,

A trick we could use previously on MVC was to set a complex value in the route data (e.g., in a route constraint) and have that value persist through to a controller action - I think the current model binder in MVC6 flowed the value through directly instead of trying to create one.

In ASP.NET Core MVC, the model binder exclusively works with string values (https://github.com/aspnet/Mvc/blob/dev/src%2FMicrosoft.AspNetCore.Mvc.Core%2FModelBinding%2FRouteValueProvider.cs#L72) - which means any complex types would be at most `ToString()`-ed and the value passed through to the model binder.

What solutions do you suggest to allow these complex types to be flowed through to a controller. It's quite an advanced use case, as mostly you'll go directly from `RouterMiddleware` -> `MvcRouteHandler` -> `Controller/Action`, but in my case, I have a custom router middleware that *may* delegate back to MVC, I was hoping to do this:

````
public class PageLinkHandler : ILinkHandler
{
  public async Task HandleAsync(RouteContext context, Link link)
  {
    context.RouteData.Values.Add("controller", "Pages");
    context.RouteData.Values.Add("action", "Display");
    context.RouteData.Values.Add("link", link);
    
    var handler = new MvcRouteHandler();
    await handler.InvokeAsync(context);
  }
}
```

And in my controller:

````
public class PagesController : Controller
{
  public async Task<IActionResult> Display(Link link)
  {
    // Link instance here is generated by model binder instead of the value originally set in the handler.
  }
}
````

**Comment by scottt732** [comment]
I have a similar issue.  In MVC 5 I was using ValueProviders to perform DB lookups.

    [Route("Users/{userId}")]
    public IActionResult Details(int userId, UserModel user) 
    {
        // user is populated by a UserValueProvider.  It reads userId from the route parameters,
        // performs a DB lookup, and returns a model as a ValueProviderResult.
    }

If I was misusing value providers, that's fine, but I'm curious if there are any workarounds as well.

**Comment by rynowak** [comment]
I'd suggest writing a custom model binder rather than a value provider for both of these cases.

Model binders get to look at the type of model being bound and can do the appropriate thing when it's `UserModel` or `Link`. Model binders can be scoped to a single parameter/property or based on the model type.

Value providers are intended to represent "raw" user input that's sent over the wire as key-value pairs. Data in value providers is considered applicable to to any model object that has a matching key. 

We made this API change on purpose to try and draw a distinction between the two. The answer to the question of "value provider or model binder?" wasn't always clear in the past but I think we've got it right with this change. If you feel like this had made something significantly harder, let us know and we can help by providing samples or adding additional extensibility support.
