### ISSUE TITLE
Generating View Without a DBContext is still not Supported

### ISSUE THREAD

**Issue by AcousticGuitar** [aspnet/Mvc#4427]
VS2015 Community Update 2, 1.0.0-rc1-update1 of (DNX SDK)

Attemtpting to create a view is giving the error listed above even though the view does not need EF within it.  The Wizard will not enable the Add button until the Model is filled in for a "Details" view.  However, attempts to add without filling in the DBContext portion issues the message listed in headline.

**Comment by danroth27** [comment]
@prafullbhosale Can you take a look?

**Comment by prafullbhosale** [comment]
@AcousticGuitar This was a known issue with RC1 scaffolding. 
Adding emtpy view isn't supported yet via scaffolding. 

The DBContext is needed in order to get the model's metadata. 
I think a better experience would be to keep the add button disabled if the DbContext is not provided. 
@sayedihashimi thoughts?

**Comment by AcousticGuitar** [comment]
No problem I didn’t realize that MVC 6 was still in infancy…  Thanks!

**Comment by Eilon** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/203.
