### ISSUE TITLE
Update sample projects

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#4428]
Going forward all sample projects should have these changes:
In your Startup.cs you must include
```
new WebHostBuilder().UseContentRoot(Directory.GetCurrentDirectory()).UseDefaultHostConfiguration(args)
```
in your project.json you need
```
"content": [
    "wwwroot",
    "Views",
    "appsettings.json",
    "web.config"
],
```
Samples:
- [x] ActionConstraintSample.Web
- [x] CustomRouteSample.Web	
- [x] EmbeddedViewSample.Web
- [x] FormatFilterSample.Web
- [x] InlineConstraintSample.Web
- [x] JsonPatchSample.Web
- [x] LocalizationSample.Web
- [x] MvcSandbox
- [x] MvcSubAreaSample.Web
- [x] TagHelperSample.Web
- [x] UrlHelperSample.Web

Test websites:
- [x] ApiExplorerWebSite
- [x] ApplicationModelWebSite
- [x] BasicWebSite
- [x] ControllersFromServicesClassLibrary
- [x] ControllersFromServicesWebSite
- [x] CorsWebSite
- [x] ErrorPageMiddlewareWebSite
- [x] FilesWebSite
- [x] FiltersWebSite
- [x] FormatterWebSite
- [x] HtmlGenerationWebSite
- [x] Microsoft.AspNetCore.Mvc.TestConfiguration
- [x] RazorPageExecutionInstrumentationWebSite
- [x] RazorWebSite
- [x] RoutingWebSite
- [x] SimpleWebSite
- [x] TagHelpersWebSite
- [x] UserClassLibrary
- [x] VersioningWebSite
- [x] WebApiCompatShimWebSite
- [x] XmlFormattersWebSite

**Comment by GuardRex** [comment]
For reference ...

> .UseDefaultHostConfiguration(args)

Should be `UseDefaultHostingConfiguration(args), and it's going away: https://github.com/aspnet/Hosting/issues/727 https://github.com/aspnet/Hosting/issues/700

> "content"

Becoming `publishInclude` soon: https://github.com/dotnet/cli/issues/792

> "web.config"

Depending on if you want the `publish-iis` tooling to generate the file from scratch. cli-samples had them removed: https://github.com/aspnet/cli-samples/pull/46 but they were left in Security with a comment by @moozzyk in https://github.com/aspnet/Security/pull/799

**Comment by ryanbrandenburg** [comment]
@GuardRex FYI I've already merged #4503 for this bug. To confirm what you're saying though, `UseDefaultHostingConfiguration` can be remove from all samples, and web.config can be omitted for those projects that use publish-iis? Since the change for `content` would appear to be breaking I assume the person making the change will fix all the samples.

**Comment by GuardRex** [comment]
@ryanbrandenburg The `UseDefaultHostingConfiguration` is still WIP. The `web.config` issue is better commented on by @moozzyk who has his finger on the pulse of samples and the file. For `content`, I think they're saying it will be backwards compat in https://github.com/dotnet/cli/pull/2493#issue-148246289, but yeah, I definitely feel an official Announcement is on the way when this stuff hits.

Personally, yeah, I :heart: love :heart: the idea of his tooling generating the file for me, and I have my apps setup with my own version of his tooling (`GuardRex.AspNetCore.Server.IISIntegration.Tools` ... he'll probably call that "malware"! :smile: ). https://github.com/aspnet/IISIntegration/issues/144#issuecomment-212991722

But yes, you can rely upon his tooling to gen the file on `post-publish` of the project, as long as you're ok with the attribute default values he has in the `web.config` generated by the tool. I hacked it, because I needed the log enabled by default, and I wanted the application name to be the prefix of the log file.

**Comment by ryanbrandenburg** [comment]
I spoke to the team and it sounds like we want to keep our `web.config` files rather than generating them, and we'll address the rest of the things once they're completed.
