### ISSUE TITLE
set current culture to browser culture by default (validation)

### ISSUE THREAD

**Issue by omuleanu** [aspnet/Mvc#4443]
In mvc 5 I had this in web.config:
`<globalization culture="auto" uiCulture="auto"/>`
this way I was getting the browser culture when calling:
`Thread.CurrentThread.CurrentCulture`

what's the equivalent of this in mvc 6 ?

atm the default culture is the one used by my windows not by the browser

**Comment by danroth27** [comment]
See https://docs.asp.net/en/dev/fundamentals/localization.html

**Comment by omuleanu** [comment]
@danroth27 I tried 
`services.AddMvc().AddDataAnnotationsLocalization()`
still having the same problem
the validation is ignoring the browser language ( Accept-Language header )
calling CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern gives the correct format (according to Accept-Language header)

but a property in a viewmodel like this:
```
        [Required]
        public DateTime? Date { get; set; }
```
is not being validated
I would get an error message like: 

> The value '07/20/2011' is not valid for Date.
but if the date is something like this 01/01/2011 it validates ok

**Comment by omuleanu** [comment]
@danroth27 looks like this is impossible for now, unless you change it
http://stackoverflow.com/questions/36590969/enabling-client-based-culture-in-asp-net-core

**Comment by danroth27** [comment]
@DamianEdwards @ryanbrandenburg 

We ship [localization middleware](https://docs.asp.net/en/dev/fundamentals/localization.html#localization-middleware) that you can add to your application to setup the correct culture for you.

I don't see anything from the StackOverflow thread that indicates an issue that we need to address. What specifically do you need us to change? Why does the localization middleware not work for you?

**Comment by omuleanu** [comment]
@danroth27 the problem is mentioned in the many comments on the answer

right now the app can't support all cultures by default (auto),
you have to specify all possible cultures
Something like: 

```
app.UseRequestLocalization(new RequestLocalizationOptions()
            {
                SupportedCultures = new List<CultureInfo>
                {
                    new CultureInfo("de"),
                    new CultureInfo("en"),
                    new CultureInfo("fr"),
           ...
                }
            }, new RequestCulture("en"));
```
you can see this:
https://github.com/aspnet/Localization/issues/237
and this I believe is the change that created the problem: https://github.com/aspnet/Localization/issues/111

**Comment by Eilon** [comment]
Copying my comment from https://github.com/aspnet/Localization/issues/111#issuecomment-209539299:

=========
@omuleanu I believe there were some concerns around allowing completely arbitrary cultures that browsers send, which would potentially cause internal culture caches to potentially grow infinitely, causing memory issues. On OSes such as Windows 10, there is an infinite number of valid cultures, and ASP.NET Core Localization has to cache them (because creating cultures is a bit expensive), so if browsers send en-US-1, en-US-2, ..., en-US-9999 then ASP.NET's culture cache would grow and take up all memory.

Our belief is that sites only support a relatively small set of cultures (at most a few dozen, and that's extremely rare), so listing them all is reasonable.

If a site wishes to support completely arbitrary cultures (i.e. allow *anything* a browser sends), then they will have to use some other middleware.

@ryanbrandenburg @DamianEdwards was this the exact reason? Or was there something else?

**Comment by Eilon** [comment]
In regard to this specific request, ASP.NET Core will not set the culture automatically out-of-the-box. ASP.NET Core is designed around "pay as you go" so you have to enable all the features you want, which means almost nothing is enabled automatically.
