### ISSUE TITLE
Trimming samples \ functional tests

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#4449]
To make local builds faster by moving some of our samples to a separate repo. Additionally we could consider further trimming \ merging functional tests.

**Comment by Eilon** [comment]
We did a massive purge several months ago and killed probably 20-30 sample and test sites. I'm not sure the effort to simply merge/delete some would be worth it because we already did the ones that were relatively easy.

As far as moving to another repo, that's certainly possible, but that would probably make it more difficult to work on MVC because the tests would always be broken, no? Ultimately for perf we're expecting some big perf improvements in dotnet-cli, which should shave several minutes off the build time of MVC.

**Comment by pranavkm** [comment]
There's at least one set of functional tests around filter invocation that could be converted into unit tests or consolidated into a single functional test. Perhaps there's more of those we could poach. That said, it'd be nice to move most of the samples out to a samples repo \ Entropy. Regardless of the average dev work flow, it'd be faster to have projects in general in Mvc.

**Comment by rynowak** [comment]
There are currently 10 sample projects in MVC (not including MVC sandbox). It would be super cool to move those to entropy.

**Comment by Eilon** [comment]
Ah, moving the *samples* specifically is something I can get more onboard with.

**Comment by rynowak** [comment]
When parallel builds are a thing we might also want to 'split' the functional tests project to avoid a knot of dependencies as well, but that's a future problem for FUTURE PRANAV

:car: :fire: :fire: :fire: :fire: :watch:

**Comment by pranavkm** [comment]
> :car: :fire: :fire_engine: e: :fire: :fire: :watch: :tokyo_tower: 

FTFY

**Comment by Eilon** [comment]
Let's move just the samples to Entropy, plus any associated tests.

**Comment by pranavkm** [comment]
The work remaining here is to refactor the FilterWebsite tests. We can move that to 1.0.1

**Comment by Eilon** [comment]
Okie dokie.

**Comment by Eilon** [comment]
Moving to 1.2.
