### ISSUE TITLE
File input doesn't get bound on nested models

### ISSUE THREAD

**Issue by Kukkimonsuta** [aspnet/Mvc#4485]
#### Description

When binding nested models, file inputs get ignored if they are the only input on given submodel (works fine on root model).

Modified `HelloMvc` from cli-samples: https://github.com/Kukkimonsuta/nested-file-binding
#### Setup

``` c#
public class RootModel
{
    public ChildModel Child { get; set; }
}

public class ChildModel
{
    public string Text { get; set; }
    public IFormFile File { get; set; }
}
```

``` html
<!-- form1 -->
<input type='file' name='child.file' />
```

``` html
<!-- form2 -->
<input type='file' name='child.file' />
<input type='text' name='child.text' />
```
#### Expected behaviour
- `form1` binds `RootModel.Child.File` creating instance of both `RootModel` and `ChildModel`
- `form2` binds `RootModel.Child.File` and `RootModel.Child.Text` creating instance of both `RootModel` and `ChildModel`
#### Actual behaviour
- `form1` will create instance of `RootModel` and ignore `ChildModel` leaving it null
- `form2` works as expected

**Comment by dougbu** [comment]
This is expected because `form1` does not contain value provider data for the `ChildModel`. Either add an `<input type="hidden" name="child.irrelevant" value="irrelevant"/>` element to the form or remove the `Text` property from `ChildModel`. (Not positive the second option will work but it should.)

**Comment by rynowak** [comment]
> or remove the Text property from ChildModel. (Not positive the second option will work but it should.)

I don't think this will have an effect

**Comment by Kukkimonsuta** [comment]
Thanks for suggestions, I've tried both solutions, but they don't seem work unless I pollute both model and request with extra data:

* adding hidden input with name that doesn't exist in model (for instance `child.irrelevant`) doesn't force model binder to create instance of `ChildModel` and bind `File`
* removing `Text` from `ChildModel` makes it impossible to bind the model (even when other keys starting with `child.` exist)

**Comment by Eilon** [comment]
@dougbu @rynowak any further thoughts on how to achieve this scenario? Or is it deliberately not supported for some reason?

**Comment by rynowak** [comment]
I have some ideas here to improve this area, but it needs a bigger discussion.

**Comment by Eilon** [comment]
@rynowak ok I'll park on your plate for v1.0.0 and when you have a chance the three of us can get together to discuss.

**Comment by Eilon** [comment]
We are not fixing this for v1.0.0 but we will take another look in the future.

**Comment by loled1728** [comment]
Pretty annoiyng thing. My model looks like this now to make it work if anyone has that issue it may be helpful. You have to send some extra value to make file bind to the model. If you don't have to bind it to the model it is visible in Request.Form.Files. But since I want my view models having IFormFile field this is example how I workaround this:

`public class SomeVM
{
  public GalleryVM Gallery { get; set; }
}
public class GalleryVM
{
  public IFormFile UploadingImage { get; set; }
  public bool FormFileHack { get; set; }
  //gallery properties...
}
//the view .cshtml

<input type="file" name="Gallery.UploadingImage" />
<input type="hidden" name="Gallery.FormFileHack" />
`

**Comment by Eilon** [comment]
@rynowak any thoughts on the complexity of fixing this? Does it involve rewriting model binding?

**Comment by rynowak** [comment]
The only simple fix for this would be to introduce a new metadata type and a new semantic. Something that says "hey you, always bind this".

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
