### ISSUE TITLE
Depend on `HtmlString` from `Microsoft.AspNetCore.Html`.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#4558]
`HtmlString` today inherits from `HtmlEncodedString` and only adds the [Empty](https://github.com/aspnet/Mvc/blob/30ace9f35a63da9527281f903c71059accb33274/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/HtmlString.cs#L14) property. Aside from back compat it seems odd to have both available; might be nice to have just one right way of saying "this is already encoded".

/cc @Eilon

**Comment by Muchiachio** [comment]
:+1: for leaving only `HtmlString` and moving it to abstractions.
Most of the time `IHtmlString` interface is used anyway, which is self explanatory and widely known.

**Comment by dougbu** [comment]
@NTaylorMullen were you really proposing removing `HtmlString`? That's the one that's broadly known, in a commonly-referenced namespace, and what users should use. `HtmlEncodedString` exists primarily because some low-level classes had to be aware of the concept. And back-compat is a great reason to keep the 10 line subclass.

@Muchiachio `IHtmlString` does not exist in ASP.NET Core MVC.

**Comment by NTaylorMullen** [comment]
@dougbu Yes, removing HtmlString.

**Comment by Muchiachio** [comment]
oh sorry I meant `IHtmlContent` :)

**Comment by NTaylorMullen** [comment]
Talked a bit offline. This issue should be "remove `HtmlString`" and i'll file a new issue to rename `HtmlEncodedString` => `HtmlString`

**Comment by NTaylorMullen** [comment]
https://github.com/aspnet/NodeServices/pull/75/commits/24692f07cdba22fbbe420f3941a936ecfb0c9bcd
55922d68d49d0700732d23b8d53c75cb17cad81e
