### ISSUE TITLE
Custom Routing and Redirect

### ISSUE THREAD

**Issue by Luca7993** [aspnet/Mvc#4574]
I have the need to build routing at runtime because I have a cms project where routing is configurable and I need to refresh them when update. With old asp.net, I could reset the route configuration and reloading it. Using default routing with mvc 6, I can't refresh the routing at Runtime. So I tried to use a custom router middleware, where I added a method for reloading the routes. It works well and I can reload the routes during runtime.

But with this custom routing, the Redirect in an ActionResult is not working anymore and I can't found the problem (I also tried to look the original code in github without success) If i use Response.Redirect inside the controller method, the redirect is working. If instead I use RedirectToAction, or a simple custom MyRedirectResult, the redirect is not working (error http 404).

[At this link ](https://github.com/Luca7993/CustomRoutingAndRedirectProblem) there is a sample project with this behavior. In the startup file you can setup it to use the default routing (everything work) or custom routing

I can solve the problem Always using Response.Redirect inside the controller method, but I would like to understand why the redirecttoaction is not working

thank you Luca

**Comment by dougbu** [comment]
The link you provided is not publicly-accessible. Please host your project as a GitHub repo. Failing that please make the existing link public.

**Comment by Luca7993** [comment]
Sorry, I thought it was a public link.
Anyway, I have changed now the link to a github repository

**Comment by Eilon** [comment]
@Luca7993 thanks for sharing the detailed code. I think the issue here is that MVC simply doesn't "see" all the other routes. MVC's helper methods (`Url.Action`, `RedirectToRoute`, etc.) only "see" the routes that were configured in the call to `UseMvc()` that the current request is on.

Please refer to https://github.com/aspnet/Routing/issues/289 where a similar issue is in discussion.

cc @sebastienros in case he has thoughts on this, given that he works on Orchard.
