### ISSUE TITLE
Boxing of Action Parameters

### ISSUE THREAD

**Issue by SamuelEnglard** [aspnet/Mvc#4590]
The current pipeline has all values for parameters to an action as `object`s. This means that when I use a `struct` as a parameter it get's boxed. And that boxing and unboxing gets really bad if I work with them in Filters. Would you be open to work that would prevent this boxing? (Generics, Expressions, and `Reflection.Emit` most likely to be used in some combination)

**Comment by rynowak** [comment]
> boxing and unboxing gets really bad if I work with them in Filters. 

Do you have any performance data you can share that suggest boxing of action arguments is a significant contributor to the overall performance of an application? An allocation profile would be most helpful.

> Would you be open to work that would prevent this boxing? (Generics, Expressions, and Reflection.Emit most likely to be used in some combination)

If there's evidence that this would have an impact in a practical scenario we'd consider making changes, provided the changes are a good design fit.

In particular one of the challenges that I foresee would be that [ActionExecutingContext](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Filters/ActionExecutingContext.cs#L49) exposes the arguments as an `IDictionary<string, object>` which is pretty useful and has a long legacy of being used for all kinds of things.

**Comment by SamuelEnglard** [comment]
How do I do perf on .NET Core? The built in tools for VS2015 don't seem to work on Core.

**Comment by davidfowl** [comment]
@SamuelEnglard do it on .NET Framework, there shouldn't be any difference in this regard.

**Comment by Eilon** [comment]
@SamuelEnglard we use [JetBrains dotMemory](https://www.jetbrains.com/dotmemory/) for most of our memory allocation investigations. It has a free trial that you can use as well.

I'm closing this issue for now because there is no specific action to take here. Given what @rynowak mentioned it is relatively unlikely that boxing could be completely avoided for the particular examples given due to other important features. But if you have specific findings on allocations please log issues on those findings and we can discuss the details. Thanks!
