### ISSUE TITLE
Unicode symbols are turned into &#x....

### ISSUE THREAD

**Issue by AR1ES** [aspnet/Mvc#4596]
When I use the Unicode (or Cyrillic) in the output HTML I get encoded symbols like `&#x2122;`, etc.
The error occurs only when I use string objects (e.g. data loading from DB).
Take a look at an example. For template
```
<h1>Test™</h1>
```
the output HTML is
```
<h1>Test™</h1>
```

However for template
```
<h1>@("Test™")</h1>
```
the output HTML is
```
<h1>Test&#x2122;</h1>
```

I'am using RC1.
Fortunately browsers displays all fine, but this is a great overhead for Cyrillic sites (8 symbols instead 1).

**Comment by dougbu** [comment]
The literal `Test™` is not further encoded because the system assumes the Razor author has written valid (safe) HTML. However all output from C# is encoded because the system assumes included values come from a form submission or other user input.

If you're _positive_ some ranges of Unicode characters are safe for your application and visiting browsers, you can adjust the `HtmlEncoder`, `JavaScriptEncoder` and `UrlEncoder` defaults e.g.
``` c#
public class Startup
{
    ...
    serviceCollection.AddWebEncoders(options =>
    {
        options.TextEncoderSettings = new TextEncoderSettings(
            UnicodeRanges.Cyrillic,
            UnicodeRanges.LatinExtendedB,
            UnicodeRanges.LetterlikeSymbols);
    });
    ...
}
```

Note that by default the `TextEncoderSettings` property is `null` but the various encoders have internal defaults.
