### ISSUE TITLE
Remove `IActionFilter`, `IAsyncActionFilter`, `IDisposable` implementations from `Controller`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4640]
As I mentioned in #4639,
>  The MVC filter invocation infrastructure handles both asynchronous and synchronous filters just fine.

So, the `virtual` methods in `Controller` for `IActionFilter` and `IAsyncActionFilter` don't do enough to be worthwhile. At best they made it clear controllers can be action filters -- a documentation issue.

And the `IDisposable` implementation in `Controller` is similarly anemic. The `DefaultControllerActivator` handles the case where a controller is disposable but doesn't require it.

If any of these `interface` implementations are valuable, they should be included in `ControllerBase` instead. None of these interfaces are linked to view features. Might be good to have a clear non-view / view split between `ControllerBase` and `Controller`.

**Comment by rynowak** [comment]
The action filter implementations are here for compat with users' existing code. We frequently get questions about when it's "safe" to do initialization in a controller, and this is/has been the answer.

IMO we should consider removing `IDisposable`. It made more sense when we didn't have DI. It's probably not a good idea to keep it for compat, because in a DI world your existing code is likely wrong.

**Comment by Eilon** [comment]
All the compat reasons trump everything else at this time.
