### ISSUE TITLE
How to get to the e.g. bindingsource that provided the value for an invalid modelstate

### ISSUE THREAD

**Issue by NinoFloris** [aspnet/Mvc#4642]
As per JSON API specifictation http://jsonapi.org/format/#error-objects

I would like to reply with a source that is either a json pointer or parameter when my modelstate is invalid via an `OnActionExecuting` action filter. There is a boatload of info in this `ActionExecutingContext` but really not anything useful to allow me to distinguish where the error came from. Was it bound via a query parameter or was it found in the body or whatever?

Is there any way to do this?

**Comment by Eilon** [comment]
@NinoFloris I don't think that information is available after the binding has completed. At most you have the key in the model state dictionary, but that won't tell you where the data came from. Of course, that answer is sometimes impossible to provide: if data is *missing*, how do you know from where it was missing? The model binding system probably queried several different value providers (form, query string, route data, etc.) and none of them returned a value. But which one of them "should" have had the value?

Perhaps if your scenario is more constrained, you can just always say, for example, if there's an error in the `id` then it came from the form, and all other errors came from the JSON payload.

Might that work?

**Comment by NickAb** [comment]
I run into somewhat similar problem. In my case I know for sure that I am binding and validating model from body. What I want to do is to convert ModelState keys from string containing C# property names to names that correspond to JsonProperty names of corresponding properties. E.g., if I have a following DTO
```
{
    [JsonProperty("code")]
    [Required]
    [RegularExpression(Ensure.RegularFeatureCodeRegEx)]
    public string FeatureCode { get; set; }

    [JsonProperty("name")]
    [Required]
    [StringLength(32, MinimumLength = 3)]
    public string Name { get; set; }
}
```
and I have validation error in Code or Name properties, I will get following ModelState errors:
```
"FeatureCode":["... FeatureCode ... \"^[a-z][a-z|0-9|-]{0,31}$\"."], "Name":["... Name ... 3 ... 32."]
```
while (because I have separate WebAPI and Single Page Application client), I would like errors to be at least
```
"code":["... FeatureCode ... \"^[a-z][a-z|0-9|-]{0,31}$\"."], "name":["... Name ... 3 ... 32."]
```
so that keys would correspond not to CLR properties names, but to names that will be used in successful json response. This will allow me to display errors at corresponding fields of form on client side without need for client side to know how to map WebAPI internal names to public names in json.

I would like to know if there is anyway to extend binder or validator so that it will use "display" names for keys instead of CLR properties names.
For now I settled on this code that uses reflection to get attribute from properties, but this will work in simple cases only.
```
public static void IsModelStateValid<T>(ModelStateDictionary modelState)
        {
            if (modelState.IsValid)
            {
                return;
            }

            var exception = new BadArgumentsException("...");

            foreach (var source in modelState.Where(x => x.Value.ValidationState == ModelValidationState.Invalid))
            {
                var name = source .Key;
                var info = typeof(T).GetProperty(source.Key);
                var attr = (JsonPropertyAttribute)info.GetCustomAttributes(typeof(JsonPropertyAttribute), true)
                    .FirstOrDefault();

                if (attr != null)
                {
                    name = attr.PropertyName;
                }

                exception.Data.Add(name, source.Value.Errors.Select(x => x.ErrorMessage).ToList());
            }

            throw exception;
        }
```

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
