### ISSUE TITLE
Filters provided by an `IFilterFactory` cannot usefully implement `IOrderedFilter`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#4648]
The `DefaultFilterProvider` does not change the `FilterProviderContext.Results` order when it encounters `IFilterFactory` implementations. The order therefore matches that of the `ActionDescriptor.FilterDescriptors`, which `ControllerActionDescriptorBuilder` sets based on the `IFilterFactory`'s `Order` and `Scope`.

Suggest `DefaultFilterProvider` should reorder the `Results` when a created filter implements `IOrderedFilter`. If not, should expand the documentation of `IOrderedFilter` to cover cases where the `Order` is not honoured.

**Comment by Eilon** [comment]
The order is intended to be a setting that the person directly using the attribute/filter would apply. It is not intended to be useful for filters to determine their own order because they can't possible know what other filters exist. That's why we have filter stages - to have large logical groups of filters that *are* guaranteed to happen before/after other groups.
