### ISSUE TITLE
ModelBinder attribute attached to a class has no effect (broken in rc2-final)

### ISSUE THREAD

**Issue by AlekseyMartynov** [aspnet/Mvc#4652]
I have a model class and a binder:
```
[ModelBinder(BinderType = typeof(MyModelBinder))]
public class MyModel {
    public string Foo;
}

public class MyModelBinder : IModelBinder {

    public Task BindModelAsync(ModelBindingContext bindingContext) {
        var model = new MyModel {
            Foo = "Bar"
        };

        bindingContext.Result = ModelBindingResult.Success(bindingContext.ModelName, model);                               
        return Task.CompletedTask;
    }
}
```

Usage:
```
public IActionResult Index(MyModel model)
{
    return View();
}
```

In rc2, the binder isn't invoked, but the same approach works fine with classic MVC 5 and DNX rc1-final.
Full sample: https://github.com/AlekseyMartynov/aspnetcore-rc2-modelbinding

**Comment by dougbu** [comment]
I can reproduce this issue. The `BinderTypeModelBinderProvider` isn't called though the `ModelBinderFactory` has an instance first in its `_providers` -- as expected. Will see if I can reproduce this in the MVC Sandbox and debug further...

**Comment by dougbu** [comment]
:cool: bug :sunglasses: 

Well `BinderTypeModelBinderProvider` is called but it's checking `context.BindingInfo?.BinderType` instead of `context.Metadata.BinderType`. At the top level, the first is non-`null` only when binding attributes are on the parameter. Binding attributes on a parameter _type_ are not used.

Probably best for `ModelBinderFactory` to initialize `DefaultModelBinderProviderContext.BindingInfo` using both its own `ModelBinderFactoryContext.BindingInfo` and `ModelBinderFactoryContext.Metadata.BindingInfo`. No need for any changes except when initializing for the top level model.

This issue affects at least
- `BinderTypeModelBinderProvider`
- `BodyModelBinderProvider`
- `HeaderModelBinderProvider`
- `ServicesModelBinderProvider`

**Comment by Eilon** [comment]
Umm, and add a unit test? 😄

**Comment by dougbu** [comment]
@Eilon well I've fixed the bug while proving to myself I understood it. So why not :smiley_cat:

**Comment by dougbu** [comment]
e63f094

**Comment by jruckert** [comment]
Is there a work around for this (if we want to keep using rc2-final)??

**Comment by AlekseyMartynov** [comment]
@jruckert yes, the workaround is to use the binder attribute explicitly ([example](https://github.com/DevExpress/DevExtreme.AspNet.Data/blob/8402c717a677246f4389d3c46439e166364c3e3d/net/Sample/Controllers/NorthwindController.cs#L22))

**Comment by vaindil** [comment]
@dougbu I don't know if this is working. The attribute seems to have no effect in my code. Model binders are still called in order like normal, the attribute does nothing.

```csharp
[HttpGet]
public async Task<IActionResult> Get([ModelBinder(BinderType = typeof(MyModelBinder))] int userId)
{
    // stuff
}
```

**Comment by dougbu** [comment]
@vaindil please open a new issue describing the exact scenario where you're seeing a regression of this fix.

I assume you are using an Mvc package more recent than 1.0.0. But, please include the `project.json` content in the new issue.
