### ISSUE TITLE
Add default asp-fallback-test for the script TagHelper

### ISSUE THREAD

**Issue by halter73** [aspnet/Mvc#4722]
I think there should be a default `asp-fallback-test` which is used if a specific one isn't already provided.

It should be possible to use a DOM event like `scriptElement.onload` to determine whether or not the script was successfully loaded. This might not catch quite everything a custom test would like if an empty 200 response was returned instead of the expected script, but I suspect this would catch the vast majority of script load failures.

Here is an example test the @glennc added to http://packagesearch.azurewebsites.net/. A complicated fallback test could probably be omitted if a default was provided.

```html
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-route.js"
        asp-fallback-src="~/lib/angular-route/angular-route.min.js"
        asp-fallback-test="(function() { try { window.angular.module('ngRoute'); return true; } catch(e) { return false; } })()">
</script>
```

**Comment by NTaylorMullen** [comment]
In order to accomplish this we'd need to render onload attributes on the rendered Script tags from our `ScriptTagHelper`. That's an approach that's been discouraged in modern HTML.

The other potential alternative would have been to create script elements in JavaScript, attach onload events and then append them to the DOM. The problem with that approach is that you break the synchronous script injection behavior made possible by the `ScriptTagHelper`. Attempting to work around synchronous script injection is discussed in depth [here](https://github.com/aspnet/Mvc/issues/5248).

@Eilon / @danroth27 I suggest closing this issue as will not fix.
