### ISSUE TITLE
Remove disable buffering feature from our action result classes

### ISSUE THREAD

**Issue by javiercn** [aspnet/Mvc#4766]
See https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ContentResult.cs#L70
It's not implemented by any of our servers and we haven't figured out in detail how it would work, it doesn't hurt right now to have it, but it's a premature optimization. We can remove it at a later point

**Comment by lodejard** [comment]
I actually does hurt to have it - see #4876. The action results should only disable buffering if it's necessary for them to function correctly, but it shouldn't be done as an optimization because it's counteracting the app dev's choice to add buffering middleware.

Calling flushasync on the response body when you don't need to  fits into the same category.
