### ISSUE TITLE
No service for type 'Microsoft.AspNetCore.Identity.UserManager has been registered. ??

### ISSUE THREAD

**Issue by ermithun** [aspnet/Mvc#4783]
migrating  UserManagement in different  class library gives this Error:
No service for type 'Microsoft.AspNetCore.Identity.UserManager has been registered. ??

**Comment by javiercn** [comment]
@HaoK does this sound familiar to you?

Are you calling AddIdentity in ConfigureServices on Startup.cs?

**Comment by ermithun** [comment]
Yes
 In ConfigureService on Startup.cs i have called
            services.AddIdentity<ApplicationUser,ApplicationRole>()
                .AddEntityFrameworkStores<ApplicationDbContext>()
                .AddDefaultTokenProviders();

what should i do for this

**Comment by HaoK** [comment]
Hard to say, can you include the relevant code in the ctor and startup?

**Comment by Eilon** [comment]
@HaoK any further idea on this?

**Comment by HaoK** [comment]
My guess is there's a type mismatch somewhere, i.e. asking for `UserManager<IdentityUser>' instead of `UserManager<ApplicationUser>` or something along those lines which causes the service not to be found.  Without any more relevant code there's nothing we can do other than speculate...

**Comment by Eilon** [comment]
So it is.

**Comment by pettechbytes** [comment]
I hope this doesn't reopen this issue, but I can comment and explain what happened (or at least assume).  I ran into the same issue and it was because during my testing, I renamed ApplicationUser to my own name (SomethingUser) and then decided to move the class to another class library.  The problem was that I left the SomethingUser defined in my web project thus the constructor for the UserManager didn't know which one I was targeting when in my ConfigureServices I identified it as the SomethingUser in my class library.  Great hint HaoK, it helped me correct my own issue.  It was a type mismatch.

**Comment by light-traveller** [comment]
In `_LoginPartial.cshtml` replace the following:
`SignInManager<IdentityUser>` and `UserManager<IdentityUser>` 
with:
`SignInManager<ApplicationUser>` and `SignInManager<ApplicationUser>`.

**Comment by wstaelens** [comment]
_LoginPartial.cshtml change to:
``` 
@*@inject SignInManager<IdentityUser> SignInManager
  @inject UserManager<IdentityUser> UserManager*@
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
```

**Comment by andersonphiri** [comment]
@HaoK  I thought if ApplicationUser is deriving IdentityUser the an is-a will work???? but it doesnt, you will have to put the type explicitly

**Comment by javiercn** [comment]
@andersonphiri That's not the case, you need to have the specific user type for DI purposes
