### ISSUE TITLE
Naming inconsistency between AuthorizationFilterContext and ExceptionContext

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#4796]
The other three 'types' of filters (`Action`, `Resource`, and `Result`) each have multiple 'phases' with corresponding contexts (`Executing` and `Executed`) but these two (`Authorization` and `Exception`) are 'eponymous'. Obviously `AuthorizationAuthorizationContext` and `ExceptionExceptionContext` won't do, but I feel that the two should at least be consistent with each other -- and since `AuthorizationContext` and `ExceptionContext` both seem very generic, I feel that the best action to take would be to rename `ExceptionContext` to `ExceptionFilterContext`.

**Comment by dougbu** [comment]
@tuespetre could you clarify your concern? Is it just that `AuthorizationFilterContext` and `ExceptionContext` don't share their naming scheme?

I suspect what's confusing me is your mention of the other three filter types and their sync and async variants.

Side note: MVC 5 has an `AuthorizationContext` instead of an `AuthorizationFilterContext` though they serve the same purpose. We may have renamed that one but not `ExceptionContext` at some point.

**Comment by tuespetre** [comment]
@dougbu that is correct. It is purely an issue with the naming schemes.

**Comment by rynowak** [comment]
We renamed `AuthorizationContext` -> `AuthorizationFilterContext` to avoid a naming conflict with a type in the AuthZ system.

We discussed this suggestion and would rather leave `ExceptionContext` where it is. We'd prefer the inconsistency in this case to introducing a breaking change with MVC5 and all of our legacy.

**Comment by tuespetre** [comment]
Thanks @dougbu and @rynowak!
