### ISSUE TITLE
Calling conventions for ViewComponents

### ISSUE THREAD

**Issue by bfolder2001** [aspnet/Mvc#4812]
Invoking ViewComponents currently feels a little messy, mostly for two reasons:

1. The name of the component is a magic string with no compile-time binding.
2. The parameters are passed in via an anonymous object with no intellisense available.

The current documented method as of RC2 (and please advise if I'm wrong here) appears to be:

`@await Component.InvokeAsync("UserTable", new { users = Model.Users })`

With a little bit of work and the new `nameof` expression we can get around point 1, but it's a little awkward as `nameof` returns the full class name. In the example above, the likelihood is that if following convention your class will be named `UserTableViewComponent` and the following will throw an error:

`@await Component.InvokeAsync(nameof(UserTableViewComponent), new { users = Model.Users })`

If we rename our class and manually derive from `ViewComponent` or decorate with attributes we have a working solution (at the cost of breaking convention):

`@await Component.InvokeAsync(nameof(UserTable), new { users = Model.Users })`

Would it be possible for the `InvokeAsync()` method to be aware of convention based usage of `nameof` and automatically detect and remove `ViewComponent` from the end of the component name, when specified?

I have seen the generically typed version of `InvokeAsync()`, but unfortunately razor really doesn't play well with generics in method calls, parsing the `<` and `>` as HTML tags, leaving you with additional parenthesis:

`@(await Component.InvokeAsync<UserTableViewComponent>(new { users = Model.Users }))`

This final one seems to probably be the best way to adhere to conventions and not rely on magic strings, yet in every piece of documentation and tutorial I've seen it's plain old `InvokeAsync()` that's used. Is there a reason why?

Regarding the parameter passing, and taking into the account the above, having used and written TagHelpers in .NET Core (which are absolutely fantastic, by the way!) I can't help feel that the same kind of approach, with parameters automatically converted into kebab-case attributes, would be so much more pleasant to use and interact with in your views. Following the example above, the ideal would seem to be to be able to do something like:

`<user-table users="Model.Users" />`

If Visual Studio integration and Intellisense could work as well on the above as it did on TagHelpers it'd seem to be a pretty big win for usability and readability in razor views.

Thanks, and as a PS, I think you're all doing great work with .NET Core.

**Comment by Eilon** [comment]
@NTaylorMullen do you have any thoughts on this?

**Comment by NTaylorMullen** [comment]
It'd be odd to add custom IntelliSense for `ViewComponent`s seeing that they're C# already. However; we've talked about adding `ViewComponent`s `TagHelper` by default. Aka converting `ViewComponent`s into `TagHelper`s automagically.

I do however think it's a good idea to accept the `ViewComponent` ending and strip it off at resolution time. @rynowak opinions?

**Comment by bfolder2001** [comment]
@NTaylorMullen Regarding the Intellisense, I don't really mean anything custom, rather than allowing the IDE to inform you of what parameters your ViewComponent expects. In the example above:

`@await Component.InvokeAsync("UserTable", new { users = Model.Users })`

As far as I can see the only way to know that the ViewComponent expects a parameter called `users` is developer head-knowledge, and as it's an anonymous object it's effectively another magic string (changing the signature of your `InvokeAsync()` at a later date will just prevent parameters being passed along, likely creating silent failures or other unpredictable results).

With a less trivial example, say a ViewComponent with 5+ parameters, and especially on a project with a large number of ViewComponents, it feels like the lack of Intellisense here would be a weak point, at least as far as I understand the situation.

Compounding the above is that an obvious design pattern seems to me to be to create a strongly typed object to hold the component's settings and data, a `ComponentViewModel` if you will. All the required options and data can be passed in within a single strongly typed object and that same object can be passed on to the ViewComponent's view for rendering. At the point of invocation, this then requires something along the lines of:

`@(await Component.InvokeAsync<UserTable>(new { new UserTableComponentModel() { users = Model.Users }}))`

This has the positive impact of allowing Intellisense to kick in when setting the properties of `UserTableComponentModel`, and if you stick to internal conventions it should always be obvious what your model object's name should be in relation to the ViewComponent itself. It definitely feels like a little bit of syntactic sugar could make things even friendlier though.

I realise that with this simple example a strongly typed model for the component is overkill, but add a couple of boolean settings and the like into the mix as well and the positives I see with this approach multiply quickly.

**Comment by NTaylorMullen** [comment]
@bfolder2001 With what's available currently what's stopping you from doing:

`@(await Component.InvokeAsync<UserTable>(new UserTableComponentModel() { users = Model.Users }))`


Note, the lack of `new {`.

**Comment by bfolder2001** [comment]
@NTaylorMullen Sorry, I was writing from memory in my above post and the code should be:

`@(await Component.InvokeAsync<UserTable>(new { model = new UserTableComponentModel() { users = Model.Users }}))`

That's given the method signature: `InvokeAsync(UserTableComponentModel model)`

Note the additional `model =` in there. The binding of parameters doesn't seem to work in the same way as model binding on MVC views does.

I haven't tested it, but I would imagine that if you duplicated the names and types of the properties of your `UserTableComponentModel` into the method signature itself then it would bind properly when called as you suggested, but then you don't end up with your strongly typed object inside `InvokeAsync()`.

**Comment by NTaylorMullen** [comment]
Ah, @bfolder2001 I see. Ya that's currently not supported.

So `ViewComponent` invocation is an interesting thing and we understand that the current methods of invoking them aren't as good as they could be.Talked a bit offline about this and it's a tough decision. Do we take steps to make the current API slightly more consumable or do we add a true fix?

We've had design discussions on what a true fix might look like and that ended up having a more `@inject` like syntax with hard IntelliSense. We like that alternative but decided to not push for it in RTM due to the size of the change.

To give some suggestions on a few of your issues:

> I haven't tested it, but I would imagine that if you duplicated the names and types of the properties of your UserTableComponentModel into the method signature itself then it would bind properly when called as you suggested

Correct



> Would it be possible for the InvokeAsync() method to be aware of convention based usage of nameof and automatically detect and remove ViewComponent from the end of the component name, when specified?

Add an extension method to the `IViewComponentHelper` to do this for you :smile:. Problem with doing this out of the box on our end is it becomes viral. Ex: everywhere we take in a Controller string do we then also strip out `Controller` if it exists? Raises a lot of questions like that :smile:

**Comment by bfolder2001** [comment]
Thanks for the reply, @NTaylorMullen! I'm fairly comfortable with the workflow I've figured out, and I've at least removed all but one of the magic strings (and the magic string that's left can be consistent across an entire project, so no per-component head knowledge to learn and remember). I think the geneically typed version of `InvokeAsync()` is nicer than the `nameof()` method anyway, so no need for the extension method; I didn't consider the slippery slope that would mean for the framework!

Anyway, thanks for the discussion and hopefully you guys will be able to revisit this for the "true fix" for versions after RTM.

**Comment by tuespetre** [comment]
@NTaylorMullen: The TagHelper syntax *sounds* nice at first, but how will it work with descendant tags? Seems like the 'shape' of the two concepts might be too different to smoothly blend them together like that...

Could we allow ViewComponents to be called directly?

  - Inject ViewComponents as services into controllers/actions and return `IViewComponentResult` from the controller actions:
    ```
    public class MyController : Controller
    {
        public async Task<IActionResult> Index([FromServices]MyViewComponent component)
        {
            var result = await component.InvokeAsync("strongly", "typed", "args");

            // A new 'convenience' overload
            return ViewComponent(result);
        }
    }
    ```

  - Inject ViewComponents into views and allow direct writing of the `IViewComponentResult`:
    ```
    @inject MyViewComponent MyComponent

    <h1>Hello, friends!</h1>

    @await MyComponent.InvokeAsync("strongly", "typed", "args")
    ```


We already have `AddViewComponentsAsServices()` to make the ViewComponents injectable. For the controllers we would need another `IActionResult` (`ViewComponentResultResult`?) and that convenience method, and for the views we would need to extend the MVC Razor host in some way (my first thought on that is to add an `ExecuteAsync` method to `IViewComponentHelper`/`DefaultViewComponentHelper` and generate code like `await Component.ExecuteAsync(await MyComponent.InvokeAsync("strongly", "typed", "args");` instead of `Write(await MyComponent.InvokeAsync("strongly", "typed", "args");`.)

**Comment by NTaylorMullen** [comment]
@tuespetre I'm not entirely sure what you mean by descendant tags as it relates to ViewComponents. 

As for invoking ViewComponents directly (not through some sort of helper), that'd be difficult because you would not be able to wrap the ViewComponent invocations and therefore would not be able to add consistent diagnostic data around said invocations. This in turn would break glimpse. Also, if you want to invoke ViewComponents directly that isn't far off from just building a standalone service that you invoke :smile: 

If you're interested, [here's](https://github.com/aspnet/Mvc/blob/889af503185a3b110e89831c704e9e187bfdabf3/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewComponents/DefaultViewComponentInvoker.cs#L102-L138) the piece that deals with the invocation wrapping.

**Comment by danroth27** [comment]
We plan to address view component invocation by supporting invoking view components as tag helpers #1051.

**Comment by tuespetre** [comment]
@NTaylorMullen very good point about the diagnostics. Thanks for the exposé!
