### ISSUE TITLE
Null view model

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#4826]
While debugging an app with `NullReferenceException` intercepted, I noticed some coming from a view with `<input asp-for>` tag helpers. The Model being null, I would expect that it throws an exception. However I was not expecting the view to render correctly with this exception thrown.

Is that expected?

**Comment by dougbu** [comment]
We ignore `NullReferenceException`s when evaluating a user's expression in both HTML and tag helpers. Have a look at [`ExpressionMetadataProvider`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ExpressionMetadataProvider.cs#L83-L86).

Note that otherwise MVC could not generate a Create page -- everything is `null` there.
