### ISSUE TITLE
Bundling and minifying options discussion point

### ISSUE THREAD

**Issue by TheBeardedLlama** [aspnet/Mvc#4835]
(please feel free to point me somewhere else if this is not the right place to have this conversation!)

I know I'm a bit late to the party with this one, but I'm trying to understand what options we have based on the changes in ASP.Net core.

Am I correct in saying that in *core* the only available option is to have everything (i.e. css and js assets) precompiled and included at build time?

I have loads of follow up questions if the answer to the above is yes, but I will save on typing if this is not the right forum and/or I've got the wrong end of the stick.

[Also is there a definitive document somewhere explaining precisely how this works in *core*?]

**Comment by Eilon** [comment]
cc @madskristensen

**Comment by madskristensen** [comment]
@TheBeardedLlama The ASP.NET Core template will will be switching to use the Bundler & Minifier system instead of using Node/npm/Gulp to do bundling and minification of CSS and JS files. I just created this [wiki page](https://github.com/madskristensen/BundlerMinifier/wiki) with more details.

You can use it today already to test it out on existing .NET Core RC2 apps. The VS extension part of the system provides a great VS experience for creating and maintaining the client assets and works on both Website projects, WAP (webforms and mvc) projects as well as .NET Core.

**Comment by TheBeardedLlama** [comment]
That sounds great @madskristensen thank you! Glad to see the back of gulp tbh ;)

I take it this is still a non runtime bundler/minifier?

Has the system that was available up until MVC5 been retired?

**Comment by Eilon** [comment]
@TheBeardedLlama yeah the system @madskristensen is talking about is used at build-time.

There are no plans at this time to bring the previous system to ASP.NET Core. I wouldn't say it's retired - it's just not available on ASP.NET Core. It works great in ASP.NET 4.x apps.

**Comment by TheBeardedLlama** [comment]
I see @Eilon, thank you for the explanation

I know it works great, that's why I'm enquiring about it ;)

**Comment by Eilon** [comment]
@TheBeardedLlama the trend right now seems to be toward using build-time systems. It's of course a trade-off. By doing it at build time, you pay the cost only at dev-time/build-time, and even there you pay the cost only when the source files change. By doing it at runtime, you avoid needing any build-time process, but you pay the cost every time the app starts up.
