### ISSUE TITLE
Design Dictionary Types for Routing/Html/Url

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#491]
**Updated by @rynowak **

What I did here is optimize the allocations *inside* `RouteValueDictionary`, and provide a struct enumerator so that we can `foreach` efficiently.

For the case where we're constructing an `RVD` around an object, we now do so without creating the 'full' dictionary.

This all reflects our learnings about allocations being super significant in MVC/Routing.

===================

Preserving original text for posterity. If we find motivation to do any of thse things, we'll reactivate this or open new bugs.

~~Need to come up with an efficient and intuitive design for the various dictionary types we use in webfx/routing.~~

~~We brought back the old property helper code for turning objects into dictionaries (just WebFX). Should we commonize this with routing?~~

~~Eilon's idea is to throw on strings and other types that we expect aren't useful here.~~

~~e.g. We typically look for specific tokens (controller, action) - These can be optimized to have faster access with pre computed keys.~~

**Comment by rynowak** [comment]
Self assigning as I've been working on this for perf.

**Comment by rynowak** [comment]
Change in routing: aspnet/Routing@d4b96b27c0a7ab051b6b90a72a131e5042e141be

**Comment by rynowak** [comment]
Change in Mvc aspnet/Mvc@4bcf236450edaecd07ab2e8b83b3879bf70c13be

**Comment by rynowak** [comment]
Reopening this issue, as I think we need to do more here. We should consider treating RVD as a list rather than a 'real' dictionary. Even with the changes in this area so far, we can push it much further, routing is still a really significant source of allocations.

Here's an example of what we can do - allocations 3000 requests to a simple API including link generation:

**Before**
![image](https://cloud.githubusercontent.com/assets/1430011/11639028/0baf578a-9cdf-11e5-9791-cf5b5c205935.png)

**After**
![image](https://cloud.githubusercontent.com/assets/1430011/11639039/21b9198a-9cdf-11e5-960a-1cb894eda89f.png)

The total savings here is about 6.25% of all allocations.

**Comment by rynowak** [comment]
Final change in routing aspnet/Routing@dd46f6b00f036081ba23843de8a0fb96902fd55c
