### ISSUE TITLE
Remove ViewEngine property of ViewComponentResult (it doesn't do anything)

### ISSUE THREAD

**Issue by cjqian** [aspnet/Mvc#4916]

**Comment by Eilon** [comment]
@cjqian can you provide more info about this? Why it isn't needed anymore? Does the property not work anymore?

**Comment by cjqian** [comment]
@rynowak

**Comment by rynowak** [comment]
This wasn't really ever used for anything I don't think.

**Comment by Eilon** [comment]
Well we can't remove it... Did it just always no-op or something?

**Comment by dougbu** [comment]
> Did it just always no-op or something?

There's exactly `(0 + zero + nada)` references to this property in the MVC repo. No reads; no writes.

**Comment by Eilon** [comment]
Hmm, well, we can't remove it due to compatibility, just in case someone is calling it. But in the meantime we can certainly document it as serving no purpose. E.g. "This property is never set and should not be used. It will be removed in a future release." We can mark as `Obsolete` (warning, not error) with the same message as well.

**Comment by Eilon** [comment]
I logged https://github.com/aspnet/Mvc/issues/5066 to mark the property as obsolete. Then we'll do the removal (this bug) in 2.0.0.
