### ISSUE TITLE
Label tag helper caching model metadata too aggressively 

### ISSUE THREAD

**Issue by Muchiachio** [aspnet/Mvc#4957]
I found an inconsistency between html and tag helper output on labels. That is, if you use
```HTML
<label asp-for="Test"></label>
```
it will always return the same (first init) display name value, even though they can change, for example in globalized scenarios.
But html helper doesn't do that, it works as expected and always updates display name value.
```C#
Html.LabelFor(model => model.Test)
```
[Here's](https://github.com/Muchiachio/TagHelperMetadata) a repro solution. This worked in RC2, seems like a regression.

**Comment by dougbu** [comment]
Strange but not horrendous. `LabelFor()` and the `<label>` tag helper _should_ work almost identically. But turning off `ModelMetadata` caching, as your `RandomDisplayNameMetadataProvider` does is strongly _not_ recommended. It's also not required since the `ModelMetadata.DisplayName` getter wraps a `DisplayMetadata.DisplayName()` call.

Instead use an `IDisplayMetadataProvider` implementation e.g.
``` c#
services.AddMvc(config => config.ModelMetadataDetailsProviders.Add(new RandomModelMetadata()));
```
...
``` c#
public class RandomModelMetadata : IDisplayMetadataProvider
{
    public void CreateDisplayMetadata(DisplayMetadataProviderContext context)
    {
        if (context.Key.MetadataKind == ModelMetadataKind.Property && context.Key.ContainerType == typeof(Model))
        {
            context.DisplayMetadata.DisplayName = () => new Random().Next(Int32.MaxValue).ToString();
        }
    }
}
```

**Comment by Muchiachio** [comment]
Thanks for a workaround @dougbu it works, I was still using [this](https://github.com/aspnet/Mvc/issues/2340#issuecomment-109031611) approach, which is kind of old now.
So is this by design? I would say consistency across both would be great, at least for simple cases where html helper can catch up with the new tag helper functionality.

**Comment by dougbu** [comment]
Yes, by design.

What you're seeing is an artifact of the many singletons in the system. The stack of singletons involved in HTML helpers happens to be shallower than that for tag helpers. You'd need to change numerous services (`IModelExpressionProvider`, `IRazorPageActivator`, `IRazorViewEngine` and more) as well as replace the `ICompositeViewEngine` so that it ignores the passed-in `IViewEngine`s (from `MvcViewOptions.ViewEngines`) and calls a unique `IRazorViewEngine` instance.

Replacing the `IModelMetadataProvider`, especially with something that is not a singleton, is not recommended.
