### ISSUE TITLE
Feature request: Environment tag helper wildcard/exclude support

### ISSUE THREAD

**Issue by msetze01** [aspnet/Mvc#4975]
Hey guys,

@csharpfritz gave a nice demo of ASP.NET Core to our user group and while reviewing the new environment tag helper, a member asked about "else" support for the environment tag helper (presumably to output some content if the hosting environment had not matched a previous set of environment names). I don't think this is possible with the current design but I could think of a couple additions that might be useful for shops with more than the typical Dev/Stage/Prod environment tiers. 

So, the situation is that I have some content to include in one or a handful of well-known environments, but a number of other environments where I wish to include some other content and exclude the well-known ones. I would hope to support something like:

```
<environment names="Development,Test">
(Dev, Test content)
</environment>
```

```
<environment names="!Development,!Test,*">
(QA, Staging, Production etc. content)
</environment>
```

I'd be happy to contribute a pull request but wanted to get feedback on this idea first.

**Comment by Eilon** [comment]
Yeah I'd love to see a feature that supports this. I know that I’d use it in my own app. I want to render some UI "only when not in production," and I don’t want to have to enumerate all the environments that aren’t "production" (because it might change at any time).

Another idea to toss out there is to have some kind of `operator` or `inverse` option, which, would tell them system to apply a "not" to the result:

```html
<environment names="Development,Test" operator="Not">
(QA, Staging, Production etc. content)
</environment>

--OR--

<environment names="Development,Test" inverse="true">
(QA, Staging, Production etc. content)
</environment>
```

Or just a different list of environments:

```html
<environment namesToExclude="Development,Test">
(QA, Staging, Production etc. content)
</environment>
```

(Actual names of proposed properties are just examples, not specific suggestions.)

**Comment by Eilon** [comment]
We ended up building this a little while ago: https://github.com/aspnet/Mvc/issues/5671#issuecomment-272021274
