### ISSUE TITLE
What is the DataAnnotation for Integer (int) model validation

### ISSUE THREAD

**Issue by MichelLaplane** [aspnet/Mvc#4995]
ASP.NET CORE rc2.
When using an int field in a model, if you type some characters in the field in the view associated with the model, no error message is given.
If your field is of type decimal, the error message is displayed.
Any explantions?
Is there a DataAnnotation for integer a thing like  [DataType(DataType.number)] could be valuable.

Best regards

**Comment by dougbu** [comment]
1. What HTML or tag helper are you using for the `int` field? The `<input/>` tag helper or `@Html.EditorFor(...)` should generate an `<input type="number" .../>` element and the browser (optionally, together w/ unobtrusive validation) will provide client-side validation.
 1. `decimal` is further special-cased because browsers don't understand the datatype.
 2. I suspect your `.cshtml` contains `<input type="text" asp-for="..." />` and the `type` attribute in there prevents MVC's `int` handling.
2. We do not own [`[DataType]`](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/DataTypeAttribute.cs) or the [`DataType`](https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/DataType.cs) `enum`. I've linked to their source files in the dotnet/corefx repo. If you think something is missing, you'll need it added there before MVC can tag advantage of it.
3. File data annotation bugs at https://github.com/dotnet/corefx/issues/new

**Comment by MichelLaplane** [comment]
Hi dougbu thank you for your help

**With int and no Error message displayed if I type "a" in the input box**

My model is 

`namespace` `MvcMovieCore.Models`
`{`
`    public class Movie`
`    {`
`    public int ID { get; set; }`
`    public int Price { get; set; }`
`    }`
`  }`

My View is

`@model `MvcMovieCore.Models.Movie`
``@{`
`    ViewData["Title"] = `"Edit";`
``}`
`<h2>Edit</h2>`
`<form` asp-action="Edit">
`<div class="form-horizontal">`    
`        <h4>Movie</h4>`
`        <div asp-validation-summary="ModelOnly" class="text-danger"></div>`
`        <input type="hidden" asp-for="ID" />`
`        <div class="form-group">`
`            <label asp-for="Price" class="col-md-2 control-label"></label>`
`            <div class="col-md-10">`
`                <input asp-for="Price" class="form-control" />`
`                <span asp-validation-for="Price" class="text-danger" />`
`            </div>`
`        </div>`
`    </div>`
`</form>`
`<div>`
`    <a asp-action="Index">Back to list</a>`
`</div>`
`@section Scripts {`
`    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}`
`}`

**With Decimal Error Message "The field Price must be a number." is displayed if I type "a" in the input box**

Here is my model

`namespace MvcMovieCore.Models`
`{`
`    public class Movie`
`    {`
`    public int ID { get; set; }`
`    public decimal Price { get; set; }`
`    }`
`  }`

The view is the same

Best regards

**Comment by dougbu** [comment]
Suspect this is about your browser. Which are you using?

**Comment by MichelLaplane** [comment]
I use always IE and currently it is IE 11.

**Comment by dougbu** [comment]
This issue seems specific to IE. A `type="number"` field in IE accepts any character. But if I enter a string with initial garbage e.g. `a12`, IE empties the field when I tab out. If instead I enter `12a`, the value is retained and submitted if the view contains a `type="submit"` field.

The behaviour is very different when using Chrome. Chrome simply ignores characters that are invalid for `type="number"`. Type `a12` or `12a` in the `Price` field and Chrome displays `12`.

Note there's no error message when using either browser other than the server-side validation message added in the `12a` / IE case.


Separately your view includes a bug common in generated `.cshtml` files: `<span>` elements should not be self-closing. (This bug will be fixed in the next tooling release  but won't fix existing views.) Change
``` html
<span asp-validation-for="Price" class="text-danger" />
```
to
``` html
<span asp-validation-for="Price" class="text-danger"></span>
```

**Comment by dougbu** [comment]
BTW it doesn't look like any change is needed in MVC or Unobtrusive Validation.

**Comment by Eilon** [comment]
@dougbu so you feel this is just a browser behavior thing? Nothing at all in ASP.NET to do?

**Comment by dougbu** [comment]
> so you feel this is just a browser behavior thing?

@Eilon yes.

**Comment by MichelLaplane** [comment]
Thank you @dougbu for all these explanations.
Yes when in IE the tab empties the field I have also noticed that.
But sorry to not agree with you about no bug if you type an alpha character first because of no error displayed. For now I have changed all my int field to decimal field in my database at is not I think a good practice.
I could add a [required] attribute but in this case the error message is wrong and could disturb the user.
Best regards.

**Comment by dougbu** [comment]
@MichelLaplane suggest you file an IE bug about it's odd `type="number"` handling. If you prefer to use `[DataType]` to work around the IE bug, file something where that attribute lives -- https://github.com/dotnet/corefx/issues.

Another option would be to layer something on top of #4877 -- device detection. But right now, there's nothing user agent-specific in MVC.

**Comment by MichelLaplane** [comment]
Done thanks dougbu
