### ISSUE TITLE
UrlHelper does not generate url if app called UseMvc without params.

### ISSUE THREAD

**Issue by unjello** [aspnet/Mvc#5025]
Followed this tutorial[1] to get my first ASP.NET Core app running. Newly generated WebAPI project in `Startup.cs` uses `app.UseMvc()` not specifying routing template. I got an error where `CreatedAtAction` returned 201 with a generated URL, but it was null. And `UrlHelper` was also returning `null` for any combination of actions[2], until I have explicitly called:
```
app.UseMvc(routes =>
{
    routes.MapRoute(
        name: "default",
        template: "{controller}/{action}");
});
```

It was just `UrlHelper` that did not work, cause all other routing worked fine, ie. HTTP actions were routed to correct components. I was able to call each action defined. It was just this helper that later resulted in IIS throwing error 500[2] on exiting one of the controllers.

[1] https://docs.asp.net/en/latest/tutorials/first-web-api.html
[2] http://stackoverflow.com/questions/38369885/asp-net-core-createdataction-in-httppost-action-returns-201-but-entire-request-e

**Comment by rynowak** [comment]
`app.UseMvc()` will only use attribute routing. Use `app.UseMvc(routes =>{ ... })` if you want to define conventional routes. That said, we recommend using attribute routing for building APIs - it allows you to be very precise with the URL patterns that you match.

Regarding the example code you gave, this code `[HttpGet("{id}", Name = "GetTodo")]` defines a **route name** not an **action name**. Use `CreatedAtRoute(...)` instead of `CreatedAtAction(...)`

**Comment by unjello** [comment]
Thanks a lot! Makes sense now.
