### ISSUE TITLE
`DefaultValueAttribute` Should be Applied Before Binding for Action Parameters

### ISSUE THREAD

**Issue by SamuelEnglard** [aspnet/Mvc#5035]
In #2414 support for `DefaultValueAttribute` on Action Parameters was added. It is done right before executing the Action, after Model Binding. I think it should be done before/during Model Binding. My reasoning is that since `DefaultValueAttribute` can only take simple types a developer might need the value to go through binging to be valid type for the parameter.

For example I have a parameter of type `Microsoft.Net.Http.Headers.MediaTypeHeaderValue`. In the `DefaultValueAttribute` I use the string representation of the MIME type. I need that string to go through binding to become a `MediaTypeHeaderValue`.

Currently I've solved this issue by adding a `IValueProviderFactory` that exposes `DefaultValueAttributes`. While I'm fine with this solution I think I might not be the only one with this problem.

**Comment by Eilon** [comment]
@rynowak @dougbu thoughts?

**Comment by rynowak** [comment]
We intentionally don't do this, because we want it to be clear that `ActionExecutingContext.ActionArguments` contains the values that came from model binding, and not default values.

I think we need to take a look at this area though, and improve something here. It's a little too clumsy right now to try and attach arbitrary data to a model binder through an attribute. We intentionally put up a barrier between "model binding world" and "reflection world" and we don't provide good ways to get back and forth.

**Comment by SamuelEnglard** [comment]
@rynowak I can get that.

Two solutions I can think of quickly are to

1. Add a property to `ModelBindingAttribute` to bind against default value
2. Add a "BindingFallbackValueAttribute" attribute

**Comment by dougbu** [comment]
Another alternative would be to treat `DefaultValueAttribute` as a UI assist: Continue to ignore the attribute in model binding but use it in HTML generation when an edit field would otherwise be empty.

**Comment by SamuelEnglard** [comment]
@dougbu That is a good idea but then something needs to replace what it was before still I'd think

**Comment by Eilon** [comment]
We are not planning to make changes to this behavior.
