### ISSUE TITLE
Microsoft.AspNetCore.Mvc depending on Newtonsoft.Json

### ISSUE THREAD

**Issue by radiosterne** [aspnet/Mvc#5055]
I have a web application project using AspNet.Core. For data layer it uses Elasticsearch.Net in version 1.4.3. I can not update Elasticsearch.Net to a higher version because of compatibility problems with my elasticsearch version in production environment. Therefore, I have conflicting versions of Newtonsoft.Json in my data and presentation layers (ES.Net in my version only works with Newtonsoft.Json 6.0). Besides, guys, how comes MVC pattern implementation depends on one particular serialization implementation? Why should i have Newtonsoft.Json installed and used as a dependency even if I'm not using json at all? I suggest removing all json-specific code from AspNetCore.Mvc and migrating it to, let's say, AspNetCore.Mvc.Json.

**Comment by jbogard** [comment]
Have you tried installing with -IgnoreDependencies?

**Comment by Eilon** [comment]
There are no plans to remove the Json.NET dependency from MVC because we think it is useful for almost all scenarios. (Though clearly there are some scenarios where it is not needed or useful.)

@davidfowl are there any project.json tricks to enable this scenario?

@radiosterne as a side note, have you contacted the owners of the Elastic Search package that you're using to see if they can upgrade that package's dependencies? Json.NET 6.x is over a year old, which in internet years is like a million years ago 😄

**Comment by tuespetre** [comment]
If you specify `Newtonsoft.Json` as a dependency in your `project.json` with the needed version (`9.0.1`) and then be sure to clear out your `/bin` folder (especially to get rid of the generated `*.exe.config` with its `bindingRedirects`) it should work.

**Comment by JamesNK** [comment]
Couldn't you just reference Microsoft.AspNetCore.Mvc.Core? That doesn't bring in the JSON formatter, and therefor no Json.NET
