### ISSUE TITLE
Html.Hidden() does not respect value passed in if present in ModelState.

### ISSUE THREAD

**Issue by ctolkien** [aspnet/Mvc#5079]
Scenario:
```csharp
public IActionResult Index(string id)
{
    return View();
}
```

View:

```csharp
@Html.Hidden("id", value: "Hellooooooo")
```

Request via` /controller/index/wat`

This generates:

```HTML
<input id="id" name="id" type="hidden" value="wat">
```

Whereas I would expect:

```HTML
<input id="id" name="id" type="hidden" value="Hellooooooo">
```

The documentation for that overload states: `Value: if non-null, value to include in the element`.

Sample repo:
https://github.com/ctolkien/mvc-bug-repro

**Comment by ctolkien** [comment]
https://github.com/aspnet/Mvc/blob/8a6e99c7c0efc3f88ae8fd8a2ce6255fb57c72f1/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L1233

**Comment by Eilon** [comment]
Hmm don't all HTML helpers work this way? ModelState always takes precedence because it includes what is believed to be the "latest updated value." It's there to preserve the user's input in case they perhaps typed in a value that isn't valid, but could still be corrected and then they could submit again.

I believe this is the behavior all the way back to ASP.NET MVC 1.0.

**Comment by ctolkien** [comment]
>ModelState always takes precedence because it includes what is believed to be the "latest updated value."

I could understand that being the case if no value was supplied, e.g `@Html.Hidden("id")`, however when there is explicitly a value being defined?

I do remember hitting a similar issue with mvc.old and it being a pain in the backside then :) - not sure if exactly the same. Here's a concrete example of how this bit:

Given `/controller/action/123`

```HTML
@model SomeViewModel

@foreach(var item in SomeViewModel.Children)
{
    <form asp-action="DeleteChild">
        @Html.Hidden("id", item.Id)
        <button>Delete Child</button>
    </form>
}
```
^ `item.Id` is ignored, uses `123` from the route, wrong record gets deleted.

It's also... quite brittle, in that someone might change the name of one of the route params, which then causes a knock on effect of breaking your (previously working) razor code.

**Comment by Eilon** [comment]
@ctolkien the idea here is that an explicit value passed into the HTML Helper is an *initial value*, but that ModelState then reflects an *updated value* that is of presumably higher importance. Otherwise once the user visiting the site starts editing the value, and perhaps seeing various validation errors, would then see the current state of *their* data as opposed to seeing the initial values again.

Though, I'll be honest, even though I think the current behavior is the *best* behavior overall, I fully realize that it isn't always the *right* behavior.
