### ISSUE TITLE
Controller action returns 200 OK when an exception is thrown in iterator

### ISSUE THREAD

**Issue by jugglingthebits** [aspnet/Mvc#5083]
Hi,

we have come across an irritating behavior in the exception handling for controller actions. We were using the MongoDB api to lazily query collections and return their results as JSON. The success case works as expected, however, when MongoDB could not connect to the DB, the resulting TimeoutException was just ignored, with a 200 OK status code and an empty array as the value.

We were able to produce the following code showing that behaviour:

```c#
    [Route("api/some")]
    public class AController : ControllerBase
    {
        [HttpGet]
        public IEnumerable Get()
        {
            return ThrowFromIterator();
        }

        public IEnumerable ThrowFromIterator()
        {
            throw new ArgumentException();
            yield break;
        }
    }
```
(See also [this repo](https://github.com/jugglingthebits/aspnetcore-throwfromiterator))

Expected result:
Returns HTTP 500 internal server error.

Actual result:
Returns HTTP 200 OK with an empty JSON array as the value.

It seems that exceptions thrown from iterator functions are not handled properly.

**Comment by rynowak** [comment]
It is very likely the case that your exception is thrown while writing to the body, after headers have already been sent to the client, so there's no take-backs on the 200 that was already sent as part of the response. The client will see an error because the body will come back as incomplete.

If you want to deterministically report a 500 when this happens you'll need to either:
- Buffer your `IEnumerable` as part of the action (`.ToList()`)
- Buffer the response body - https://github.com/aspnet/BasicMiddleware/tree/dev/src/Microsoft.AspNetCore.Buffering

Obviously both of these things require more server-side resources, which is why we don't have this kind of behavior by default.

**Comment by Eilon** [comment]
@rynowak is the exact repro case here by design?

**Comment by rynowak** [comment]
Throwing after flushing headers resulting in a 200 is definitely by design, I'm not sure we have confirmation yet that's what @jugglingthebits is seeing.

Do you have a log or exception stack trace?

**Comment by jugglingthebits** [comment]
@rynowak yes, the exception is thrown during json serialization. [Stacktrace here](https://gist.github.com/jugglingthebits/da5eace09d185f03718dd5ae76fb5d12)

I guess this error case should be caught earlier as the MongoDB client should detect that it cannot establish a connection during initialization, not when enumerating a collection.

**Comment by rynowak** [comment]
Thanks for confirming, this is by-design then. Let us know if you need anything else!
