### ISSUE TITLE
asp-format is not respected on input[type=hidden] fields

### ISSUE THREAD

**Issue by Haplois** [aspnet/Mvc#5094]
I have a form with couple of hidden fields. One of them is `DateTime?`, this field is not rendered in the RFC3389 format. Furthermore, if I define a `asp-format` attribute, tag helper simply dismisses this.

To fix this, I forked the repository and started to make code changes. I didn't issued a pull request since it felt like a huge change. Is it OK? 

Changes are here: https://github.com/Haplois/Mvc/commit/623eeb331fb3674c4987254cc27b7f2cf6ca5b54

**Comment by Eilon** [comment]
@dougbu can you have a look? I'm not super familiar with what the intended interaction of these properties and behaviors is.

**Comment by dougbu** [comment]
@Haplois this would be a breaking change since formats, especially default formats, have not applied to `hidden` fields in any previous version. If it were just adding `asp-format` support for `hidden` fields i.e. if `GetFormat()` was never called in the `hidden` case, I'd be less concerned. (Of course, adding the `format` parameter to `IHtmlGenerator.GenerateHidden()` is fine.)

More generally, please do not call the existing `InputTagHelper.GenerateTextBox()` method or rename it. That method brings in too many additional behaviour changes.

But your commit is close to what we'd like to see in a PR as long as we can do it in 1.1.0...

@Eilon in the past, `Html.Hidden()` and `Html.HiddenFor<T>()` didn't have a `format` parameter. The difference here is the `<input>` tag helper appears to support `asp-format` regardless of the `type` value. But supporting `asp-format` w/ `type='hidden'` would be a different behaviour from 1.0.0. As long as you're fine w/ that small behaviour change and we limit things to _just_ that behaviour change, this commit is pretty close.

**Comment by Haplois** [comment]
@dougbu since `InputTagHelper.GenerateTextBox()` is a private method and I generalized it little bit I renamed it and thought it is OK. I'm reverting that change, and moving that new functionality to the `InputTagHelper.GenerateHidden()` instead.

**Comment by Haplois** [comment]
BTW, since `inputType` and `inputTypeHint` variables in the `InputTagHelper.Process()` are only used in `InputTagHelper.GenerateTextBox()` is it OK there (or into the `default` statement of the `switch`)?

**Comment by dougbu** [comment]
Those variables are fine where they are but I'm not positive what you mean by "is it :ok: there"?

**Comment by Haplois** [comment]
@dougbu somehow I deleted a part of message before I post it. What I tried to write was: "is it OK to move it there"

**Comment by dougbu** [comment]
Let's not do additional refactoring in this PR

**Comment by Haplois** [comment]
Should I issue a pull request?

**Comment by dougbu** [comment]
@Haplois let's have a look I think. @Eilon any concern about the slight behaviour change from 1.0.0?

**Comment by Eilon** [comment]
@dougbu regarding this comment>

> @Eilon in the past,  Html.Hidden()  and  Html.HiddenFor<T>()  didn't have a  format  parameter. The difference here is the  <input>  tag helper appears to support  asp-format  regardless of the  type  value. But supporting  asp-format  w/  type='hidden'  would be a different behaviour from 1.0.0. As long as you're fine w/ that small behaviour change and we limit things to just that behaviour change, this commit is pretty close.

I'm not sure I understand what the difference in behavior is. You're saying the Hidden HTML Helpers never supported format. But the Hidden Tag Helpers do support format? And what's the change? I.e. what's the before after that's changing?

Hidden HTML Helper:
* 1.0.0 --> Doesn't support format
* 1.1.0 --> Add support for format (?)

Hidden Tag Helper:
* 1.0.0 --> Already supports format (?)
* 1.1.0 --> No change (?)

**Comment by dougbu** [comment]
@Eilon sorry for throwing in the HTML helpers. That just served to make my comment more confusing.

The 1.0.0 `<input>` tag helper takes after the HTML helpers though the `asp-format` attribute exists and can be bound regardless of the `type` attribute generated. So,

##### Hidden HTML helper
No change.

##### `<input/>` tag helper
* 1.0.0 -> has `asp-format` but that attribute is ignored when the chosen `type` is `'hidden'`
* 1.1.0 -> add support for (will no longer ignore) `asp-format` when the chosen `type` is `'hidden'`

**Comment by Eilon** [comment]
Seems safe enough to add. Let's do it.

**Comment by Haplois** [comment]
I issued the pull request. Sorry for delay. I'm on vocation.

**Comment by dougbu** [comment]
4bda1cb and 34a4c8c
Thanks very much for 4bda1cb @Haplois!
