### ISSUE TITLE
FileExtensions Data annotation invalid ModelState

### ISSUE THREAD

**Issue by leroyd** [aspnet/Mvc#5117]
I have this property in my ViewModel :
```C#
        [Display(Name = "Images")]
        [FileExtensions(Extensions = "jpg,jpeg")]
        [DataType(DataType.Upload)]
        public IEnumerable<IFormFile> Files { get; set; }
```
And into my action :
```C#
        public IActionResult Create(MyViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Do Action
            }

            return View(model);
        }
```
I upload a .jpg picture into the form, and ModelState return an error like "jpg, jpeg not allowed".
(The validation worked with RC1 version).
But I can find the file into the property's model (so I can do a custom validation).

**Comment by Eilon** [comment]
@leroyd can you clarify what used to work and what doesn't work now?

Also, I'm pretty sure that the `[FileExtensions(Extensions = "jpg,jpeg")]` property needs to be applied to a `string` property. It doesn't work on `IFormFile` properties, and definitely not on `IEnumerable<IFormFile>` properties.

I think that the reason you're seeing it "validate" as invalid is because the attribute returns "invalid" if the property isn't a string. You can see the source code here: https://github.com/dotnet/corefx/blob/master/src/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/FileExtensionsAttribute.cs#L57-L71

**Comment by leroyd** [comment]
(ty for linq, I looked for that without success)
After some tests with RC1 version, the ModelState stay valid with others extensions.
So indeed, "FileExtensions" is not appropriate for "IFormFile" files.

Thank you for your help.

**Comment by Eilon** [comment]
Great!

**Comment by vanillajonathan** [comment]
This code could be extended to check the type if it is a `IFormFile`.

```cs
public override bool IsValid(object value)
{
    if (value == null)
    {
        return true;
    }

    var valueAsIFormFile = value as IFormFile;
    if (valueAsIFormFile != null)
    {
        return ValidateExtension(valueAsIFormFile.FileName);
    }

    var valueAsString = value as string;
    if (valueAsString != null)
    {
        return ValidateExtension(valueAsString);
    }

    return false;
}
```

**Comment by Eilon** [comment]
@vanillajonathan unfortunately that would cause a circular reference in the assemblies --> the core .NET assemblies can't reference ASP.NET's type (`IFormFile`).

**Comment by vanillajonathan** [comment]
@Eilon, true but the ASP.NET MVC could ship its own `FileExtensions` class. Or some end-user can implement their version with the above code if they want to have that functionality in their project.

**Comment by leroyd** [comment]
Thank you Vanilla. I did the same check in my code. Like I using net451 Framework, there is no problem with `IFormFile`.
For the others... Indeed, they have to adapted with Core assemblies.
