### ISSUE TITLE
Remote validation calling server-side Action with inconsistent parameter name

### ISSUE THREAD

**Issue by oleksii-vynnychenko** [aspnet/Mvc#5145]
I have domain model that has remote validation on field UrlName:
```
public class Page
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        [Remote(action: "ValidateUrlName", controller: "Page")]
        public string UrlName { get; set; }
        [Required]
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        [DataType(DataType.Date)]
        public DateTime AddedDate { get; set; }
    }
```

View model using domain model (Page class):
```
public class PageEditViewModel
    {
        [Required]
        public Page NewPage { get; set; }
        public List<int> RelatedPagesIds { get; set; }
        public MultiSelectList OtherPages { get; set; }
    }
```
Validation method in PageController (non-relevant methods are omited and only signature of that method is relevant)
```
    public class PageController : Controller
    {
        [AcceptVerbs("Get", "Post")]
        public IActionResult ValidateUrlName( string urlName) 
            => Json(!_pages.IsUrlNameAlreadyExists(urlName) ?
                "true" : $"Page with UrlName '{urlName}' already exists");
    }

```
There's a View with it's PageEditViewModel model should remotely validate input of UrlName.

```
@model global::Task02.ViewModels.PageEditViewModel
    <div class="col-md-10">
        <input asp-for="@Model.NewPage.UrlName" class="form-control" />
        <span asp-validation-for="@Model.NewPage.UrlName" class="text-danger"></span>
    </div>
```

Problem: for example I'm entering `UrlName 2` in input field and it actually sends GET method but instead of
`http://localhost:1030/Page/ValidateUrlName?UrlName=UrlName%202`
it sends for some reason
`http://localhost:1030/Page/ValidateUrlName?NewPage.UrlName=UrlName%202`
So Action method can't bind `NewPage.UrlName` to `string urlName` parameter of that Action method (as I understand) and `string urlName` is null.

When using other View with `Page` class as a model of course it makes this GET call
`http://localhost:1030/Page/ValidateUrlName?UrlName=UrlName%202` and parameter binds and Action method actually validating.

Is there any reason for that behaviour? It's `UrlName` that is marked with [Remote] atribute, so why add names of every Model properties that contain `UrlName` property inside to GET request query? I mean, I can parse it from `HttpContext.Request.QueryString` but it feels not right obviously.

**Comment by dougbu** [comment]
Why are you comparing a view with `@model PageEditViewModel` with one that has `@model Page`? The two are going to send different keys for the properties of the `Page` sub-model or model (respectively).

**Comment by oleksii-vynnychenko** [comment]
Ok, then what should developer do in this case? I have domain model Page that I actually use in that and other Controller and as a model for Views. What should I do if I need specific ViewModel for some other View that contains Page as a parameter AND I need remote validation of same field in both cases of same UrlName property? I can't mark UrlName property with [Remote] in PageEditViewModel because it's a property of Page.

I might be wrong, but to me it seems strange that for validation purposes of same field in both cases it sends different URL query string key so one Action method can't figure out both cases. Is there any other way around this issue like for example making explicit binding (some Attribute that is not yet in documentation?) if there's only one URL query string key and only one string parameter of Action method, even if names of them doesn't equal? Any solution where code won't be duplicated?

**Comment by dougbu** [comment]
@oleksii-vynnychenko, override the key used to bind arguments of the `ValidateUrlName()` action:
``` c#
public IActionResult ValidateUrlName([Bind(Prefix = "NewPage.UserName")] string urlName)
{
}
```

**Comment by oleksii-vynnychenko** [comment]
OK, but what if I have 50 different ViewModels that nest Page instance with different names `NewPage`, `EditedPage`, `PulledPage`, `ParsedPage` and so on...? Or when it's IEnumerable<Page> it'll be I think `NewPage[0].UrlName`, `NewPage[1].UrlName`, etc. You can't write all of those in [Bind(Prefix)].

What I'm saying is - isn't it better ONLY for validation purposes (only when model is being validated) to send that GET request with query key named after only property that is marked with [RemoteAttribute] (`UrlName` in this case)? By logic we're validating value for property of `Page` entity and it shouldn't matter if that entity is nested inside other model and how that instance of entity is named inside the code because instance name can vary but name of property being validated doesn't change.

**Comment by dougbu** [comment]
Names are generated and checked consistently in MVC. They depend on the context, specifically the type hierarchy above any particular property. To do otherwise results very quickly in duplicate keys for distinct properties.

**Comment by Eilon** [comment]
For the reasons mentioned here, we are not planning to change this behavior.

**Comment by chrisdpratt** [comment]
I'm resurrecting this one. I don't think proper weight was given to the issue creator's concerns here. Currently, remote validation works in one very narrow circumstance: you have a direct one-to-one correlation between a particular model with a property with the `RemoteAttribute`, and a particular action that validate specifically that property on that one particular model.

If you how are applying `RemoteAttribute` to a property on a base class that will be used in multiple places, it's effectively useless, as you cannot control what the actual param names will end up being for the purpose of the action method.

For example, let's consider a common scenario a checkout with  billing and shipping addresses, each with a phone number that will need to be remote validated. An address is an address, so obviously both the billing and shipping address properties will use the same `Address` type. However, when remote validation occurs client side, the shipping phone number will be validated via something like `https://mysite.com/phone/validate?ShippingAddress.PhoneNumber`, while the billing phone number will be validated via something like `https://mysite.com/phone/validate?BillingAddress.PhoneNumber`. Obviously, one action cannot respond to both of these, so the only choice becomes to duplicate code.

The bit about the naming depending on context is entirely dismissive. That's understandable when you're binding a full object hierarchy. However, for remote validation, you're generally sending just one piece of data, or maybe two. You don't need to preserve the object hierarchy, because it doesn't matter in the context. As a result, the correct thing for the Unobstrusive Validation script to do would be to send only the property name(s), i.e. just `PhoneNumber`. Then, it doesn't matter what context it's used in, as long as the validating action takes something like `phoneNumber`, you're good to go.

Keeping it as-is actually reduces the utility, and frankly makes no sense. This issue should not have been closed.
