### ISSUE TITLE
javascript in view folder (each view have one javascript) ASP.NET Core MVC 6

### ISSUE THREAD

**Issue by mukundabrt** [aspnet/Mvc#5169]
**ASP.NET Core MVC 6**
How to manage js file for each view. I have view specific javascript file and i dont want to place js file in script folder coz three are more than 100 views in my project.
Is there any idea to place js file with views in view folder? or any idea ?

**Comment by sentyaev** [comment]
I prefer different project structure instead of default ASP.NET MVC app.
There is an [Jimmy Bogard article](https://lostechies.com/jimmybogard/2015/07/02/ndc-talk-on-solid-in-slices-not-layers-video-online/) and [video](https://vimeo.com/131633177).
I'm simplified this a lot, you can find high-level ideas [here](http://blog.sentyaev.net/2016/08/20/custom-views-location.html).

**Comment by fletchsod-developer** [comment]
I'm in same boat as you are.  But the provided links doesn't say how for "each view have one javascript".  :-/
