### ISSUE TITLE
UrlHelperFactory.GetUrlHelper may throw an exception

### ISSUE THREAD

**Issue by vdachev** [aspnet/Mvc#5170]
While trying to mock a controller I came across a `KeyNotFoundException` in the `UrlHelperFactory`'s `GetUrlHelper` method.

It seems the following code relies on the `typeof(IUrlHelper)` key already populated in the `Items` collection:
```csharp
// Perf: Create only one UrlHelper per context
var urlHelper = httpContext.Items[typeof(IUrlHelper)] as IUrlHelper;
if (urlHelper == null)
{
   urlHelper = new UrlHelper(context);
   httpContext.Items[typeof(IUrlHelper)] = urlHelper;
}
```

If the key is missing, this line throws an exception, instead of returning `null`. I believe that the following code should be used instead:
```csharp
// Perf: Create only one UrlHelper per context
object urlHelper;
if (!httpContext.Items.TryGetvalue(typeof(IUrlHelper), out urlHelper)
	|| !(urlHelper is IUrlHelper))
{
	urlHelper = new UrlHelper(context);
	httpContext.Items[typeof(IUrlHelper)] = urlHelper;
}

return (IUrlHelper)urlHelper;
```

**Comment by rynowak** [comment]
Did you create a mock for `HttpContext.Items`? Right now this code expects `Items` to return null on a missing key, which is something we should probably fix since it's specified as `IDictionary<>`. 

Regardless, I'd strongly suggest using `DefaultHttpContext` in your tests - you'll need less mock setup stuff. It's what we do and we haven't run into any limitations.
