### ISSUE TITLE
Using ActionDescriptor.DisplayName from ApiExplorer

### ISSUE THREAD

**Issue by tuespetre** [aspnet/Mvc#5179]
When generating API docs, I would like to be able to use a 'friendly name' for each action. This 'friendly name' must be distinct from the 'action name', because the action names themselves should be terse for use in `asp-action="..."` tag helpers, controller results, and so forth.

I found that each `ApiDescription` references the `ActionDescriptor`, and `ActionDescriptor` exposes a `DisplayName` property in addition to the `ActionName`. Great! Well, it turns out that the framework does not seem to set the `DisplayName` property from anywhere, and the default implementation of `ControllerActionDescriptor` will return more of a 'debug view'-looking name. 

At this point, I would be happy if the controller actions supported the `DisplayNameAttribute`, and I could understand if the team did not want to provide that convention by default. So I sought out to add this in my already-existing `IApplicationModelConvention`:

```
private class CustomApplicationModelConvention : IApplicationModelConvention
{
    public void Apply(ApplicationModel application)
    {
        application.ApiExplorer.IsVisible = true;

        foreach (var controller in application.Controllers)
        {
            string area;

            if (!controller.RouteValues.TryGetValue("area", out area) || area != "Api")
            {
                controller.ApiExplorer.IsVisible = false;
            }

            if (string.IsNullOrEmpty(controller.ApiExplorer.GroupName))
            {
                controller.ApiExplorer.GroupName = controller.ControllerName;
            }

            foreach (var action in controller.Actions)
            {
                var displayNameAttribute = action.Attributes.OfType<DisplayNameAttribute>().FirstOrDefault();

                if (displayNameAttribute != null)
                {
                    action.DisplayName = displayNameAttribute.DisplayName;
                }
            }
        }
    }
}
```

...but there is a problem here: `ActionModel` does not have a `DisplayName` property. Instead, I need to do this:

```
foreach (var action in controller.Actions)
{
    var displayNameAttribute = action.Attributes.OfType<DisplayNameAttribute>().FirstOrDefault();

    if (displayNameAttribute != null)
    {
        action.Properties.Add(typeof(DisplayNameAttribute), displayNameAttribute);
    }
}
```

...and then declare another mini-infrastructure class like this:

```
private class CustomActionDescriptorProvider : IActionDescriptorProvider
{
    public int Order => 0;

    public void OnProvidersExecuting(ActionDescriptorProviderContext context)
    {
    }

    public void OnProvidersExecuted(ActionDescriptorProviderContext context)
    {
        foreach (var action in context.Results)
        {
            var displayNameAttribute = action.GetProperty<DisplayNameAttribute>();

            if (displayNameAttribute != null)
            {
                action.DisplayName = displayNameAttribute.DisplayName;
            }
        }
    }
}
```

...and now finally I can get a useful `DisplayName` from the `ApiExplorer` data.

So, these are my questions:
- Can/should `DisplayName` be added as part of `ActionModel`?
- Should there perhaps be something like an `ApiExplorerDescriptionAttribute` at the action level with `Name` and `Description` properties, with additional matching properties on the `ApiExplorerModel` and `ApiDescription` classes?

**Comment by rynowak** [comment]
I'm not against adding a `DisplayName` property to `ActionModel`. That would streamline this, and it works with the current design of using `ActionModel` to customize the raw ingredients that go into build the ADs. 

Do you have suggestions about what would build a better default 'DisplayName'? This is probably something we could improve as well.

=================

A few thoughts based on your other comments:

This is all working as intended at least from my point of view. It's intended that you can stash things in the property bag of the application models / action descriptors. It's also intended that you can wire that kind of thing up using a convention and base it off of `[DisplayName]` or read it from a json file or whatever you want. I hope did didn't make you sad to have to write 30-40 LOC to accomplish this because that's the way we want something like this to be possible. 

----------------

Regarding adding features to API Explorer - that's a tricky one... From a philosophical point of view, I don't like to add things to API Explorer without a **strong** motivating factor. The reason is that while we provide data to libraries like [Ahoy/Swagger](https://github.com/domaindrivendev/Ahoy) - we don't ourselves control how it's used and shown.  If Swagger goes out of vogue and another new technology shows up that doesn't expose a 'description' then it becomes vestigial.  

We'd rather that libraries discover the metadata they need so they can do it in the way that makes the most sense for them. An example of this would be Ahoy's use of XML doc files for the description on APIs.

----------------

I also just don't like overloading the `System.ComponentModel` attributes. These were created for property grids and designers for WinForms. I think the expectations for support and completeness are much higher when we put something like this in the box. This support and your convention would be a good item for an "MVC Contrib" style project.

It would be better to create an attribute that's custom for whatever the consumer is because the fidelity could be better than `[DisplayName]` if it needs to be. And at that point, whoever's reading the data should be the one to ship the attribute.

**Comment by tuespetre** [comment]
> This is all working as intended at least from my point of view. It's intended that you can stash things in the property bag of the application models / action descriptors. It's also intended that you can wire that kind of thing up using a convention and base it off of [DisplayName] or read it from a json file or whatever you want. I hope did didn't make you sad to have to write 30-40 LOC to accomplish this because that's the way we want something like this to be possible.

I agree, it's a good feature. It was a pleasure to discover it and think of some other potential scenarios for using it.  Not sad at all! :joy_cat: I just submitted this issue because I felt that name/description are fundamental enough to API documentation that maybe they should have first-class support.

> Regarding adding features to API Explorer - that's a tricky one... From a philosophical point of view, I don't like to add things to API Explorer without a strong motivating factor. The reason is that while we provide data to libraries like Ahoy/Swagger - we don't ourselves control how it's used and shown. If Swagger goes out of vogue and another new technology shows up that doesn't expose a 'description' then it becomes vestigial.
>
> We'd rather that libraries discover the metadata they need so they can do it in the way that makes the most sense for them. An example of this would be Ahoy's use of XML doc files for the description on APIs.

Makes sense. Now with that said, I do think a `Description` property would be a good thing to have in general. It's unlikely for a Swagger-like project to forego support for a description/notes on an API. 

> I also just don't like overloading the System.ComponentModel attributes. These were created for property grids and designers for WinForms. I think the expectations for support and completeness are much higher when we put something like this in the box. This support and your convention would be a good item for an "MVC Contrib" style project.
>
> It would be better to create an attribute that's custom for whatever the consumer is because the fidelity could be better than [DisplayName] if it needs to be. And at that point, whoever's reading the data should be the one to ship the attribute.

Agreed, sometimes I wish both EF and MVC would offer their own attribute collections, and I have certain feelings about `System.ComponentModel.DataAnnotations`... anyways, I used it because it was there. I would much rather have something like an `ApiDescriptionAttribute`. :wink:

**Comment by rynowak** [comment]
So it sounds like the open issue here is - does MVC want to provide a set of descriptive attributes that an addon library like swashbuckle may or may not consume.

/cc @elilon my preference is no, unless we ship our own direct support. These things are better done by the library that you're actually using to expose the data.

**Comment by rynowak** [comment]
Having read through this again, I propose that we add `DisplayName` to all of our model/descriptor stuff, that makes this a pretty straightforward enhancement.


I don't think there's much else actionable here for us, using a convention to do this is pretty easy once we do the above. We want to make sure that you can build things without friction, but not too much policy in the box.

**Comment by pranavkm** [comment]
We looked at this issue again during triage yesterday. While having a display \ description metadata associated with `ApiExplorerModel` is a nice to have feature, we don't think it's very valuable when most community packages that use ApiExplorer (Swashbuckle \ NSwag) don't actually consume it. They already have mechanisms to read some of this (for instance the description) using doc comments and I'm not sure how these attributes would play with it.
