### ISSUE TITLE
StaticFiles and MVC

### ISSUE THREAD

**Issue by SergeyBarskiy** [aspnet/Mvc#5213]
If I enable static files and and MVC route, in that order, I can run into the following problem.  If I accidentally forgot to include some file in say node_modules folder, if static files middleware cannot find it, it does not handle the request and it is delegated with MVC middleware via event a default route if my file name has two slashes in it.  I think we need to bring back an ability to ignore route in MVC, so that I can exclude a folder with only static files from MVC middleware.
Thanks.

**Comment by SteveSandersonMS** [comment]
> If I accidentally forgot to include some file in say node_modules folder, if static files middleware cannot find it, it does not handle the request

That sounds like you're serving your `node_modules/` dir publicly. Most people wouldn't want to do that, as it typically contains thousands of files that you have no reason to serve to the public. I'm not saying it's strictly going to cause you harm, but you might want to consider different approaches, such as using a build tool like webpack to put the relevant bundles in `wwwroot` instead of serving the whole of `node_modules/`.

>  I think we need to bring back an ability to ignore route in MVC

Yes, that could be useful. For example, if your build process drops static files into `wwwroot/static/`, then you might want to exclude URLs prefixed with `static/` from matching the MVC default route.

Perhaps it is possible to achieve this already with a custom route. Another possible solution would be to use `MapSpaFallbackRoute`, as it's designed for roughly this scenario (even if you aren't building a SPA) - https://github.com/aspnet/Routing/issues/293#issuecomment-217217812

**Comment by SergeyBarskiy** [comment]
@SteveSandersonMS

This (aspnet/Routing#293 (comment) ) issue describes almost exact problem and solution I was pursuing.    I also created a fallback route, but it is still falls through to MVC, which should not happen.  I do not see how without ignore route you could ensure that requests for static files will not fall through to MVC.

**Comment by rynowak** [comment]
@SergeyBarskiy - do you want *ignore route* to skip routing and go to the next middleware, or do you want it to stop processing middleware and 404?

**Comment by SergeyBarskiy** [comment]
@rynowak I prefer 404.  In part because this is how I expect it to work.  I think request for a static file should be handled by static file middleware, never by MVC.  I would be happy though to let MVC not handle the request, which should result in 404.  Personally in my project I do not have any middleware after MVC.  However, how would ASP.NET Core know that the request is intended for static files?

**Comment by Mukesh-Joshi** [comment]
I am having a different kind of issue. When I added a route Route[{string1}/{string2}] on my action, and my controller already has a route["ABC/"], my svg icons are taking ABC/svg/abc.svg path.

**Comment by rynowak** [comment]
@Mukesh-Joshi - please open a new issue and include some code examples so we can see what you're doing.

**Comment by Eilon** [comment]
I think the core of this issue is described in https://github.com/aspnet/Routing/issues/293, so closing this.

It's important to keep in mind that there's no such thing as "a request to a static file" because unless it matches a static file, there's no way to know what was intended. So at most a developer could register certain URL templates as producing 404's in Routing.
