### ISSUE TITLE
NonViewComponentAttribute 

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Mvc#5226]
Currently if I have the following class in the project:

```c#
public class BaseViewComponent
{
    // nothing interesting here, continue reading
}
```

I will receive an exception from the view component descriptor collection provider that the above class is missing `Invoke` or `InvokeAsync` method. I can easily fix the issue by making the class abstract but since there are `NonControllerAttribute` and `NonActionAttribute` maybe it will be useful to have `NonViewComponentAttribute`.

**Comment by javiercn** [comment]
I believe NonViewComponent as described here might introduce an inconsistency with the behavior for NonController. NonController marks everything in the hierarchy as not a controller. I'm not sure what the convention for view components is, but given that BaseViewComponent is being picked up, I tend to think its not compatible with the controller one. This is just something to factor in.

**Comment by ryanbrandenburg** [comment]
I think @javiercn is right here, we'd want it to behave the same for a hypothetical `NonViewComponentAttribute` as it does for `NonControllerAttribute`, so the solution to your problem is, as you said, mark it abstract like we do [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ControllerBase.cs). That said I think it's perfectly reasonable to add a `NonViewComponentAttribute` seeing as it seems to be the pattern.
