### ISSUE TITLE
Multi targeting libraries

### ISSUE THREAD

**Issue by greenplanet** [aspnet/Mvc#5283]
We have developed a library that can be used in classic MVC5 and MVC Core projects. In a classic MVC5 project the library itself (like MVC5) references System.Web.dll. In MVC Core projects the library references some Microsoft.AspNetCore.Http.\*.dll. For example, the MVC application provides an HttpContext to the library. Currently we have two TFM in our NuGet package:

Package
--bin\\**net451**\\library.dll  (references System.Web.dll)
--bin\\**netcoreapp1.0**\\library.dll  (references Microsoft.AspNetCore.\*.dlls)

What TFM a MVC Core project chooses if it runs on traditional .NET? If it references the **net451** dll it would fail, because this library needs a System.Web.HttpContext.

Do we need an additional TFM?

**Comment by pranavkm** [comment]
Your library package should probably reference a `netstandard1.x` TFM rather than `netcoreapp` (See https://github.com/davidfowl/NetStandard/blob/master/platforms.cs for what those terms mean). NuGet, which does the framework resolution, will pick the most compatible TFM. In this case, a `net4x` targeting package would resolve the `net451` binaries so you don't have to be concerned about an application targeting netcoreapp failing at runtime when it fails to resolve System.Web references.

**Comment by danroth27** [comment]
You might also consider separating the MVC 5 and ASP.NET Core support into separate packages since they really are different frameworks.
