### ISSUE TITLE
Windows 10 New Default Regional Settings of AM/PM Causing Bug In Framework

### ISSUE THREAD

**Issue by Reafidy** [aspnet/Mvc#5297]
I am using a Kendo Grid from the Kendo UI for ASP.NET MVC core. When editing a date column from the grid,  the date format is passed incorrectly and the model state fails.

Telerik have stated this is a limitation of the MVC framework and have requested a bug be logged. 

On further research the problem is related to the way the datetime is passed and the regional settings of the computer, specifically en-NZ on the windows 10 platform.  As of windows 10 the default regional settings for New Zealand are formatted differently, more specifically the am/pm is formatted as "AM/PM".  However in windows 7 the default was "a.m./p.m".   I also understand the problem is not specific to just en-NZ.

Changing the regional settings to those of windows 7 fixes the original issue with the grid above, however this is not a reasonable solution to ask every windows 10 client.

[Screen Cast Illustration of The Problem](http://www.screencast.com/t/mflPtbogbo7)

[Screen Cast Work Around](http://screencast.com/t/pU8Cw5sYu)

Sample project illustrating the problem.  Of course the regional settings will need to be set to en-NZ and only on windows 10:
[KendoGridEditDateTimeNZ.zip](https://github.com/aspnet/Mvc/files/481207/KendoGridEditDateTimeNZ.zip)

**Comment by danroth27** [comment]
Binding to DateTime will get model bound using the current culture. Your alternative is to modify your model to bind to a string.

**Comment by danroth27** [comment]
Form data will get model bound to DateTime current culture, which might explain your issue. Your alternative is to modify your model to bind to a string.

**Comment by Reafidy** [comment]
> Form data will get model bound to DateTime current culture, which might explain your issue.

Right, so your saying this is an issue with the Telerik framework?  It appears their culture settings expect a different format (the windows 7 format of a.m./p.m.). Whereas the MVC framework is passing it as AM/PM in line with operating system culture settings.

**Comment by danroth27** [comment]
MVC is doing the work of model binding the form data to the model type, and when binding to a DateTime it use the current culture (which apparently has different behavior on Win7 and Win10). The issue here is really that the browser and the server have different interpretations of the specific culture being used. Is it possible to configure KendoUI to use the invariant culture instead?

@dougbu Can we model bind to DataTime using the invariant culture? Does that just work or do you have to configure something?

To work around this you would need to model bind to a string instead of a DateTime and then parse the string as you deem appropriate. In this particular case, it looks like the model types were generated from the DB, so you might need to define specific DTO types instead of exposing the DB types directly from your actions.

**Comment by dougbu** [comment]
> Can we model bind to `DateTime` using the invariant culture?

Replace the `FormValueProviderFactory` or `JQueryFormValueProviderFactory` in `MvcOptions.ValueProviderFactories` with a factory that creates `FormValueProvider` or `JQueryFormValueProvider` instances using `CultureInfo.InvariantCulture` and not `CultureInfo.CurrentCulture`.

Note the `RouteValueProviderFactory` and `QueryStringValueProviderFactory` already use `CultureInfo.InvariantCulture` because URLs are much less likely to be user-entered.

**Comment by danroth27** [comment]
Closing as there really isn't anything for us to do in MVC on this one.

**Comment by Reafidy** [comment]
Sure.  Sorry to waste your time on that one. Thanks heaps for the help.
