### ISSUE TITLE
Support DisplayName Attribute

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#532]

**Comment by yishaigalatzer** [comment]
We don't plan to support `[DisplayName]` use `[Display]` instead as it is cross platform.

**Comment by bhojwanimukesh** [comment]
@yishaigalatzer I want to extend the behavior of `[DisplayName]` in a way where the given name will be taken as default, and it will fetch from the database as it's configurable. as you recommend to use `[Display]` instead, I won't be able to extend it as it is sealed. Here is my [question](http://stackoverflow.com/questions/39405594/mvc-6-vnext-display-name-attribute-not-working) posted on the very item.

**Comment by dougbu** [comment]
@bhojwanimukesh we added support for `[DisplayName]` in the 1.1.0-preview1 milestone. Everything should be ready for your extension if you update to 1.1.0 bits.

We filed #5296 rather than reopen this long-dead issue. See also PR #5324 and commit 6cdd045.

**Comment by ongun23** [comment]
Prompt field is missing.

**Comment by dougbu** [comment]
**Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

In addition, `[Display(Prompt = "a placeholder")]` is supported. It's used as the `placeholder` attribute value for `<textarea>` elements and `<input/>` elements with `type`s `text`, `search`, `url`, `tel`, `email`, `password`, or `number`.
