### ISSUE TITLE
Client-cancelled requests occasionally provide null body

### ISSUE THREAD

**Issue by brphelps** [aspnet/Mvc#5341]
This is an interesting issue we originally noticed in production and that I was able to reproduce end-to-end while simulating cancelled requests mid-send.

It appears that, sometimes, when a request is cancelled, the Body stream reports "CanRead = true" while the stream is actually inaccessible, and the argument to a [FromBody] parameter is "null" at the entry to an MVC method. I'm only able to reproduce this in < 5% of my requests locally, but it's providing interesting blips in our telemetry that the MVC framework currently abstracts away from us to the point of being unable to 'tell' that the request was cancelled mid-receipt. 

Example tracking:

```
        [HttpPost]
        public void Post([FromBody]Whatever value)
        {
            total++;
            if (value == null)
            {
                totalNull++;
            }
            Debug.WriteLine("total " + total + " totalNull " + totalNull);
        }
```

Is this expected or a known issue? Is there some way we can detect that the body was not fully available to the Request Body stream (content-length indicates content but no content was read / available?)?

**Comment by rynowak** [comment]
It's both surprising and not-surprising to me :-1: There are some odd cases today where you can use `[FromBody]` and have your action called with a null argument.

My suggestion for you while we figure this out would be write an `IActionFilter` that does what you'd like this do it (stop processing, reject the request with a 400, etc).

/cc @Tratcher @davidfowl @halter73

**Comment by brphelps** [comment]
That approach makes sense, but I'm not sure we have enough information to intelligently decide what to do in an action filter, do we? 

Basically, it seems like MVC will at some point read from the Body stream, and if that doesn't complete, will result in a null argument to [FromBody]. My specific question is "How do I know when this has happened?" I'm thinking that the framework itself may be suppressing an exception when reading from the stream and not indicating in the request pipeline that the body wasn't fully processed, which is really the information I'd need to decide what to do.

**Comment by rynowak** [comment]
> I'm thinking that the framework itself may be suppressing an exception when reading from the stream

I'm waiting for @Tratcher or @halter73 to comment on this possibility. Being really noisy about disconnects from the client in the past has caused more trouble than it's worth for a few reasons. If we throw exceptions for disconnects then these also become something you have to analyze in logs.

In general formatters will return `null` when there's nothing in the request body. So while a disconnect could result in 'no body' - there's also the possibility that the client sent an empty body and didn't disconnect. Would you want to handle these cases differently? Or would you just return `400` and ignore the fact that your disconnected clients won't see it?

**Comment by rynowak** [comment]
As as aside to whether or not we have a functional bug - as someone running a production service, what's your ideal? What you like like to see in the logs?

**Comment by brphelps** [comment]
The main concern right now is around traffic analysis, and specifically, how we treat this type of traffic from a telemetry perspective. From my perspective it seems risky to conflate interrupted/aborted requests with 400s, as one indicates a known "fine" scenario and the other indicates a bad calling pattern. We've actually had at least one person looking at the traffic spend a significant time trying to debug the client side to understand how it could be possible that the code was submitting an empty body, when that was never actually happening.

In terms of expected behavior, I don't have a great suggestion that works without additional consumer wireup. I don't know if the status code return is particularly important in the context of an aborted request, so if there *was* a way to know, I think it would be a matter of trying to prevent the request from proceeding through the pipeline (but this could be surprising too). I think preserving the existing behavior would be perfectly fine if there was also additional detail exposed so that we could take action (or take 'inaction' in the case of logging errors).

**Comment by Tratcher** [comment]
We decided to suppress errors in the response stream, but not the request stream. The app needs to know if the response body is incomplete.

**Comment by rynowak** [comment]
So then is your take that this is a functional bug?

**Comment by Tratcher** [comment]
Yes, at some level. If the request body is incomplete then the consumer of the body should know that. If MVC is the consumer then it may choose to handle the error without invoking the controller.

The first question is how is the disconnect being surfaced via the request stream? Does the request stream return 0 or does it throw? It should throw, 0 should be reserved for completed requests.

**Comment by rynowak** [comment]
@brphelps - do you know if there's an error in `ModelState` - whether it's right or wrong, this is where you'd find it.

**Comment by halter73** [comment]
We log and throw from Request.Body.ReadAsync() for incomplete/invalid requests. No one has really questioned that behavior. We can't reasonably prevent that request stream finished gracefully when request data is missing. That could lead to subtle bugs in the application layer.

The only thing that we silence are Response.Body.WriteAsync() errors, since completion for WriteAsync() doesn't guarantee delivery anyway, and these types of errors are fare more common.

@rynowak What would you do `Whatever value` was supposed to come from the querystring and it was missing?

**Comment by brphelps** [comment]
It looks like a "keyless" entry in ModelState, and ModelState is reporting Invalid.

Exception: {Microsoft.AspNetCore.Server.Kestrel.BadHttpRequestException: Unexpected end of request content
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.MessageBody.ForContentLength.ReadAsyncImplementation(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.MessageBody.ReadAsync(ArraySegment`1 buffer, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.ReadIntoBuffer()
   at Microsoft.AspNetCore.WebUtilities.HttpRequestStreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)}

**Comment by brphelps** [comment]
@halter73 -- From my perspective this is a subtle distinction that has more to do with transport than anything else, and generally MVC (thankfully) abstracts it out. When reading things from the body, there's a wider variety of things that can go wrong at the transport layer (vs. if a transport bug happened while sending the URI itself, you may not even get routed to the correct place / HTTP would just reject the request, right?).

We don't really have to worry about errors during communication when processing the request URI because it's not really a thing that can happen, but reading request bodies is a bit different as they can fail mid-processing. I'm mostly just requesting a very clear indication that that has happened so I can programmatically choose what to do :).

**Comment by Tratcher** [comment]
Hmm, BadHttpRequestException should be wrapped in an IOException @halter73

**Comment by rynowak** [comment]
And from an MVC point of view, we should probably rethrow `IOException`

**Comment by brockallen** [comment]
> And from an MVC point of view, we should probably rethrow IOException

Throwing in this situation was quite problematic in Web API: https://aspnetwebstack.codeplex.com/workitem/1797

We have customers with tons of false positives in their error logs because the browser closes the connection before the server has a chance to fully emit the response. Not sure what the solution is, but it'd be nice to know/detect this fairly common scenario so the web server doesn't look like it's reporting lots of failures.

**Comment by rynowak** [comment]
@brockallen - this is the opposite, we're talking about incomplete **requests**.

**Comment by brockallen** [comment]
But does that matter? It's the same situation, right? The client closes its connection (which it's allowed to do). I understand that lots of server-side code will start to fall apart because of it... but it's not an error condition per-se, is it? I mean it's not an error that a network admin needs to know about and do something, for example. 

Again, I don't know the right answer, but I'm simply raising the issue that it's a possible common scenario that can result in exceptions (NREs, etc). Being able to detect this sort of scenario is useful so logging can possibly filter it out or at least lower the log severity so alarms aren't raised. Perhaps you disagree (which is fine, of course), I'm just providing my 2 cents on what my customers experience for this type of scenario.

**Comment by rynowak** [comment]
>But does that matter? It's the same situation, right? The client closes its connection (which it's allowed to do).

Yeah I think you're right. I think our behavior in this situation is already ideal, as I'll explain. I've had my :coffee: now :+1: 

It's not the same situation - in the 'incomplete response' scenario we've already processed the request (successfully) and are just trying to reply and say what we did. In this case, the request is invalid because the client omitted data (0-length body). 

However, I don't see any reason why we would treat this differently than any other type of invalid input. You should get a model state error explaining that we couldn't read from the stream. This is similar to what would happen if the client submitted gibberish instead of JSON.

If you want to avoid these cases reaching your controller, write an action filter that does what you want.

**Comment by Tratcher** [comment]
If model binding fails to load the complete request body why invoke the controller at all? Why not just terminate the request? You already know the client disconnected.

**Comment by rynowak** [comment]
> If model binding fails to load the complete request body why invoke the controller at all? Why not just terminate the request? You already know the client disconnected.

If we did something like this we would do it with a filter so it can be changed. That's basically what I suggested to @brphelps. The delta here is a) we need a clearer indication that IO was the problem, and b) whether this would be on by default or not.

**Comment by rynowak** [comment]
I'm going to close this ancient issue with an update. Along the way somewhere we forgot to respond to this but there have been some improvements for 2.0.0.

We will no longer consider a `null` model object that was bound with `[FromBody]` to be valid by default. That options lives [here](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/MvcOptions.cs#L47).

The intention here is that anything that would prevent us from deserializing the body data (including empty data) is just another kind of 'invalid' request. This makes the number of choices you have to make as an application author pretty limited - all of the things you don't want to take action upon are already marked as invalid.

----------------

If anyone has a concern about the case where the body was incomplete and you feel the need to handle that case specially please reply or open another with more details. I'm going to close this out for now

**Comment by maxMint** [comment]
Very confusing behavior, ModelState does not provide any evidence except saying that model is invalid and no way to differentiate cancelled error vs other errors.
