### ISSUE TITLE
How would I go about getting the current router?

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Mvc#5346]
I'm in a situation where I would like to be able to render templates for emails.  I'm using a class that instantiates a context and everything needed to run the razor engine.

Unfortunately, this snippet just initializes an empty routing table rather than using the one from the current running application.

Is there a safe way that I can obtain the current routing configuration to pass along to the templater?

**Comment by Eilon** [comment]
What exactly do you mean by "the current router"? Is this within the context of an ASP.NET Core request that was handler by the routing middleware?

I ask this because an application can have many routers - there can even be more than one that is "current" because a router can call another router!

If you have access to the current HttpContext for the request (assuming this is in the context of a request), you can get the [`IRoutingFeature`](https://github.com/aspnet/Routing/blob/dev/src/Microsoft.AspNetCore.Routing.Abstractions/IRoutingFeature.cs), and from that you can get the `RouteData`, and that has a collection of the current `IRouter`s for the request.u

**Comment by atrauzzi** [comment]
Hah, I actually ended up figuring it out myself.

```
            IHttpContextAccessor httpContextAccessor,
            IActionContextAccessor actionContextAccessor
```
