### ISSUE TITLE
Consider removing use of HashSet in ValidationVisitor

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#5361]
The `ValidationVisitor` uses a `HashSet<object>` with the reference equality comparer to break cycles during validation. 

This data is from a sampling profile of LargeJsonApi using the POST test. The total time spent processing requests is about 28s.
![image](https://cloud.githubusercontent.com/assets/1430011/19080942/7502c1f6-8a0d-11e6-82d2-b07f8c836292.png)

The far-right column is exclusive time (own time). This means that manipulating the set used for cycle-breaking cost 1134ms or 4% of request processing time.

Give that we don't expect any of these values to hash in an orderly way, we don't expect to support a super large max depth, **and** we're effectively using the set as a *stack*, I'm sure we can do better using an array or `List<object>`. If we're concerned about large N (very very deep models), we use a hybrid approach where we switch to a `HashSet<object>` above a certain threshold.

**Comment by ryanbrandenburg** [comment]
Version|Request time|Item being Profiled|%
----|---|---|---
Hashset|29561|1240|4.19%
List|23323|241|1.03%
List|23372|321|1.37%
Stack|24090|234|0.97%
Stack|32789|229|0.70%

Above is the data I generated while profiling this scenario.  It seems like both the list and stack versions are clear improvements over the current HashSet system. The two are close enough to each other performance-wise that I think it would be prudent to choose the one with the clearest code, as at those levels any advantage might just be random chance. For my money the stack version is clearer since the list version is essentially just using list to implement a stack.

**Comment by rynowak** [comment]
`Stack<>` doesn't support random access, how did you implement `ISet<>.Add()`?

**Comment by ryanbrandenburg** [comment]
After consulting with @rynowak I've abandoned stack as impossible, generated these new numbers:

| Version | Request time | Item being Profiled | %     |
|---------|--------------|---------------------|-------|
| Hashset | 27740        | 1244                | 4.48% |
| Hashset | 24891        | 1089                | 4.38% |
| List    | 31034        | 275                 | 0.89% |
| List    | 25205        | 338                 | 1.34% |

And created a test which should catch anyone else trying to make the same mistake related to model cycle depth.

Do we have any examples of more deeply nested models to get perf data against (I saw BigModelBinding but even that doesn't seem that deeply nested)? I suspect the list will perform worse than hashset for deep/complex models.

**Comment by rynowak** [comment]
What was the max depth that `LargeJsonApi` gets to?

**Comment by ryanbrandenburg** [comment]
`LargeJsonApi` gets to 15. Do we think that's sufficient?

**Comment by ryanbrandenburg** [comment]
After talking in person we've decided to go with the hybrid aproach (a class which switches between List and HashSet above ~20) to avoid possible exhorbitant costs for hugely nested models.
