### ISSUE TITLE
ErrorMessage for custom validation attributes is not localized

### ISSUE THREAD

**Issue by mikkoha** [aspnet/Mvc#5402]
For built in validation attributes the localization works as expected. However, I can not get localized messages for the validation attributes I have written my self.

E.g. if I have in my ViewModel

```
[Required(ErrorMessage = "MyErrorMessage")]
public string MyFirstProperty { get; set; }

[CustomRequired(ErrorMessage = "MyErrorMessage")]
public string MySecondProperty { get; set; }
```

only the message of the first property is localized while for the second I just get the key as the message.

**Comment by dougbu** [comment]
The easiest way to localize client-side validation attributes is to implement `IClientModelValidator` in your custom `ValidationAttribute`. See the [`RemoteAttribute`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/RemoteAttribute.cs) for an example.

The easiest way to localize errors encountered during server-side validation is to override `IsValid(object value, ValidationContext validationContext)` in your custom `ValidationAttribute`. Use `validationContext.GetService(typeof(IStringLocalizerFactory))` to get the factory. Then localize as you wish if the factory is non-`null`.

If you don't want that code in your attribute, implement a custom validation attribute adapter. The [Mvc Localization Sample](https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.LocalizationSample.Web) takes this approach. As you can see there, this option is more involved because it also requires a custom adapter provider.
