### ISSUE TITLE
Why MVC project based and developed on old .net  4.5.1 ?

### ISSUE THREAD

**Issue by Wallsmedia** [aspnet/Mvc#5409]
I have pull out the MVC solution. I want add feature XmlResult, but
I have spotted that every project has net 4.5.1. target
....
 "frameworks": {
    "net451": { .....

Microsoft doesn't support it any more.
Why it doesn't move to .net 4.5.2 ?

**Comment by rynowak** [comment]
We support the minimum version we can for desktop .NET. This means that it can run on all subsequent version of desktop .NET, including 4.5.2, 4.6.0, 4.6.1, 4.6.2, and all future releases.

Version 4.5.1 is pretty ubiquitous so that's what we target, we'd gain very little by requiring a newer version.

**Comment by davidfowl** [comment]
We also started this project ~2.5 years ago and were supporting mono back then.
