### ISSUE TITLE
CookieTempDataProvider chunking broken

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#5430]
When attempting to retrieve temp data that was saved large enough to be chunked we get the error `System.IO.IOException: The encryption operation failed, see inner exception. --> Interop+OpenSsl+SslException: SSL Read BIO failed with OpenSSL error`.

This seems to replicate on both Ubuntu and Windows.

**Comment by ryanbrandenburg** [comment]
So, after doing further investigation we find that this problem happens in Firefox and Chrome, but not IE. It appears that the final chunk is getting saved, but the chunks before it are either geting "overridden" or never saved at all.

**Comment by kichalla** [comment]
We currently do ChunkIntoCookies(Base64Encode(DataProtect(BsonSerialize(actualData)))) and the chunking cookie manager makes sure to limit cookie size to it default cookie size (4070). But it appears that these Base64 encoded chunked parts themselves are again url encoded (probably at the hosting layer?) and because of which its exceeding the limit of 4096 bytes in Chrome and Firefox. IE seems to have a limit of 5117 bytes. (site to test: http://browsercookielimits.squawky.net/)

**Comment by kichalla** [comment]
cc @sebastienros

**Comment by kichalla** [comment]
cc @Tratcher

**Comment by Tratcher** [comment]
You should be using this https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/DataHandler/TextEncoder.cs

**Comment by kichalla** [comment]
32710bbfbea53349ba187610588bbbc96ad51cb4
