### ISSUE TITLE
Simplify resource names when `LanguageViewLocationExpander` provided view location

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#5441]
E.g. have a view for the generic "zh" locale (`_Layout.zh.cshtml`), injected an `IViewLocalizer` into the view, nothing overrides the default implementation of that `interface` (`ViewLocalizer`), and the current culture is `new CultureInfo("zh-HK")`. The resource search looks for
- `_Layout.zh.zh-HK.resx`
- `_Layout.zh.zh-CHT.resx`
- `_Layout.zh.zh-Hant.resx`
- `_Layout.zh.zh.resx`

But users could reasonably expect the resource search to check
- `_Layout.zh-HK.resx`
- `_Layout.zh-CHT.resx`
- `_Layout.zh-Hant.resx`
- `_Layout.zh.resx`

Suggest `ViewLocalizer` should fallback to undoing the work of the `LanguageViewLocationExpander`. In particular, it should special-case scenario where created `IHtmlLocalizer` contains no strings at all. (I.e. `_localizerFactory.Create(BuildBaseName(path), _applicationName)` returns an `IHtmlLocalizer` for which `localizer.GetAllStrings(includeParentCultures: true)` returns an empty enumeration.) In that case, walk through the `CultureInfo.Parent` hierarchy to find a `path` segment matching `culture.Name` and, if there's a match, create a new `IHtmlLocalizer` with a base name built from the `path` without that segment.

Should be careful w.r.t. matching `path` segments depending on the current `LanguageViewLocationExpanderFormat`. Unfortunately that choice is not visible without private reflection into the `LanguageViewLocationExpander`. But, could add a property to that `class` and check the `RazorViewEngineOptions.ViewLocationExpanders` for a `LanguageViewLocationExpander` instance. Or, at least match only `"\.{locale}\.cshtml"` and `"/{locale}/"`. Should not do this extra work unless there is an `LanguageViewLocationExpander` instance in `ViewLocationExpanders` with or without a new property on that `class`.

Would prefer to recommend doing this `CultureInfo.Parent` walk unconditionally. Unfortunately, that would be a breaking change for anyone who already has a `_Layout.zh.zh-CHT.resx` resource file.

---

Found working with sample application at [dougbu/Localized.1.1-preview](https://github.com/dougbu/Localized.1.1-preview).

**Comment by Eilon** [comment]
These are two features that don't know about each other and shouldn't be used together because clearly they conflict. If you have localized views, use one or the other.

**Comment by dougbu** [comment]
@Eilon I discussed this one w/ @DamianEdwards. His conclusion was we _should_ have better support for the scenario. And, using the localization view location provider and `IViewLocalizer` together are a match for the scenario.

What exists today _works_ though the required resource filenames are somewhat awkward -- the point of this bug. Why should users avoid the two features together?

If we don't fix this issue, I'd only recommend additional documentation to make discovery of those resource filenames easier.

BTW though I introduced my suggestion as "undoing the work of the `LanguageViewLocationExpander`", it doesn't actually link the two features. My suggestion is basically to fallback to simpler resource names.

**Comment by Eilon** [comment]
How does "undoing the work of the expander" not amount to linking the two features? It involves one component having knowledge of another component's output, no?

But anyway, I still don't get why anyone would use these two features together. I see them as being absolutely mutually exclusive when it comes to localized views - they are both completely different strategies for locating localized views. Use one or the other.

**Comment by dougbu** [comment]
I'm not making myself clear. Let's chat quickly tomorrow.

**Comment by Eilon** [comment]
Discussed with @dougbu and I understand this now. This turns out to be far more complex -- it seems that the ViewLocalizer might need to know about every stage of what the View Location Expanders did. E.g. for the view `/Views/Shared/_Layout.zh.cshtml` that is running, presumably the ViewLocalizer would want to look for all of these for the `zh-HK` culture:

* `Views.Shared._Layout.zh.zh-HK.resx`
* `Views.Shared._Layout.zh.zh-CHT.resx`
* `Views.Shared._Layout.zh.zh-Hant.resx`
* `Views.Shared._Layout.zh.zh.resx`
* `Views.Home._Layout.zh.zh-HK.resx`
* `Views.Home._Layout.zh.zh-CHT.resx`
* `Views.Home._Layout.zh.zh-Hant.resx`
* `Views.Home._Layout.zh.zh.resx`

Or something like that.

And this seems totally crazy and unreasonable to try to scan so many difference places. And imagine there were other view location expanders, you'd have something like this:

* `Views.Shared._Layout.mobile.zh.zh-HK.resx`
* `Views.Shared._Layout.mobile.zh.zh-CHT.resx`
* `Views.Shared._Layout.mobile.zh.zh-Hant.resx`
* `Views.Shared._Layout.mobile.zh.zh.resx`
* `Views.Home._Layout.zh.mobile.zh-HK.resx`
* `Views.Home._Layout.zh.mobile.zh-CHT.resx`
* `Views.Home._Layout.zh.mobile.zh-Hant.resx`
* `Views.Home._Layout.zh.mobile.zh.resx`
* `Views.Shared._Layout.zh.mobile.zh-HK.resx`
* `Views.Shared._Layout.zh.mobile.zh-CHT.resx`
* `Views.Shared._Layout.zh.mobile.zh-Hant.resx`
* `Views.Shared._Layout.zh.mobile.zh.resx`
* `Views.Home._Layout.zh.mobile.zh-HK.resx`
* `Views.Home._Layout.zh.mobile.zh-CHT.resx`
* `Views.Home._Layout.zh.mobile.zh-Hant.resx`
* `Views.Home._Layout.zh.mobile.zh.resx`

So, given that it's massively complex and it's not entirely clear what the correct behavior should be, this is in Backlog.

**Comment by hishamco** [comment]
After I faced an issue in this PR https://github.com/aspnet/Entropy/pull/134 which leads me to open an issue here https://github.com/aspnet/Mvc/issues/5527, the current behavior for `LanguageViewLocationExpander` resources is unexpected at all for devs, it takes me two days to figure it out after deep digging into the code, plus @dougbu help :) ,so hope we take this in our mind in the future releases. IMHO this doesn't need to be in **Backlog** anymore, because it's a critical issue, along side with that I 'll try to write a blog post about it to make some awareness for such situation.

My humble suggestion to keep the resource names as expected `_Layout.{culture}.resx` as well as layout and partials names `{culture}._Layout.cshtml` or `_Layout.{culture}.cshtml`, becucase me As developer may I need different resource files for different culture as well as different layouts

**Comment by Eilon** [comment]
Looks like this was already reported in https://github.com/aspnet/Mvc/issues/4881, so closing this as a dup.
