### ISSUE TITLE
Custom IViewLocationExpander with pre-compilation

### ISSUE THREAD

**Issue by gdau** [aspnet/Mvc#5508]
Not sure if this is an issue with precompilation or IViewLocationExpander, but if I use feature slices more or less outlined here:

[https://msdn.microsoft.com/en-us/magazine/mt763233.aspx](https://msdn.microsoft.com/en-us/magazine/mt763233.aspx)

So my custom IViewLocationExpander has views located in a "Features" folder rather than inside "Views". When I run the site locally, it works fine. When I publish the site, it works fine. When I publish with Razor Precompilation, then it shows the following relevant error logs at runtime:

```
2016-11-07 11:04:23 [Information] Executing ViewResult, running view at path "Features\Home\Index.cshtml".
2016-11-07 11:04:23 [Information] Executed action "WebApplication15.Features.Home.HomeController.Index (WebApplication15)" in 21.5078ms
2016-11-07 11:04:23 [Error] An unhandled exception has occurred: The layout view 'Shared/_Layout.cshtml' could not be located. The following locations were searched:
Shared/_Layout.cshtml
```
As you can see, it seems to be dropping the "Features" prefix, thereby not finding the view. Is precompilation with custom view expanders a supported scenario?

**Comment by pranavkm** [comment]
Do you have a repro application to share?

**Comment by gdau** [comment]
I do indeed. This is the simplest app I could create that demonstrates the problem. If you run it, it works fine - if you publish it and try run it from the published output it fails when you visit the page.

[WebApplication18.zip](https://github.com/aspnet/Mvc/files/580678/WebApplication18.zip)

**Comment by pranavkm** [comment]
Sorry it took me a while to get to this. We were in the middle of branching for 1.1.0. I'm able to repro the issue and I'm having a look.

**Comment by pranavkm** [comment]
@gdau doesn't look like this is limited to view location expanders. This affects any view that is specified using a relative path. The problem appears to be the result of expecting a normalized path (paths with forward slashes) but end up with one with back slashes because that's the way the tool generates the assembly.

@Eilon IMO, this might be symptomatic of something larger, but for now, we can make a smallish fix to the precompilation tool to code gen view paths with forward slashes. Would be pretty low risk. Thoughts for taking this in 1.1.0?

**Comment by Eilon** [comment]
Is there any other workaround for this?

**Comment by pranavkm** [comment]
Not using relative paths should work.

**Comment by dougbu** [comment]
@pranavkm let's keep our terminology straight: View names e.g. `"Index"` aren't the same as view paths (relative or not) e.g. `"Home/Index.cshtml"`. You must mean view names in this issue because `IViewLocationExpander`s aren't applicable when finding views using a path. Correct?

**Comment by pranavkm** [comment]
@dougbu , I phrased it poorly, but the issue is orthogonal to ViewLocationExpanders. It happens because the app has a relative path `Shared/_Layout.cshtml` and precompilation generates metadata with back slashes that ends up here - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngine.cs#L342.

**Comment by dougbu** [comment]
@pranavkm so `RazorViewEngine.GetAbsolutePath()` assumes xplat-normalized paths but doesn't get such in this scenario. What's the root cause of its (undocumented) assumptions being up-ended i.e. isn't there something between the precompilation tool and the view engine that should be fixing the paths?

**Comment by pranavkm** [comment]
The `CompilerCache` attaches the non-normalized path to `CompilerCacheResult` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CompilerCache.cs#L62. We do the same thing for runtime generated views - https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CompilerCache.cs#L161. 

This ends up as page path \ `ExecutingFilePath`: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CompilerCacheResult.cs#L63-L65. I didn't spend time looking at why it works with the `IFileProvider`, but the precompilation tool was producing metadata preserving the OS path-separator (so back-slashes on Windows). We decided to change it to normalize paths there, but I'm not sure if there's other scenarios we missed here.

**Comment by dougbu** [comment]
Making more sense to me though I suspect the cache key difference is more pertinent: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CompilerCache.cs#L63 (using whatever is in the dictionary) versus https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/CompilerCache.cs#L146 (using the normalized path).

**Comment by pranavkm** [comment]
@gdau , we decided we were going to need a bit more time to address this issue and wouldn't be taking a fix for this in the 1.1.0 release. In the meanwhile, a simple fix for your case would be to modify /Features/_ViewStart.cshtml to use the layout name rather than specify a relative path. Here's what it looks like:

```C#
@{
  Layout = "_Layout";
}
```

This should address the issue for now and cause the Layout lookup to go thru the view location expander which it currently does not.

**Comment by gdau** [comment]
This workaround does indeed make it work for me now. Thanks for taking a look at this.

**Comment by pranavkm** [comment]
We'll use https://github.com/aspnet/MvcPrecompilation/issues/27 and https://github.com/aspnet/MvcPrecompilation/issues/33 to keep track of the work to make precompilation work with relative paths and path traversals. I'll go ahead and close this for now.
