### ISSUE TITLE
PrecompiledView does not honor comment

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Mvc#5546]
![image](https://cloud.githubusercontent.com/assets/12871379/20422203/268e8044-ad69-11e6-97a4-7b0da37bf0b2.png)

![image](https://cloud.githubusercontent.com/assets/12871379/20422214/37986d6e-ad69-11e6-900b-daa2056a7365.png)

Double click the error message and its referring to commented line

![image](https://cloud.githubusercontent.com/assets/12871379/20422239/622c309c-ad69-11e6-92da-c70990bdbf2a.png)

**Comment by pranavkm** [comment]
Are you able to navigate to the page without precompilation?

cc @NTaylorMullen

**Comment by andrew-vandenbrink** [comment]
Yes, no problem with navigate to the page

**Comment by pranavkm** [comment]
I can't reproduce this error. Could you provide a minimal reproduction for this?

**Comment by andrew-vandenbrink** [comment]
-Create new project
-Change project.json to enable precompile view
-Go to Views/Home/Index.cshtml
-Add this line
```
@Component.InvokeAsync("Navigation",new NavigationModel())
```
-Publish (set always delete before publish)
![image](https://cloud.githubusercontent.com/assets/12871379/20514058/3359c3d2-b08a-11e6-95a6-5d995d442beb.png)

-Error as expected
-Comment the line
```
@*@Component.InvokeAsync("Navigation",new NavigationModel())*@
```
-Publish
-Error 
![image](https://cloud.githubusercontent.com/assets/12871379/20514024/f95f532c-b089-11e6-8b07-079292941d9a.png)


Its the new project, it sometimes happen, sometimes not, in my another project it always happen
Notice that it's pointing to **PublishOutput** but I checked the file, it's also commented

Try to publish first with error first on the view
Comment the line
Publish again

**Comment by andrew-vandenbrink** [comment]
Deleting "PublishOutput" folder solve this issue

![image](https://cloud.githubusercontent.com/assets/12871379/20514605/30a55306-b08d-11e6-82c3-ee3fed997ddf.png)

**Comment by Eilon** [comment]
@pranavkm please investigate further to see if there's a bug here.

**Comment by andrew-vandenbrink** [comment]
It's tooling issue I guess.

I deployed PrecompileViews yesterday, I barely able to feel any improvement in startup....

**Comment by pranavkm** [comment]
@andrew-vandenbrink I tried your repro steps a couple times over and I can't seem to repro the issue. Disabling the "Delete all existing files prior to publish" doesn't make a difference either since view compilation isn't incremental and always compiles the views from source (i.e. the actual files from disk). 

I'm guessing this is reaching a bit, but do you save the file after making an edit? It's not listed as an explicit step in your list of reproduction steps. View compilation doesn't interact with VS's unsaved buffer so a file with an edit that isn't saved wouldn't be picked up by the tool.

**Comment by andrew-vandenbrink** [comment]
@pranavkm  I never press ctrl+s or save manually
Always build or publish as its automatically save anyway right?

Publish with error
Comment the offending line
Publish again

As you can see on the tab, there is no unsaved status

![image](https://cloud.githubusercontent.com/assets/12871379/20698746/73cdde5c-b603-11e6-9d9c-c502f765b239.png)

**Comment by andrew-vandenbrink** [comment]
I just tested again

Publish with error
Comment offending line
Press ctrl+s
Publish 

Still the same issue.

**Comment by pranavkm** [comment]
Could you disable publishing view files from your project? For one, you probably don't want to compile those since it's doubling the size of your precompiled output. I'll go ahead and update our documents to call this out.

It's hard to tell from your logs, but it looks like you have view compilation is setup to run as a `prepublish` step rather than a post publish. That's the only way I could reproduce your error since the order of execution is

* Precompilation runs on old files and fails
* Publish overwrites these files.

**Comment by andrew-vandenbrink** [comment]
@pranavkm your reply makes me wonder how precompile choose which view to precompile?
Considering that I need to **exclude** some view to precompile as that view is different for every users.

Removing views from publish solve the issue but my scripts option is on postpublish for sure

![image](https://cloud.githubusercontent.com/assets/12871379/20742113/a50199a2-b6ce-11e6-8ef1-c657b6033b99.png)

**Comment by pranavkm** [comment]
The tool compiles any cshtml file (recursive) specified under `--content--root` option which defaults to project directory when not specified. It does not support an option to exclude as yet, feel free to file an issue in https://github.com/aspnet/MvcPrecompilation/issues if you'd like to start a discussion about it.

I'm really not sure why it was picking up old files (I can't reproduce it locally) but seeing that not publishing views fixes it, I'm going to consider this issue resolved for now.

**Comment by andrew-vandenbrink** [comment]
ok
