### ISSUE TITLE
RedirectResult should support preservation of HTTP method

### ISSUE THREAD

**Issue by smarts** [aspnet/Mvc#5609]
Status codes 303, 307, & 308 are valid redirect codes and should be incorporated into `RedirectResult` and the corresponding controller methods. My guess is that 303 probably isn't a big deal, but the other 2 should definitely be handled.
Similar issue: aspnet/httpabstractions#735

**Comment by juunas11** [comment]
If we are changing RedirectResult, we should be changing `RedirectToActionResult` and `RedirectToRouteResult` as well.

Currently there is a boolean property `Permanent`, that specifies if a 301 or 302 is used. This would have to change so that we could specify the type e.g. with an enum. Something like:

````
public enum RedirectType
{
    Permanent = 301,
    Found = 302,
    SeeOther = 303,
    TemporaryMethodPreserved = 307,
    PermanentMethodPreserved = 308
}
````

The 307 and 308 status codes would need to be named in such a way that they will not be confused with 301 and 302.

`ControllerBase` redirect methods would need updates too.

**Comment by smarts** [comment]
@juunas11 you could do that, or you could add another Boolean value: `PreserveMethod`. But yes, all the redirect-focused action results need to change. 👍

**Comment by Eilon** [comment]
For the methods on ControllerBase, each of the Redirect/RedirectToAction/RedirectToRoute methods should gain an additional overload, adding a new `bool preserveMethod` parameter (and all the current overloads can just call into that).

For the RedirectResult/RedirectToActionResult/RedirectToRouteResult types, each should gain a new ctor and matching get/set property called PreserveMethod.

**Comment by jbagga** [comment]
Also added `PreserveMethod` to `LocalRedirectResult`
