### ISSUE TITLE
[Feature Request/Question] Using MVC to implement isolated pieces of middleware?

### ISSUE THREAD

**Issue by MikaelGRA** [aspnet/Mvc#5630]
Hello,

I am currently working on implementing a middleware component for AspNetCore that exposes an API that should be used in several different applications.

In order to do so, I felt that that obvious choice would be to build ontop of the MVC middleware in order to take advantage of all the things in it, that makes it easy to build great APIs. However, either I am missing something or this is not a use-case that has been considered for MVC. 

My idea was to simply use the IApplicationBuilder method 'Map' to expose my API to an isolated part of the application. Within the callback of the map method I would call my own extension method (for my isolated middleware) that in turn would call 'UseMvc'.

The idea would be that within this isolated part of the application, ONLY the controllers exposed in my middleware assembly would be used and it would have it's own content negotiation rules, etc.

This approach however, does not work. If you do this, the content negotiation rules is shared based on the registered services in the DI container of the 'host' application. Also, the routes that are exposed through the 'host' applications own controllers will be available both places where 'UseMvc' has been called (This is espacially troublesome if the host application decides to use attribute routing, as these are automatically registered in both 'UseMvc' instances and overrides any other routes you might have defined).

So my question is simple: Is it possible to use Mvc to implement completely isolated pieces middlewares? If it is, which approach should one take?

I do certainly feel that if it is not possible to do this, that it is a missed opportunity for Mvc.

For instance, here's a project that I feel, could have taken advantage of Mvc, however, have resorted to implementing it as an low level middleware component for AspNetCore instead: https://github.com/IdentityServer/IdentityServer4 
_(Of course, I don't know the authors exact arguments for implementing it as low level middleware, but I certainly do feel it would have been easier to implement it with Mvc.)_

Let me also point out that it WAS possible to do this in the 'old' OWIN pipeline using Web API, since you could define your own isolated HttpConfigurations with their own services, etc.

**Comment by tuespetre** [comment]
Something something Application Part Providers, maybe? This is an interesting issue you have raised; I'm desiring something lately along the lines of Django's admin functionality.

**Comment by Eilon** [comment]
There are probably some ways to make this work in ASP.NET Core, though it's also probably not trivial. Isolating routes, controllers, and views can be done via having your own instance of the middleware and using application parts. But isolating services is more complex.

Perhaps @sebastienros can offer some pointers about what Orchard2 does (https://github.com/OrchardCMS/Orchard2) because it apparently does per-tenant isolation of some services. That's not *exactly* what is being asked for here, but perhaps a similar solution could work.

**Comment by MikaelGRA** [comment]
Hello @Eilon 

I would definitely be interested in being able to just isolate routes, controllers and views without necessarily being able to seperate the services (at least to begin with).

However, I am a bit confused what you mean by 'having your own instance of the middleware'. It would be very helpful to me if you could clarify that. 

I know that you can use ApplicationParts to, for instance, control which controllers are available to MVC. However, as far as I can see, this is still a part of the shared services (the single dependency container), hence it being the same for all 'instances' of MVC. So I cannot see how that can be involved in isolating routes in MVC.

**Comment by Eilon** [comment]
@MikaelGRA to isolate routes just call `app.UseMvc(...)` multiple times in your Startup.cs `Configure` method, one for each "group" of routes. Each instance of MVC will see only its own routes.

But yes, as you mention, this gets tricky with shared services, because by default they are shared between all the calls to `UseMvc()`. That's where I'm wondering if @sebastienros has a pointer to how something like this is done in Orchard2.

**Comment by rynowak** [comment]
The unit of isolation of MVC is the service provider. If you call `UseMvc(...)` multiple times, all of your controllers/actions are available to all of them and there is no way to configure this behavior.

**Comment by Eilon** [comment]
@rynowak not directly, no. But I think with some custom stuff in the mix you could implement services to be tenant-aware and thus return per-tenant info to each UseMvc call.

**Comment by sebastienros** [comment]
I have been summoned twice so I feel compelled to answer ;)

> I would definitely be interested in being able to just isolate routes, controllers and views without necessarily being able to seperate the services (at least to begin with).

These are part of the configuration as services and middleware instances. Their state is the configuration. To isolate different parts of your application you will then need to isolate your services and your middlewares. This is exactly what Orchard is doing.

The idea is that we create as many containers as we have "tenants". Each tenant defines its own url prefix or domain name. There is a middleware that resolves which tenant the current is targeting and then selects the corresponding container and the sets of middlewares for this tenant. Because we are also based on modules, we also need to register custom ApplicationPart instances so that controllers from different modules are not leaking in tenants where they are not used.

Maybe you should use Orchard Core, it has two parts, a SaaS framework and a CMS, you don't have to use any custom module from Orchard, just yours. Ping me on skype if you want to give it a try.

**Comment by MikaelGRA** [comment]
Perhaps @sebastienros can give me a few pointers to where in the Orchard source code I can look for how you achieve this?

Anyway, I definitely still feel that this is a relevant issue to be considered. Hopefully there will be an (easy) solution to this in the future versions of MVC, as I feel a lot projects would benefit from it.

**Comment by tuespetre** [comment]
A thought on service providers (containers) in this scenario: isn't RequestServices settable? So that 'custom stuff' @eilon was mentioning would maybe entail your own 'UseWhatever()' method that invokes 'Use()' with a delegate that sets a custom composite service provider to RequestServices, adds Mvc to the 'prioritized' service provider within the composite provider, calls 'UseMvc', and afterwards sets the RequestServices back to normal. I mean maybe you would build the custom service provider earlier on in ConfigureServices and then make use of it in the custom middleware but that's the general idea... /ramble

**Comment by MikaelGRA** [comment]
That is a pretty interesting idea. Seems a bit hacky, but I could definitely see it working. Are you allowed to just change the RequestServices like that? Couldn't that have some severe impact on the framework as a whole? I can imagine, especially things like authorization/authentication services might have a problem with it.

**Comment by tuespetre** [comment]
@MikaelGRA I got around to trying it out today. Here's what I ended up doing:

- Created an `AddMyThing` extension to `IServiceCollection` that internally creates its own new `ServiceCollection` and calls `AddMvc()` and whatever else on it
- Created a `UseMyThing` extension to `IApplicationBuilder` that behaves like `app.Map()`, creating a new `IApplicationBuilder` that uses the custom service collection for `ApplicationServices`, and invoking `UseMvc()` on it.

Problems:

- Mvc relies on some stuff that `WebHostBuilder` puts into the service collection before `Configure()` but after `ConfigureServices()`. Things like `ObjectPoolProvider`, `ILoggerFactory`, `DiagnosticSource`, etc. so you have to work around that somehow.

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.
