### ISSUE TITLE
Input tag helper ignores validation attributes defined in the most specific model class

### ISSUE THREAD

**Issue by MissaouiChedy** [aspnet/Mvc#5638]
# Context
Please consider the following example that demonstrates the issue.
## Example
Consider the following cshtml simplified View:
```
@model MvcSandbox.Models.Holder
        <form>
            <input asp-for="Name" />
        </form>
```
This view is strongly typed with the following Holder Model:
```
public class Holder
    {
        [Required]
        public virtual string Name { get; set; }
    }
```
The Holder Model as a subclass:
```
public class SubHolder : Holder
    {
        [MaxLength(200)]
        public override string Name { get; set; }
    }
```
The `SubHolder` class redefines the Name property and adds the `[MaxLength]` validation attribute.

In the Controller action that returns this view we supply an Instance of `SubHolder`:
`return View(new SubHolder());`
## What Happens?
One of the responsibilities of the input tag helper is to render an input tag that has the correct html validation attribute applied, so one would expect to see the following input tag rendered for the Name property in the previous example:
`<input data-val="true" data-val-maxlength="The field Name must be a string or array type with a maximum length of '200'." data-val-maxlength-max="200" data-val-required="The Name field is required." id="Name" name="Name" value="" type="text">`

Unfortunately this is not the case and the `[MaxLength]` attribute is ignored we get something like this instead:
`<input data-val="true" data-val-required="The Name field is required." id="Name" name="Name" value="" type="text">`
## Motivation
Ignoring validation attribute in specific classes makes the chtml view non reusable for sub classes of the class used to type the view, I understand that this case might be "edgy" but I think that taking into account attributes in the most specific class makes the template engine more polymorphic and avoids duplicating the view when subclasses only redefine properties in order to add new attributes.
## Causes of this behavior
It seems that the cause of the behavior lies in the `ExpressionMetadataProvider.FromLambdaExpression<TModel, TResult>` method which returns a `ModelExplorer` object that contains the more abstract type of the model (the one specified in the view) to the input tag helper.
# Proposal
Make the input tag helper recognize the most specific type.

_P.S_
_For the record I already successfully made the necessary changes to `ExpressionMetadataProvider.FromLambdaExpression<TModel, TResult>` to realize the desired behavior (from the standpoint of the issue), I would like to get some feedback before sending a pull request._

**Comment by frankabbruzzese** [comment]
@MissaouiChedy , the change you are proposing would cause incoherent behavior between client validation and server side validation performed during the Model Binding stage. In fact, when you post the form the model binder can no way understand you are posting  `SubHolder` fields, so it will attempt to create an `Holder` instance thus applying  `Holder` validation rules.

In general, the Mvc framework has no way to understand you want to deal with the more specific subclass of the View ViewModel. Moreover, dealing with View ViewModel subclasses would require rendering also the subclass extrafields, so in any case, the general solution of the problem is more complex of the way you are scketcing it here.

If we suppose that the action method where you post the page already knows wich subclass it will receive the general solution to your problem is something like:
`

@if(Model is SubHolder)
{
var Model = ViewData.Model as SubHolder;
<input asp-for="@Model.Name" />
......
}
else if (Model is ...)
.....
....
`
This way you declare explicitaly which subclasses to handle and how to handle them.

On the other side if the action method where you will post the page doesn't know which subclass it will receive, then you must put this information, somehow, in the View, and use a custom model binder.

Give a look to this [subclass tag helper](http://examples.aspnetcore.mvc-controls.com/InputExamples/SubClass) it solves exactly this problem in general. Full doc is [here](http://documentation.aspnetcore.mvc-controls.com/Input/SubClass)

**Comment by MissaouiChedy** [comment]
@frankabbruzzese I did not foresee the incoherence between client-side and server-side validation thanks for pointing it out.

Actually the situation in which I initially needed this behavior is not properly depicted in the example I provided, so please bear with me :-)

Consider now that we have the following chtml file:
```
@model MvcSandbox.Models.Holder
     <div>
         <input asp-for="Name" />
     </div>
```
The previous view is used as a generic editor template for objects of the `Holder` class or its subclasses.
Assuming that:
 - Holder and its sub classes are always used as properties in other view models
 - Subclasses of Holder only override existing properties to add validation attribute

How can I introduce the proposed behavior without changing the framework?

Currently in my project I copy pasted the `ModelExpressionProvider` service and the `ExpressionMetadataProvider` static class, slightly changed their name by prefixing them with custom, introduced the needed behavior and then registered the `CustomModelExpressionProvider` under `Startup.ConfigureServices`. I don't think this solution is clean, is there a better way?

**Comment by frankabbruzzese** [comment]
What have you done is the correct way to change a behavior. However, behavior should be changed coherently.  If the problem is just client validatio you dont need to change anything something like;


```
@if(Model is SubHolder)
{
var Model = ViewData.Model as SubHolder;
<input asp-for="@Model.Name" />
......
}
else {
<input asp-for="Name" />
}
.....
....
```

should work.

However, the fact remains that the model binder is not able to understand which has been submitted.

So if the Action method where you post your page has a ViewModel like:

```
public class MyViewModel
{
    public SubHolder MySubProperty {get; set;}
}
```

everything should work properly. However, if the receiving ViewModel is:

```
public class MyRawViewModel
{
    public Holder MyProperty {get; set;}
}
```

the model binder wouldn table to create a SubHolder instance but would create simply an Holder instance. Your simple meta data provider can't change also the model binder behavior.

**Comment by MissaouiChedy** [comment]
Understood, thank you for the support.
