### ISSUE TITLE
Unable to find the views in custom view engine

### ISSUE THREAD

**Issue by hishamco** [aspnet/Mvc#5648]
I'm working on a `MarkdownViewEngine`, but I faced a strange issue in views searched location, I setup the `ViewLocationsFormats` as the following:
```csharp
markdownOptions.ViewLocationFormats.Add("/Views/{1}/{0}" + MarkdownViewEngine.ViewExtension);
markdownOptions.ViewLocationFormats.Add("/Views/Shared/{0}" + MarkdownViewEngine.ViewExtension);
```
like what we have here in `RazorViewEngine` https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/RazorViewEngineOptionsSetup.cs#L56

I fixed the issue by removing the forward slash at the beginning as it works as expected, I'm not sure if this a bug or I did something wrong.

/cc @NTaylorMullen @rynowak

**Comment by hishamco** [comment]
FYI I pushed the source into my repo [MarkdownViewEngine](https://github.com/hishamco/MarkdownViewEngine)

**Comment by dougbu** [comment]
@hishamco you're using the file system directly -- at least [here](https://github.com/hishamco/MarkdownViewEngine/blob/master/src/MarkdownViewEngine/MarkdownViewEngine.cs#L102). That makes your view engine very different from `RazorViewEngine` e.g. `/` is the application root in `RazorViewEngine` and the drive root in `MarkdownViewEngine`.

Recommend using `IFileProvider`s, perhaps via the `IRazorViewEngineFileProviderAccessor` found in DI (if MVC is configured).

**Comment by hishamco** [comment]
Injecting `IFileProvider` in the PR https://github.com/hishamco/MarkdownViewEngine/commit/efd1db245d2aae808751f6473d2c90dcafca9b3c makes everything happy 😄 

thanks @dougbu

**Comment by rynowak** [comment]
> using the file system directly

I know you already made the change, but for anyone else looking at this, we strongly recommend using the `IFileProvider` for anything that's going to serve content from a site. 

This is a security issue because the path traversal operator (`\..\`) could be used with the `System.IO` apis to serve a file outside of your site's folder. If any of your view location formats are ever used with untrusted input  and you are using the `System.IO` apis this is a risk.  Our `IFileProvider` implementations don't allow serving content from outside of the directory they are given when created.

**Comment by hishamco** [comment]
Thanks @rynowak
