### ISSUE TITLE
[Comment/Question] ModelMetadataTypeAttribute

### ISSUE THREAD

**Issue by RandyBuchholz** [aspnet/Mvc#5650]
## Background
As I understand, this attribute was originally conceived to help address the case where when reversing a database, EntityFramework overwrites the model classes, causing any attributes you would applied to be lost. The attribute helped create "Buddy Classes". The examples I see apply this attribute to a partial class on the entity class. The comments in the source say, "This attribute specifies the metadata class to associate with a data model class."

## Question
My question is about the vision for this class. Is the intent that this class be specific to the case of data model classes, or more general use (i.e., "Merge Attributes")? I'm using it for more general use, but wonder if any future plans would make this a bad idea.

## Example
View Dictionary. I have a data dictionary for all of the data domains in my database. Even though a term appears in many tables, it has/should have the same meaning. This being the case, in my Views, I want them all to have the same display attribute (with the ability to override), regardless of the table they came from. Another case where I want consistency is when I create "targeted" ViewModel's that are subsets (conceptually) of other ViewModels. In these cases, the common approach is to duplicate the Display attribute. 

The approach I'm taking to this is creating View Dictionary classes that I bind to my view models (not my entity models). These contain the display attributes, as well as any other "Dictionary" information I may want to manage.

For example, the ViewDictionary MemberDictionary
```
public class MemberDictionary
{
    [Display(Name = "Member Name")]  
    public string MemberName { get; set; }  
    public string MemberNameDef => "Put general definition here.";  
}
```
is used to support any ViewModel that uses the MemberName data domain/element. Here, one that shows the member details, and one for an application form.

```
[ModelMetadataType(typeof(MemberDictionary)]
public class ShowMemberDetailsViewModel
{
    public string MemberName { get; set; }
}

[ModelMetadataType(typeof(MemberDictionary)]
public class MembershipApplicationViewModel
{
    public string MemberName { get; set; }
}
```
This way, I am able to both reuse my display attributes for consistency, and (a plus) maintain a functional data dictionary in my source. I can inherit these with overrides too, to create more localized dictionaries.

I'm wondering if this is "misuse" of the intent of the attribute (if the intended scope was data models) that could lead to future problems. 

## Suggestion
 Conceptually, I have an issue with common approach of applying this attribute to a partial class on an entity class. This, to me, breaks the separation of data and display. My suggestion is rather trivial (and it  may be nit-picky), but should the description in the source be changed to eliminate "data model"? (Unless the vision is that this only be used in that case.)

**Comment by frankabbruzzese** [comment]
@RandyBuchholz ,
You may use the MetaDataTypeAttribute on DTO/ViewModels. I'ts a way to share same DataAnnotations between several classes with some common properties (by adding the same MetaDataType class to all of them). It's main limitation is that .Net offers no native support for it: each service that want to support it must read the annotation and do itself all needed job to extract information. Thus, there are no garantees about its support. For sure it is supported by the Mvc MetaData extraction engine. 

Anyway it is quite risky to use, because properties with the same semantics  might need different attributes in different ViewModels. Typical example is the RequiredAttribute: the same property (I mean with the same semantic) might be requiredin a ViewModel but not needed into another one (this is a quite common scenario). Also property labels might differ in different Views, ie ViewModels, 
I use it just for sharing Validation atrtributes whose intended meaning is to restrict the original type of a property, such as the RangeAttribute. For sure that validation attributes do not change if the semantic remain the same since same semanti means same restricted type.

**Comment by RandyBuchholz** [comment]
@frankabbruzzese, It's nice that TagHelpers have good support, and much of MVC as well.

I get around differences in ViewModel needs through inheritance. I have an "application" level dictionary that is aligned with the data dictionary for my database. I'm doing domain driven, so I inherit and override for the domains, and so on.  When I create a new ViewModel I check to see if an existing dictionary fits and use that. If not, I'll derive a new one, thinking about keeping it reusable. I was surprised at how few I actually needed once I developed a good approach. I'm pretty rigorous about naming. If a term is ambiguous within a domain I create two that aren't. 

Required is a good example of a case that has difficulties. Ideally, if it is required for the composition of the object it is required in the dictionary. But as you said, in some views it may not be. If it's numerous, I derive a new dictionary. I'm looking at extending the required attribute to have a bool, so I can use it to override. Another approach I use is to create a proxy property on ViewModels that have the exception case. A little extra work, but much less than adding attributes to every item on every ViewModel.

**Comment by Eilon** [comment]
This should probably be fine, per @frankabbruzzese 's comments. While the attributes were certainly designed for "data models" they certainly need not be restricted to that.
