### ISSUE TITLE
Create a helper to retrieve the FullPath of the request

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#5660]
Right now it's done by doing 

```csharp
Context.Request.PathBase + Context.Request.Path + Context.Request.QueryString
```

This is used in cases when you want to create a `returnUrl` parameter. The solution is not obvious and there are no samples making use of it.

It might also be an extension on HttpRequest.

Sample usage: https://github.com/aspnet/Security/blob/master/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L348

**Comment by Eilon** [comment]
I believe that @Tratcher has some strong thoughts about why this doesn't exist. We do have a `GetDisplayUrl()` extension method here: https://github.com/aspnet/HttpAbstractions/blob/87cd79d6fc54bb4abf07c1e380cd7a9498a78612/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs#L177

But, as the name and docs clearly state, it is not reliable.

Unfortunately, I do not recall *why* it isn't reliable, but I'm sure @Tratcher does.

**Comment by Tratcher** [comment]
See UriHelper.BuildRelative: https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http.Extensions/UriHelper.cs#L27

In this context we don't have a FullPath property because nobody can agree what they want in it (e.g. you included the Query in your example).  The other reason we don't do this is that when generating something like the return url it usually does not exactly match the current request, you add or remove path segments and query parameters.

**Comment by rynowak** [comment]
This is not related to MVC.

**Comment by Eilon** [comment]
I chatted with @sebastienros and I think that if we added two extension methods to `HttpRequest` it could be useful, and also clear what they do (and don't do): `GetRequestPath()` and `GetRequestPathAndQuery()`. That way they show up in Intellisense right next to each other, and there should be no confusion about what they do.

@sebastienros can you log a new bug in HttpAbstractions for this?

**Comment by sebastienros** [comment]
Duplicate of https://github.com/aspnet/HttpAbstractions/issues/755
