### ISSUE TITLE
[Question] Distributed CSRF Tokens

### ISSUE THREAD

**Issue by shairozan** [aspnet/Mvc#5681]
So we've deployed a dotnet core application in a docker swarm load balanced between an application load balancer. What we noticed is that if we had more than one container of the application running, sporadically posts would fail with logs indicating that a csrf token doesn't exist in the keychain. 

Is there a way to natively separate or distribute the csrf tokens such that they're all sharing the same token on request, similar to how session can be distributed via sql, or cache?

**Comment by Eilon** [comment]
You need to make sure you set the application discriminator (so that it isn't random) as well make sure the keys are all stored in the same location. This is all done via the Data Protection feature.

You can check out the docs here: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview
