### ISSUE TITLE
Discussion: Input tag helper uses "datetime-local"

### ISSUE THREAD

**Issue by jbagga** [aspnet/Mvc#5714]
If `type` is not explicitly specified as `"datetime"` when using the `input` tag helper, the value renders as `"datetime-local"`, instead of `"datetime"` for better browser support.

See announcement https://github.com/aspnet/Announcements/issues/213

**Comment by Eilon** [comment]
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Comment by mikes-gh** [comment]
Having a problem with this.

View

`<input asp-for="StartDate" class="form-control" size="10" placeholder="Start" />`

ViewModel

```
[Required(ErrorMessage = "{0} is required")]
[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMM yyyy}")]
public DateTime? StartDate { get; set; }
```

Which in 2.0 renders in Development as

```
<input class="form-control" size="10" placeholder="Start" type="datetime" data-val="true" data-val-required="StartDate is required" id="StartDate" name="StartDate" value="25 Apr 2018">
```

But when I deploy to Production it renders as (note datetime-local)

```
<input class="form-control" size="10" placeholder="Start" type="datetime-local" data-val="true" data-val-required="StartDate is required" id="StartDate" name="StartDate" value="25 Apr 2018">
```

It Breaks in Chrome on Production but works in IE 11 

The date picker I'm using recommends type text  which is why it works on Development as I think Chrome treats datetime as text and datetime-local as a date

My issue is the difference in behaviour between Development and Production.  Maybe something to do with precompiled views?

**Comment by mikes-gh** [comment]
As always I found the issue soon after I posted.
I forgot to update my launch.json to run the 2.0 version of my app so my production was 2.0 but my dev was on 1.1

Sorry for noise.
