### ISSUE TITLE
Question: correct way of passing ViewDataDictionary to partial view?

### ISSUE THREAD

**Issue by WHarris22** [aspnet/Mvc#5732]
I know this isn't the right place for a question but I feel like I will get a better / quicker response here.

**Problem**
I have a view which loads a partial view twice and I want to pass a HtmlFieldPrefix property so that the two partial view input elements can be distinguishable. 

**Solutions**
I came across a way of being able to do this which involved the following code:

`@Html.Partial("_Filters", Model, new ViewDataDictionary(new EmptyModelMetadataProvider(), new ModelStateDictionary()) { TemplateInfo = { HtmlFieldPrefix = "LgContainer"}})`

Then after some playing around I realised you could also do it like this (passing in the ViewData from the ViewContext):

`@Html.Partial("_Filters", Model, new ViewDataDictionary(ViewContext.ViewData) { TemplateInfo = { HtmlFieldPrefix = "LgContainer"}})`

**My Question**
I tried to Google partial views and view context related things and a few peopple have said that a partial view should use the same view context as its parent view, which I guess means that the second option I provided is the more logical way of doing this.

So I would just like to get somebody else's opinion and if they could tell me which option is the "best practice" way to do this?

**Comment by frankabbruzzese** [comment]
@WHarris22 , for sure the first solution is in generally wrong. Passing an empty ModelState makes no sense: this way your partial view will not show sever returned validation errors.  Second solution is generally better, since it retains all main view infos: ModelState, if client side validation is on or off, and other options.

Unluckly, also second solution has its downside, mainly:
1.  It moves all ViewBag entries to the called partial view, which in some cases might cause problems;
2. Initialize ViewDataDictionary with main View metadata, which might cause problems when your model is null. In fact if model is not null metadata are recomputed, otherwise they are not. However, you may pass the right metadata after creation in various way; simplest way is by setting the ModelExplorer property.

**Comment by WHarris22** [comment]
@frankabbruzzese thanks for the quick response that was really helpful. If its not too much to ask could you give me an example of what you see as the best way to do this then?

**Comment by frankabbruzzese** [comment]
Since VieBag entry in most of cases are not a big issue you might follow approach 2. However, if model might be null. Once created ViewDictionary set its ModelExplorer property, before passing it to Html.Partial:

`vd.ModelExplorer = ViewData.GetExplorerForExpression(ModelTypeHere, model)`

Obviously if your partial must receive the same model as the main view, you may avoid all this. 
`@Html.Partial(viewName)` it's enough.

**Comment by WHarris22** [comment]
Ok thanks for the example.

In my situation although I have inputs in my partial i'm not actually dealing with validation so I think I should be alright with the second option I said to begin with.

I guess your recommendations will be more suitable for when the partial has a form with validation occurring.
