### ISSUE TITLE
Thread.CurrentPrincipal.Identity.Name is empty in AspNetCore on .NET Framework 

### ISSUE THREAD

**Issue by dopare** [aspnet/Mvc#5759]
Steps to reproduce:

1. In Visual Studio 2015 create ASP.NET Core Web Application (**.NET Framework**)
2. Choose Individual Authentication
3. In authorized controller ( for example in `ManageController.cs` ) `Thread.CurrentPrincipal.Identity.Name` is empty even `HttpContext.User` contains all user data.

I am not sure if this is a bug or design decision.

**Comment by frankabbruzzese** [comment]
with async programming a single request spans sevefal threads so request information cant be associated to a single thread like in previous asp.net mvc versions.

**Comment by dopare** [comment]
I think previous asp.net mvc version also supports async programming.

**Comment by dopare** [comment]
So `Thread.CurrentPrincipal.Identity.Name` is ignored ?

**Comment by frankabbruzzese** [comment]
@dopare , 
At beginning Asp.net used `SharedStatic` properties for objects that are global to the whole request since request were mono-thread. Then, with async programming some request data were attached to all request threads to mantain compatibility. Now with the break change of asp.net core such globals are handled by the Dependency Injection engine thus ensuring better testability. As a consequence, at moment,` Thread.CurrentPrincipal` is ignored, but other people want this feature again, so maybe they will reappear. Please follows the discussion in the link posted by Tratcher.

**Comment by dopare** [comment]
@frankabbruzzese thanks.
