### ISSUE TITLE
ViewCompilation on publish fails when renaming Assembly in csproj

### ISSUE THREAD

**Issue by IRooc** [aspnet/Mvc#5780]
Create a new WebApplication targeting netcoreapp1.1 and add ViewCompilation with following csproj:
```
<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>netcoreapp1.1</TargetFramework>
		<MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
	</PropertyGroup>

	<PropertyGroup>
		<PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
		<PackageReference Include="Microsoft.AspNetCore" Version="1.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.ViewCompilation" Version="1.1.0-msbuild3-update1" />
	</ItemGroup>
	<ItemGroup>
		<DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild3-final" />
	</ItemGroup>

</Project>

```

```dotnet publish``` works fine

Now add ```<AssemblyName>NewAssemblyName</AssemblyName>``` to the first PropertyGroup and try ```dotnet publish``` again.

this will fail with ```Could not load file or assembly 'WebApplication1, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.``` exception on precompilation

**Comment by davidfowl** [comment]
If you're feeling lucky and want to send a pull request, the issue is here:

https://github.com/aspnet/MvcPrecompilation/blob/ed28b1671b514d60a127ac12ed717b29bd3a6ff8/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/common.targets#L23

And here

https://github.com/aspnet/MvcPrecompilation/blob/ed28b1671b514d60a127ac12ed717b29bd3a6ff8/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/build/common.targets#L6

It should be `$(AssemblyName)` (which is inferred from the project name if not specified).

**Comment by IRooc** [comment]
Hope I did it correctly, never done it before... https://github.com/aspnet/MvcPrecompilation/pull/82
