### ISSUE TITLE
Simplify functional testing of an MVC app with Views

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#5793]
Customers that try to test MVC always run into the fact that they need to override the content root.

See https://github.com/mattridgway/MvcIntegrationTests#failing-tests (old)

Our MvcFixture solves this nicely (it can even be reduced further). We should expose some type of helper to make this easier.

https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.FunctionalTests/MvcTestFixture.cs#L51-L72

**Comment by dougbu** [comment]
@davidfowl most of our repos deploy web sites rather than load them in memory as MVC does. Isn't deploying what we'd suggest to customers for their functional testing?

Either way, one or two other repos have variants of the `MvcTestFixture`. We might want that class public (at least in an internal `.Sources` package) for our own use.

**Comment by davidfowl** [comment]
> @davidfowl most of our repos deploy web sites rather than load them in memory as MVC does. Isn't deploying what we'd suggest to customers for their functional testing?

I hope not.

> Either way, one or two other repos have variants of the MvcTestFixture. We might want that class public (at least in an internal .Sources package) for our own use.

I'm less concerned what we use for ourselves.

**Comment by Eilon** [comment]
Closing in favor of https://github.com/aspnet/Mvc/issues/6233.
