### ISSUE TITLE
Confused with response result way.

### ISSUE THREAD

**Issue by sonphnt** [aspnet/Mvc#5821]
Hi Everyone,

There are a lot of ways to return a response to client from web api. But I would like to know what is the best way and consistent way in best practices to use between these:

```
return new BadRequestResult();
return new BadRequestObjectResult("My bad");
return BadRequest("My bad");
```

Combine with Webapi action GET-PUT-POST-DELETE
Which way of returning a response is the best?
Sometimes we use in PUT like this

`return new NoContentResult();`

Sometimes we use in POST like this

`return OK();`

Thanks

**Comment by Eilon** [comment]
These are all totally acceptable ways to write the code.

We usually recommend the `return XyzResult(...)` (without the `new`) because they often have "friendlier" overloads for creation of the result types. But, if you look at what those helper methods do, they just set a few things and then call `new XyzResult()`.
