### ISSUE TITLE
Model State serialization should comply naming rules

### ISSUE THREAD

**Issue by msmolka** [aspnet/Mvc#5854]
When serializing model state errors it should comply naming convention rules.
So 
when json serizalizer is using pascal case: use keys with pascal: NameOfMany
when json serizalizer is using camel case: use keys with camel case name: nameOfMany

currently errors returned have different casing than properties sent.

**Comment by Eilon** [comment]
The model binding system is designed to store errors using the .NET type's naming scheme because that's what it's reporting errors about. Model state is generally used for model binding so it needs to be able to correlate the errors with the state of the in-memory model. Unfortunately, with formatters such as JSON and XML that correlation isn't a good match, but I also don't think there's a way to fix this because it doesn't know the origin name of the data field.

**Comment by msmolka** [comment]
Ok, I understand, I wrote my own SerializeError class to serialize names in came case
