### ISSUE TITLE
[Question] Why appending the generated html from checkbox input tag helpers to output.Content?

### ISSUE THREAD

**Issue by MissaouiChedy** [aspnet/Mvc#5857]
In the [`InputTagHelper.Process`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs#L133) method, Html check-boxes (`<input type="checkbox"/>`) are generated differently than the other `input` types.

In my understanding, for all the other `input` types, the `TagHelperOutput` instance passed to the `Process` method:
 - Keeps the `TagName` property
 - Populates the `Attributes` property
 - Populates the `Content` property, if necessary

Whereas, for the `hidden` and `checkbox` types, it:
- Sets the `TagName` property to be `null`
- Clears the `Attributes` property
- Appends the generated html to the `Content` property

The previous behavior is located under the [`TagHelper.GenerateCheckBox`](https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs#L255) method.

Why not having a unified behavior for all `<input>` types?

**Comment by dougbu** [comment]
> Why not having a unified behavior for all `<input>` types?

In short, because a checkbox needs a hidden `<input>` with the value `"false"` to be model bound. A cleared checkbox should set the model's property to `false`. Without the second  `<input>`, the property would not be changed.

Closing this issue because I believe I've answered your question. Feel free to reopen if you meant something different.
