### ISSUE TITLE
HttpResponseException exists in both Microsoft.AspNetCore.Mvc.WebApiCompatShim and System.Web.Http

### ISSUE THREAD

**Issue by vfab** [aspnet/Mvc#5861]
We're building a multi-framework IoT app using both NET Core & .NET 4.5.2.  But we're getting errors like what's in the title: `The type 'HttpResponseException' exists in both 'Microsoft.AspNetCore.Mvc.WebApiCompatShim, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'`.  
I see that WebApiCompatShim redefines System.Web.Http, but don't know how to fix this error.  Any suggestions?

Thanks

**Comment by vfab** [comment]
FYI, I finally got past this by deleting all references to WebApiCompatShim.  Would still like to understand what's behind this, however.  Are they never intended to live together in the same project?

**Comment by danroth27** [comment]
@vfab The Web API Compat Shim is primarily for making it easier for existing ASP.NET Web API customers to migrate to ASP.NET Core. It puts a Web API facade over ASP.NET Core MVC so that you can for the most part copy and past your existing ApiControllers into a new ASP.NET Core project. It's intended to be used in an ASP.NET Core app, which generally should not have any references to ASP.NET Web API.
