### ISSUE TITLE
NumericClientModelValidatorProvider not working with integers, thus localization isn't supported for integers

### ISSUE THREAD

**Issue by annayafi** [aspnet/Mvc#5865]
Add a simple int field in your view model. 
Add a simple `<span asp-validation-for=` for this field.
You always get a message : "Please enter a valid number". This is not a mvc resource, but the default jquery validate message. 
Because `Microsoft.AspNetCore.Mvc.DataAnnotations.InternalNumericClientModelValidatorProvider` only deal with float, double, decimal:

```c#
 // Check only the numeric types for which we set type='text'.
            if (typeToValidate == typeof(float) ||
                typeToValidate == typeof(double) ||
                typeToValidate == typeof(decimal))
            {
```

Here's what I did as a work around, in Startup.cs

```c#
.AddViewOptions(o=>
                {
                    var result = o.ClientModelValidatorProviders.SingleOrMaybe(e => e.GetType() == typeof(NumericClientModelValidatorProvider));
                    o.ClientModelValidatorProviders.Remove(result.Value);
                    o.ClientModelValidatorProviders.Add(new CustomNumericClientModelValidatorProvider());
                })
```

And here's my provider:

```c#
internal class CustomNumericClientModelValidatorProvider : IClientModelValidatorProvider
    {
        public void CreateValidators(ClientValidatorProviderContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var typeToValidate = context.ModelMetadata.UnderlyingOrModelType;

            // Check only the numeric types for which we set type='text'.
            if (typeToValidate == typeof(float) ||
                typeToValidate == typeof(double) ||
                typeToValidate == typeof(decimal)|| typeToValidate == typeof(int))
            {
                for (var i = 0; i < context.Results.Count; i++)
                {
                    var validator = context.Results[i].Validator;
                    if (validator != null && validator is NumericClientModelValidator)
                    {
                        // A validator is already present. No need to add one.
                        return;
                    }
                }

                context.Results.Add(new ClientValidatorItem
                {
                    Validator = new NumericClientModelValidator(), //or specific to get special message for int
                    IsReusable = true
                });
            }
        }
    }
```

It would be nice to get this native, ideally with an accessor on the ModelBindingMessageProvider for int like (NumericClientModelValidator)

```c#
 if (modelMetadata.UnderlyingOrModelType == typeof(int))
     return modelMetadata.ModelBindingMessageProvider.ValueMustBeAnIntAccessor(modelMetadata.GetDisplayName());

  return modelMetadata.ModelBindingMessageProvider.ValueMustBeANumberAccessor(modelMetadata.GetDisplayName());
```

Thank you

**Comment by Eilon** [comment]
Hmm I wonder if the reason for this is that jQuery Validation's validator is specifically about decimal-type numbers, that is, ones that might have a `.` in them for fractions. On the other hand, integers of course cannot have a `.`. I took a look at what jQuery Validation has, and it's pretty clear that https://jqueryvalidation.org/number-method/ is meant for scenarios with numbers that allow decimal points. It doesn't seem to have validators for integers. The closest thing is https://jqueryvalidation.org/digits-method/, but that's not the right semantics.

@dougbu does that make sense to you?

**Comment by dougbu** [comment]
> @dougbu does that make sense to you?

Yup. In addition, for `type="number"` inputs (what we use for `int`), the "The default step is 1 (allowing only integers to be selected by the user&hellip;" according to the [HTML 5.0 spec](https://www.w3.org/TR/html5/forms.html#number-state-(type=number)).

**Comment by frankabbruzzese** [comment]
@dougbu,  It is not exact. 
Also with step=1, user is able to insert manually(without using increment/decrement buttons) any decimal. However, in this case, an error is returned by "native" form validation...but jquery validation plugin disables native validation. So with client validation on, user is able to insert  decimal numbers in any int field.

In general, wrong format client validation is quite incomplete, since it doesn't handle also all date/time related input types. Howwever, all problems comes from the JavaScript side. The case of the integer is easily solved by adding a new JavaScript validation rule that is specific for integers. It could be added in the unobtrusive validation plug-in.

However, the problem with dates and times is very difficult to solve, since not all Date and Time related Html5 inputs are supported in all main browsers, so validation rules can't just handle the international format used by Html5 inputs but should work also with localized dates in case browser doesnt support the original Html5 type.

**Comment by annayafi** [comment]
This is not exactly the issue.  This is not about entering special characters in a field type number. The problem is that **there is no way mvc can control and localize the message, regarding int fields in view models.** 
For other numerics, we would simply in Startup.cs:
```c#
options.ModelBindingMessageProvider.ValueMustBeANumberAccessor = (x) => string.Format(validationsStringLocalizer["ValueMustBeANumber"], x);
```
And the message is localized for numerics. But there is no way in mvc to localize the message for int types. And the default jquery message is displayed, come what may. So, if you type in: "2e3" in the input field, you'll see this message. And excepted the workaround I posted, there is no "native" way...

**Comment by asiffermann** [comment]
Agreed!

And that's because jQuery Validate automatically register a https://jqueryvalidation.org/number-method/ on input `type="number"`.

I think that's the meaning of the comment above in `InternalNumericClientModelValidatorProvider`: you only have to explicitly set the `data-val-number` when the generated input is of type text.
But if you don't, you cannot pass the custom validation message to jQuery Validate... And that's a pity :smile:

**Comment by frankabbruzzese** [comment]
@annayafi @asiffermann , the fact that mvc doesn't handle integers is not actually a bug, it is a decision. Since jquery plugin has no rule that is specific for integers but just for decimals, integers were excluded from validation. So a coherent fix should define a new integer specific validation rule on the javascript side and only after that recalling it from an mvc validator.

**Comment by frankabbruzzese** [comment]
About text fields, they would work if one fixes as I explained above, but ...just for english locales, since jquery plugin just validate the international format used by all html5 fields and just the english culture browsers when text fields are used. I speak of dot versus comma in numbers not of the language of the error message!

However localization of numbers and dates is very hard to solve, since it would require the adoption of a client side localization library and the redefinition of all javascript validation rules, and a kinda coordination with the model binder that should be informed if the property was rendered in an html5 field and is in an international format or in a text field and is in a localized format.

**Comment by mkArtakMSFT** [comment]
@kichalla FYI, as you're doing something in this area

**Comment by kichalla** [comment]
Discussed with @dougbu and agreed that there's no action item for us here.
