### ISSUE TITLE
InputTagHelper doesn't copy pre-existing attributes correctly for checkboxes.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#5981]
Given the following `TagHelper`:

```C#
[HtmlTargetElement("input", Attributes = "asp-for,[type=checkbox]")]
public class FooTagHelper : TagHelper
{
    public override int Order => -2000;

    public override void Process(TagHelperContext context, TagHelperOutput output)
    {
        var tb = new TagBuilder("input");
        tb.AddCssClass("myclass");
        output.MergeAttributes(tb);
    }
}
```

And the following source:
```HTML
<input asp-for="BoolVal" class="my-control" type="checkbox" />
```

You end up getting an invalid class attribute value:

```HTML
<input checked="checked" class="Microsoft.AspNetCore.Mvc.TagHelpers.TagHelperOutputExtensions&#x2B;ClassAttributeHtmlContent" data-val="true" data-val-required="The BoolVal field is required." id="BoolVal" name="BoolVal" type="checkbox" value="true" /><input name="BoolVal" type="hidden" value="false" />
```

This is because of how we [copy the pre-existing output attributes](https://github.com/aspnet/Mvc/blob/1197657e5bd534a1bbed15708ab51f2462598dc6/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs#L293).

**Comment by dougbu** [comment]
Root cause is the `HtmlGenerator` does not handle `IHtmlContent` in `htmlAttribute` dictionaries it's given. No need for such support elsewhere; the MVC tag helpers should be passing `htmlAttributes: null` except in this one case.

This problem would mostly go away if we fixed #5902. But, might still need to do something special when `!ViewContext.FormContext.CanRenderAtEndOfForm`.
