### ISSUE TITLE
Added polymorphic json support for the root object

### ISSUE THREAD

**Issue by dougbu** [aspnet/Mvc#6082]
This issue is intended to track decisions on PR #5980.

If we choose to accept that PR, should also change our `Controller.Json()` methods to use the passed object's declared type i.e. change `JsonResult Json(object data)` (and so on) to `JsonResult Json<TResult>(TResult data)`. That would also expose explicit control of the serialized type without touching the `JsonResult` e.g.
``` c#
class SubClass : Exposed
{
}

public class HomeController : Controller
{
    public IActionResult SomeJson()
    {
        var sub = new SubClass();
        return Json<Exposed>(sub);
    }
}
```

**Comment by TylerBrinkley** [comment]
I would have included the change to `Controller.Json()` but seeing how it's a breaking change I wasn't sure it would be accepted.

**Comment by Eilon** [comment]
@TylerBrinkley the code in https://github.com/aspnet/Mvc/pull/5980 looks good and we think it's reasonable to include in ASP.NET Core 2.1 - thanks!

We also took a look at the tests and we feel that they don't cover the exact scenario under consideration here, which is to allow a *declared type* to vary from the *runtime type* during serialization. That is, it seems like there should be:
1. Tests that show exactly which properties get serialized if there's a base type such as `Person { Name }` and a derived type `Employee : Person { Team }` that you can control whether `Team` gets serialized
2. Tests that show what actually got serialized, as opposed to using Json.NET to generate the expected output.
3. We probably don't want tests that use TypeNameHandling because that is a poor security practice and we'd probably end up changing the test anyway because it would end up getting flagged in a security review 😄

**Comment by Eilon** [comment]
Assigning to @dougbu to track this.

**Comment by TylerBrinkley** [comment]
@Eilon, I don't believe Json.NET is setup to allow the scenario you mention in your first point with only serializing members of the base class. Also, passing the declared type to the serializer is only used for `TypeNameHandling.Auto`.

**Comment by dougbu** [comment]
@TylerBrinkley what exactly should `DeclaredType` control? For
``` c#
class Person
{
    public string Name { get; set; }
}
class Employee : Person
{
    public string Team { get; set; }
}

var joe = new Employee { Name = "Joe", Team = "Mighty Ducks" };
var result = Json(joe);
result.DeclaredType = typeof(Person);
return result;
```
The response body with after #5980 remains
``` json
{"Team":"Mighty Ducks","Name":"Joe"}
```
If instead I change the serializer settings to use `TypeNameHandling.Auto`, the body is
``` json
{"$type":"SomeNamespace.Employee, SomeAssembly","Team":"Mighty Ducks","Name":"Joe"}
```

Note the serialized type is `Employee` and not `Person`.

@Eilon these settings do not change the properties that are serialized.

**Comment by dougbu** [comment]
FYI @Eilon to serialize only base class properties, users can for example
``` c#
        private class Person
        {
            [JsonProperty]
            public string Name { get; set; }
        }

        [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
        private class Employee : Person
        {
            public string Team { get; set; }
        }
```

And, [this guy](http://www.ithoughts.de/json-net-and-serializing-only-base-class-properties) suggests a generic `DefaultContractResolver` subclass that opts in or out depending on a property's declaring type.

**Comment by Eilon** [comment]
Oh I thought by default only members of the *declared type* got serialized? That's not the case?

**Comment by TylerBrinkley** [comment]
@dougbu The only thing `DeclaredType` should control is whether to output the type name when using `TypeNameHandling.Auto`.

In your example, if your api can return any type of `Person` then if the runtime type is not a `Person` but a derived class like `Employee` then it's type name should be added when using `TypeNameHandling.Auto`.

**Comment by dougbu** [comment]
> That's not the case?

Yup, the polymorphic support here is about recreating e.g. a subclass of something `abstract`. Json.NET uses a `$type` property for that purpose.

FYI I'd normally recommend a custom model binder here. But, that won't work except at the top level of a model.

@TylerBrinkley does everything work end-to-end with the #5980 changes in place? Or, is it necessary to enable a non-default `TypeNameHandling` in input formatting as well? I'd be concerned about recommending such a change because I haven't seen anything that validates the `$type` value before constructing an instance.

**Comment by TylerBrinkley** [comment]
@dougbu In order to deserialize the json to its specified `$type` the user must specify a non-default `TypeNameHandling` otherwise the `$type` json property will just be ignored. Does that help?

**Comment by Eilon** [comment]
Hi all, from what we can tell, there are no issues serializing all the properties of derived types. (I initially thought that wasn't the case, but that was incorrect.)

It appears that this particular request is fundamentally about making Json.NET's [TypeNameHandling](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_TypeNameHandling.htm) feature more usable in ASP.NET Core MVC. Given that the feature is not easy to use in a secure manner, we want to avoid adding features that encourage its use.

We recommend writing a custom formatter (or action result, etc.) that can handle this specific use case wherever it is needed.

Closing because there are no plans to implement this.

**Comment by TylerBrinkley** [comment]
For my use, it's for an internal api that is not directly nor indirectly exposed externally so I'm not concerned about the potential security issues.

Thanks for looking at the request. I'll just wrap my returned objects in a wrapper object since the `TypeNameHandling` feature works fine with non-root objects.

**Comment by Eilon** [comment]
Indeed, for internal APIs that aren't publicly exposed this is certainly much safer. Unfortunately we're concerned about the broader usage where we think the risk is just too high. Quite unfortunate.
