### ISSUE TITLE
No parameter injection when creating a custom view derived from a razor page.

### ISSUE THREAD

**Issue by rjamesnw** [aspnet/Mvc#6093]
When my custom `ViewPage` type, which inherits from `RazorPage`, gets created for a view, nothing gets injected into the constructor parameters.  The generated view code seems to use `[RazorInject]` instead on properties.  Why the inconsistency?

**Comment by rynowak** [comment]
We don't support constructor injection for views, because there's no way to write a constructor in vanilla Razor. 

`@inject` in Razor isn't *just* DI. It also supports injecting services which implement `IViewContextAware`, meaning that they can capture information from the current `ViewContext`.

Beware that anything in a `.Internal` namespace is an implementation detail and subject to change.

**Comment by rjamesnw** [comment]
Is that like when the C# team said it "wasn't possible" to put async in a catch block, then later figured it out? :p  ;) I'm pretty sure someone smart enough could figure something out. ;)
