### ISSUE TITLE
Inconsistent memory consumption report

### ISSUE THREAD

**Issue by CoskunSunali** [aspnet/Mvc#6106]
I am not exactly sure of the reason behind the inconsistency so I am creating the issue under the MVC repo.

Creating an empty web application (no custom code at all) and running it via F5 makes VS 2017 report somewhat strange memory usage. One session reports 295MB and the other one reports 142 MB of memory usage.

The two requests are exactly the same; I click F5 and take a screenshot as soon as I see the default homepage of the default MVC project template. You can see the number of events, etc. being the same in the two requests.

The results are totally random. Sometimes it will consume 295 MB initially and some other times it will consume 142 MB initially.

P.S.: I don't have access to paid tools like dotMemory and VS does not seem to do a great job when it comes to fully profiling an ASP.NET Core app - or I cannot manage to do it somehow.

![image](https://cloud.githubusercontent.com/assets/6509380/24824827/b12e1c3e-1c1b-11e7-9c1e-39b4e264cac0.png)

![image](https://cloud.githubusercontent.com/assets/6509380/24824828/b43a0528-1c1b-11e7-8f1f-6985aac18847.png)

**Comment by rynowak** [comment]
The `Take Snapshot` button in this case would be useful. VS can show you what .NET objects are in memory.

It's also good to reflect on the fact that the behavior of the GC isn't predictable. It's likely that startup is going to trigger a GC sometime during the first request. Based on when exactly that happens, a different set of objects might be eligible for GC, which can explain the difference that you're seeing.

It's also worth knowing that measuring the memory 'in use' by a process is a bit of an art rather than a science. In this case it looks like VS is showing Private Bytes - http://stackoverflow.com/questions/1984186/what-is-private-bytes-virtual-bytes-working-set. I'll bet if you take snapshots and look at the number and size of .NET objects in memory it will be rather consistent, while the Private Bytes might vary a lot.

**Comment by CoskunSunali** [comment]
You might be right. My conclusion is that the 295 MB of memory being used by my app (an empty `WebApplication1`) does not seem to be realistic.

If I publish the same app and serve it using IIS, the `dotnet.exe` serving my web app does not consume more than 60-70 MB of memory at most.

Regarding the GC, I agree with what you said. However, even if GC is not predictable, would you personally expect to see 300 MB of memory usage being reported on that screen with an empty template web site?

Did you have a chance to try this yourself by creating an empty web site?

**Comment by CoskunSunali** [comment]
Just tried running the same application using `dotnet run` and the `dotnet.exe` instance being created consumes no more than 31 MB of memory. If all my app's objects live within the context of that `dotnet.exe` instance; 31 vs 295, there definitely seems to be a tooling issue if nothing else, imho.

**Comment by mkArtakMSFT** [comment]
Closing this is this doesn't seem related to MVC. If you feel that this is still a problem, feel free to open a new issue through the VS feedback.
