### ISSUE TITLE
[Enhancement] Don't bind collection of specific types

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6112]
There is `ExcludeBindingMetadataProvider` which can exclude properties of a specific type from model binding. However is doesn't exclude related collection types.

For instance, properties of type `Type` are excluded in the default configuration of MVC, but a property of type `Type[]` or `List<Type>` would still be bound.

Related to #6110

**Comment by Eilon** [comment]
Is this actually important? That is, are there reasonable cases where there's some kind of list of `Type` that appears in something you might model bind, and we should exclude by default?

I ask this because there are of course thousands of types in the system that would would never want to model bind, and we obviously won't list them all, nor variations of them (list, nullable, etc.).

We added `Type` because it does actually show up in places where model binding happens and caused a bit of grief to users.

**Comment by Eilon** [comment]
Closing for now, awaiting further customer feedback. The current workaround is to either annotate the property/type to indicate it shouldn't be bound, or to add the type to the list of excluded types for model binding.
