### ISSUE TITLE
Consider passing arguments dictionary in ExceptionContext

### ISSUE THREAD

**Issue by cortex93** [aspnet/Mvc#6154]
Hi,

Would it be possible to have access to the Dictionary<string, object> of arguments owns by the action invoker ?

I have a custom ExceptionFilter that logs errors with given arguments. Currently, to do that, I need to  implement IActionFilter to extract context.ActionArguments.

The idea is to log arguments only when an error occured and be able to set log level above Information.
I am aware that arguments can be empty if exception occured before model binding ends.

**Comment by Eilon** [comment]
Hmm I'm guessing that after the action invoker has invoked the action method, it has no use for the parameters dictionary, so presumably it's gone by the time an exception filter might run.

The technique you're doing by saving the arguments in advance is all I can think of.

cc @rynowak in case you have thoughts?

**Comment by rynowak** [comment]
We don't provide the action arguments on `ExceptionContext` because it would most often be empty.

I'd suggest that an action filter is actually the **best** way to achieve what you want. In all of the cases where the arguments would be available (after model binding), an action filter can also see the exception.
