### ISSUE TITLE
Better action name handling for async actions

### ISSUE THREAD

**Issue by danroth27** [aspnet/Mvc#6188]
Currently we are pretty smart about removing the controller suffix from the controller name when using the `[controller]` route token. With actions we just take the method name, which is pretty annoying when you need to switch your action to be async and then decide to use the ActionNameAsync naming convention. Can we remove the "Async" suffix from the action name for routing purposes?:

Ideally these would result in the same route:

```c#
[HttpGet("[action]")
public Stuff GetStuff()

[HttpGet("[action]")
public async Task<Stuff> GetStuffAsync()
```

**Comment by rynowak** [comment]
We do this for Pages 😎 

You can also already do this with a convention. We could consider doing this with an 'in the box' convention that you can remove if you don't want it.

**Comment by Eilon** [comment]
This would of course be a breaking change (if it were on by default), but worse so, it wouldn't "break" anything per se, until you realize your actions/routes/URLs/views/whatever don't work anymore.

So, it would have been nice to do this for v1, but I fear that there's no good way to have this be the default anymore. And if it's not the default, it feels somewhat pointless, because almost no one will use it 😦
