### ISSUE TITLE
asp-for prioritizes the query string over the Model

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Mvc#6250]
Repro:
Controller with actions:
```
public IActionResult Query(string query) 
{
  return Query(new ViewModel { Query = query + " BOO!" });
}

[HttpPost]
public IActionResult Query(ViewModel model)
{
}
```

In the view, the view model type is `ViewModel` then call `<input asp-for=Query />`

Request `/Query?query=foo`

Expected:
- input with `"foo BOO!"`

Result:
- input with `"foo"`

Mitigation:
Name the view model properties differently than the query string ones.

**Comment by rynowak** [comment]
The HTML Helpers and TagHelpers are designed so that they always display form fields with the value the user submitted if possible.

Ever make a simple mistake submitting a form and have it come back blank when the server rejects the post? We use the `ModelStateDictionary`/`ViewData` for this because the value you entered my not be convertable to the model's property type.
