### ISSUE TITLE
Razor Page doesn't compile when dash/hyphen used in file name

### ISSUE THREAD

**Issue by mikebrind** [aspnet/Mvc#6296]
If you use a dash / hyphen in a Razor Page file name, the resulting page will not compile. This is because the generated type name includes invalid characters e.g _hyphen-test.cshtml_ becomes.

`public class hyphen-test_Page : global::Microsoft.AspNetCore.Mvc.RazorPages.Page`

You probably want to replace them with underscores.

**Comment by rynowak** [comment]
Thanks for reporting this, we'll get it fixed.

**Comment by mehowq** [comment]
There is still (2.1.0-preview1-007211) an issue with IntelliSense with the filenames containing dashes.

In order to reproduce:
- create a new razor page e.g. razorpagetest.cshtml
- in the code add ViewData["Title"] = "Test123";
- save and close the file
- rename razorpagetest.cshtml to razor-pagetest.cshtml
- save and close the file
- reopen the file and you will see errors on the errors list (although it build OK)
