### ISSUE TITLE
aspnetcore.mvc has dependency on the specific version of Newtonsoft.json.

### ISSUE THREAD

**Issue by sankar1204** [aspnet/Mvc#6317]
Hi,
I have a scenario where I need to use System.Web.Http v=5.2.3.0 and AspNetCore.mvc v= 1.1.2 together. 
system.Web.Http has dependency on Newtonsoft.Json v 6.0.0.0
AspNetCore.mvc has dependency on Newtonsoft.Json v 9.0.1 (Microsoft.Extensions.Configuration.Json)

which is causing  problem in Json  deserialization. Is it possible to downgrade Newtonsoft.Json v in Microsoft.Extensions.Configuration.Json or upgrade System.Web.Http to use Newtonsoft.Json v 9.0.1.

can anyone help?

**Comment by frankabbruzzese** [comment]
What is the error message you receive? A message saying that the right version was not found, or json.net doesnt work properly. If the 9.01 version is "accepted" by both libraries the problem is binary incompatibility, and can't be solved! If version is not accepted you may add directives to force version replacement in the configuration file. However, in turn, this might cause binary incompatibilities.

**Comment by Eilon** [comment]
Both should work just fine using the same higher version of NewtonSoft.Json. But, even if it doesn't, there's unfortunately not much that can be done about it.

Though, it's quite odd to see both of these libraries in the same application - mixing Web API 2.x and ASP.NET Core 1.x is unusual.
