### ISSUE TITLE
FormTagHelper asp-all-route-data does not accept RouteValueDictionary

### ISSUE THREAD

**Issue by awyl** [aspnet/Mvc#6358]
Exception:

`Cannot implicitly convert type 'Microsoft.AspNetCore.Routing.RouteValueDictionary' to 'System.Collections.Generic.IDictionary<string, string>'`

**Comment by Eilon** [comment]
`RouteValueDictionary` implements `IDictionary<string, object>`, but not `IDictionary<string, string>`, so that's what causes this error.

I believe the tag helper that processes the `asp-all-route-data` attribute specifically uses string/string so that the most common cases are supported.

If you want to pass in a `RouteValueDictionary`, you'll need to convert it to a string/string dictionary, which you could do by writing a custom extension method (or other method) that does the conversion.

E.g. something like:

```c#
    public static class MyExtensions
    {
        public static IDictionary<string, string> ToStringDictionary(this RouteValueDictionary rvd)
        {
            return rvd.ToDictionary(kvp => kvp.Key, kvp => Convert.ToString(kvp.Value, CultureInfo.InvariantCulture));
        }
    }
```

Then where you need to use it, do this:

```html
<a class="nice" asp-all-route-data="@rvd.ToStringDictionary()">Click me!</a>
```

**Comment by aqueenan** [comment]
@Eilon Could the `asp-all-route-data` tag be enhanced so that the default behaviour, when used without a value, is to provide all of the route date? I.e.:
```html
<a class="nice" asp-all-route-data>Click me!</a>
```
would be equivalent to:
```html
<a class="nice" asp-all-route-data="@rvd.ToStringDictionary()">Click me!</a>
```
