### ISSUE TITLE
Cors preflight calling action when cors attributes are absent

### ISSUE THREAD

**Issue by ItsVeryWindy** [aspnet/Mvc#6396]
I'm experiencing this issue where I have enabled cors in my startup class and have built a policy and have applied it with the EnableCors attribute on some of my classes.

On classes where I haven't used the attribute, I noticed that when doing the preflight options request it ended up calling the action instead which feels like unexpected behaviour.

**Comment by rynowak** [comment]
Is your action limiting the set of verbs it supports? Using `[HttpGet]` or similar?

**Comment by ItsVeryWindy** [comment]
Yes. Also, this only happens when the Access-Control-Request-Method on the OPTIONS request header matches what I've limited it to.

**Comment by Gerfaut** [comment]
Hi, 

I just faced the exact same problem here but no only when CORS has been setup. 
To make sure it was not due to something else in the code, I tried to reproduce it on the smallest code base possible : I created a .net core WebApi project based on the default template (``` dotnet new webapi ``` - See [core-CORS-solution.zip](https://github.com/aspnet/Mvc/files/1088381/core-CORS-solution.zip)). 

I did any CORS configuration or something. 

It gaves me the following code where I just added the Options method : 


    [Route("api/[controller]")]
    public class ValuesController : Controller
    {

        [HttpOptions]
        public IEnumerable<string> Options()
        {
            return new string[] { "options1", "options2" };
        }

        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

       ... Others methods ... 
    }


Now when I'm trying to do some requests, here are the results : 

Cross Domain call: 

    OPTIONS http://localhost:58232/api/values HTTP/1.1
    Accept-Encoding: gzip,deflate
    Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,nl;q=0.2
    Access-Control-Request-Headers: device_id,language
    Access-Control-Request-Method: GET
    Origin: http://localhost:3000
    Referer: http://localhost:3000/
    User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Result**: The Get method is hit and the return is ["value1", "value2"]. This is not correct and it should go to the OPTIONS method.

If I do a request without the ORIGIN header, then it is not interpreted as a Cross Domain call:

    OPTIONS http://localhost:58232/api/values HTTP/1.1
    Accept-Encoding: gzip,deflate
    Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,nl;q=0.2
    Access-Control-Request-Headers: device_id,language
    Access-Control-Request-Method: GET
    Referer: http://localhost:3000/
    User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.

**Result**: The Options method is hit and the return is well the body of the Options method. 

I did a .NET 4.5 (Full Framework - See [fullframework-CORS-solution.zip](https://github.com/aspnet/Mvc/files/1088380/fullframework-CORS-solution.zip)) Web API project to test the behavior and the result is not the same: both of the calls are going to the Options method. 

Those requests have been tested on Fiddler and on a HTML/JS website on an other domain (to ensure Cross Domain call).

Hope this can help a bit, 

Thank you ! 

_Gerfaut_

**Comment by Eilon** [comment]
@javiercn - can you take a look?
