### ISSUE TITLE
GetErrorMessage method of "ValidationAttributeAdapter<TAttribute>"  having incorrect if condition for string localizer

### ISSUE THREAD

**Issue by srivas-ksh** [aspnet/Mvc#6397]
hi,

We are trying to get localized the validation messages for the model. 
The below "if" condition seems to be incorrectly placed in code

```c#
if (_stringLocalizer != null &&
                !string.IsNullOrEmpty(Attribute.ErrorMessage) &&
                string.IsNullOrEmpty(Attribute.ErrorMessageResourceName) &&
                Attribute.ErrorMessageResourceType == null)
            {
                return _stringLocalizer[Attribute.ErrorMessage, arguments];
            }
```

The above condition prevents the stringlocalizer if the error message resource type and resource name are set. It doesn't looks proper check. 
Please suggest if i am missing out something.

**Comment by Eilon** [comment]
@javiercn - can you take a look? Please consult with @ryanbrandenburg as necessary.

**Comment by javiercn** [comment]
The behavior is by design. IStringLocalizer is only meant to be used in case that no resource type nor resource name has been set and in the case where the message has been explicitly defined by the user.

You should use either the Message property or the ResourceType+ResourceName combination, but not both at the same time.
