### ISSUE TITLE
ASP.NET MVC core Tag helper for GridView

### ISSUE THREAD

**Issue by VenkateshSrini** [aspnet/Mvc#6406]
Hi,
In ASP.NET MVC core we see that Data Table, Data view and data set are coming back. In ASP.NET web forms world we use to bind the data table directly to Data grid. The table column names are inferred from the Data Table column names. 

The same scenario can happen in case of Razor pages also. So the ask is Can we have a built TagHelper (like form taghelper ect:-) for Grid View also that will function like data grid. This will help easy migration of Web form application to Razor Pages very easily.

**Comment by Eilon** [comment]
Hi @VenkateshSrini , there's nothing currently built in for that, but there are some really cool tag helpers from other vendors that offer rich functionality, such as these: http://ultimate.grapecity.com/Studio/Platform/MVC

**Comment by VenkateshSrini** [comment]
No. The flexgrid does not address my requirements of getting column name
from data table. If there are any such tagHelper that does this please let
me know.

**Comment by frankabbruzzese** [comment]
@VenkateshSrini, what do you mean with "getting column name from data table"?
If you mean that the grid connects directly with a DB through connection string and get both metadata and data this way, you'll not find any grid that works this way, for the simple reason that a similar behavior would break MVC paradigm.

On the other side if you want the grid take column names from property metadata of a C# class (the class of the items in the IEnumerable being rendered by the grid), then you may try Mvc Controls Toolkit Core grid see. It has both [query](http://examples.aspnetcore.mvc-controls.com/Food) and [edit ](http://examples.aspnetcore.mvc-controls.com/Grids/AjaxServerQuery)capabilities.

**Comment by VenkateshSrini** [comment]
@frankabbruzzese ,
I still see that the column definition is provided in the cshtml. In case of binding to Data Table what happens is the grid dynamically gets the column  name and type from the data table. This data table itself would   be dynamic and filled from SQLAdapter class. I think since these features are coming with .NET 2.0 This version of MV control tool kit might not suit my needs. Or Iam I missing something ?

Will I have to do some customization ?

**Comment by frankabbruzzese** [comment]
@VenkateshSrini, no! Column names are not written in views (you may overrite them here but you are not required to do it)  but their are extracted from the data classes passed to the grid. For instance, you may pass an IEnumerable of Product class instances to the view, in which case column names correspond either to the name of the properties of the Product class or to strings passed in a DisplayAttribute that decorates  properties: this is a standrad in Asp.net Mvc..

However, columns ARE NOT EXTRACTED directly from the database with an SQLAdapter or with any other interface, for the simple reason that, according to the MVC paradigm, Views can take data that just from controllers (or ViewComponents) NOT directly from the data layer.

Separation of application in layers increases modularity and maintenaibility of applications. That's why I think you will not find a similar grid for asp.net mvc. 
You can't migrate from web forms keeping the same application organization and architecture, you need to reorganize it.

Dynamic columns that adapts to any change one might perform on a DB might appear attracting, but as a matter of fact, this way you can't customize specific columns (their size, position, etc.), so your level of control on the grid appearence is very low. This is the reason why applications must be layered: each layer is responsible for something. View are responsible for appearence while darta layer is responsible for extracting data from DB. Views exists to let you cutomize the appearence of data so any control or tag helper must give you this opportunity, but if columns change dynamically you miss this opportunity and you are forced to display all columns with a standard algorithm.

**Comment by VenkateshSrini** [comment]
@frankabbruzzese,
I totally understand the separation of concerns that you are stating. My question is if the MVC grid controller has to dynamically read schema not from a IENumeration of strongly defined object like Student or schema, but more from a IEnumerable of DataRow, will that be possible. I think not as of today because DataTable and Data Row are coming to full action only in .NET core 2.0 version. So my ask is there a tag helper which can make his happen. 

In the end whether it is a MVC control toolkit or TagHelper HTML tables are going to be rendered. So which way should we go?
1) Write a custom tag helper that will read IENumerable<DataRow> and create the columns
2) Customize the MVC control toolkit  core to read from iEnumerable<DataRow>

**Comment by frankabbruzzese** [comment]
@VenkateshSrini, I don't think you'll find an out-of-the-box solution. If you don't need grid faetures like element editing or filter/sorting you may implement yourself the grid either as a new tag helper or simply as a ViewComponent. On the controller side you should assemble  an `IEnumerable<IEnumerable<NameValue>>` Where NameValue is a struct containin the column name and the column value. Then two nested for cycle might render all rows and then all columns. A preprocessing to extract all column headers is necessary. However, if data contains 0 rows you have no information to write the column headers.

Another solution that might allow more advanced grid features, would be using a JavaScript grid that receives data in Json Format. Most of Javascript grids, if no column information is available extracts column headers from the property names of the JavaScript objects. Thus, onthe controller side you might assemble Json manually with the name/value pair you have. However, if you allow grid to send you queries, such as filtering on a property name you should be able to assemble somehow the sql query to retrieve that data from the dymamic values received.

**Comment by VenkateshSrini** [comment]
Nice! What does it take to customize the MVC core toolkit to this requirement ?

**Comment by hishamco** [comment]
@VenkateshSrini nothing will stop you to implement such tag helper, the only thing is limited if you wanna use data binding expression, because you need sort of variable that hold the current row

**Comment by VenkateshSrini** [comment]
Hi,

Thanks for all your suggestion. I'm looking at the option of customizing
the MVC core tool kit based on .NET core 2.0 Preview 2

**Comment by frankabbruzzese** [comment]
@VenkateshSrini ,
A new .Ne 2.0 optimized version of the Mvc Controls Toolkit will be avaliable after ,Net 2.0 RTM. We wiil provide dynamic detail forms form based (ie rendering a single dynamic record made of name/value/metadata columns). 
However, at moment we have no plan supporting dynamic grids. The reason is that, a similar grid can't have usual grid facilities. For instance it can't have OData queries support since OData queries require a pre-existing data schema to be parsed. The same would be true for any custom query representation.

The point here, is that, if you want to do anything not trivial the grid MUST extract directly metadata from the db, and this would break separation of concerns and would make the grid dependent from db stauffs which is not acceptable.

On the other side if you just need a table with column headers you may implement it with a ViewComponent. Each row of grid data will be an IEnumerable of name/value pairs, so your data wil be an IEnumerable of IEnumerables of Name/Value pairs. 

Just loop through the first row to extract the column names, so that you may write the table thead with all column names. Then loop trough your data with 2 nested  loops. The outer loop will render all rows, while the inner loop will write all column values in a row. 

If you want you may implement this with an Mvc Controls Toolkit component to take advantage of its templating engine. However, you must familiarize with the toolkit befor you will be able to design a new component. In any case, this would't enable you to have queries and several stuffs a grid usually have.

**Comment by frankabbruzzese** [comment]
@VenkateshSrini , anyway if you come with some new ideas/proposals you may post them either on the appriopriate Mvc Controls Toolkit repository (whose list is [here](https://github.com/MvcControlsToolkit)), or in the [Home repository](https://github.com/MvcControlsToolkit/Home).

**Comment by Eilon** [comment]
Moving this to discussions because there aren't any current plans to have this built-in.

cc @DamianEdwards FYI.

**Comment by mkArtakMSFT** [comment]
We're closing this issue as there are no any plans to support this in the near future.
