### ISSUE TITLE
Use a generic type as a TagHelper

### ISSUE THREAD

**Issue by DDoSolitary** [aspnet/Mvc#6513]
``` C#
@addTagHelper SomeTagHelper<SomeType>, SomeAssembly
```

``` C#
public class SomeTagHelper<T> : TagHelper
{
	public override void Process(TagHelperContext context, TagHelperOutput output)
	{
		// Do something
	}
}
```

Is it possible to do something like the above code snippet does?

**Comment by rynowak** [comment]
No, this is no supported today

**Comment by DDoSolitary** [comment]
Is there a way to implement something that has similar functionality?
And is there any plans for this?
Thanks.

**Comment by rynowak** [comment]
> Is there a way to implement something that has similar functionality?

We need more detail about what you're actually trying to accomplish to be able to answer that question. 

You could do something close by doing this:
```
public class MyTagHelper<T> : TagHelper
{
  // put your implementation here
}

public class MyFooTagHelper : MyTagHelper<Foo>
{
  // A thin wrapper to make it callable by tag helpers
}
```

> And is there any plans for this?

There is no planned work to enable this. If you can explain why this is important then that will help us figure out i

**Comment by DDoSolitary** [comment]
Thank you for your information. The code you provided does work in my scenario.

> There is no planned work to enable this...

I think it isn't an important feature, too. 😄 I just think that it'll be good if it is implemented.

Just close this issue if you think it isn't needed.

**Comment by dougbu** [comment]
We have no plans in this area.

**Comment by cmxl** [comment]
I do think this is an important feature.
We want one single taghelper for generic models that we pass via a taghelper attribute.
it is not practical to inherit from the generic taghelper for every single model we pass to the view.
also there would be a new taghelper name for every model.

**Comment by dougbu** [comment]
**@cmxl Hi, it looks like you are posting on a closed issue/PR/commit!**

We're very likely to lose track of your bug/feedback/question unless you:
1. Open a new issue
2. Explain very clearly what you need help with
3. If you think you have found a bug, include detailed repro steps so that we can investigate the problem

In addition, please note that tag helpers can handle any model type already. Exposing `ModelExpression` properties takes care of that e.g. have a look at how the [`InputTagHelper`](https://github.com/aspnet/Mvc/blob/cbe152676305cd9a70be5998fcf301ab13d3ccf4/src/Microsoft.AspNetCore.Mvc.TagHelpers/InputTagHelper.cs) is implemented.
