### ISSUE TITLE
Add support for backing properties on activated types with View Data via a [ViewData] attribute

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Mvc#6525]
Basically, we should have an equivalent of the `TempData` attribute, but backed by `ViewData`, so that it's super easy to share data between different model class instances, e.g. from a `PageModel` to the declared model of a partial view. This would allow for easily passing typed data from a controller or `PageModel` to a partial invoked from a Layout page, without having to manually set and retrieve the data via the `ViewData` dictionary.

The attribute should be supported on the properties of classes for:
- Page Models
- Controllers
- View Components
- Partial models

**Comment by mkArtakMSFT** [comment]
Moving this further to 2.1.0-preview2 milestone. FYI, @DamianEdwards

**Comment by pranavkm** [comment]
Some questions \ notes from my design PR:

1.  `TempDataAttribute` - was there a reason we chose to prefix the keys for this with `TempData-`? For `ViewData-`, it feels like we could get away with not prefixing it. It does make some interesting easier to do (listed below)

2 `asp-viewdata-` dictionary prefix for  `PartialTagHelper`
Passing ViewData values to a partial via `ViewDataAttribute` is hard to make work (for us) and doesn't look nice (for users):
```C#
// Index.cshtml
@functions {
    [ViewData]
    public string SomeProperty { get; set; }
}
@{ SomeProperty = DateTime.UtcNow; }

<partial name="_MyPartial" />
```

We could instead have add à la `asp-route-` thing<sup>[1]</sup>:

```C#
// Index.cshtml
<partial name="_MyPartial" asp-viewdata-SomeProperty="DateTime.UtcNow" />
```

This works nicely with the not having a prefix-bit, since the partial would just do:
    
```C#
// _MyPartial.cshtml
@functions {
    [ViewData]
    public DateTime SomeProperty { get; set; }
}
```

3. We should consider adding some directive(s) to Razor (cc @davidfowl) that makes authoring the view much nicer:
```C#
// _MyPartial.cshtml
@viewdataproperty DateTime SomeProperty
```

We could also consider adding a directive that defaults to producing string properties. It makes writing some boiler plate code more terse e.g.

```C#
// Index.cshtml
@viewdata Title "Home Page" 

// which generates
@functions {
    [ViewData]
    public string Title { get; set; } = "Home Page"
}
```

And can be consumed like so:
```C#
// _Layout.cshtml
<title>@ViewData["Title"]</title>

// or
 
// _Layout.cshtml
@viewdata Title
<title>@Title</title>
```
------------------------------------------

Notes:
[1] - I'm a bit of a noob here - how do you pass a literal value to this? Like a string?

**Comment by pranavkm** [comment]
Filed https://github.com/aspnet/Mvc/issues/7409 to track design of `@viewdata` directive. For 2.1.0, `ViewData` annotated properties that are set in controllers or pages, can be looked up by their names in `ViewData` i.e. this works:

```C#
// HomeController.cs
[ViewData]
public string Name { get; set; }

// Index.cshtml
@ViewData["Name"]
```

Making this work in partial model is difficult - primarily because Mvc does not manage own their life cycles today. @DamianEdwards wanted us to consider ways to make this work, not to pass values directly to a partial, but to have values set in a controller pipe through to a partial model type

```C#
// HomeController.cs
[ViewData]
public string Name { get; set; }

// PartialModel.cs
public string Name { get; set; } < This gets set to the controller value.
```

One possible solution to this might be to have a proxy type that wraps over the correct Vdd instance, so that all reads and writes to it end up being pass through to the correct Vdd e.g. `public ViewDataProperty<string> Name { get; set; }` where `ViewDataProperty` is contextualized to the current view's ViewData. This might also be useful as the backing type when we implement https://github.com/aspnet/Mvc/issues/7409.
