### ISSUE TITLE
Action results pattern

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Mvc#657]
Examples:

`JsonResult` allow status code on JsonResult.

`RedirectResult` exposes the url but doesn't let you change it.

Also `redirectresult` eagerly resolves UrlHelper just to find out if a Url is local (which means a service is resolved on every call unnecessarily).

See:
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNet.Mvc.Core/ActionResults/RedirectResult.cs#L35

Suggested pattern: Every result exposes properties as get set, so results filters can modify them and observe the values. 

Services are resolved on a per needed basis, and not eagerly.

Static things like IsLocalUrl are not done as Transient services, they can either be static methods or Singleton services.

**Comment by rynowak** [comment]
Doing a pass and cleaning this up things that should be true in general.

**Properties are get/set by default**
- Some require a not-null value (`FileStreamResult`)
- Services needed by the result are get/set and default to null. They are resolved inside `Execute`

Exception to this is `HttpStatusCodeResult` and derived classes. Since all this class does is set a status code, it's not get/set. Then you can't end up with an `NotFoundResult(201)` or other nonsense.

Adding a `StatusCode` property to the more complex result types where it makes sense. (`ViewResult`, `ContentResult`, but not `FileResult`).

**Comment by rynowak** [comment]
692a07240c34ee12c317eddb7cc28d744818b02d
