### ISSUE TITLE
ViewModel parameter with the same name as the action does not receive the data

### ISSUE THREAD

**Issue by AndreuCodina** [aspnet/Mvc#6599]
When you have an action and a parameter which is a class (a ViewModel, for example) with the same name, the action doesn't receive the data unless you send the data with a hack.

I am going to show it with an example.
My example consists of users who can comment publications with the Publication controller and the **Comment** action, and the action has a parameter which is of type CommentViewModel, and its name is **comment** (the same name).

**PublicationsController.cs**
```
[Produces("application/json")]
[Route("api/[controller]/[action]")]
public class PublicationsController : Controller
{
    [HttpGet]
    public IActionResult Comment(CommentViewModel comment)
    {
        if (ModelState.IsValid)
        {
            return Ok();
        }
        else
        {
            return BadRequest();
        }
    }
}
```

**CommentViewModel.cs**
```
public class CommentViewModel
{
    [Required]
    public string Author { get; set; }

    [Required]
    public string Comment { get; set; }

    [Required]
    public int PublicationId { get; set; }
}
```

If you send the query correctly:
http://localhost:56740/api/publications/comment?author=Andreu&comment=Hellooo&publicationId=4

You don't receive the data:
![comment](https://user-images.githubusercontent.com/30506301/28719709-310609b2-73ab-11e7-9f13-29761e8f946d.png)

If you send the query with the name of the parameter (comment) with a dot before, you receive the data. For this example, you must write "comment." before "author":
http://localhost:56740/api/publications/comment?comment.author=Andreu&comment=Hellooo&publicationId=4
![commentdotproperty](https://user-images.githubusercontent.com/30506301/28719716-3c8eb0a4-73ab-11e7-8fd8-67b7609c446c.png)

Besides, if you send, for example, a string (which is a class too), with the same name as before (comment), you receive the data:
`public IActionResult Comment(string comment)`

Or if you use another name for the parameter, you receive the data as well:
`public IActionResult Comment(CommentViewModel comm)`

The example can be downloaded here: https://github.com/AndreuCodina/ViewModelParameterPossibleBug

**Comment by Eilon** [comment]
cc @rynowak @dougbu 

Yes, this is a tricky case because MVC by default doesn't know whether to use the `comment.` prefix for the sub-properties are not. In the case of your model type, in theory you could either post (`author`, `comment`, `publicationid`) (no prefix), or (`comment.author`, `comment.comment`, `comment.publicationid`) (with prefix). MVC tries to use one and then the other, and once it decides whether to use a prefix, it uses (or doesn't use) it for the entire model object.

I believe you can explicitly set this behavior by applying the `[Bind(Prefix = "comment")]` attribute to your `CommentViewModel comment` parameter like so:

```c#
    public IActionResult Comment([Bind(Prefix = "comment")] CommentViewModel comment)
```

And that will force MVC to always use that prefix.

**Comment by dougbu** [comment]
@AndreuCodina the ambiguity here is between the `Comment` property and the `comment` parameter name. Because the parameter name matches an available value, MVC goes down the "use the `comment` prefix" path.

All of @Eilon's suggestions will avoid the confusion, as would renaming the `Comment` property or the `comment` parameter name.

**Comment by pranavkm** [comment]
Dup of https://github.com/aspnet/Mvc/issues/3735. The plan of action is to add an analyzer to cover this - https://github.com/aspnet/Mvc/issues/7753
