### ISSUE TITLE
AuthorizeFolder should be more general purpose

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Mvc#6630]
Seems like AuthorizeFolder should be made into a more general purpose "apply this auth scheme to this route/route prefix". Is there any fundamental reason it needs to be tied to razor pages instead of routing? I'm thinking something like:

```
// Anything under api is gets [Authorize(AuthenticationSchemes = "Bearer")] by default
options.AuthorizeRoutePrefix("api", scheme: "Bearer");

// Anything under "admin" gets [Authorize("MyAdminPolicy")]
options.AuthorizeRoute("admin", policyName: "MyAdminPolicy");
```

/cc @rynowak @DamianEdwards

**Comment by rynowak** [comment]
It could be applied to anything that uses attribute routing. I think it's more trouble than it's worth since it doesn't apply to conventional routing.

We should just build a fluent API for conventions in general.

**Comment by Eilon** [comment]
In general we've avoided placing too many semantics on routes (such as authorization policies) because with conventional routes there can be more than one route that goes to a given controller/action. However, with attribute routes the story is different because they tend to act more exclusively (you can have more than one attribute route, but they are explicit).

**Comment by Eilon** [comment]
Adding a fluent API for conventions sounds like an interesting area to investigate. Shall we log a new bug for that to see what scenarios we'd want to cover?

**Comment by rynowak** [comment]
Sounds great

**Comment by Eilon** [comment]
Closing because I logged https://github.com/aspnet/Mvc/issues/6682.
