### ISSUE TITLE
@page directive should show an error if it's not first in file

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6633]
_From @pakrym on July 19, 2017 18:58_

Or user would just get 404 trying to run it

_Copied from original issue: aspnet/Razor#1569_

**Comment by pranavkm** [comment]
Spoke to @NTaylorMullen offline and I hadn't fully understood how `ParseLeadingDirectives` works. It stops after parsing the first directive (which is totally not what the name indicates). If we do make the API robust enough to allow parsing more than one leading directive, would we allow the file to be a "Razor Page" at that point e.g. would we consider the following file to be a valid Razor Page?

```
@model TestModel
@inject IService MyService
@page
...
```

My guess is no since this would be a breaking behavioral change. We currently log malformed `@page` directives as warnings to the log. Would we give this a similar treatment error \ warnings to the log or would we throw?

**Comment by rynowak** [comment]
This suggestion is about the editing experience. If you get squiggles in the editor then you know it's wrong.

**Comment by pranavkm** [comment]
Gotcha. I assumed you wanted a runtime error since you moved it from Razor to here.

**Comment by ardalis** [comment]
Just ran into this with a client. Links to page weren't being built, and direct access resulted in 404. Took 15 minutes to realize this was the issue:

```
@using Some.Namespace;
@page
```
Either a tooling squiggle or a runtime error or both would be appreciated.

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, how easy will this be to accomplish?

**Comment by NTaylorMullen** [comment]
@mkArtakMSFT depends on how thorough we want to be. If we're ok on relying on generating Razor output on build then this wouldn't be too rough. If we're not ok with that then we'll have a bit of work on our hands to make our leading directive parser continue parsing until it hits non-directive content (lots of work).

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, what should the user experience be here? There are essentially two scenarios here:

**Comment by mkArtakMSFT** [comment]
From @NTaylorMullen: We're going to only do build time for the first iteration. If we find a need to also do runtime compilation in the future we'll review this then.

**Comment by ajaybhargavb** [comment]
a7178a66bd9b58e24ae0df36f80b71da44058a6f
