### ISSUE TITLE
Nested reference can be accessible from Dotnet core 1.0.0

### ISSUE THREAD

**Issue by ndeen86** [aspnet/Mvc#6635]
I have created Business and DataAccess Layer for my web project using dotnet core. I have added Data access reference in Business layer and referenced the business layer in UI (web) project.

> I noticed, I am able to access my Data access layer from my UI (web) project.
![referenceissue](https://user-images.githubusercontent.com/21333556/29084399-7a8b5ab8-7c31-11e7-85a4-e319b8004ac3.PNG)

 But My web has reference only with Business layer project. My Business layer only has the Data access. Can someone suggest me how restrict access nested reference.

**Comment by Eilon** [comment]
The only way to actually restrict access is to make the types `internal`, and then use the assembly-level `InternalsVisibleTo` attribute to restrict access.

However, this is not something I recommend.

Instead I recommend using appropriate abstractions such as exposing things via interfaces (contracts), and using dependency injection in Startup to associate the contracts with implementations. Beyond that, make sure all code is reviewed.

Because this is not an MVC-specific product question or bug, I highly recommend asking this on a site such as https://stackoverflow.com/ or https://softwareengineering.stackexchange.com/.
