### ISSUE TITLE
Label for prop with empty DisplayName renders without for-attribute

### ISSUE THREAD

**Issue by tlycken** [aspnet/Mvc#6638]
Given the following view model

```
public class MyViewModel
{
    [DisplayName("")]
    public bool MyProperty { get; set; }
}
```

and the following view

```
@model MyViewModel

<input type="checkbox" asp-for="MyProperty" />
<label asp-for="MyProperty></label>
```

the rendered markup for the label is

```
<label></label>
```

and not, as I had expected,

```
<label for="MyProperty"></label>
```

Is this an intentional decision, or a bug?

I can circumvent it by specifying `[DisplayName(" ")]` (i.e. a space, and not an empty string) but it feels hacky...

**Comment by dougbu** [comment]
@tlycken I agree this looks odd. `[DisplayName("")]` is a strange corner case and it seems we haven't tested its use in combination with all tag and HTML helpers.

FYI to __Triage__ team: Fix is to remove the short-circuit at [line 424 of `DefaultHtmlGenerator`](https://github.com/aspnet/Mvc/blob/eb5c23ea8e3542fe537ffef8ca419a315b60dbbb/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L424) and instead make the call [here](https://github.com/aspnet/Mvc/blob/eb5c23ea8e3542fe537ffef8ca419a315b60dbbb/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L431) conditional. May need to add a special case for when `fullName` is `null` or empty because that's a supported case (even though other tag and HTML helpers will `throw` then).

**Comment by tlycken** [comment]
Just for information and context:

My use case here is styling checkboxes; by setting `input[type=checkbox] { visibility: hidden; }` and styling the label I can achieve things like [this](https://codepen.io/bbodine1/pen/novBm), but that only works if the label is linked with the checkbox, so that clicking the label changes the checked-state of the checkbox.

**Comment by Eilon** [comment]
@dougbu I agree with removing the short-circuit, it's plain wrong. But why make this conditional:
https://github.com/aspnet/Mvc/blob/eb5c23ea8e3542fe537ffef8ca419a315b60dbbb/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L431
?

**Comment by Eilon** [comment]
Oh, is it to prevent clearing out any explicit text that was already in the CSHTML markup? If so that sounds fine.

**Comment by dougbu** [comment]
> is it to prevent clearing out any explicit text that was already in the CSHTML markup?

No, my recommendation to conditionalize [line 431](https://github.com/aspnet/Mvc/blob/eb5c23ea8e3542fe537ffef8ca419a315b60dbbb/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L431) was incorrect. The existing text case is handled at [line 70 of `LabelTagHelper`](https://github.com/aspnet/Mvc/blob/5fee1cac83d5e41a3027a7f30d87764e18850c54/src/Microsoft.AspNetCore.Mvc.TagHelpers/LabelTagHelper.cs#L70).

[line 424 of `DefaultHtmlGenerator`](https://github.com/aspnet/Mvc/blob/eb5c23ea8e3542fe537ffef8ca419a315b60dbbb/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L424) short-circuits the method in an attempt to avoid generating a uselessly-empty `<label>`. Put another way, the condition always makes sense for `Html.Label(...)` and `Html.LabelFor(...)` but is wrong if the `<label>` tag helper already has content.

We should instead move the current [line 424]((https://github.com/aspnet/Mvc/blob/eb5c23ea8e3542fe537ffef8ca419a315b60dbbb/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/DefaultHtmlGenerator.cs#L424)) condition from `DefaultHtmlGenerator.GenerateLabel()` up into its callers. `LabelTagHelper` might for example suppress output if the returned `TagBuilder` has no content (`!HasInnerHtml`) and the child content is useless (`IsEmptyOrWhiteSpace`). The HTML helpers will be simpler.

> `LabelTagHelper` might for example suppress output if the returned `TagBuilder` has no content (`!HasInnerHtml`) and the child content is useless (`IsEmptyOrWhiteSpace`).

@tlycken do you prefer we completely remove the condition? You mention expecting `<label for="MyProperty"></label>` for your case. But, is no output at all actually better?

**Comment by dougbu** [comment]
Separately, HTML and tag helpers will already avoid `<label for="">My name</label>`. Instead, the more-correct `<label>My name</label>` is output. No need for anything more in `GenerateLabel()`.

See condition [here](https://github.com/aspnet/Mvc/blob/5fee1cac83d5e41a3027a7f30d87764e18850c54/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Rendering/TagBuilder.cs#L232-L233):
``` c#
    if (string.Equals(key, "id", StringComparison.OrdinalIgnoreCase) &&
        string.IsNullOrEmpty(attribute.Value))
```

**Comment by Eilon** [comment]
@dougbu that's a bit of an information overload for me. What observable changes are you proposing to make? I.e. in what conditions will results be different, and how?

**Comment by dougbu** [comment]
Sorry.

For cases where the generated `<label>` content would be empty e.g. because `MyProperty` has an associated `[DisplayName("")]`:
1. In the original description's case of `<label asp-for="MyProperty></label>`, generate nothing at all.
2. Also no-op in the similar `Html.Label("MyProperty")` case.
3. But, generate `<label for="MyProperty">My name</label>` if the .cshtml contains `<label asp-for="MyProperty>My name</label>`.

The question I asked @tlycken is general because I'm unsure avoiding a "useless" `<label>` makes much sense e.g. the element might be useful to JavaScript. If others feels we're being too prescriptive here, could instead remove the condition completely and generate the following for the above cases:
1. `<label for="MyProperty"></label>` 
2. `<label for="MyProperty"></label>` 
3. `<label for="MyProperty">My name</label>` -- the same behaviour as above.

Current behaviour is
1. `<label></label>` i.e. the tag helper removes `asp-for` but doesn't suppress the output or add the `for` attribute.
2. HTML helper generates nothing
3. `<label>My name</label>` i.e. the tag helper does not add the `for` attribute though it has the needed information.

**Comment by dougbu** [comment]
My first suggestion changes the behaviour when using the `<label>` tag helper but not for the HTML helper. The alternative changes what both HTML and tag helpers generate.

**Comment by tlycken** [comment]
@dougbu I _think_ you've already suggested behavior that works for me, but just to clarify and explicitly answer your question, my expectations would be the following:

1.  **Omitting a tag I've explicitly asked for is really unhelpful.** If there is a `<label>` or `Html.LabelFor()` on the view, a `<label>` is _always_ rendered. If there is a link to a model property (using `asp-for` or a lambda expression), the rendered label _always_ has a `for` attribute pointing to that property.

2. The content is decided according to the following priorities:
    1. Hard-coded content:
        `<label asp-for="MyProperty">something something</label>` and
        `Html.LabelFor(m => m.MyProperty, "something something")` both always render
        `<label for="MyProperty">something something</label>`.

        Additionally, the tag helper ignores whitespace, while the html helper doesn't:  
        `Html.LabelFor(m => m.MyProperty, "")` always renders an empty `<label>` tag, while
      `<label asp-for="MyProperty">            </label>` is treated the same as
      `<label asp-for="MyProperty"></label>` and gets its content from ii or iii.

      2. `[DisplayName]`: If the content was not already specified by i., and there is a `[DisplayName]` attribute, the content of the label will be set by the `[DisplayName]` attribute, even if it means the content will be empty.

      3. If none of i. and ii. yield a content specification for the label, the content is determined by the property name (with the same defaults as today) so that
      `<label asp-for="MyProperty"></label>` renders as 
      `<label for="MyProperty">MyProperty</label>` etc.

I hope this clarifies what I'm asking for.

**Comment by dougbu** [comment]
> __Omitting a tag I've explicitly asked for is really unhelpful.__

I filed #6668 about one case where we currently suppress output.

> I hope this clarifies what I'm asking for.

Absolutely. You much prefer my second suggestion, never suppressing output from the `<label>` tag helper.

> Additionally, the tag helper ignores whitespace, while the html helper doesn't:
`Html.LabelFor(m => m.MyProperty, "")` always renders an empty `<label>` tag, while
`<label asp-for="MyProperty">            </label>` is treated the same as
`<label asp-for="MyProperty"></label>` and gets its content from ii or iii.

The specific inconsistency between HTML and tag helpers you've described here makes sense. The user who typed `Html.LabelFor(m => m.MyProperty, "")` explicitly passed the label text and MVC honours that request. On the other hand
``` html
  <label asp-for="MyProperty">
  </label>
```
is nowhere near as explicit.

We could add an `asp-use-whitespace-content="true"` attribute but I'm not sure it's worthwhile. You can get that by avoiding the tag helper:
``` html
  <label for="@Html.IdFor(m => m.MyProperty)">
  </label>
```

**Comment by dougbu** [comment]
Side note: Did you mean `Html.LabelFor(m => m.MyProperty, "")` or `Html.LabelFor(m => m.MyProperty, " ")` @tlycken? In 2.0.0 and later at least, the first (with an empty `labelText` argument) outputs nothing while the second generates a `<label>` containing the specified whitespace.

**Comment by dougbu** [comment]
Additional note: I'm fine with generating `<label for="MyProperty"></label>` for `Html.LabelFor(m => m.MyProperty, string.Empty)`. I'm also fine with changing the `Html.Label(...)` and `Html.LabelFor(...)` behaviour in the `[DisplayName("")]` case. All amount to an explicit request for an empty `<label>`.

Admittedly, there's a lot of HTML helper history and these two helpers are consistent with other HTML helpers w.r.t. generating nothing in some cases. But, explicit user request trumps that consistency as well as back-compatibility -- especially since these cases are rather narrow.

**Comment by dougbu** [comment]
Updated and reordered cases are:
1. (OD) `<label asp-for="MyProperty></label>` and `MyProperty` has an associated `[DisplayName("")]` (or `[Display(Name="")]`)
2. `<label asp-for="MyProperty>My name</label>` and `MyProperty` has an associated `[DisplayName("")]`
3. `Html.Label("MyProperty")` / `Html.LabelFor(m => m.MyProperty)` and `MyProperty` has an associated `[DisplayName("")]`
4. `Html.Label("MyProperty", string.Empty)` / `Html.Label("MyProperty", string.Empty)`
    - attributes on `MyProperty` are not relevant here

Current behaviour is
1. `<label></label>` i.e. the tag helper removes `asp-for` but doesn't suppress the output nor add the `for` attribute
2. `<label>My name</label>` i.e. the tag helper removes `asp-for` but does not add the `for` attribute though it has the needed information
3. HTML helper generates nothing
4. HTML helper generates nothing

Suggested behaviour:
1. `<label for="MyProperty"></label>` 
2. `<label for="MyProperty">My name</label>`
3. `<label for="MyProperty"></label>` 
4. `<label for="MyProperty"></label>` 

I am not suggesting changes to the `Html.Label("MyProperty", "{whitespace}")` behaviour. Nor am I suggesting the `<label asp-for="MyProperty">{whitespace}</label>` behaviour should change (unless `MyProperty` has an empty name as described in 1. and 2. above).

**Comment by dougbu** [comment]
@Eilon / @DamianEdwards any objection to the changes I proposed [just above](https://github.com/aspnet/Mvc/issues/6638#issuecomment-322857027)?

**Comment by DamianEdwards** [comment]
👍

**Comment by dougbu** [comment]
Realized there's a special case where the HTML helpers would go from not generating anything to spitting out `<label for=""></label>` which is both invalid (see #6728) and useless. Decided to maintain the "not generating anything" behaviour for back-compatiblity.

This is specific to `HtmlHelper.LabelForModel()` or similar in a top-level view. So, we'll maintain compatibility in a corner case. (A corner case that tests exercised much more than the cases discussed above ☹️.)

**Comment by Eilon** [comment]
Sounds good to me.

**Comment by dougbu** [comment]
8645ada
