### ISSUE TITLE
No way to route for RazorPages?

### ISSUE THREAD

**Issue by HolyOne** [aspnet/Mvc#6671]
Hello,
I either couldnt find any documentation to route asp.net Core Razor Pages or there is none.

I tried app.UseRouting but it only gives me access to httpcontext
I tried MVC.routing
I tried attribute on PageModel (cshtml' s code files)

but could not achieve something like  /{lang}/{Page}  (Having page route to the cshtml file with lang parameter)

**Comment by pranavkm** [comment]
We're planning on adding support for attribute routes for Razor Pages as part of 2.1.0. See https://github.com/aspnet/Mvc/issues/6605. For the 2.0.0 release, you should be able to use `AddPageRoute` (https://github.com/aspnet/Mvc/blob/e09a0f5b7c4d60f65850761dc0fdf77fc600746d/test/WebSites/RazorPagesWebSite/Startup.cs#L22) to do this.

**Comment by HolyOne** [comment]
Yeah I could achive that but it only routes for a single page

 what I am trying to do is generating a route for every page in the solution like
 options.Conventions.AddPageRoute("/{page}", "{language}/{page}");

**Comment by pranavkm** [comment]
You can register a `IPageRouteModelConvention` which does this. Something along the lines of

```C#
public class LanguagePageRouteModelConvention : IPageRouteModelConvention
{
   public void Apply(PageRouteModel model)
   {
        var selectorCount = model.Selectors.Count;
        for (var i =0; i < selectorCount; i++)
        {
            var selector = model.Selectors[i];
            model.Selectors.Add(new SelectorModel
            {
                AttributeRouteModel = new AttributeRouteModel
                {
                    Template = AttributeRouteModel.CombineTemplates("{language}", selector.AttributeRouteModel.Template),
                }
            });
        }
   }
}

// In Startup
options.Conventions.Add(new LanguagePageRouteModelConvention());
```

**Comment by Eilon** [comment]
Closing because we'll cover this in https://github.com/aspnet/Mvc/issues/6605.

**Comment by guardrex** [comment]
@HolyOne I'm working on some documentation that includes the feature that @pranavkm described. May I ask a question about your app's layout?

If one were routing to separate folders of localized pages where the folder name *is* the language ...

* *Pages* folder
   * *en-us* folder
      * page1.cshtml (en-US)
      * page2.cshtml (en-US)
   * *en-au* folder
      * page1.cshtml (en-AU)
      * page2.cshtml (en-AU)

... then the folder structure itself automatically provides routing for those pages, so `/en-us/page1` would route correctly and `/en-au/page1` would route correctly. There would be no need to setup a new convention.

Therefore, I imagine that your pages don't sit inside your solution that way. I was wondering if you could explain a bit more about your scenario that required the added convention in order to meet your needs?

**Comment by HolyOne** [comment]
Yes this kind of folder structure would solve the problem but it is very bad design.

If I have 10 languages, and I want to include some image or text, I would need to open and modify html of each one.

Language support is the worst part of .net technologies. Resource localization is a nightmare in all project types but I should open another Issue for that.

**Comment by guardrex** [comment]
@HolyOne Ok, thanks. I just wanted to make sure I wasn't missing something there. The topics I'm working on for Razor Pages deal extensively with the conventions for controlling routing, so that's why I was curious. For the image and text issues, I think/hope [ordinary localization approaches](https://docs.microsoft.com/aspnet/core/fundamentals/localization) work ... I haven't had to implement localization yet in a web app ... just Xam apps. Thanks again.
