### ISSUE TITLE
Razor Pages support ASP.Net server controls or have server controls?

### ISSUE THREAD

**Issue by ghd258** [aspnet/Mvc#6683]
The MVC programming model to his advantage, but there are also disadvantages, page data and logic processing mainly by JS control, C# is only to the front-end data transfer function, the C# instead of weakening, the enhanced JS and web; from ASPX, aspx.cs aspx.cs played this way with powerful back-end processing capabilities of C#, not only can provide data, but also can process the front interface with C# display or logical processing; hope to use the Razor Pages Cs, play the powerful function of C#

**Comment by frankabbruzzese** [comment]
Since from the beginning, Asp.net Mvc provided substitutes to WebForm server controls: Html helpers, and now tag helpers. You may use them to implement any kind of "server control", with the only constraint to conform to Mvc paradigm, and application layering, i.e. "controls" deals with ViewModels, while access to DB must be dealt with in different modules for better reusability.

However you may implement also standard DB access modules, standrad controllers that implement specific protocols, and so on...

**Comment by hishamco** [comment]
This is a duplicate for the issue https://github.com/aspnet/Home/issues/2142

**Comment by Eilon** [comment]
Razor Pages has a feature called Tag Helpers, which have some similarities to Web Forms server controls, though they are also different in many significant ways.

You can read more about tag helpers here: https://docs.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/intro

**Comment by hishamco** [comment]
Also you can have a look to my blog post [Razor Pages Commands & Events](http://hishambinateya.com/razor-pages-commands-and-events)
