### ISSUE TITLE
Taghelper - url - invalid route- throw warning

### ISSUE THREAD

**Issue by dwdickens** [aspnet/Mvc#6684]
Hi, loving ASP.NET thank you so much for all of the hard work!

A suggestion - if the URL taghelper cannot resolve the controller/action route, it should throw a warning to catch this in the log.

Eg:  `<a asp-route-id="123" asp-action="MisspeltAction" asp-controller="MyController">'

       <a asp-route-id="123" asp-action="MisspeltAction" asp-controller="MyController">

Should throw a warning. At the moment it seems to happily push out a url of /MyController/MisspeltAction/123

**Comment by Eilon** [comment]
Historically we don't throw in this case because we feel it would make the process of developing an app more difficult. In the case above, it's possible that you're still building your app, and you know that you *will* have an action named `MyController.MisspeltAction`, so in that view you generate the URL for the action, but you haven't yet written the action itself. Then, later, you'll go ahead and implement that new action.

So, maybe there just ought to be an option such as "Strict URL Generation" or similar?

**Comment by Eilon** [comment]
Related previous discussion: https://github.com/aspnet/Mvc/issues/302

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.
