### ISSUE TITLE
Calling tag helpers from within a tag helper?

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#6731]
We want to write an enhanced tag helper around the select tag helper which adds necessary stuff for our special-dropdown-helper-library.

What's the recommended way to call another tag helper (e.g., the select tag helper) from a new tag helper written by us?

**Comment by NTaylorMullen** [comment]
There are two valid approaches you can use here:

1. Create a new select TagHelper that runs before or after the MVC TagHelper. 
2. Create your own select TagHelper and new up the Mvc select TagHelper and call its `ProcessAsync` method.

For number 1, your TagHelper would of course require the Mvc select TagHelper to apply to the current document.

For number 2, you'll need to inject all the relevant services in order to construct the Mvc SelectTagHelper.

**Comment by drauch** [comment]
Are there any samples outside to perform (2)?

**Comment by NTaylorMullen** [comment]
Not sure I follow. The SelectTagHelper ctor takes an IHtmlGenerator which comes from DI.

**Comment by drauch** [comment]
I'm talking about the ProcessAsync method and its parameters :)

**Comment by NTaylorMullen** [comment]
@drauch ah, so it sounds like you can't re-use the current `TagHelperOutput`/`TagHelperContext` that are passed in. If that's the case take a look at the Razor tests that initialize those types:

https://github.com/aspnet/Razor/blob/4b68a48f1d05c48f208040fc9e005ff113831953/test/Microsoft.AspNetCore.Razor.Runtime.Test/TagHelpers/TagHelperOutputTest.cs

https://github.com/aspnet/Razor/blob/4b68a48f1d05c48f208040fc9e005ff113831953/test/Microsoft.AspNetCore.Razor.Runtime.Test/TagHelpers/TagHelperContextTest.cs
