### ISSUE TITLE
Razor Pages

### ISSUE THREAD

**Issue by OmerHatip** [aspnet/Mvc#6741]
Hello everybody
this is my first post here, so forgive me if i'm posting in the wrong place.

i'm an old fashioned programmer, programming server/client apps.
I started to learn asp.net core with the new version 2.0. 
I started with Razor Pages, I loved it because it's very close to my old traditional asp.

as a beginner in this field I noticed that there is something going wrong (with me) in naming .

why we have to name the Index Page as "IndexModel" regarding to my understand the model is "Customer" for example not the Page, so if we can write something like this it will be more clear

@page MyWebApp.Customers.IndexPage
@model  MyWebApp.Customers.Customer

so we have a reference for page object instance , and also we have a type of our Model that we are working with

in this line I thing there is some magic when it works even if the Customers list is empty
@Html.DisplayNameFor(model => model.Customers[0].Name)

in my case we will write 
 @foreach (var Customer in page.Customers)
and
@Html.DisplayNameFor(model => model.Name)

Finally,
I know and understand the big efforts the team made,
but it's just a beginner suggestion.
Thanks.

**Comment by Eilon** [comment]
@pranavkm can you assist?

**Comment by Code-DJ** [comment]
If I may add my question rather than creating a new issue. Not sure what the convention is.

Assuming a folder structure that has folders and sub-folders under the Pages folder. If we have one JavaScript per page, since the JavaScript is supposed to be in the wwwroot folder, won't there be a lot of navigating around in Visual Studio when trying to open the cshtml and corresponding JavaScript? Assuming I would want to maintain the same folder structure for the JavaScript as the Pages what is the best way to do this?

**Comment by hishamco** [comment]
@OmerHatip let me explain everything to you:

1- `@page` directive is used to flag the `.cshtml` as a RazorPage, it may contains a route options if you want too

2- `@model` directive is used to specify the page model aka **ViewModel** not the model itself. FYI RazorPages are using MVVM pattern, so that's why you see something like `IndexPageModel`.

3- `@Html.DisplayNameFor(model => model.Customers[0].Name)` is basically used to get the display name for a property, I don't think we need to loop through the collection, catching that property from the first object is enough in this case

hope this solve your questions

**Comment by hishamco** [comment]
@Code-DJ you can keep your JavaScript files in the same place of your pages folder, I already did something similar when I need to place my assets per theme. Please checkout my [Theming repo](https://github.com/hishamco/Theming), specifically [here ](https://github.com/hishamco/Theming/blob/master/Theming/Startup.cs#L57-L62) where I configured the `FileProvider` for the static files

**Comment by Code-DJ** [comment]
Thanks @hishamco. Just to be sure, if I set the StaticFileOptions to the following, will it only server js, css from that path:

```C#
app.UseStaticFiles(new StaticFileOptions()
{
        FileProvider = new PhysicalFileProvider(Path.Combine(Directory.GetCurrentDirectory(), "Pages")),
        RequestPath = string.Empty
});
```

**Comment by OmerHatip** [comment]
Thank you everybody.

I changed my plan and started with MVC.
