### ISSUE TITLE
prototype build-time code generation using swagger

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6788]

**Comment by billpratt** [comment]
Please consider using strongly-typed attribute descriptors for swagger documentation instead of using XML documentation. 😄

**Comment by rynowak** [comment]
> Please consider using strongly-typed attribute descriptors for swagger documentation instead of using XML documentation. 😄

I was thinking I was the only one in the world that didn't find that compelling.

This is something we've considered a few times, and have always ended up deferring on it because we don't consume the descriptions ourselves.

**Comment by billpratt** [comment]
Here's an example where having the framework support it is a good idea 
https://github.com/dotnet/sdk/issues/795#issuecomment-329219685

**Comment by dougbu** [comment]
Marking this as `done` because prototype is available which works end-to-end using NSwag document and code generation tools. See https://github.com/dougbu/CodeGeneration

Will file new issues covering additional work such is finishing our document generation tool and integrating these bits into an SDK.
