### ISSUE TITLE
MvcJsonOptions.JsonSerializerSettings setter is needed

### ISSUE THREAD

**Issue by evil-shrike** [aspnet/Mvc#6816]
Currently in 2.0 for configuring `JsonSerializerSettings` we're doing something like that:
```
			services.AddMvc().AddJsonOptions(opt =>
			{
				opt.SerializerSettings.Converters = ...
			});
```

What's wrong with this approach for me is that I have a JsonSerializerSettings  inside my DI-container, so I need to use it as a whole. But `MvcJsonOptions` has no `SerializerSettings` setter.
This isn't possible:
```
var settings = container.Resolve<JsonSerializerSettings>();
opt.SerializerSettings = settings;
```
So I have to assign every property from my JsonSerializerSettings to `MvcsonOptions.SerializerSettings`.
It's VERY tedious! Really painful.

So please add setter for `MvcJsonOptions.JsonSerializerSettings`.

**Comment by Eilon** [comment]
Hi @evil-shrike the reason we don't have it settable is that options in ASP.NET Core in general are "composable," meaning that different components and parts of an app can each contribute various settings. If it were settable, that means that a component would be able to (perhaps inadvertently) overwrite important settings provided by another component.

For example, here are MVC's default JsonSerializerSettings: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Formatters.Json/JsonSerializerSettingsProvider.cs#L29-L42

Note that there are some important settings there that an app doesn't necessarily intend to override (such as max depth and TypeNameHandling).

The pattern in ASP.NET Core for composing configuration is that instead of storing a data object in DI (such as `JsonSerializerSettings`), you could instead register an object that can *configure* the data object.

You can do this by registering an additional configure object for the JSON settings, something like:

```c#
services.Configure<MvcJsonOptions>(options =>
{
    options.SerializerSettings.X = x;
    options.SerializerSettings.Y = y;
});
```

And this way your settings will compose with other settings that exist.

cc @rynowak for any further thoughts.

**Comment by evil-shrike** [comment]
@Eilon I thought hard about what you said. In general I understand the idea, it looks very reasonable.

But in my case I'm having difficulties to implement this approach.
The thing is that I need a `JsonSerializerSettings` instance in many places of my app/lib.
So it should be registered in DI-container. I use Autofac but it shouldn't be important. I use a "module" to create JsonSerializeSettings because while creating that settings I need other objects.

```
		protected override void Load(ContainerBuilder builder)
		{
			builder.Register(container =>
			{
				// delegate creation to a provider (JsonSerializationSettingsProvider)
				var provider = container.Resolve<JsonSerializationSettingsProvider>();
				return provider.Create();
			}).As<JsonSerializerSettings>();

			builder.RegisterType<JsonSerializationSettingsProvider>()
				.IfNotRegistered(typeof(JsonSerializationSettingsProvider))
				.SingleInstance()
				.OnActivating(ea =>
				{
					var provider = ea.Instance;
					var container = ea.Context;
					// some my other components needed for creating JsonSerializerSettings 
					provider.Config = container.Resolve<XConfig>();
					provider.AppFactory = container.Resolve<Func<IXCoreApplication>>();
					provider.Converters = container.Resolve<IList<JsonConverter>>();
				});
		}
```
Then `JsonSerializationSettingsProvider` creates the serializer settings:
```
			public JsonSerializerSettings Create()
			{
				return GetSerializeSettings(Config, AppFactory, Converters);
			}

			public virtual JsonSerializerSettings GetSerializeSettings(
				XConfig config, Func<IXCoreApplication> appFactory, IEnumerable<JsonConverter> jsonConverters = null)
			{
			    // here I create JsonSerializerSettings
			}
```
Please note that JsonSerializationSettingsProvider can be easily overridden. So that code is inside my lib and can be overridden in an app.

Here's the code of creating JsonSerializerSettings. It's not very important but just to make it clear:
```
public virtual JsonSerializerSettings GetSerializeSettings(
	XConfig config, Func<IXCoreApplication> appFactory, IEnumerable<JsonConverter> jsonConverters = null)
{
	var contractResolver = new XCamelCasePropertyNamesContractResolver();
	var converters = new List<JsonConverter>
	{
		new XIsoDateTimeConverter
		{
			// NOTE: Fix DateTime as http://es5.github.com/#x15.9.1.15 (for IE)
			DateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fff",
			DateTimeStyles = DateTimeStyles.RoundtripKind
		},
		new XIsoDateTimeOffsetConverter
		{
			DateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.fffzzz",
			DateTimeStyles = DateTimeStyles.RoundtripKind
		},
		new ExceptionJsonConverter {IsDebug = config.IsDebug},
		new DomainJsonConverter(appFactory, contractResolver),
		new XObjectIdentityConverter(),
		new NotAuthorizedPropValueConverter(),
		new LobPropValueDtoConverter(),
		new DomainObjectRightsJsonConverter(),
		new TimeSpanValueConverter(),
		new DecimalConverter(),
		new Int64Converter()
	};
	if (jsonConverters != null)
		converters.AddRange(jsonConverters);
		var settings = new JsonSerializerSettings
	{
		Formatting = config.IsDebug ? Formatting.Indented : Formatting.None,
		Converters = converters,
		ContractResolver = contractResolver,
		DateFormatHandling = DateFormatHandling.IsoDateFormat,
		DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind,
		DateParseHandling = DateParseHandling.DateTime,
		ReferenceLoopHandling = ReferenceLoopHandling.Ignore
	};
	return settings;
}
```

Now that code should be moved to `IMvcBuilder.Services.Configure<MvcJsonOptions>`'s callback:
```
	builder.Services.Configure<MvcJsonOptions>((opt) =>
	{
		// here I must get my JsonSerializationSettingsProvider from container and 
		// fill opt.SerializerSettings
	});
```

What is the problem here. Let's review `ConfigureServices` with usage of 3rd-party DI-container:
```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    var builder = new ContainerBuilder(); // a builder for Autofac container
    // registering components inside the builder
    // among others here my JsonSerializationSettingsProvider  should be registered

    services.AddMvc();
    services.Configure<MvcJsonOptions>((o) =>
    {
        // TODO: setup o.SerializerSettings
    });
    // register all services from IServiceCollection inside the DI-container
    builder.Populate(services);

    var container = builder.Build();
    return new AutofacServiceProvider(container);
}
```

`Configure<MvcJsonOptions>` should be done before `builder.Populate`.  
`builder.Populate` should be done before `builder.Build()`.  
Inside the callback which configure `MvcJsonOptions` I need my DI-container, which I can have only after `builder.Build()`. So it's kinda a chicken and egg situation.

I hope it's not very tangled.

What would help.
Inside `MvcJsonOptions` SerializerSettings is created with static method `JsonSerializerSettingsProvider.CreateSerializerSettings`. Why not to resolve JsonSerializerSettingsProvider as a service? It'd help a lot.

**Comment by khellang** [comment]
You could create a class that implements `IConfigureOptions<MvcJsonOptions>` and add it to the service collection, like this:

https://github.com/aspnet/Mvc/blob/1c4b0fcdf38320b2f02c0bb7c31df5bd391ace07/src/Microsoft.AspNetCore.Mvc.Formatters.Json/DependencyInjection/MvcJsonMvcCoreBuilderExtensions.cs#L76-L77

That way, you have access to the container (through constructor injection) when the options is being populated. See https://github.com/aspnet/Mvc/blob/1c4b0fcdf38320b2f02c0bb7c31df5bd391ace07/src/Microsoft.AspNetCore.Mvc.Formatters.Json/Internal/MvcJsonMvcOptionsSetup.cs for an example.

**Comment by weitzhandler** [comment]
How do I get a `JsonSerializer`/`JsonSerializerSettings` injected controller?

Example:

```c#
public class FilesController
{
  readonly IJsonSerializerSettings _JsonSerializerSettings;
  public FilesController(IJsonSerializerSettings jsonSerializerSettings)
  {
    _JsonSerializerSettings = jsonSerializerSettings;
  }

  public async Task<IActionResult> Post()
  {
    MultipartSection jsonSection = ExtractJsonSection();
    Stream jsonStream = jsonSection.Body;

    using (var streamReader = new StreamReader(jsonStream))
    using (var jsonReader = new JsonTextReader(streamReader))
    {
      var serializer = JsonSerializer.Create(_JsonSerializerSettings);
      var model = serializer.Deserialize<MyEntityType>(jsonReader);
    }    
  }
}
```

**Comment by weitzhandler** [comment]
@Eilon 

How do I get a `JsonSerializer`/`JsonSerializerSettings` injected controller?

Example:

```c#
public class FilesController
{
  readonly IJsonSerializerSettings _JsonSerializerSettings;
  public FilesController(IJsonSerializerSettings jsonSerializerSettings)
  {
    _JsonSerializerSettings = jsonSerializerSettings;
  }

  public async Task<IActionResult> Post()
  {
    MultipartSection jsonSection = ExtractJsonSection();
    Stream jsonStream = jsonSection.Body;

    using (var streamReader = new StreamReader(jsonStream))
    using (var jsonReader = new JsonTextReader(streamReader))
    {
      var serializer = JsonSerializer.Create(_JsonSerializerSettings);
      var model = serializer.Deserialize<MyEntityType>(jsonReader);
    }    
  }
}
```

**Comment by khellang** [comment]
@weitzhandler Inject `IOptions<MvcJsonOptions>` in your controller and use that :smile:

**Comment by weitzhandler** [comment]
@khellang Thank you!

**Comment by yugabe** [comment]
Anyone wandering here trying to figure out how to "properly" inject SerializerSettings into your application, I found the following to be a good way to do it:

```CSharp
services.AddSingleton(s => s.GetRequiredService<MvcJsonOptions>().SerializerSettings);
```

Obviously, you can use other lifetime scopes depending on your needs. This way you can implement a class which can serialize any given object based on the current settings:

```CSharp
public class JsonSerializer : IJsonSerializer
{
    public JsonSerializer(JsonSerializerSettings settings)
        => Settings = settings;

    public JsonSerializerSettings Settings { get; }

    public string Serialize(object @object) => JsonConvert.SerializeObject(@object, Settings);
}

public interface IJsonSerializer 
{
    string Serialize(object @object); 
}
```

I needed to do this because I didn't want to add a reference to MVC just to be able to serialize JSON.

**Comment by yugabe** [comment]
@wpo365 Sure. Elaborating on the example I outlined above, let's say you got 3 projects to keep things very clean. 

Your `Core` project doesn't reference anything, and only contains your main POCO models, and the interfaces of your own domain services. This project contains the `IJsonSerializer` interface, which you an consider a service (infrastructe though, not domain, but it's irrelevant in this case).

Now there's your upper-framework-agnostic business logic layer, let's put this in a project called `Bll`. This references the `Core` project and implements `IJsonSerializer` with `JsonSerializer`. This references Newtonsoft.Json, but not AspNetCore.

Finally, in your top UI layer, let's call this the `Web` project, you do reference AspNetCore packages and configure DI the way I showed above. You add `JsonSerializerSettings` to the container, so that you'll be able to resolve the concrete serializer when registering it to DI this way:
```CSharp
services.AddSingleton<IJsonSerializer, JsonSerializer>();
```

You're good to go to inject `IJsonSerializer` anywhere the container resolves from now, including your services, controllers, etc.
