### ISSUE TITLE
Use names in EventIds for logging

### ISSUE THREAD

**Issue by anurse** [aspnet/Mvc#6818]
When logging, we use `int`s for the `eventId` parameter, but the `EventId` type that is used can actually also support holding a name. Names are easier to query and inspect in structure log storage. So, as an example, a `LoggerMessage.Define` should change to something like this:

```csharp
LoggerMessage.Define<...>(LogLevel.Trace, new EventId(1, "[Event Name]"), "... message ...");
```

(Event ID names don't need a prefix because `EventId` is only unique within a Logger, so there's no need to prefix it).

**Comment by josephearl** [comment]
Numeric event IDs are somewhat meaningless when looking through logs, this would be a great improvement.

**Comment by mkArtakMSFT** [comment]
@glennc, is this something we should prioritize for 2.2 milestone?

**Comment by glennc** [comment]
Changing existing eventIds would be a breaking change for customers, suddenly things parsing logs looking for numbers would need to change. Right?

Given that I don't think we could do something meaningful here in 2.2 at all, and I don't know if the improvement would ever be worth the potential pain. But we could have the discussion for new things we log, if we do that it should be all-or-nothing in that all components get strings instead of ints as we go forward.

**Comment by anurse** [comment]
> suddenly things parsing logs looking for numbers would need to change. Right?

No, my understanding is that it is not breaking. It somewhat depends on the logging provider but most of them track the Event ID and Event Name as separate data fields. So as long as we don't **change** the numbers, any queries that were based on "EventID = 123" should continue to work, we would just be additionally enabling queries based on "EventName = zoinks"

**Comment by mkArtakMSFT** [comment]
This is understood now. It's about logging additional data (the event name). Punting to a future release as we won't have time to handle this now.
