### ISSUE TITLE
Crazy Idea: Use IHostedService to 'preload' TagHelpers

### ISSUE THREAD

**Issue by rynowak** [aspnet/Mvc#6820]
We've seen feedback in the past that doing a background warmup of Roslyn by creating an empty compilation has a measurable impact on startup perf.

Can we leverage `IHostedService` to use some heuristics about when we expect Roslyn/Razor to be required and trigger tag helper discovery early? Tag Helper Discovery creates a compilation so this should have the desired effect.

**Comment by Eilon** [comment]
Please remind me because I need to be reminded: is there any potential for an ordering issue here? Can something of any reasonable significance end up happening in the wrong order? Like, a situation where tag helper discovery happens before "everything is loaded," such as what could happen with Application Parts?

**Comment by rynowak** [comment]
`IHostedService` is part of DI https://github.com/aspnet/Hosting/blob/e7541e99a7c125f29d30c1454d463df65d6eab98/test/Microsoft.AspNetCore.Hosting.Tests/WebHostTests.cs#L489

So no. All of MVC's configuration needs to happen before DI or it's lazy.

**Comment by Yves57** [comment]
Maybe #5746...

**Comment by rynowak** [comment]
Yes! that's the one I was thinking of. I couldn't find the item to link it.

**Comment by rynowak** [comment]
Tracking this work here - https://github.com/aspnet/Razor/issues/1739 we do plan to do this for 2.1
