### ISSUE TITLE
Validators are not obtained correctly for nested properties

### ISSUE THREAD

**Issue by ag-petrov** [aspnet/Mvc#6862]
When having the below models.

```
 public class ProductViewModel
    {
        [Required]
        [Display(Name = "Product name")]
        public string ProductName
        {
            get;
            set;
        }

        [UIHint("ClientCategory")]
        public CategoryViewModel Category 
        { 
            get; 
            set; 
        }

    }
   public class CategoryViewModel
    {
        public int CategoryID { get; set; }
        [Required]
        [Display(Name = "Category name")]
        public string CategoryName { get; set; }
    }
```

And the following view

```
@model ProductViewModel

@Html.MyOwnHtmlHelper("Category.CategoryName")
```

Extracting the validators using the GetValidators method as demonstrated below does not work. It works for the ProductName property for example but not for nested properties.

```
public static HtmlString MyOwnHtmlHelper<TModel>(this IHtmlHelper<TModel> helper, string fieldName)
        {
            var explorer = ExpressionMetadataProvider.FromStringExpression(fieldName, helper.ViewData, helper.MetadataProvider);
            var validator = new ClientValidatorCache();
            var optionsAccessor = helper.ViewContext.HttpContext.GetService<IOptions<MvcViewOptions>>();
            var clientValidatorProviders = optionsAccessor.Value.ClientModelValidatorProviders;
            var clientModelValidatorProvider = new CompositeClientModelValidatorProvider(clientValidatorProviders);
            var validators = validator.GetValidators(explorer.Metadata, clientModelValidatorProvider);
            // Validators are empty when using nested properties

            .....
        }
```

**Comment by Eilon** [comment]
@SteveSandersonMS can you take a look?

cc @rynowak @dougbu

**Comment by SteveSandersonMS** [comment]
OK, having investigated, I think it comes down to this line of code: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/ExpressionMetadataProvider.cs#L150

The `ExpressionMetadataProvider.FromStringExpression` method tries to find metadata:

1. **In `ViewData` treated as a dictionary**
    * It does this by calling `ViewDataEvaluator.Eval(viewData, expression)`, which looks at `ViewData` as a dictionary (not the `Model` object), and walks through all the different combinations of tokens present in `expression` to find the thing you're asking about. That is, if `expression` is `"Category.CategoryName"`, then it will look for `ViewData["Category.CategoryName"]` or `ViewData["Category"]["CategoryName"]`.
   * If something matches, it returns the `ModelMetadata` for that item

2. **In the metadata for `ViewData.Model`**
   * It does this by calling `viewData.ModelExplorer.GetExplorerForProperty(expression)`, which in turn is looking for an actual property on the `Model` type with name `expression`. It does *not* split up `expression` into tokens and walk through the sequence of named properties - it *only* looks for a property whose name exactly matches `expression`, even if that's some string like `"Category.CategoryName"`. This is why you can't locate nested properties on `Model`.

So, if we wanted to fix this, we could change `ExpressionMetadataProvider.FromStringExpression` so that it has similar expression-walking logic when calling `viewData.ModelExplorer` as it does when searching through `ViewDataDictionary`.

However, before we really pursue this, we should be clearer about the use cases. Most of the APIs involved in this repro case are in the `Microsoft.AspNetCore.Mvc.ViewFeatures.Internal` namespace. @Eilon @rynowak @dougbu How much do we support the direct use of those APIs?

Similarly, @ag-petrov, do you have any repro that only uses public APIs? There would be a stronger case for changing the behavior if there is. Or if you have a case for why some of these APIs should really be public that's also worth raising, though it would end up being treated as a separate issue.

**Comment by dougbu** [comment]
@SteveSandersonMS 1. in your list checks through `ViewData.Model` as well. See [`ViewDataEvaluator` line 59](https://github.com/aspnet/Mvc/blob/eeac99985a61e75ca48e620f0371e16df018d6d7/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/ViewDataEvaluator.cs#L59) for example. I believe 2. happens if `null` appears anywhere in the expression before the last node e.g. when `ViewData.Model` is `null`.

Rationale: The relevant code has been significantly refactored compared to what's in ASP.NET MVC 5.2.3. But, I bet any restrictions on the handled expression names are inherited from the older framework. I don't know the original reasoning.

W.r.t. public APIs: The main use case for the `ExpressionMetadataProvider.FromStringExpression(...)` method is string-based HTML helpers e.g. `@Html.TextBox(...)` in a view. Should be easily to test.

Implementation: It's certainly possible to recurse through the `ModelMetadata` property tree then create a `ModelExplorer` with a `null` `Model` and the correct metadata. Switching to `ElementMetadata` will add further complications. If we decide `Container` is interesting, will also need to do the `ViewDataEvaluator` thing until it reaches a `null` property then confirm whether there's only one more property to go.

**Comment by rynowak** [comment]
>  How much do we support the direct use of those APIs?

In general direct usage of these APIs doesn't have any official support. We usually want to know if there's a bug/repro/solution that surfaces through one of our more common use cases. This isn't to be mean or to pull a bait and switch - in some cases we just didn't fully design extensibility/infrastructure where it's needed - and also in some cases we find that a user is doing something "the hard way" rather than using things the intended way.

However, if there's a genuine gap that can be covered by `.Internal` APIs we will usually add to migrate things or redesign them to meet the needs.

**Comment by mkArtakMSFT** [comment]
Thank you for contacting us, @ag-petrov.
To evaluate this feature request, we'd like to understand more about your scenario. Could you please elaborate on the scenario and the problem you're trying to solve?

**Comment by ag-petrov** [comment]
I do apologize for not replying earlier. As for the problem we have custom helpers which render input elements that need the validation attributes. The logic which does this is rather complex and I have extracted only a certain part just to illustrate the case. If there is alternative approach that I can use that would be great. 

The issue that we faced is - How to get the nested property validation attributes?
Any suggestions on the above are appreciated.

**Comment by dougbu** [comment]
> How to get the nested property validation attributes?
#### `.Internal` namespaces
If possible, grab the `ValidationHtmlAttributeProvider` from DI and use that instead of dealing directly with types in `.Internal` namespaces. That is, avoid `ClientValidatorCache` and `ExpressionMetadataProvider` if you can. Please let us know if the `ValidationHtmlAttributeProvider` abstraction doesn't meet your needs. It's possible to extend that or to move `ClientValidatorCache` and `ExpressionMetadataProvider` elsewhere.

#### No validation attributes generated
The code you provided looks :ok: and I doubt `ValidationHtmlAttributeProvider` will behave differently. That is, you'll probably still see no attributes for nested properties when the `ProductViewModel` or its `Category` are `null`. That restriction should be identical to using, say, `Html.TextBox("Category.CategoryName")` in the same scenario. Please let us know if you *different* behaviour for your helper from MVC's `string`-based helpers.

If the behaviour is the same, I suggest:
1. Make your custom helper expression-based i.e. more like `Html.TextBoxFor(...)` than `Html.TextBox(...)`.
2. Split out a template view for the `CategoryViewModel` and use `Display("Category", ...)` or `Editor("Category", ...)` in the view for `ProductViewModel`.
3. Do something like (2.) using a partial view. The top-level view will also need to update and restore `ViewData.TemplateInfo.HtmlFieldPrefix` to make `id` and `name` attribute values correct for the generated elements.

#### Nits
If you need to use it, your helper should resolve `ClientValidatorCache` from DI.

**Comment by mkArtakMSFT** [comment]
@ag-petrov, did the solution provided resolve your issue?

**Comment by ag-petrov** [comment]
I see that **ValidationHtmlAttributeProvider** targets **ASP.NET Core 1.1** and **2.0**. However my project uses ASP.NET Core 1.0 and I can not update. Are there any other alternatives?

**Comment by mkArtakMSFT** [comment]
@dougbu, would you have any suggestion for @ag-petrov's situation? Not sure, though, that there will be.

**Comment by dougbu** [comment]
@ag-petrov if you *must* stick with the oldest ASP.NET Core MVC release, I guess your only choices are to use the `.Internal` types directly or to copy the code you need.
