### ISSUE TITLE
Split Middleware Invoke method into two seperate methods, Before and After invocation

### ISSUE THREAD

**Issue by a-patel** [aspnet/Mvc#6885]
Middleware contain method Invoke which contain http request before and after execution logic separated by request delegate, it should be split into two separate methods (e.g. BeforeInvocation and AfterInvocation) like action filter method (e.g. OnActionExecutiong and OnActionExecuted).
It is not necessary that all middleware has both before/after invocation logic.

**Comment by davidrevoledo** [comment]
@a-patel but the await next() doesn't work to decide if do the work after or before of the middle ware chain execution ?

**Comment by Eilon** [comment]
This is already trivial when writing middleware: just put code before or after calling `next()` (or don't call `next()` at all). If we add before/after methods then a lot of other complexity has to be added to control all the behaviors around whether an error happens, how to process it, etc. Note that MVC's OnActionExecuting/Executed are not trivial: they have a complex context object with complex behavior.

Closing because there are no plans to implement this.
