### ISSUE TITLE
Tag helpers don't work with a dynamic model

### ISSUE THREAD

**Issue by aqueenan** [aspnet/Mvc#6925]
If the model for a Razor page is `dynamic`, either explicitly (using `@model dynamic`) or implicitly (by omitting the `@model` directive), Visual Studio shows the error "An expression tree may not contain a dynamic operation" for the tag, and the tag helpers produce view code that fails to compile,

Could the tag helpers be improved so that they work with dynamic?

The code that fails to compile is produced by `MvcTagHelperAttributeValueCodeRenderer.RenderAttributeValue`, which outputs a lambda for the field.

**Comment by rynowak** [comment]
Please include a complete code sample that demonstrates the problem so that we can understand what you're doing

**Comment by aqueenan** [comment]
Here's the code sample.

[WebApplication1.zip](https://github.com/aspnet/Mvc/files/1367780/WebApplication1.zip)

**Comment by Eilon** [comment]
@pranavkm can you take a look at the repro?

**Comment by NTaylorMullen** [comment]
This has never worked has it? I don't believe we've ever supported Html helpers that have a "For" expression with dynamic values. Same things goes for TagHelpers `asp-for` ModelExpression attributes.

**Comment by Eilon** [comment]
Oh sure, `dynamic` doesn't work in expressions. Should we avoid generating bad code or something here?

**Comment by Eilon** [comment]
Or is it not us generating bad code? Not clear to me where the "error" is.

**Comment by NTaylorMullen** [comment]
So we aren't technically generating bad code. The model is set as dynamic and so the Razor parser spits out whatever the current model is as part of an expression, i.e.: `CreateModelExpression(__model => Model.Foo)`. This just happens to be a compile error in C# because the user is trying to use dynamic in the expression (the `Model`).

The only possible "fix" for this case would be to provide a better error message. We could accomplish that only at runtime with a Roslyn rewriter (much like what we do with caching expressions for performance reasons today).

I'm not convinced its worth improving the experience, the error message is already pretty good 😄

**Comment by Eilon** [comment]
So everything is fine until you use any strongly-typed model-based helper, in which case "we generate what we were told to," but then C# gets unhappy?

**Comment by NTaylorMullen** [comment]
> So everything is fine until you use any strongly-typed model-based helper, in which case "we generate what we were told to," but then C# gets unhappy?

I don't 100% follow, but for example, this is invalid C# (basically what's going on behind the scenes in Razor):
```C#
dynamic Model = new ExpandoObject();
SomethingExpression(() => Model.SomeProperty);

void SomethingExpression(Expression<Func<object>> expression)
{
}
```

Basically, expression trees in C# can't contain dynamic operations.

**Comment by Eilon** [comment]
Yeah I'm asking whether in an "empty" page or if I'm just using non-`For` helpers, everything always works, right? But with a `dynamic` model, once I use a `For` HTML helper, or an `asp-for` tag helper, the page won't compile.

**Comment by NTaylorMullen** [comment]
> Yeah I'm asking whether in an "empty" page or if I'm just using non-For helpers, everything always works, right? But with a dynamic model, once I use a For HTML helper, or an asp-for tag helper, the page won't compile.

Yes, 100% correct.

**Comment by Eilon** [comment]
Ok then I agree there isn't really anything to fix here. Though, I do also think the error isn't *ideal* because it's hard for a user to know what exactly caused this problem - especially when they don't see the lambda that caused the problem.

But, I also don't think there's any reasonable way to fix the error because it would likely involve diving into stuff that we normally don't dive into.

For that reason, I'm closing this bug.

**Comment by aqueenan** [comment]
Instead of emitting code using expression-based syntax, is there an equivalent string-based syntax that could be emitted when the model is dynamic?

That is, instead of emitting code that called [EditorFor](https://docs.microsoft.com/en-au/dotnet/api/microsoft.aspnetcore.mvc.rendering.ihtmlhelper-1.editorfor?view=aspnetcore-2.0)-like methods instead of [Editor](https://docs.microsoft.com/en-au/dotnet/api/microsoft.aspnetcore.mvc.rendering.ihtmlhelper.editor?view=aspnetcore-2.0)-like methods.
