### ISSUE TITLE
Potential DDOS issue in model binding files

### ISSUE THREAD

**Issue by jchannon** [aspnet/Mvc#6933]
I was looking at this code https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/Binders/FormFileModelBinder.cs#L53-L132

If a request had a million files it would seem the binder will just sit there adding `IFormFile` to a `List<T>` using up memory. Obviously if the files with greater than 64kb and it wrote to disk after 60k files it would error however the former would slow things down a lot.

Obviously this could kill the client machine too uploading lots of files so it might not be  practical risk anyway but thought I'd see what people thought

**Comment by jchannon** [comment]
This might be handled ok by https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/Features/FormOptions.cs when `HttpRequest.ReadFormAsync` is called

**Comment by rynowak** [comment]
Yes, the limits in `FormOptions` exist to serve as a single point for controlling how large (in a few different ways) form data and file-uploads can be.

In particular you are limited to 1024 files by default (assuming you don't hit a global body size limit before that).

/cc @Tratcher @blowdart

**Comment by Tratcher** [comment]
Kestrel's request body size is the first limit you'll hit.
https://github.com/aspnet/KestrelHttpServer/blob/66a3c9496afb9694db13318c4f637ab2dbe1a7d5/src/Kestrel.Core/KestrelServerLimits.cs#L150

After that yes there are a variety of limits in FormOptions you'll hit depending on the shape of your upload.

**Comment by Eilon** [comment]
Right, ASP.NET Core, and also Kestrel and MVC in particular, each have several settings to control various sizes and limits. You can also mitigate attacks by using additional software such as IIS, nginx, which have their own types of protections and limits. If you wish to report a specific attack or concern, please work through Microsoft Security Response Center <secure@microsoft.com> so that the details are not posted publicly.
