### ISSUE TITLE
Suggestion: Utilize the model type defined in a resolved view for visitedObjects instead of string

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Mvc#6951]
I have gotten bitten by the visitedObjects being populated by the string type when I attempt to force a null object to render.

```c#
Html.Editor("notInViewState","ModelWithCustomStringEditor")
```
This causes issues if I have a custom editor for the string type on a property in my model.

The current work around is to define a variable with the type set to the intended datatype
```c#
ModelWithCustomStringEditor temp = null;
Html.EditorFor(m=>temp,"ModelWithCustomStringEditor")
```
but this seems to be a bit of a gotcha.

**Comment by Eilon** [comment]
@Tarig0 sorry I'm not sure I understand what the issue is here. What is the expected behavior, and what behavior are you getting?

**Comment by Tarig0** [comment]
InvalidOperationException: The model item passed into the ViewDataDictionary is of type 'System.Collections.Generic.List`1[Labels.Electrical.Models.ElectricalFanPart]', but this ViewDataDictionary instance requires a model item of type 'System.Collections.Generic.IList`1[Labels.Electrical.Models.Interfaces.IElectricalPart]'.

**Comment by Tarig0** [comment]
The current behavior

The first block will have the following template path

BASE -> "string"<ModelWithCustomStringEditor> -> "string"<CustomStringEditor>

I would expect this to be
BASE -> "ModelWithCustomString"<ModelWithCustomStringEditor> ->  "string"<CustomStringEditor>

**Comment by Eilon** [comment]
@Tarig0 thanks for the extra info.

@dougbu any idea on this?

**Comment by Tarig0** [comment]
Note this suggestion steamed from the issue #6939

**Comment by dougbu** [comment]
> any idea on this?

Something is definitely wrong here. Passing `Editor(...)` an explicit `templateName` should use that name.

@Tarig0 please provide a repro project, preferably as a GitHub repo. Need to be sure I'm understanding your scenario.

**Comment by Tarig0** [comment]
https://github.com/Tarig0/CustomStringEditor

**Comment by Tarig0** [comment]
https://github.com/aspnet/Mvc/blob/8f8bf5af341b5cc07e0611dc9a3a02e471e2bf63/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewFeatures/TemplateBuilder.cs#L145

This is the section of code that I think if you could extract the resolved type of the model and use that over the string type found in the modelexplorer

**Comment by dougbu** [comment]
@Tarig0 the code you copied above looks fine since `TemplateInfo` information is shared only "vertically" i.e. between nested views. And, you won't have a `string` view inside another `string` view. However your application isn't providing enough metadata for the system to work properly.

One issue in your application is [this line](https://github.com/Tarig0/CustomStringEditor/blob/102b7c865c6cc9085762a2f41831d05ddf38470a/Views/Home/Index.cshtml#L11)
``` c#
@Html.Editor("notinViewState", "ModelWithCustomStringEditor")
```

`Editor(...)` cannot be used with expression names that do not map to `ViewDataDictionary` keys, `Model` properties, or indexers and property accesses relative to one of those two. So, the call should be
``` c#
@Html.Editor("ModelWithCustomStringEditors")
```
or
``` c#
@Html.Editor(nameof(ParentModel.ModelWithCustomStringEditors))
```
Either will iterate through the `Model.ModelWithCustomStringEditors` collection and invoke the ModelWithCustomStringEditor.cshtml template for each. That template will have the correct metadata and `TemplateBuilder` won't refuse to render it.

However, the model is `null` in your application, not even an empty collection. That hits a restriction of `string`-based HTML helpers: They traverse the model or `ViewData` entries, not metadata, and thus can find information about `null` properties but nothing inside `null` collections or objects. Use `EditorFor(...)` instead e.g.
``` c#
@Html.EditorFor(m => m.ModelWithCustomStringEditors[0])
```
(For the above to work, you'll also have to switch the property from `IEnumerable<T>` to `IList<T>` or `ICollection<T>`.)

**Comment by dougbu** [comment]
@Tarig0 I think I've answered your questions. Please reopen if I missed something.
