### ISSUE TITLE
Query parameter not bound if method parameter has same name as property

### ISSUE THREAD

**Issue by joacar** [aspnet/Mvc#6971]
If the parameter name in the method is the same as the property beeing bound via query string it doesn't work. If I prefix the query string key then the value is parsed correctly

**Question**: Should/can the `[FromQuery]` attribute be used on a property to indicate that it should use that name instead of the property name when creating the query string?

E.g. `[FromQuery(Name = "q")]public string SomeReallyLongPropertyName { get; set; }` would generate `http://github.com/aspnet/Mvc?q=work`?

Attaching a solution where the issue and the question is present.

Thank

[AspNetCoreMVcBugs.zip](https://github.com/aspnet/Mvc/files/1397651/AspNetCoreMVcBugs.zip)

**Comment by Eilon** [comment]
@rynowak can you take a look at this?

**Comment by rynowak** [comment]
This is MVC's prefix detection logic in action.

When MVC sees a parameter like `public IActionResult HelloNameWorks([FromQuery] HelloViewModel hello)`...

It tries first to see if a key was provided for `hello`.  If it finds one then it will try to bind `hello.FirstName`, `hello.LastName`, etc for all of the properties on `HelloViewModel` - in your case it's going to look for `hello.Hello`.  Using a property name with the same name as the parameter will almost always do the wrong thing due to how this feature behaves.

You can can fix your specific issue by using `[ModelBinder(Prefix="")]` or `[FromQuery(Name="")]` on the parameter to force it to look for `Hello` from the query string instead of `hello.Hello`.

-----------------

@Eilon - this is not a bug, but it's a good candidate for more logging and an analyzer.

**Comment by Eilon** [comment]
Ok I added this to our tracking item for future analyzers. Beyond that, this issue is currently by-design.
