### ISSUE TITLE
Flaky test CacheTagHelperTest.ProcessAsync_WorksForNestedCacheTagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Mvc#6985]
I ran this non-stop for over an hour without repro. Seems very inconsistent but still flaky 😄 

http://aspnetci/viewLog.html?buildId=347170&tab=buildResultsDiv&buildTypeId=Patches_20x_Public_TestWin2012#testNameId-8007269666152451102

/cc @ryanbrandenburg

**Comment by Eilon** [comment]
@sebastienros can you take a look?

**Comment by pranavkm** [comment]
I dug in to this because I had repeated failures on desktop with this when I was working on the 2.1.0 acquisition. There's a couple of issues here at play:

1. CancellationToken.Register may throw a ObjectDisposedException on desktop if the TokenSource has been disposed. I say *may* because it's currently behind an app context switch. Relevant code: http://referencesource.microsoft.com/#mscorlib/system/threading/CancellationTokenSource.cs,637. 

2. In CacheTagHelper, we assume that once the tag helper contents were processed, the remainder of steps (which included `CacheEntry.Dispose`) would not throw and therefore used TCS.SetException. The stack trace we see in the CI log is from attempting to set an exception on a TCS that was already set. 

I spoke to @Tratcher and we feel that the right way to fix (1) is to put a try-catch around `CancellationToken.Register` so we can no-op when it throws an ObjectDisposedException. Additionally it would reset the `ActiveChangeCallbacks` flag to avoid future registrations that would fail.

For (2), we need to refactor the code block in https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.TagHelpers/CacheTagHelper.cs#L113-L141 so we aren't conflating errors in creating the cache entry with errors in processing the tag helper - the latter is what we care about here.

**Comment by pranavkm** [comment]
For the time being, I'd like to skip this test until we can address (1) and have it consumed in Mvc. We can use this work item to track restoring it once relevant changes have flown through.

**Comment by ryanbrandenburg** [comment]
I'm fine with that. I've added this to our list of flaky tests to further prevent it getting forgotten.

**Comment by ryanbrandenburg** [comment]
Should I assume this was fixed by aspnet/Mvc#7042?

**Comment by pranavkm** [comment]
https://github.com/aspnet/Mvc/commit/9dc9381ae4cddf2661818014b6e95fae99019f4b is the commit that fixes the issue.
