### ISSUE TITLE
Flaky tests: ServiceFilterUsesRegisteredServicesAsFilter and MiddlewareFilter_LocalizationMiddlewareRegistration_UsesRouteDataToFindCulture

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Mvc#7041]
These tests have [failed recently](http://aspnetci/viewLog.html?buildId=353793&buildTypeId=Lite_MvcTest&tab=buildResultsDiv) with errors saying a Collection has been modified. Sounds like a race condition somewhere in these codepaths.

**Comment by Eilon** [comment]
@javiercn can you take a look at this flaky test?

**Comment by javiercn** [comment]
Apparently the build completely disappeared from the history on the CI, and the test are all passing now.

I've looked at the code for the two offending tests above and there is nothing to suggest an issue related to the message above (modifying a collection while enumerating it). Without a call stack is impossible to figure out what the actual issue was, so closing this until it reproduces again.
