### ISSUE TITLE
RadioButtonFor() binding fails when using an EditorTemplate where the model is a simple property

### ISSUE THREAD

**Issue by stephenmuecke** [aspnet/Mvc#7080]
**Steps to reproduce**

Model

```c#
public class Person
{
    [UIHint("Gender")]
    public string Gender { get; set; }
}
```

Controller

```c#
public ActionResult Create
{
    Person model = new Person
    {
        Gender = "Male" // set default
    };
    return View(model);
}
```

VIew

```c#
@model Person
@using (Html.BeginForm())
{
    @Html.EditorFor(m => m.Gender)
}
```

EditorTemplate (`/Views/Shared/EditorTemplates.Gender.cshtml`)

```c#
@model String
@Html.RadioButtonFor(m => m, "Male")
@Html.RadioButtonFor(m => m, "Female")
```

**Issue**

When the view is generated, neither radio button is checked despite the value of the property being set in the model (the first radio button with the value of "Male" should be checked).

**Cause**

The `RadioButtonFor()` method calls the `private static MvcHtmlString RadioButtonHelper(.....)` method and passes a value to the `string name` parameter using `ExpressionHelper.GetExpressionText(expression),`.

Because the expression is `m => m`, this returns an empty `string`, and results in the following code snippet in that method returning `false`

```c#
isChecked = model != null &&
    !String.IsNullOrEmpty(name) && // name is empty
    String.Equals(model.ToString(), valueString, StringComparison.OrdinalIgnoreCase);
```

which in turn means that the `checked` attribute is not added.

Note: Not tested, but an `EditorTemplate`  for a `bool` model and using a `@Html.CheckboxFor(m => m)` is also likely to not bind correctly.

**Comment by Eilon** [comment]
@dougbu any idea on this?

**Comment by dougbu** [comment]
This is an issue about MVC 5.x. @stephenmuecke please it move to https://github.com/aspnet/AspNetWebStack I recommend movers such as https://github-issue-mover.appspot.com/

---

This issue is part of a longstanding MVC 5.x problem that we fixed in ASP.NET Core MVC. It was possible to fix in Core only because we had some leeway on breaking changes. See #1485 and #1487 for example.

FYI the general problem is the MVC 5.x code remains inconsistent w.r.t. using the `TemplateInfo.HtmlFieldPrefix` when interpreting expression names.

One workaround when you hit these issues is to switch to string-based HTML helpers or lambda-based HTML helpers, depending on which isn't working for your scenario. That is, one type of helper often avoids problems in scenarios the other type mishandles.

**Comment by stephenmuecke** [comment]
This issue was moved to aspnet/AspNetWebStack#108

**Comment by stephenmuecke** [comment]
@dagood . Moved and closed (FYI, I posted this as a result of [this SO question](https://stackoverflow.com/questions/47451373/radiobuttonfor-in-editortemplate-does-not-select-the-radiobutton#47451373) and its dupe does show a workaround)
