### ISSUE TITLE
RazorStyles

### ISSUE THREAD

**Issue by grahamehorner** [aspnet/Mvc#7096]
Please consider creating a RazorStyles engine for when developers require the generation of dynamic css from complex logic, example would be color, font, embedding resources based on a user/tenant profile. I propose that a file extension of .cscss, with possible support for a runtime sass/less type engine byway of .csless .cssass extensions and precomplied/embedding support similar to RazorViews/Pages

**Comment by Svek** [comment]
I would imagine that a base CSS file (for example `base-theme.css`) combined with the variations of it (for example `dark-theme.css` `light-theme.css`) would be easier to manage.

You could then use layouts, templates, sections or partial views to deal with the dynamic mapping of the styles per your requirements.

Having said that, you could just as easily create a `.cshtml` file and just do your logic then and there. The only caveat is that the RazorEngine requires a valid html tag (eg `<style>`) to know where the C# code stops and where the HTML code begins.

For example
```
@{
    string color = "black";

    if (!String.IsNullOrEmpty(color))
    {
        <style type="text/css">
            body {
                color: @color;
            }
        </style>
    }
    else
    {
        <style type="text/css">
            body {
                color: red;
            }
        </style>
    }
}
```

**Comment by mkArtakMSFT** [comment]
@danroth27, any thoughts here? /cc @DamianEdwards

**Comment by RandyBuchholz** [comment]
I've proposed the idea of a Design-Time Directive [Language Feature Proposal] #1747 that would allow you to hook this type of capability into Razor.

You can do a lot of this type of thing already, inside a script block, but there is a drawback that intellisense is somewhat broken when you mix them. (Though it looks like this may be getting fixed.)

An approach I've used is "style injection". You can create classes (I create Themes) with methods the produce css (classes or styles) based on parameters (works best if you return `HtmlString`) and then you can inject them into the page.
```
@inject ITagThemes _themes

<label class=@(condition ? _themes.OptionA(param) : _themes.OptionB(param)) ></label>
<label class=@(_Themes.Selector(param) ? _themes.OptionC : _themes.OptionD)
```
In your themes classes you can hand code, or write in Less and invoke the less compiler, and parse the output. You can create library sheets with fragments and a dictionary, then use XmlDocument (or something like HtmlAgilityPack) to pull the ones you want assemble together.

The biggest issue I've found with dynamic css is that because it is dynamic, intellisense doesn't always know about it. 

If you need to get real serious, you can create a C#/CSS library and write your CSS in C#. As an experiment, I translated the CSS object model into a set of nested classes that output CSS.
```
        public static class Margin {
            public static string Style(int s) => $"margin:{s.ToPx()};";
            public static string Style(int v, int h) => $"margin:{v.ToPx()} {h.ToPx()};";
            public static string Style(int t, int r, int b, int l) => $"margin: {t.ToPx()} {r.ToPx()} {b.ToPx()} {l.ToPx()};";
            public static class Top {
                public static string Style(int s) => $"margin-{Compass.Top(s)}";
            }
            public static class Right {
                public static string Style(int s) => $"margin-{Compass.Right(s)};";
            }
            public static class Bottom {
                public static string Style(int s) => $"margin-{Compass.Bottom(s)};";
            }
            public static class Left {
                public static string Style(int s) => $"margin-{Compass.Left(s)};";
            }
        }

// use it in classes
var style = Margin.Top.Style(10);
// produces "margin-top:10px;"
```
I backed the style injection approach with this. Though interesting, it seems more work than it is worth.

**Comment by mkArtakMSFT** [comment]
@DamianEdwards, thoughts on this?

**Comment by DamianEdwards** [comment]
It sounds interesting but seems like many others things would be a higher priority for future Razor work, not to mention that Razor as a language is really structured around HTML and its syntax.
