### ISSUE TITLE
Html.ActionLink uses HtmlAttributes in place of Route Values where Route Values are null 

### ISSUE THREAD

**Issue by knightmeister** [aspnet/Mvc#7136]
The following snippet worked as expected in ASP.NET MVC:

`@Html.ActionLink(Fields.New, "New", null, new { @class = "btn btn-success new-button" })`

Following my port to .NET Core, the action link which is built has the following markup:

`<a href="/items/new?class=btn%20btn-success%20new-button">New</a>`

Note that the query string is being built from the HTML Attributes parameter.

If I amend the code to
`@Html.ActionLink(Fields.New, "New", new { }, new { @class = "btn btn-success new-button" })`

The code works as expected and renders the following HTML:
`<a class="btn btn-success new-button" href="/items/new">New</a>`

**Comment by khellang** [comment]
Looks like there's a difference in overloads between ASP.NET MVC and ASP.NET Core.

The overload picked in ASP.NET MVC looks like this

```csharp
public static MvcHtmlString ActionLink(this HtmlHelper htmlHelper, string linkText, string actionName, object routeValues, object htmlAttributes) { }
```

In ASP.NET Core, the following overload has been added

```csharp
public static IHtmlContent ActionLink(this IHtmlHelper helper, string linkText, string actionName, string controllerName, object routeValues) { }
```

As you can see, the new overload has the same number of parameters, but has `controllerName` in the same position as `routeValues`. Since `string` is more specific than `object`, that overload is picked, which means you'd end up passing `null` as `controllerName` and the HTML attribute as `routeValues`. When you pass `new { }` instead, it will force it to use the old overload.

It's unfortunate that this overload was added when it comes to portability, but I don't think portability from ASP.NET MVC to ASP.NET Core was ever a goal.
