### ISSUE TITLE
IViewLocalizer is cached?

### ISSUE THREAD

**Issue by HenrikTP** [aspnet/Mvc#7137]
I have made an implementation of IStringLocalizerFactory and IStringLocalizer that works on a language resource db table.
Looking at examples and interface I implemented the IStringLocalizer so it takes a CultureInfo as constructor parameter and in my factory I use CurrentCulture in Create when constructing my stringlocalizers thus fixing my localizer to a specific culture. This also makes sense when looking at the method IStringLocalizer.WithCulture which is used to create a new localizer of same category but with another culture.

Everything works as expected except when changing culture, the labels of fields localized internally by IViewLocalizer are not changed. The strings produced by localizer by injection into razor views works fine as they are created each time but it seems that the localizers used by views are cached.

To make it work in view+translations I had to implement a check inside my string getters to see if culcture was changed and reload strings if nescessary. But that makes the localizers multicultural which is not my understanding of how they are supposed to be implemented.

Did I miss out on some information on how this should be implemented or is there a bug?

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, any thoughts on this?

**Comment by ryanbrandenburg** [comment]
If I understand you correctly, you created a custom `IStringLocalizer` which uses the current culture at creation as its culture, rather than the current culture when the resource is retrieved.

If so, that's not how we generally expect people to use Localizers. Generally Localizers are assumed to be multi-cultural, defaulting to the `CurrentUICulture` at the time the resource is requested. See [here](https://github.com/aspnet/Localization/blob/51549e8471c247f91d5ac57bd6f8f4c68508854b/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L207) and [here](https://github.com/aspnet/Localization/blob/51549e8471c247f91d5ac57bd6f8f4c68508854b/src/Microsoft.Extensions.Localization/ResourceManagerStringLocalizer.cs#L126). We do have the `WithCulture` function, which creates a separate `ResourceManagerWithCultureStringLocalizer`, but we don't use that in the code of Mvc or Localization, we're just making it available as an option for someone with a specific non-standard use case.

Does that answer your question?

**Comment by mkArtakMSFT** [comment]
@HenrikTP, did @ryanbrandenburg's answer help?

**Comment by HenrikTP** [comment]
Hi!
Yes @mkArtakMSFT , @ryanbrandenburg 's answer was very helpful, thank you. 
That explains why things work like they do.

/Henrik
