### ISSUE TITLE
System.IO.FileLoadException Exception occured when BaseIntermediateOutputPath is specified

### ISSUE THREAD

**Issue by yhvicey** [aspnet/Mvc#7138]
dotnet sdk version: 2.1.2
When specified BaseIntermediateOutputPath property in .csproj file and execute 'dotnet run', a FileLoadException will occur.
.csproj File:
```
...
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <BaseIntermediateOutputPath>build/obj/</BaseIntermediateOutputPath>
  </PropertyGroup>
...
```
Exception details:

> System.IO.FileLoadException: 'Could not load file or assembly 'System.ComponentModel.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

**Comment by mkArtakMSFT** [comment]
@yhvicey, can you please provide a full sample to repro the issue?

**Comment by yhvicey** [comment]
@mkArtakMSFT just create a new webapi project through dotnet cli and add BaseIntermediateOutputPath property, then run the project will repro. BTW my windows version is 1709. I'll try on linux later

**Comment by yhvicey** [comment]
@mkArtakMSFT Also occurred on ubuntu 17.10 with version 2.1.2

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please have a look? Thanks!

**Comment by NTaylorMullen** [comment]
@yhvicey if you remove the old base intermediate path (`obj` folder) you'll be able to build properly (it gets created when you `dotnet new`). 

What's happening is that once you change the base intermediate path it starts restoring / building to a new path but leaves the old one behind. Since assembly attributes files are shoved into that directory they are doubly compiled (once for the `obj` folder and once for the new `build/obj` folder).

**Comment by NTaylorMullen** [comment]
https://github.com/dotnet/sdk/issues/1497
