### ISSUE TITLE
Set Layout Page Outside of the View

### ISSUE THREAD

**Issue by nfplee** [aspnet/Mvc#7153]
I was wondering if it's possible to set the Layout page outside of the view? Please see the following for a more detailed explanation of what I'm looking for:

https://stackoverflow.com/questions/47928384/asp-net-core-set-layout-page-outside-of-the-view

If this is not possible it might be a future idea to add a hook somewhere to allow for this.

**Comment by nfplee** [comment]
I've just found the following https://stackoverflow.com/questions/39870298/how-do-i-specify-different-layouts-in-the-asp-net-core-mvc. The solution is not ideal as again it requires you to modify the view.

**Comment by pranavkm** [comment]
You could use a `IViewLocationExpander`. Here's the `LanguageViewLocationExpander` that adds search paths based on the request culture -https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/LanguageViewLocationExpander.cs#L91. Alternatively, you could calculate the path in your `_ViewStart.cshtml` instead of doing it in a result filter:

```C#
// _ViewStart
@{
Layout = ThemeLayoutCalculator.Calculate(Context, "_DefaultLayout");
}
```

**Comment by nfplee** [comment]
Thanks @pranavkm, I have added my answer to the Stack Overflow question incase it helps anyone else out.
