### ISSUE TITLE
please keep CI green in 2018

### ISSUE THREAD

**Issue by ctaggart** [aspnet/Mvc#7172]
Last time the dev branch passed CI tests was December 10. That was 22 days ago. Projects that do not maintain CI are much more difficult to contribute to. Here is how far I have to zoom out at https://github.com/aspnet/Mvc/commits/dev to see the last green CI checks.

![image](https://user-images.githubusercontent.com/80104/34469296-a834b04a-eefa-11e7-923b-2bfe08707b63.png)

**Comment by DamianEdwards** [comment]
@pranavkm

**Comment by pranavkm** [comment]
cc @ryanbrandenburg 

There's an issue with the .NET 4.7.1 that AppVeyor images have picked up which result in runtime failures. We attempted to downgrade to an older image, but that started failing too:

* https://github.com/dotnet/standard/issues/567
* https://github.com/aspnet/Mvc/pull/7069

Unfortunately neither of the suggested workarounds are very good - we don't want to retarget our tests since 461 is what we support.  Adding support to edit the generated binding redirect file seemed like overkill, considering the actual fix is coming out as part of .NET 4.7.2 which is supposed to roll out this month (❓). We'd have been a bit more motivated if our internal build agents were broken by this, however they do not have net471 installed.

**Comment by mkArtakMSFT** [comment]
So what is the plan, do we just wait for .Net 4.7.2 to roll out? @pranavkm, @ryanbrandenburg?

**Comment by pranavkm** [comment]
That was sort of what I think we had settled on when we originally discovered the failures. The other alternative would be to skip running .NET 461 tests on AppVeyor. Essentially https://github.com/aspnet/Mvc/pull/7173, but modified to skip .NET 461 tests specifically on AppVeyor. Note that this affects any repo that uses one of the types listed in https://github.com/dotnet/standard/issues/567 (`ValueTuple` being the most common cause of it all). I know Razor and Routing are affected, there may be more.

**Comment by pranavkm** [comment]
Sure, another possibility. Certainly less heavy handed than turning off all net4x tests.

**Comment by ryanbrandenburg** [comment]
I support @rynowak's suggestion, it minimizes the test loss and keeps things discover-able.

**Comment by ryanbrandenburg** [comment]
I volunteer as tribute to skip the offending tests for `net461`.

**Comment by rynowak** [comment]
https://github.com/aspnet/Mvc/pull/7184

**Comment by rynowak** [comment]
OK the current round of breaks are fixed now. 64259fe

I'm not going to make excuses for things being broken. @ctaggart thanks for pointing this out, the CI being broken like this is unacceptable.

I also want to remind everyone on the team that we're all empowered to fix something like this. If you don't know what to do, it's always OK to do **try** and do the right thing. If we decide on a better solution later, that's just how things go 😆
