### ISSUE TITLE
ModelState error "Request timed out." on OnActionExecutionAsync

### ISSUE THREAD

**Issue by clement911** [aspnet/Mvc#7195]
I'm using asp.net core mvc 2.0 on full .net and I'm experiencing an issue in an azure prod web app that I don't understand.

I have a custom `IAsyncActionFilter` and in the `OnActionExecutionAsync` I inspect `context.ModelState` and sometimes there is an error saying "Request timed out." (Key is empty string)

If I understand correctly OnActionExecutionAsync executes directly after the model binding, so how could there be a timeout? and how do I track the source?

```
public async Task OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
        {
            if (!context.ModelState.IsValid)
            {
                //context.ModelState dictionary contains a "Request timed out." entry.
...
            }
...
        }
```

Thanks

**Comment by rynowak** [comment]
My guess is that it's an issue similar to this:  https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/Formatters/InputFormatterExceptionPolicy.cs#L15

Is there an exception in the model state as well? (look in the debugger).

@kichalla - we should make sure we're logging something good in this case.

**Comment by clement911** [comment]
I don't get it.
Is there something I can do to avoid the problem?

**Comment by rynowak** [comment]
> Is there something I can do to avoid the problem?

Sorry, I don't think I provided enough information. 

It's possible that an input formatter is swallowing another exception - like the one with this message:
https://github.com/aspnet/KestrelHttpServer/blob/dfaf37cbba684a9913b79ec68fdf5ad18378c170/src/Kestrel.Core/CoreStrings.resx#L189
https://github.com/aspnet/KestrelHttpServer/blob/6584a8b5fdaba0a79c52b981cac88472bcc92d1a/src/Kestrel.Core/BadHttpRequestException.cs

So this could be a connection timing out due to inactivity - if the timeout occurs while we're trying to read the input - which is why I'm interested in the call stack. 

/cc @halter73 in case he has anything tremendous to add

-----

What we'd normally recommend for a disconnect or timeout *while a request is still sending* - is that you take the shortest path to terminate your own processing.

That might look like:
```
if (modelState.Values.Any(entry => entry.Errors.Any(error => error.Exception is BadHttpRequestException))
{
    context.Result = new EmptyResult();
}
```

**Comment by rynowak** [comment]
The behavior around input formatters swallowing all kinds of exceptions is getting an update in 2.1, which is what I linked. In the future this will just throw and bubble up the stack instead of being confusing.

**Comment by halter73** [comment]
@clement911 It's likely that you have clients uploading at less than 240 bytes/sec. If you want to allow lower upload rates, look at the "Minimum request body data rate" section of [this guide](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?tabs=aspnetcore2x#how-to-use-kestrel-in-aspnet-core-apps).

**Comment by clement911** [comment]
Thanks @halter73  this is making sense.
I think it's fair enough to throw an error if the client is too slow, however the message should be much more explicit IMO. Feel free to close this ticket if needed. I do hope the message gets clearer in the future.

**Comment by rynowak** [comment]
Personally, I think the problem with clarity is that MVC's model binding is swallowing the exception. You'd have a really clear view of what's going on from the call stack otherwise.

Do you have a suggestion for what other information you'd want to see in the error message? Keep in mind these messages are not intended to be user facing, they are for the developer or someone looking at the logs of the app.

**Comment by clement911** [comment]
When I read "Request timed out" I immediately thought of a performance issue with my app. If the message had said something like "The configured minimum request body data rate was breached. Terminating request.", it would have been much clearer. A link to documentation on how to tweak the rate would be ideal.

**Comment by rynowak** [comment]
Thanks! I'm going to move this issue to the Kestrel repo so those folks can figure out how to improve this error case.

**Comment by rynowak** [comment]
This issue was moved to aspnet/KestrelHttpServer#2245
