### ISSUE TITLE
Question: resolving scoped service in singleton

### ISSUE THREAD

**Issue by AccessViolator** [aspnet/Mvc#7267]
MVC does something with DI scopes that prevents me from resolving a scoped service inside a singleton service, e.g. if I have services like this
```
    public interface IMyScoped
    {
        string Greet();
    }

    public class MyScoped : IMyScoped
    {
        public string Greet()
        {
            return "Hello";
        }
    }

    public interface IMySingleton
    {
        string Greet();
    }

    public class MySingleton : IMySingleton
    {
        private IServiceProvider _serviceProvider;

        public MySingleton(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public string Greet()
        {
            var scoped = _serviceProvider.GetRequiredService<IMyScoped>();
            return scoped.Greet();
        }
    }
```
and resgister IMyScoped as scoped and IMySingleton as singleton, then inject IMySingleton into a controller and call Greet() on it, GetRequiredService() throws Cannot resolve scoped service IMyScoped  from root provider.
If in Startup I save service provider to a globally accessible static variable, and then use that in MySingleton instead of injecting IServiceProvider, it works, but I'm not sure if it's safe to do so.

What's the proper way of achieving this?

**Comment by davidfowl** [comment]
You need to create a scope to resolve your scoped service from. Why is the service scoped? What were you trying to achieve?

**Comment by AccessViolator** [comment]
Basically I have a bunch of services that I'd prefer to keep singleton, but somewhere down the call stack some of them may require current user info, from a service which, apparently, has to be scoped to http context.

**Comment by davidfowl** [comment]
Then creating a scope definitely _isn't_ what you want. You may want to look at using the `IHttpContextAccessor` or explicitly passing the `HttpContext` to the method directly.

**Comment by AccessViolator** [comment]
Ok, registering  IHttpContextAccessor like so
```
services.TryAddSingleton<IHttpContextAccessor, HttpContextAccessor>();
```
and changing implementation of singleton service to
```
    public class MySingleton : IMySingleton
    {
        private IHttpContextAccessor _contextAccessor;

        public MySingleton(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
        }

        public string Greet()
        {
            var scoped = _contextAccessor.HttpContext.RequestServices.GetRequiredService<IMyScoped>();
            return scoped.Greet();
        }
    }
```
seems to do the trick.

**Comment by benmccallum** [comment]
I've got a similar issue. I can probably solve it the same way, but wondering if another DI container could solve the issue.

In my case I'm trying trying to access a scoped dependency (from within a singleton) that my middleware has set some properties on from the http request. It's unravelling some auth stuff for me so I can use that earlier, but then also pass it along to another API down the line. Since I'm creating a new scope, I get a fresh instance and not the instance that went through the middleware earlier and was setup.

My knowledge with IoC containers is weak, but would a more advanced container framework allow access from my new scope to the outer scope to get my original scoped instance?

Sorry if that's all confusing, can create some real names and code if that helps.

**Comment by davidfowl** [comment]
No nothing can solve that problem. You need an AsyncLocal for that.

**Comment by benmccallum** [comment]
Thanks David, will take a look!
