### ISSUE TITLE
Inconsistent behavior between Html Helper and Razor Attribute resolution

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Mvc#7283]
Inconsistent behavior between Html Helper and Razor

```
@Html.Hidden("index","value", new { disabled })
<input name="index" type="hidden" value="value" disabled ="@disabled"/>
```

Produces

```
<input disabled="False" id="index" name="index" type="hidden" value="value">
<input id="index" name="index" type="hidden" value="value">
```

I would expects these to be the same

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen any thoughts around this?

**Comment by NTaylorMullen** [comment]
@Tarig0 we don't special case the disabled attribute in your `HtmlHelper` line, we don't special case any attributes that are passed into HTML helpers really (other than `class`). In your non-HTML helper line there's also no TagHelper applying to do that.

Maybe I'm not understanding the concern.

**Comment by Tarig0** [comment]
I guess the issue is that with razor I can do disabled ="@false" and this will omit disabled. 
When I switched to the html helper and pass {"disabled": false} this will emit the disabled="false" tag which for chrome, at least, means disable the input.

I found this out when I created my own helper to emit the last index found in the template htmlfieldprefix which I needed to disable for certain situations.

**Comment by NTaylorMullen** [comment]
@Tarig0 Ah, I see your concern now; very interesting. As nice as it would be to have a feature turned on like that (for consistency especially) it's not something we could do given the precedent of HTML Helpers. It'd be a massive behavior change for anyone who currently has HTML Helpers basically.

If we were going to pursue a feature like this it'd have to be in a major release candidate. Given the level of behavior change this would be my recommendation is to mark as by design and close @mkArtakMSFT. 

Sorry @Tarig0 hope you can understand 😢

**Comment by Tarig0** [comment]
Understood, since it is a breaking change. I'll be able to add the handling to my own html extensions. 

I guess another option it to swap out the default html generator.
