### ISSUE TITLE
MultipartReader Instance Method (ReadNextSectionAsync) throws IOException: Unexpected end of Stream, Error.

### ISSUE THREAD

**Issue by abunet** [aspnet/Mvc#7328]
@pranavkm in ref #7227, I've created a sample solution with client and server. It reproduces the exception

[MultipartReaderError.zip](https://github.com/aspnet/Mvc/files/1691823/MultipartReaderError.zip)

I have two post urls, they do the same thing (read a multipart stream).
The only difference between the two methods is that the second as a DI [FromServices] parameter.

```
        [HttpPost]
        [Route("upload")]
        public async Task<IActionResult> Upload()
        {
            try
            {
                Models.Document document = await this.GetDocumentFromRequest();
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return Ok();
        }

        [HttpPost]
        [Route("upload_with_exception")]
        public async Task<IActionResult> UploadWithException([FromServices] DocumentService docSvc)
        {
            try
            {
                Models.Document document = await this.GetDocumentFromRequest();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return StatusCode(StatusCodes.Status500InternalServerError);
            }

            return Ok();
        }
```

**Comment by pranavkm** [comment]
Thanks. The `FromServices` attribute probably results in all value provider factories to kick in and result in the `FormValueProviderFactory` to eagerly read the request body. You'll need to explicitly disable this value provider since you're taking over the body parsing. See https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Controllers/FileController.cs#L43 and https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.FileUpload/Filters/DisableFormValueModelBindingAttribute.cs.

Out of curiosity, is there a reason you're attempting to read `Document` manually? It looks like you could replace it with an `IFormFile` instance instead and just have model binding do the leg work.

**Comment by abunet** [comment]
another workaround (in my case) is to inject the service into the controller constructor instead of using [FromServices].

In the real project, I have a complex dto with multiple attributes that embeds one or more files. So I've found the doc that talks about performance dealing with large files. 
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/file-uploads#uploading-large-files-with-streaming.

I need to upload from a dotnet full 4.x client and I'm trying to have as few dependencies as possible. 
I'm considering whether to use MessagePack instead.

**Comment by pranavkm** [comment]
The doc does recommend the filter and I'd encourage using it since it makes things more obvious - things wouldn't break if future you accidentally add a parameter to these actions 😄. Closing this issue, feel free to reopen if you have more questions around this.
