### ISSUE TITLE
No Page Named "Foo" when Custom Page Route is Added And Optional Parameter Removed From RouteData

### ISSUE THREAD

**Issue by mdarrik** [aspnet/Mvc#7342]
So I'm working with a Razor Page where the Page "/Index" has an optional parameter {Project?}. When the optional parameter is an invalid value, I want to redirect users back to Index with the optional parameter clear. To do this, I'm doing the following: 

```
                RouteData.Values.Remove("TeamProject");
                return RedirectToPage(RouteData.Values);
```

When I include a custom Route like so:
`options.Conventions.AddPageRoute("/Index","{TeamProject}/home");`
This always produces an error titled like so: 
InvalidOperationException: No page named '' matches the supplied values.

If I remove the AddPageroute call, the error disappears and the RedirectToPage executes fine. 
The same thing occurs if instead I do:
```
RouteData.Values.Remove("TeamProject");
return RedirectToPage("/Index")
```

Per #6957 I've tried adding in `options.Conventions.AddPageRoute("/Index","")` and still get the same error. 
Browsing works fine in the browser, and in other places I've used ```RedirectToPage("/Index")``` without clearing the TeamProject from the RouteData and it works fine. 

I'm sure the upcoming update will probably fix this, but I'm more curious what I'm doing wrong than anything.

**Comment by mkArtakMSFT** [comment]
@rynowak, any suggestions?

**Comment by rynowak** [comment]
Routed added by `AddPageRoute` are treated as the 'preferred' out for URL generation and will cause other routes to suppress URL generation. That's handled by the code here: https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.RazorPages/DependencyInjection/PageConventionCollectionExtensions.cs#L471


This means that when you add the route `{TempProject}/home` in startup code that route will always be used for URL generation. Since you are trying to generate a URL without a `TeamProject` value this will fail. 

---
More generally, what's the user experience you want?
