### ISSUE TITLE
Question: Why model accessor is swallowing NullReferenceException?

### ISSUE THREAD

**Issue by jo-ninja** [aspnet/Mvc#7378]
### Minimal repro steps
1. Enable Visual Studio 2017 Exception Settings: System.NullReferenceException
2. Create custom class ViewModel, ex: SampleViewModel
3. Add MVC View using Visual Studio Add View dialog.
    - View name: Sample
    - Template: Create
    - Model: SampleViewModel

4. Add new Sample action on controller and return View() without passing our SampleViewModel object
5. Access the page from browser

Please refer to https://medium.com/@joni2nja/friends-dont-let-friends-swallow-nullreferenceexception-acd949833d70 for detail repro steps with screenshots.

### Expected result
I would expect the model accessor does not swallow the NullReferenceException.

### Actual result
Visual Studio will break on NullReferenceException, swallowing it and returns null.

### Question
I might have missed something, but why model accessor is swallowing NullReferenceException when it sounds like a null check guard should be added to avoid throwing exception?

**Comment by mkArtakMSFT** [comment]
@rynowak, do you have any thoughts regarding this?
I feel like there are some historical reasons for this, which I'm not sure are valid any more.

**Comment by rynowak** [comment]
The model object will be null when you have a "Create" view - this is a mainline scenario.

That means that a form like:
```
<form ...>
   <input asp-for="CustomerId" ... />
</form>
```

That wants to access `Model.CustomerId` will have to deal with the model being null in a mainline scenario. 

As to why our strategy is to **specifically* handle nullref in this common scenario.. it's an old issue that no one has fixed. We could do what the post suggests and specifically avoid the nullref in that case and a few other specific cases but we'll never totally be rid of this due to compat concerns.

**Comment by mkArtakMSFT** [comment]
Let's keep this bug to try to reduce the cases where NullRef can be thrown. I understand we won't be able to eliminate all those cases, but reducing it, especially if it'll be relatievely easy effort, will be great.

**Comment by jo-ninja** [comment]
@rynowak, thanks for the clarification.
@mkArtakMSFT, I agree with you. Thanks for adding this to the future milestone.

**Comment by pranavkm** [comment]
> Let's keep this bug to try to reduce the cases where NullRef can be thrown. 

Dup of https://github.com/aspnet/Mvc/issues/6928.
