### ISSUE TITLE
Password isn't rendered in the view

### ISSUE THREAD

**Issue by ygoe** [aspnet/Mvc#7402]
In my application's Change Password view, I request the user to enter the current and the new password. If something isn't correct, an error message is displayed for the appropriate input field. So if the current password is correct but the new password isn't allowed or something, the following happens:

* The current password has no error, but after submitting the form and returning back to it, it's empty
* The new password has an error message and is now empty, too

The issue is that the validation only represents what the user has provided, but doesn't consider what MVC has changed. It doesn't output passwords into their corresponding text fields at all, thereby producing more errors than indicated.

I've found some clues that this is supposed to be a "security measure" to prevent me from accidently leaking plain passwords to the UI where they could be recovered. This cannot possibly happen to me because I never store plain passwords in the system. And I also take great care to not make such mistakes.

So, after I have acknowledged this warning, can you please put me back into control and let me disable that behaviour so that any form input behaves just like I'd expect it to do?

**Comment by mkArtakMSFT** [comment]
@javiercn, is there any way to force MVC to maintain the filled in values in the credential fields? /cc @blowdart

**Comment by javiercn** [comment]
I do believe this is by design. This is the behavior MVC has had for password input fields for a long time. @blowdart can provide details about the specific reasons why this is done. 
This is also the same behavior most sites have when dealing with users credentials.

You can change that view to have whatever logic you want and write the form inputs yourself using `@Html.ValueFor())`

**Comment by ygoe** [comment]
Is there any more information about it that [this stub](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.rendering.htmlhelpervalueextensions.valuefor?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.AspNetCore.Mvc.Rendering.HtmlHelperValueExtensions.ValueFor%60%602);k(DevLang-csharp)%26rd%3Dtrue%26f%3D255%26MSPPError%3D-2147217396&view=aspnetcore-2.0)?

**Comment by javiercn** [comment]
@dougbu Can you provide more details about this?

**Comment by dougbu** [comment]
> an error message is displayed for the appropriate input field.

If you have client-side validation enabled, the error is correct: The password hasn't been entered or reentered.
> This cannot possibly happen to me because I never store plain passwords in the system.

Whether or not passwords are secure within your system is not the issue here. Round-tripping a password back to the browser would expose it on the page. The basic idea is to shorten the period in which someone else could view the page source and to minimize the requests and responses containing the (plain text) password.
> `@Html.ValueFor()`

Not much to say about this guy. It does what you'd expect, including round-tripping an invalid submitted value. The suggestion is to use it as the attribute value e.g.
``` html
<input asp-for="PasswordProperty" value="@Html.ValueFor(m => m.PasswordProperty)"/>
```
Again, this is **strongly** not recommended.

**Comment by blowdart** [comment]
As everyone said this is very much by design, it's not going to change, otherwise you can end up round tripping passwords into a page, and that, in the case of an XSS exploit is very bad news.

**Comment by ygoe** [comment]
Well, if you have malicious scripts running on your page, even entering a password is bad. My current situation is a Change Password form and if the new password is rejected by the server (for example because it's too simple – a decision hard to implement client-side and hard to know for the user), then at least the correct current password should remain intact. Either way, I understand your repeated concerns, and I have found a solution to handle this framework deficiency.
