### ISSUE TITLE
InvalidOperationException: Cannot find compilation library location for package ...

### ISSUE THREAD

**Issue by michaelestermann** [aspnet/Mvc#7421]
I created a new ASP.NET core mvc project and created a xunit project beside. For the views, we created an own project which contains embedded views. To make this work, we use an EmbeddedFileProvider which points to this project. 
As long as i run the unit tests within Visual Studio or with dotnet test, it works as expected. As soon as I use dotnet xunit, it fails with the exception "InvalidOperationException : Cannot find compilation library location for package 'Repro'"

I already tried the fixes from these threads, but they won't work when using embedded files in another project: 
https://github.com/dotnet/core-setup/issues/3614
https://github.com/dotnet/core-setup/issues/3494

I created a repro:  https://github.com/michaelestermann/ReproRazorCompilationIssue
Just fetch it and run dotnet xunit in the "Repro.Views.Test" folder and you'll face the exception.

We didn't manage to fix this. I think we use 'dotnet test' as long as its not working. Its not as nice as the 'dotnet xunit' because of the lack for teamcity support (dotnet xunit -teamcity).

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. One of our team members will look into it and get back to you.
@javiercn, can you please look into this?

**Comment by javiercn** [comment]
Unlike `dotnet test`, `dotnet xunit` doesn't run the tests in the context of your application, so all these types of errors happen and there's not really anything we can or are willing to do at this level.
Razor depends on 2 things to work correctly:
1) The content root path must be set to the application folder in order to find views.
2) The framework needs to be able to find the .deps file in order to resolve dependencies.

dotnet xunit doesn't run your app in the same way dotnet test does (in the context of your app) so it's not really possible for us to do anything.

That said, I do believe that the new upcoming 2.1 support for compiling Razor Views into assemblies will allow you to achieve your scenario by compiling your views into an assembly instead of using embedded files. See https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries/ for details
