### ISSUE TITLE
Weird DictionaryModelBinder? bug with guids when the guid's first character is not a number

### ISSUE THREAD

**Issue by keenjus** [aspnet/Mvc#7423]
I seem to have stumbled across a weird bug with modelbinding a dictionary that uses guids as keys.

Submitting a form like this:
Form data: `data[912cd1ad-52c0-40cb-9644-55f2eb180a97][somevalue]=test`
Action: `public IActionResult OnPost(Dictionary<string, TestViewModel> data)`

This will work as expected and I can access the value by `TestViewModel.SomeValue`

But if you happen to submit a guid that does not start with a number ex: `e67d6af7-ff03-4204-8de1-5b021713407d` or just replace a guid's first character with any letter.

`data[e67d6af7-ff03-4204-8de1-5b021713407d][somevalue]=test` FAIL
`data[a12cd1ad-52c0-40cb-9644-55f2eb180a97][somevalue]=test` FAIL
`data[112cd1ad-52c0-40cb-9644-55f2eb180a97][somevalue]=test` SUCCESS

I don't know how to explain this better but I've prepared a sample project and a demo site

Source: https://github.com/keenjus/DictionaryModelBinderBugExample
Demo: http://dictionarymodelbinderbugexample.azurewebsites.net/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. @dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
The model binding failures happen as a result of MVC's key rewriting to handle jQuery submissions. That rewrite is _almost_ all-or-nothing and a mix of collection and properties in the model types will not quite match. The "_almost_" part leads to the inconsistency you observed -- individual keys are not rewritten when they look a bit like array indices. The GUID starting with a number is enough to confuse the system and make things work here.

## Workarounds
Possible workarounds include:
1. Switch the jQuery code to submit JSON. I created a PR (keenjus/DictionaryModelBinderBugExample#1) demonstrating this approach.
2. Use only GUIDs that start with a number i.e. always confuse the system. Yup, ugly.
3. Avoid jQuery i.e. use a regular `<form>`. Yup, ugly.

## Details
In the starts-with-a-number case, the `JQueryFormValueProvider` contains the key `data[912cd1ad-52c0-40cb-9644-55f2eb180a97].somevalue` where in the starts-with-non-number case, this value provider contains the key `data.fa19cae8-abaa-48af-b39b-8bdc45c05c6f.somevalue`. This doesn't work in the second case because the `DictionaryModelBinder` is looking for `data[fa19cae8-abaa-48af-b39b-8bdc45c05c6f].somevalue`.

## Possible fixes
One option is to change the `JQueryFormValueProviderFactory` to remove the inconsistency. Then, both cases in this scenario would rewrite the GUID key and fail to bind ☹️. The important code is this block, which does not attempt to parse the entire key as an `int` or even check whether all characters are numeric: https://github.com/aspnet/Mvc/blob/90b07a9e9a3f276e69197dee1e1801add61d28d8/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/JQueryKeyValuePairNormalizer.cs#L81-L85

Another option is to change this provider factory so that `JQueryFormValueProvider` contains all possible mixes of collection and property notation. In this case, the provider would contain `data.fa19cae8-abaa-48af-b39b-8bdc45c05c6f.somevalue`, `data[fa19cae8-abaa-48af-b39b-8bdc45c05c6f].somevalue` and `data.fa19cae8-abaa-48af-b39b-8bdc45c05c6f[somevalue]`. (`FormValueProvider` always contains the original key -- `data[fa19cae8-abaa-48af-b39b-8bdc45c05c6f][somevalue]`.)

**Comment by dougbu** [comment]
Clearing all labels and my assignment&hellip;

**Comment by dougbu** [comment]
After a quick internal discussion, marking this as a bug.

Preferred fix isn't mentioned above: Change the `DictionaryModelBinder` to try both `ModelName[Key]` and `ModelName.Key`. In this case, the model binding system would find both `data[912cd1ad-52c0-40cb-9644-55f2eb180a97].somevalue` and `data.fa19cae8-abaa-48af-b39b-8bdc45c05c6f.somevalue`. This fix has is quite cheap and few (if any) back-compatibility issues because it _increases_ the cases where the model binding system succeeds.

**Comment by dougbu** [comment]
cc5ae02b7d
