### ISSUE TITLE
Minus sign for negative numbers in DisplayFor 

### ISSUE THREAD

**Issue by vanillajonathan** [aspnet/Mvc#7456]
`Html.DisplayFor` should render a negative number using a proper typographical minus sign instead of a hyphen sign.

Example `-123` would be outputted as `−123` or `&minus;123`.

**Comment by mkArtakMSFT** [comment]
Hi @vanillajonathan. Thanks for contacting us.
The character currently being rendered is [`Hyphen-Minus`](https://unicode-table.com/en/002D/) and the behavior you're observing is by design.
From [Wikipedia](https://en.wikipedia.org/wiki/Hyphen#In_computing): "_In Unicode, the hyphen-minus is encoded as U+002D (-) so that Unicode remains compatible with ASCII. However, Unicode also encodes the hyphen and minus separately, as U+2010 (‐) and U+2212 (−) respectively_"
