### ISSUE TITLE
Routing breaks when passing multiple query parameters

### ISSUE THREAD

**Issue by mkArtakMSFT** [aspnet/Mvc#7536]
Here is what I'm observing: 
![image](https://user-images.githubusercontent.com/34246760/37846183-17a770b0-2e8a-11e8-8c3f-650babb7caf3.png)
As you can see, the `Request.Querystring` is incorrectly parsed, while in the browser my actual request link is such:
![image](https://user-images.githubusercontent.com/34246760/37846237-40275ae6-2e8a-11e8-8d70-9a48b7f6a4f5.png)
 
Here what my project file looks like: https://github.com/mkArtakMSFT/GitHubMilestoneTracker/blob/master/src/MilestoneTracker/MilestoneTracker.csproj

**Comment by rynowak** [comment]
This looks like the query string was encoded incorrectly. `&amp;` is an XML entity and has no meaning in a URL. How did you build the query string?

**Comment by kichalla** [comment]
For reference, the url was being generated here:
```#html
<script type="text/javascript">
    google.charts.load('current', {
        packages: ['corechart', 'line']
    });
    google.charts.setOnLoadCallback(LoadData);

    function LoadData() {
        $.ajax({
            url: '@Url.Action("GetBurndownDataAsync", "Burndown", new { teamName= Model.TeamName, milestone=Model.Milestone })',
            type: 'GET',
            dataType: 'json',
            //contentType: "application/json; charset=utf-8",
            success: function (data, err) {
                PopulationChart(data);
                return false;
            }
        });

        return false;
    }
```
Thanks @Eilon for helping me diagnose through this and explaining it through. Based on our offline discussion, this is by design and following are the details:
- Normally if we were doing `Url.Action` from let's say within a conroller's action, it would return a url which has been url encoded and is `/MilestoneBurndown?teamName=ASP.NET MVC&milestone=2.10-preview2` (note the `&`)
- Now since `Url.Action` is being called from Razor like `@Url.Action`, this presence of `@` causes "any" content to be Html encoded. In our case the "any" content happens to be a url and so we are seeing `&` getting converted to `&amp;`. To fix this we could change `@Url.Action` to `@Html.Raw(Url.Action` which will prevent the html encoding.
- One more way to fix this issue would be to use let's say a `<div>` tag with `data-` attribute in which we could do the following. 
`<div id="test" data-url="@Url.Action(....)" />`  
In this case the content of the `data-url` attribute is html encoded (as we have seen earlier), but the browser's in-memory representation of this attribute value is a html decoded one and this is the one we would get when we read from Javascript (ex: `$(#test).attr("data-url")`). The advantage of using `data-` attribute is that instead of doing `@Html.Raw(Url.Action` and possibly causing invalid html to be rendered, we could render valid html in `data-` attribute.

**Comment by mkArtakMSFT** [comment]
Ok guys, thanks for looking into this. But that's not really the case here. It seems my second image in the issue isn't very obvious, so pasting it here again:

![image](https://user-images.githubusercontent.com/34246760/37855344-14d89c8e-2eac-11e8-8a4d-2c9ddccf959e.png)

As you can see, the link in browser has the '&' sign not encoded, so we should probably look into this further.

**Comment by rynowak** [comment]
What does fiddler say? Browsers do lots of things. HTTP is truth.

**Comment by mkArtakMSFT** [comment]
Will the view in dev-tools view help?
![image](https://user-images.githubusercontent.com/34246760/37855483-bba84366-2eac-11e8-8f44-446025049cd6.png)

The proper `&` is in URL.

**Comment by Eilon** [comment]
So the incorrect `&amp;` is showing up only in `Request.QueryString`? That is super, super weird...

**Comment by kichalla** [comment]
@mkArtakMSFT I took a look at the app and wondering if this is what's happening here.

The url points to a razor page `MilestoneBurndown` and this page has a html partial to `BurndownChart` which has the Javascript to load the data using the problematic url that I gave details about. As far as I can tell, the url in the browser is probably not the one being sent to `GetBurndownDataAsync` method.

**Comment by mkArtakMSFT** [comment]
@kichalla very good point. you may be right - checking on it now.

**Comment by mkArtakMSFT** [comment]
Ok, you're right - I was looking to a completely wrong query, as was confused myself
![image](https://user-images.githubusercontent.com/34246760/37857019-0f237b98-2eb5-11e8-9605-d8eceb31c04b.png)
Sorry for confusing you all guys, it's coming from JS indeed. Will look into this and fix. Thanks!
