### ISSUE TITLE
View precompilation during publish in 2.1-latest only works if using 2.0.0 reference

### ISSUE THREAD

**Issue by mnmr** [aspnet/Mvc#7586]
As I understand it, if you reference the Microsoft.AspNetCore.Mvc.Razor.ViewCompilation package, then views are supposed to be pre-compiled during publish.

This only works for us if we reference version 2.0.0 of the package, as opposed to the 2.1 version matching the other packages (we're using "2.1.0-*" to reference the latest stable CI build).

**Comment by pranavkm** [comment]
Are you also using newer builds of the CLI \ Sdk (https://github.com/dotnet/versions/tree/master/build-info/dotnet/product/cli/release/2.1)? For 2.1.0, we're deprecating the precompilation tool in favor of Razor.Sdk that does build and publish time compilation (see https://github.com/aspnet/Razor/issues/1740). In essence, using the latest (preview2) builds of the precompilation tool require some changes from the Sdk.

**Comment by mnmr** [comment]
Ah, that might be it - thanks!

**Comment by pranavkm** [comment]
Great. There's a 2.1.0-preview2 release slated to be released soon and that should resolve this issue. In the meanwhile, I'd encourage staying on the preview1 builds (https://blogs.msdn.microsoft.com/webdev/2018/02/27/asp-net-core-2-1-0-preview1-now-available) just so that you aren't affected by transient build and migration issues.
