### ISSUE TITLE
 The 'Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.TempDataSerializer' cannot serialize an object of type 'Microsoft.Extensions.Localization.LocalizedString'.

### ISSUE THREAD

**Issue by oferns** [aspnet/Mvc#7592]
Surely it should be able to handle this? Is there not an implicit conversion to string?

**Comment by Eilon** [comment]
Do you specifically want to store the localized string itself (e.g. `bonjour`), or the actual LocalizedString object, which contains the localized string as well as other pieces of information (such as whether the resource was found)? I'm not sure there's a big scenario for storing the actual LocalizedString, but please elaborate if you feel otherwise.

**Comment by oferns** [comment]
Yeah. I was hoping to use the info to highlight missing translations but I can pass it otherways..Ill close the issue
