### ISSUE TITLE
Classic Area Registration

### ISSUE THREAD

**Issue by oferns** [aspnet/Mvc#7599]
Am I right in thinking that the only way to register an area is to use the AreaAttribute? I used to be able to inherit from a class call AreaRegistration and call RegisterAllAreas(). Can I no longer do this? Do I have to remember to put an attribute at the top of my controller classes? If so, can anyone suggest a way of implementing a class that does what AreaRegistration used to? Or is there a compelling reason not to?

thanks
O

**Comment by mkArtakMSFT** [comment]
@pranavkm, can you please answer this question?

**Comment by pranavkm** [comment]
MVC Core does not have an built-in mechanism similar to `AreaRegistration`. When we designed areas, we found that it was much more compelling to be able to explicitly specify the area per controller rather than have something opinionated like AreaRegistration. If you do feel strongly about wanting to avoid specifying `AreaRegistration` per controller type, you could

a) Derive from a controller base type per area that has the `AreaAttribute`.
b) Use a convention, something along the lines of https://github.com/aspnet/Entropy/blob/dev/samples/Mvc.CustomRoutingConvention/NameSpaceRoutingConvention.cs#L6-L29, to determine types that belong to area namespace and register them.

**Comment by pranavkm** [comment]
@oferns here's the doc article for it - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/application-model

**Comment by mkArtakMSFT** [comment]
Thanks @pranavkm.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
