### ISSUE TITLE
"AllowEmptyStrings = true" does not work

### ISSUE THREAD

**Issue by fatih108** [aspnet/Mvc#7630]
This my ViewModel, why "AllowEmptyStrings = true" does not work. ModelState always invalid.

```
    public class LoginViewModel
    {
        [Required(ErrorMessage = "EmailRequired")]
        public string Email { get; set; }

        [Required(ErrorMessage = "PasswordRequired",AllowEmptyStrings = true)]
        public string Password { get; set; }
    }
```

**Comment by mkArtakMSFT** [comment]
Hi @fatih108.
Can you please share a repro project with us as well as share details about how you use it? What browser version do you have?

**Comment by mkArtakMSFT** [comment]
Thanks @fatih108.
One of our engineers will look into this and get back to you.

**Comment by mkArtakMSFT** [comment]
@ryanbrandenburg, can you please look into this?

**Comment by ryanbrandenburg** [comment]
@fatih108 your model.Password isn't actually string.empty in the case that you don't enter any values on your app, it's `null`.

It's possible you could accomplish this using hidden input fields and/or Javascript, but I wonder what the use case of distinguishing between `null` and `string.empty` from the form is? I suspect that your user-facing models don't actually need `AllowEmptyStrings=true`, because if being empty were OK, then this field wouldn't actually be `Required`.

**Comment by fatih108** [comment]
@ryanbrandenburg  I know that, my problem only whitespace (5 white spaces). This code working with ASP.NET MVC 6. This approach changed with .ASP Net Core?

**Comment by mkArtakMSFT** [comment]
@fatih108, are you saying that you set the value to something like `     ` and it is not getting through to the service?
@ryanbrandenburg, can you please try to repro that.

**Comment by fatih108** [comment]
@mkArtakMSFT Yes, Value white spaces not working.  Example value="    ";

**Comment by fatih108** [comment]
I added this code, `[DisplayFormat(ConvertEmptyStringToNull = false)]` and working now.
thank you for interest.
