### ISSUE TITLE
Provide an ability to configure the HTTP client created by WebApplicationFactory<T>

### ISSUE THREAD

**Issue by martincostello** [aspnet/Mvc#7635]
I'm using `WebApplicationFactory<T>` for some tests where I need to configure `HttpClient` appropriately with some default headers in order for the application to accept requests as valid.

Because all the `HttpClient Create*Client()` methods are non-virtual, it's not possible for me to override any of the implementations to set the headers before returning the client, so I need to make my own method and get all my tests to call that instead (`CreateValidClient()`) rather than have the fixture handle it for the consumers of it transparently.

It would be much easier to use `WebApplicationFactory<T>` in these tests if some (if not all) of the methods for creating `HttpClient` instances were virtual.

This is similar to #7631 which also requests changes to make it easier to make derived classes from `WebApplicationFactory<T>`.

**Comment by martincostello** [comment]
#7638

**Comment by mkArtakMSFT** [comment]
Hi @martincostello.
Can you please update the title to reflect what exactly the change is. The intent is more to have an ability to configure the created client, rather than return something else (this is inline with my review comments).
Something like "Provide an ability to configure the client created by `WebApplicationFactory<T>`".

**Comment by martincostello** [comment]
@mkArtakMSFT Done 👍
