### ISSUE TITLE
ApiController: [FromBody] param is always null (Lazy Loader)

### ISSUE THREAD

**Issue by JoelNietoTec** [aspnet/Mvc#7872]
Version: .NET Core 2.1

I have a PUT method where I'm receving a JSON object via [FromBody] param, but while debugging, the value is always null. I think this have something to do with the fact that the class has related data through lazy loading.

This is the class:
```csharp
using Microsoft.EntityFrameworkCore.Infrastructure;
using System;
using System.Collections.Generic;

namespace WebAPI.Models.Settings
{
    public partial class Bank
    {
        private Bank(ILazyLoader lazyLoader)
        {
            LazyLoader = lazyLoader;
        }

        private ILazyLoader LazyLoader;
        public int Id { get; set; }
        public int BankTypeId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }

        private BankType _type;

        public BankType Type
        {
            get => LazyLoader?.Load(this, ref _type);
            set => _type = value;
        }
    }
}
```

**Comment by mkArtakMSFT** [comment]
Hi @JoelNietoTec.

What is happening is your model binding is failing. You should see the actual error in the `ModelState`.

The problem is that MVC is looking for a public parameterless constructor on your DTO / model type, which it can't find. Consider having a separate type as a DTO which you can then map to your entity type as necessary after successful model binding.
