### ISSUE TITLE
When SetCompatibilityVersion(CompatibilityVersion.Version_2_1) is present then custom model binding does not work

### ISSUE THREAD

**Issue by Oblomoff** [aspnet/Mvc#7916]
#### Description of the problem:

When SetCompatibilityVersion(CompatibilityVersion.Version_2_1) is present then custom model binding does not work.

#### Steps to reproduce

- Download attached Sample project [Sample.zip](https://github.com/aspnet/Mvc/files/2102594/Sample.zip)
- dotnet run
- Go to https://localhost:5001/Home/About?type=string. The message is "Your type: ".
- Stop project
- Edit Startup.cs:  remove line .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
- dotnet run
- Go to https://localhost:5001/Home/About?type=string. The message is "Your type: System.String".

Manual steps 

Create new ASP.NET 2.1 MVC  project

```PowerShell
dotnet new mvc
```
Add simple Model Binder for example
```c#
    public class StringTypeBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {       
            bindingContext.Result = ModelBindingResult.Success(typeof(string));
            return Task.CompletedTask;
        }
    }
````

Use those binder like this:

```C#
        public IActionResult About([ModelBinder(typeof(StringTypeBinder))] Type type)
        {
            ViewData["Message"] = $"Your type: {type}";

            return View();
        }
```

Ensure this line in Satrtup.cs

```C#
     services.AddMvc()
                // Comment or uncomment the line below.    
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1)
            ;
```

Go to https://localhost:5001/Home/About?type=string. The message is "Your type: ".

Ensure the type parameter of method About is always null.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Oblomoff.
@dougbu, can you please look into this?

**Comment by dougbu** [comment]
@danroth27 @mkArtakMSFT @rynowak removing or overriding `ExcludeBindingMetadataProvider` is a bit cumbersome because that provider has no `public` properties. We could add a `Type` property to make the following possible:
``` c#
services
    .AddMvc()
    .SetCompatibilityVersion(Microsoft.AspNetCore.Mvc.CompatibilityVersion.Version_2_1)
    .AddMvcOptions(options =>
    {
        for (var i = options.ModelBinderProviders.Count - i; i >= 0; i--)
        {
            if (options.ModelBinderProviders[i] is ExcludeBindingMetadataProvider provider &&
                provider.Type == typeof(Type))
            {
                options.ModelBinderProviders.RemoveAt(i);
            }
        }
    });
```
We could also go further and take the `FormatterCollection` approach for `MvcOptions.ModelValidatorProviders`, providing helpers like `RemoveExclusion(Type type)`.

Separately, I'm not sure the prior behaviour of ignoring `BindingMetadata.IsBindingAllowed` for all parameters was intended but it's been that way since 1.0.0 RC2. Other `BindingMetadata` flags that were previously ignored for non-properties are `IsBindingRequired` and `IsReadOnly`. Suggest we add a `CompatibilitySwitch` named (say) `AllowParameterBindingMetadata` that's `true` in 2.1 mode and later. The new switch would control how these 3 `ModelMetadata` properties behave w.r.t. `BindingMetadata`. Then @Oblomoff would have a one-line way to restore the 2.0 and earlier behaviour without affecting much else.

**Comment by dougbu** [comment]
Clearing my assignment and the `investigate` flag. Over to you **Triage** team,

**Comment by danroth27** [comment]
> There's a default IBindingMetadataProvider of type ExcludeBindingMetadataProvider which sets BindingMetadata.IsBindingAllowed to false for any property or parameter of type `Type`

Do we know why?

> But, historically, `ModelMetadata.IsBindingAllowed` always returned `true` for action parameters -- ignoring the `BindingMetadata`. In 2.1 mode, the `BindingMetadata` flag is checked and the exclusion for Type is honoured.


Do we know why this behavior was changed?

**Comment by dougbu** [comment]
> Do we know why?

MVC excludes binding `Type` properties (previously) and `Type` parameters and properties (in 2.1 and later) because `Type` has loads of properties and is thus very expensive to bind.

> Do we know why this behavior was changed?

Introducing `ModelMetadataKind.Parameter` changed everything. As part of that change, `DefaultModelMetadata` began honouring `BindingMetadata.IsBindingAllowed`, `BindingMetadata.IsBindingRequired` and `BindingMetadata.IsReadOnly` for parameters. In most cases, that change is a **Good Thing:tm:**. But, we don't have a focused `CompatibilitySwitch` to turn if off.

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu!
@Oblomoff, given the easy workaround we plan doing nothing else here. The behavior here is by design.
