### ISSUE TITLE
ModelState.IsValid always returns true when no call to SetCompatibilityVersion

### ISSUE THREAD

**Issue by tstivers1990** [aspnet/Mvc#7933]
#### Is this a Bug or Feature request?:
I'm not certain if this is a bug or there's something I'm not aware of. If it's not a bug and in fact intended behavior, I feel like there should be a runtime or compile time error somewhere, as this is rather difficult to track down.

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
https://github.com/tstivers1990/ModelStateIsValidRepro

Repro is on the `Repro` page.

Disable JavaScript to submit the form without putting anything in the field.

#### Description of the problem:
When no call is made to `SetCompatibilityVersion` or the parameter passed to this call is `CompatibilityVersion.Version_2_0`, `ModelState.IsValid` always returns `true`.

I've tested this using `[BindProperty]` on the property instead of `[BindProperties]` on the class and it yields the same result.

**Comment by pranavkm** [comment]
Support for validation on top level properties is behind a compatibility flag since it breaks certain scenarios (https://github.com/aspnet/Mvc/issues/7413). Requiring the 2.1 compatibility feature of setting `MvcOptions.AllowValidatingTopLevelNodes` is required to enable validaton for top-level page model properties.

**Comment by pranavkm** [comment]
We wouldn't be able to do a compile time (analyzer for instance) for this since determining the state of things requires running code. A runtime error is also problematic since it would break existing apps that had erroneously put the attribute on top level properties and parameters and had it no-op in earlier releases. The best solution might be a logger warning, but it's generally not the place users go to to locate configuration errors.

**Comment by tstivers1990** [comment]
I think there should at least be some warning. If a compile or runtime error isn't feasible, then at least a log warning would be desirable. The main issue I notice is the fact that everything appears to work as expected until testing is done with JavaScript disabled. It's something that's very easy to overlook and create issues down the road that are very difficult to detect beforehand without prior knowledge of the quirk. Even detecting it in automated tests is a stretch because, most will just be writing unit tests (if they're even doing that) and unit tests wouldn't really detect this. At least, I can't think of a way to unit test for it that wouldn't end up being an integration test.

Perhaps documentation could help detect this as well. Maybe the relevant documentation pages for validation should include a warning that top-level validation doesn't work under this set of circumstances.

**Comment by tstivers1990** [comment]
Perhaps a compile time warning would be appropriate? That wouldn't break pre-existing code, but would at least alert the developer to the potential issue.

**Comment by pranavkm** [comment]
@mkArtakMSFT what's the plan here? Log a warning? That seems like really poor value since it's not the place users look at when diagnosing these kinds of issues. We cannot do any build time work here.

**Comment by mkArtakMSFT** [comment]
I agree with @tstivers1990 that the behavior here is a bit confusion. However, we can do nothing about it. As @pranavkm has said, adding a log message would add very little value. So better to do nothing.

**Comment by mkArtakMSFT** [comment]
And one more comment - the confusion will go away in 3.0, when we'll make the 2.1 behavior with the Compat switch on as default.
