### ISSUE TITLE
Disable authentication redirects for ApiControllers

### ISSUE THREAD

**Issue by MrSmoke** [aspnet/Mvc#7980]
#### Is this a Bug or Feature request?:
Feature Request

#### Description of the problem:
For projects that use a mix of SPA and local API endpoints (aka `/api/values`), it currently looks like the best solution to avoid auth redirects on the API endpoints is to add some logic similar to:

```cs
options.Events = new OpenIdConnectEvents
{
    OnRedirectToIdentityProvider = context =>
    {
        if (context.Request.Path.StartsWithSegments("/api"))
        {
            if (context.Response.StatusCode == 200)
                context.Response.StatusCode = 401;

            context.HandleResponse();
        }

        return Task.CompletedTask;
    }
};
```

With the advent of the new `[ApiController]` attribute, could we somehow use this to check if the controller is an API controller and return 401 results instead of redirect results?

**Comment by pranavkm** [comment]
cc @javiercn

**Comment by pranavkm** [comment]
In terms of identifying if you're running in the context of an API Controller, we're going to rely on the ongoing dispatcher work. https://github.com/aspnet/Mvc/issues/7756#issuecomment-388916510 has some details on what this might look like. Closing this since we'd do the work for identifying this as part of https://github.com/aspnet/Mvc/issues/7756
