### ISSUE TITLE
Please add `Attributes` property to `ModelMetadata`.

### ISSUE THREAD

**Issue by alireza-salemian** [aspnet/Mvc#7988]
In many scenarios we use reflection and in Mvc.NetCore base class **_ModelMetadata_** is a good class for that models, but property Attributes is not exist in this type and its necessary cast to _**DefaultModelMetadata**_  to access it. 
Please move this property from **_DefaultModelMetadata_** to **_ModelMetadata_**.
ex:
`var property = modelMetadata.Properties
                .OfType<DefaultModelMetadata>()
                .FirstOrDefault(p => p.Attributes.PropertyAttributes.OfType<SelectOptionsValueMapAttribute>().Any() || p.Name == "Id");`

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @alireza-salemian.
@dougbu thoughts?

**Comment by dougbu** [comment]
@mkArtakMSFT `DefaultModelMetadata.Attributes` should have been `internal` because the attribute collection is not intended for use after instances are created. We shouldn't make that collection `public`.

@alireza-salemian if `SelectOptionsValueMapAttribute` is meaningful in your application, handle it in a registered `IMetadataDetailsProvider` implementation and add the information you need to `context.DisplayMetadata.AdditionalValues`. Then, use the newly-exposed data wherever it's needed.

**Comment by alireza-salemian** [comment]
@dougbu We use knockout in our projects. generate client js model from original c# model using Reflection and Custom Attributes.  every Validation attribute exposed to client model and many other attribute. if use IMetadataDetailsProvider then duplicate memory required for cache metadata and additional processing is done.

**Comment by mkArtakMSFT** [comment]
Hi @alireza-salemian.
we have no plans to expose the `DefaultModelMetadata.Attributes` property. The suggested behavior is our recommended solution.
