### ISSUE TITLE
ASP.NET Core apps fail to load *.Views.dll when running of a network share

### ISSUE THREAD

**Issue by artiomchi** [aspnet/Mvc#7999]
Seems to specifically affect apps compiled against .NET Framework 4.6.2.

I have an app behind an IIS ARR load balancer. The app code is hosted on a network share, and I have two servers pointing it's app pool to that location.

Starting with ASP.NET Core 2.1, the framework can now precompile the views and store them in `AppName.Views.dll`. The issue is, this assembly is loaded dynamically (as far as I can see) and ends up throwing a CAS Policy issue.

If I host this app on the local drive - everything works fine. If I remove the views.dll and add the view files +refs folder to enable view compilation - the app works fine as well.

My current solution is to add a `AppName.exe.config` file with the following contents:
```xml
<configuration>
  <runtime>
    <loadFromRemoteSources enabled="true"/>
  </runtime>
</configuration>
```

#### Is this a Bug or Feature request?:
Seems like a bug with the way the app loads the precompiled views, introduced in ASP.NET Core 2.1

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
I have a simple GitHub repo with the code - it's a simple ASP.NET Core app that targets .NET 4.6.2: https://github.com/artiomchi/SimpleAspNetCoreApp

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Using version 2.1.1. Can't use the metapackage, since I'm referencing .net framework.

I'm attaching the stdout log file that contains the full stack trace and the details:
[stdout_5780_20187216501.log](https://github.com/aspnet/Mvc/files/2156065/stdout_5780_20187216501.log)

**Comment by pranavkm** [comment]
I wasn't able to reproduce the error you're seeing when deployed to a network share. The documentation for the setting - https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element?view=netframework-4.7.2#notes - says that it shouldn't be required in .NET 4.5 or newer. 

* Since you are able to reproduce the error, is there an alternate `Load*` API that works here e.g. https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.unsafeloadfrom?view=netframework-4.7.2 or https://docs.microsoft.com/en-us/dotnet/api/system.reflection.assembly.load?view=netframework-4.7.2#System_Reflection_Assembly_Load_System_Byte___? If either of those methods work, we could consider using these in our code.

* The recommended "fix" is be to create a sandboxed `AppDomain` and use that to load the assembly. Seeing that none of the AppDomain setup APIs are available in `netstandard`, we would have to recommend carefully considering your use case and using the`loadFromRemoteSources` switch. If you are unable to use the switch, you could [disable build time view compilation](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1#properties) reverting to pre-2.1 behavior.

**Comment by artiomchi** [comment]
I'm sorry, I'm not sure what you expected me to test here...

Once I compile and publish the above app, it creates `SimpleAspNetCoreApp.exe` and `SimpleAspNetCoreApp.Views.dll` (amongst 230 other files) in the publish directory. If I decompile the exe, it has this attribute on it: 
```csharp
[assembly: RelatedAssembly("SimpleAspNetCoreApp.Views")]
```

You can see that this is being used here to load the assembly: [RelatedAssemblyAttribute.cs](https://github.com/aspnet/Mvc/blob/master/src/Microsoft.AspNetCore.Mvc.Core/ApplicationParts/RelatedAssemblyAttribute.cs)

It's not me that's calling `Assembly.LoadFile` - I don't have control over it.

**Comment by pranavkm** [comment]
My suggestion was to try doing this in your `Program.Main` before MVC gets to it. Regardless, we had a talk about this issue offline and our suggestions are

a) You could disable build time \ publish time compilation of Razor views. This should get you back to the pre 2.1 behavior. https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-2.1#properties has documentation on the flags you need to set.

b) We recommend considering updating your application to target .NET Core. `Assembly.LoadFile` on CoreCLR does not have any of the CAS-related issues that desktop has, so you're not going to run in to this if you retarget your application.
