### ISSUE TITLE
Random User.IsInRole result when UserRole changes

### ISSUE THREAD

**Issue by ans-ashkan** [aspnet/Mvc#8011]
#### Is this a Bug or Feature request?:
Bug

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):
Clone and Run this [project](https://github.com/ans-ashkan/AspNetCoreUserIsInRoleTest)
do the following in order:
```
http://localhost:5000/users/getall -> 200: ["test"]
http://localhost:5000/users/signin?username=test&password=123 -> 200
http://localhost:5000/users/isinrole?role=admin -> {"isInRole":false,"identityName":"test"}
http://localhost:5000/users/adduserrole?username=test&role=admin -> 200
http://localhost:5000/users/isinrole?role=admin -> {"isInRole":**random true or false**,"identityName":"test"}
http://localhost:5000/users/signout -> 200
http://localhost:5000/users/signin?username=test&password=123 -> 200
http://localhost:5000/users/isinrole?role=admin -> {"isInRole":true,"identityName":"test"}
```

#### Description of the problem:
I'm using asp.net core 2.1 with some default identity settings and every time a role is changed the user should re-login to see the role changes.
If I invalidate Identity on each request with the following settings, then roles should be updated but UserIsInRole returns random results.

```c#
services.Configure<SecurityStampValidatorOptions>(options =>
{
     options.ValidationInterval = TimeSpan.Zero;
});
```

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`:

Microsoft.AspNetCore.App 2.1.1

[SO question of this issue](https://stackoverflow.com/questions/51107346/using-user-isinrole-returns-random-result-when-userrole-changes)

**Comment by poke** [comment]
As I’ve found out, `UserManager.AddToRoleAsync` does not actually update the user’s security stamp, so the security stamp will not actually be invalidated. So this mechanism does not actually work for refreshing the login for the user on the basis of changed roles. The observed effect is still very interesting and I don’t really understand yet what is going on.

I’ve already been investigating this a bit, and looked at the browser requests more closely, and these are my findings so far:

The cookie will be kept for as long as the requests stay within the `ValidationInterval`. If we make multiple requests within that configured second, then only the first will have a `Set-Cookie` header, and the remaining ones will be kept. If we set the interval up to 5 seconds, we can make requests with the same identity for 5 seconds before we get a new `Set-Cookie` with an updated token.

By adding a `Claims = User.Claims.Select(c => new { c.Type, c.Value })` line to the output of the `IsInRole` action, I was able to see the exact claims that are part of the identity. As expected, the `SecurityStamp` stays the same on all requests, regardless of whether I do additional `Add/RemoveRole` calls to change the roles.

However, and now this is very interesting, the role claim is only ever included when the `ValidationInterval` kicks in and updates the cookie. So on every request that has a `Set-Cookie` header, I *can* see the role while on *all other* requests, the role is missing. Yes, it is missing even afterwards. So multiple browser requests may look like this:

```
REQ  Cookie: <cookie-1>
RES  InRole: false

REQ  Cookie: <cookie-1>
RES  InRole: true
     Set-Cookie: <cookie-2>

REQ  Cookie: <cookie-2>
RES  InRole: false

REQ  Cookie: <cookie-2>
RES  InRole: false

REQ  Cookie: <cookie-2>
RES  InRole: false

REQ  Cookie: <cookie-2>
RES  InRole: true
     Set-Cookie: <cookie-3>

REQ  Cookie: <cookie-3>
RES  InRole: false
```

This seems very odd to me. I *believe* what is going on here is that when the validation interval expires, a new identity is being created which loads the roles from the database and displays the updated state. This is then available in the controller and results in the set role claim. The cookie authentication handler however then just reissues the previous identity which does not have the updated roles.

It would be *correct* for the cookie handler to reuse the existing identity (since as per the security stamp validation, the identity is still valid), but the temporarily created identity (probably for validation purposes) should not leak outside of the validation process.

So that really would be a bug. And that probably also already exists in the wild already while just being less visible since the default validation interval is 30 minutes, making this appear only for one request within 30 minutes and as such very unlikely to be observed.

**Comment by poke** [comment]
/cc @HaoK (since this was basically your work in https://github.com/aspnet/Identity/pull/1351)

(and yes, Mvc is probably the wrong repo for this :/)

**Comment by PinpointTownes** [comment]
FYI, the fact the "cookies refresh" stuff doesn't work properly in 2.1 is due to a known bug: https://github.com/aspnet/Security/issues/1788

**Comment by khellang** [comment]
Looks like they're going with Option 1; https://github.com/aspnet/Security/pull/1795 :smile

**Comment by poke** [comment]
\*sigh\* Guess I am too late to the party :cry: 

Guess we can close this then @ans-ashkan. I have also answered your SO question with a better approach.

**Comment by ans-ashkan** [comment]
Thanks everyone, It's nice to have such awesome community (which also is super fast).

**Comment by HaoK** [comment]
I'm glad you came to the same conclusion I did for the fix @poke :)  But yeah this was a regression
