### ISSUE TITLE
Array 'errors' in ValidationProblemDetails not included when serialising to XML

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8221]
_From @dannyhaak on August 5, 2018 11:5_

When offering both 'application/problem+xml' and 'application/problem+json' as content types, it seems that the array with 'errors' is not serialised in XML, but it is in JSON.

When requesting with accept header set to 'application/problem+xml':
```
<?xml version="1.0" encoding="utf-8"?>
<ValidationProblemDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <Type>https://mimasu.nl/validation</Type>
    <Title>One or more validation errors occurred.</Title>
    <Status>400</Status>
    <Detail>Please refer to the errors property for additional details.</Detail>
    <Instance>/api/epcis_xml/v1/capture</Instance>
</ValidationProblemDetails>
```

When requesting with accept header set to 'application/problem+json':
```
{
    "errors": {
        "EpcisBody.EventList": [
            "The field EventList is invalid."
        ]
    },
    "type": "https://mimasu.nl/validation",
    "title": "One or more validation errors occurred.",
    "status": 400,
    "detail": "Please refer to the errors property for additional details.",
    "instance": "/api/epcis_xml/v1/capture"
}
```

This happens on the same controller, same method.

The version of `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All` is 2.1.2 and the output of `dotnet --info` is:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.301
 Commit:    59524873d6

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.1.301/

Host (useful for support):
  Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  2.1.301 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

_Copied from original issue: aspnet/Home#3388_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @dannyhaak.
@dougbu, can you please loom into this?

**Comment by dougbu** [comment]
@dannyhaak this looks like something is down-casting the `ValidationProblemDetails` to `ProblemDetails` before performing the XML serialization. But, I'm not seeing suspect code in aspnet/Mvc.

Could you please share your `Startup` class and the specific action? That'll help figure this out.

**Comment by dannyhaak** [comment]
@dougbu Thanks for your quick reply. Please find attached my Start-up class. The controller is very simple:
```
[HttpPost]
[Route("api/epcis_xml/v1/capture")]
[ProducesResponseType(200)]
[ProducesResponseType(typeof(ValidationProblemDetails), 400)]
[Consumes("application/xml")]
[Produces("application/xml", "application/problem+xml", "application/problem+json")]
public IActionResult Capture([FromBody]EpcisDocumentXml documentEvents)
{
    return new OkResult();
}
```

Curious whether you can find something.

[Startup.cs.zip](https://github.com/aspnet/Mvc/files/2279212/Startup.cs.zip)

**Comment by dougbu** [comment]
@dannyhaak no down-casts involved but the problem is pretty clear. Your `Startup` uses a hand-constructed setup similar to `MvcBuilder.AddXmlSerializerFormatters()`. `XmlSerializer` has a known inability to serialize or deserialize `IDictionary<TKey, TValue>` properties like the `ValidationProblemDetails.Errors` property. (MVC contains a workaround for all top-level `IEnumerable<>` models but that isn't invoked for properties.) Switch to using `XmlDataContractSerializer`s:
``` c#
services
    .AddMvc()
    .AddXmlDataContractSerializerFormatters()
    .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);
```

----

For more information, see the [documentation](https://docs.microsoft.com/en-ca/dotnet/api/system.xml.serialization.xmlserializer?view=netcore-2.1#overriding-default-serialization) for the `XmlSerializer` class. Note `Dictionary<TKey, TValue>` is an `ICollection<KeyValuePair<TKey, TValue>>` but lacks the `public KeyValuePair<TKey, TValue> this[int index] { get; set; }` property that `XmlSerializer` requires.

----

Separately, details of your setup weren't the issue here but we recommend calling the provided `IMvcBuilder` extension methods instead of doing custom setup. `AddXmlSerializerFormatters()`, `AddXmlDataContractSerializerFormatters()`, et cetera ensure the setup is complete. (Kind-of worked in this case because you were mainly missing `FormatterMappings` for `*.xml` retrievals and that wasn't relevant in your scenarios.)

**Comment by dougbu** [comment]
FYI I've relabeled this a `question`.

**Comment by dannyhaak** [comment]
@dougbu Thanks for the thorough explanation - and sorry for raising this as a bug. Unfortunately, I cannot use `XmlDataContractSerializer` for other reasons. I have created a work-around in which I extend ProblemDetails with a List of errors, fill it in `InvalidModelStateResponseFactory` and that seems to work fine for both XML and JSON. I am also using `AddXmlSerializerFormatters()` right now. The issue can be closed.
