### ISSUE TITLE
ApiController attribute - Enforcing 415 Unsupported Media Type with bad Content-Type

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8236]
_From @YouvalLabade on August 4, 2018 20:32_

With the attribute `[ApiController]` how to return a `415 Unsupported Media Type` if the `Content-Type` is incorrect or unsupported?

Should we do something like this ? 

```
services.Configure<ApiBehaviorOptions>(config =>
{
	config.InvalidModelStateResponseFactory = (actionContext) =>
	{
		var errors = actionContext.ModelState.Values.SelectMany(modelState => modelState.Errors);

		if(errors.Any(modelError => modelError?.Exception?.GetType() == typeof(UnsupportedContentTypeException)))
		{
			return new StatusCodeResult(StatusCodes.Status415UnsupportedMediaType);
		}

		return new BadRequestResult();
	};
});
```

_Copied from original issue: aspnet/Home#3387_

**Comment by pranavkm** [comment]
@Youuuuuuuuuuu that's a reasonable workaround for now. However it does seem like a bug that the framework does not correctly handle this for you. I'll try bringing this up for patch consideration.

**Comment by pranavkm** [comment]
cc @YouvalLabade

**Comment by pranavkm** [comment]
cc @rynowak \ @dougbu. 

The current instance of [`UnsupportedContentTypeFilter`](https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/UnsupportedContentTypeFilter.cs) isn't ordered and is consequently has an implicit order of `0`, `Scope = Global`. `ModelStateInvalidFilter` that `ApiBehaviorApplicationModelProvider` adds to actions is `Order = -2000, Scope = Action`. It runs prior to `UnsupportedContentTypeFilter` and ends up producing a `BadResult` instead of a `UnsupportedMediaTypeResult`.

We could

a) make `UnsupportedContentTypeFilter` ordered and give it a default order that is earlier than `ModelStateInvalidFilter`. Users could change it they are broken by it.
b) make `UnsupportedContentTypeFilter` ordered. Leave the global one as is (so it continues to have an order of 0). Add a second one in `ApiBehaviorApplicationModelProvider` if we're also adding `ModelStateInvalidFilter`. Limits the order change to `ApiController` instances that are the ones primarily affected by this issue.
c) Make `UnsupportedContentTypeFilter` a resource filter (in addition to being an `IActionFilter`)? Checking for a formatting failure seems like a resource filter concern. <-- Least patch-worthy solution.

**Comment by dougbu** [comment]
What other `StatusCode`-setting filters do we have? Don't want `ModelStateInvalidFilter` interfering with an `AuthorizeFilter` (for example) either. (Might imply this issue is better handled together with #7125.)

Another alternative would be to make `StatusCode`-setting filters more aware of each other. They could no-op when a "more specific" `StatusCode` may be set later or even invoke later setters before doing their own work. Throwing this out but likely this is too fragile and complicated to be worthwhile; it also introduces an implicit ordering that confusingly overrides the usual `Order`.

Whatever the case, I agree a filter that sets `StatusCode` to something fairly generic like `BadRequest` should not supercede one that sets `StatusCode` to `UnsupportedContentType`, `MethodNotAllowed` or `ImATeaPot`.

**Comment by rynowak** [comment]
I'm not sure that c) is even valid. A resource filter would run before model binding, so we wouldn't be able to see the error.

I'm in favor of a) because it's the simplest to reason about.
