### ISSUE TITLE
If exception occurs in AuthorizationHandler then ExceptionFilter doesn't catch it

### ISSUE THREAD

**Issue by abatishchev** [aspnet/Mvc#8259]
#### Is this a Bug or Feature request?:

Bug or by design?

#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

```c#
public override void ConfigureServices(IServiceCollection services)
{
    services.AddMvc(options =>
        options.Filters.Add<ResponseStatusCodeFilter>())
            .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

    services.AddAuthorization(options =>
        options.AddPolicy("Usage", policy => policy.Requirements.Add(new UsageAuthorizationRequirement())));

    services.AddSingleton<IAuthorizationHandler, UsageAuthorizationHandler>();
}

class UsageAuthorizationRequirement : IAuthorizationRequirement { }

[Authorize(Policy = "Usage")]
[ApiController]
class UsageController : ControllerBase { }

class UsageAuthorizationHandler : AuthorizationHandler<UsageAuthorizationRequirement>
{
    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, UsageAuthorizationRequirement requirement)
    {
       throw new UsageNotFoundException();
    }
}

class ResponseStatusCodeFilter : ExceptionFilterAttribute
{
    public override void OnException(ExceptionContext context)
    {
        switch (context.Exception)
        {
            case UsageNotFoundException usageNotFoundException:
            {
                context.HttpContext.Response.StatusCode = (int)HttpStatusCode.NotFound;
                break;
            }
        }
    }
}
```

#### Description of the problem:

I have an authorization handler that might throw an exception. By having the exception filter preceding the authorization filter, I would expect the exception to be cough by the exception filter but this doesn't happen. Is is an incorrect assumption? If it is, what should be then the apporach for global exception handling? I'm using API controllers, no views, if that matters.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 

```xml
<PackageReference Include="Microsoft.AspNetCore" Version="2.1.2" />
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
```

**Comment by khellang** [comment]
> what should be then the apporach for global exception handling?

IMO, that should always be middleware outside MVC. See https://codeopinion.com/http-api-problem-details-in-asp-net-core/

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @abatishchev.
The behavior you observe is by design. The image in the following docs article shows the order in which different types of filters are executed: https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1
As you can see, the Authorization filters are executed well in advance from Exception filters, hence the Exception filters have no chance to catch those exceptions.
As @khellang has pointed out, the proven way to catch any exception would be to register a custom middleware in the beginning of the stack.

**Comment by ATLSAPI** [comment]
Actually, we had a similar issue, although not in middleware but in our ViewComponents. 
We registered a global exception filter, and as excepted, exceptions thrown within the controller were caught, but those thrown in the ViewComponent where not caught and bubbled up. Is that also by design? Are ViewComponents not executed within MVC? Or is this a genuine issue that is known/needs to be raised with the relevant code/stack trace?

**Comment by pranavkm** [comment]
Here's the filter execution pipeline - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-2.1#filter-types. Exception filters attempt to capture errors before a result starts executing - the intent is that once you write to the response, MVC won't be able to recover from it and produce a different action. The recommendation is to use the [exception handler middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/error-handling?view=aspnetcore-2.1) to handle these.

**Comment by ATLSAPI** [comment]
@pranavkm Please, could you reply to the above? Just so I know if its a genuine problem or not. Thanks

**Comment by pranavkm** [comment]
> So it is logical to assume that any exception thrown within ViewComponents should be caught by the exception filter.

That wouldn't be the case. Exception filters rely on the stage of execution i.e. has the action finished executing and the result is being executed, and not on whether a response has been written. Like you said, that would be a very inconsistent experience.
