### ISSUE TITLE
Different binding Data from JSON to Controller in .NET core API and Web API 2

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8300]
_From @LeDucThang on August 14, 2018 5:39_

# Issue Title

Different binding Data from JSON to Controller in .NET core API and Web API 2

# General
compare between API in .NET core 2.1 and Web API 2 in .NET Framework 4.6

With .NET core, i used this configuration in Startup file

```c#
services.AddMvc(options =>
            {
                options.Filters.Add(new AuthenticationFilter(Configuration, JWTHandler));
            }).AddJsonOptions(options =>
            {
                options.SerializerSettings.Converters.Add(new Newtonsoft.Json.Converters.StringEnumConverter());
                options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                options.SerializerSettings.DefaultValueHandling = DefaultValueHandling.Populate;
            });
```

With .NET 4.6, i use default template Web API 2

My DTO:

```c#
public class CarrierEntity : BaseEntity
    {
        public Guid Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public CarrierEntity():base() { }
        public CarrierEntity(Carrier Carrier, params object[] args) :base(Carrier) {}
    }
```

My Controller:

```c#
[Route("api/Carriers")]
public class CarrierController : CommonController
{
	private ICarrierService CarrierService;
	public CarrierController(ICarrierService CarrierService)
	{
		this.CarrierService = CarrierService;
	}
	[Route(""), HttpPost]
	public CarrierEntity Create([FromBody]CarrierEntity CarrierEntity)
	{
		return CarrierService.Create(EmployeeEntity, CarrierEntity);
	}
}
```

I use this json for 2 case 

```json
{
   "Code":"ABC",
   "Name":"ABC"
}
```

With .NET full, the mapped object is

```json
{
   "Id": "00000000-0000-0000-0000-000000000000",
  "Code":"ABC",
   "Name":"ABC"
   "IsActive":false
}
```

With .NET core, the controller cannot bind json to CarrierEntity object. 
But if i use json like bottom, my .net core web app can bind json to CarrierEntity object.

```json
{
   "Id": "00000000-0000-0000-0000-000000000000",
  "Code":"ABC",
   "Name":"ABC"
   "IsActive":false
} 
```

My question is which configuration can make .net core web app binding like old framework web api 2

_Copied from original issue: dotnet/core#1858_

**Comment by mkArtakMSFT** [comment]
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
> With .NET core, the controller cannot bind json to `CarrierEntity` object.

@LeDucThang please clarify this statement. For example, is the `CarrierService` value non-`null` but all properties uninitialized? Does the `ModelState` include errors?

I'm also wondering whether the difference between ASP.NET MVC and ASP.NET Core MVC is due to different versions of Json.NET. Please check if using the latest Newtonsoft.Json package (v11.0.2) in both makes the behaviour consistent.

If differences remain, please provide us with two minimal repro projects that illustrate the inconsistency, preferably hosted in a GitHub repo. That'll help avoid me testing different scenarios than your exact case or speculating about `BaseEntity` and `CommonController`.

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Comment by LeDucThang** [comment]
Dear mkArtakMSFT  and dougbu
Last week, i was too busy and could not response you. I give you my repository with 4 case which compared between WebAPI2 and CoreAPI in TestAPI project

https://github.com/LeDucThang/EShop

the main difference is : WebAPI recognize null to DefaultValue and CoreAPI cannot parse json to entity object

**Comment by dougbu** [comment]
@LeDucThang the difference here goes away if you update the actions to check `ModelState.IsValid`:
``` c#
if (!ModelState.IsValid)
{
    return BadRequest(ModelState);
}
```
In both ASP.NET Core MVC and ASP.NET Web API errors are reported in your tests. In the Core case, the response is
```
"{\"Time\":[\"Error converting value {null} to type 'System.DateTime'. Path 'Time', line 1, position 38.\"]}"
```
And for non-Core, the same error is serialized as
```
"{\"Message\":\"The request is invalid.\",\"ModelState\":{\"CarrierEntity.Time\":[\"Error converting value {null} to type 'System.DateTime'. Path 'Time', line 1, position 38.\"]}}"
```

With respect to the `null` parameter value, we made an intentional change between Web API and ASP.NET Core MVC to be more consistent about deserialization errors. The model is not bound when the request is invalid.

**Comment by LeDucThang** [comment]
i understood. thank you very much. i will change my project with your suggestion
