### ISSUE TITLE
dotnet core MVC application can not display Global Resource in the browser  when deploy to the  Docker Container

### ISSUE THREAD

**Issue by Benknightdark** [aspnet/Mvc#8306]
Hey Guys, I publish a Dotnet Core MVC application , and Deploy it to the Docker Container , but  it can not disply the global resources in the browser.

But If I publish the application to the windows or linux os , the global resources can  be displayed in the browser . 

I'm so confused  , is someone know how to fix this problem

dotnet core info in my computer 
![image](https://user-images.githubusercontent.com/5799487/44453629-1b348a00-a62c-11e8-90ff-61818fd42a26.png)
my dockerfile
![image](https://user-images.githubusercontent.com/5799487/44453666-37382b80-a62c-11e8-8ba4-cbb5dbf20f5e.png)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @Benknightdark.
By `global resources` do you mean locatization files (`resx` files)?

**Comment by Benknightdark** [comment]
Yes. I use resx files

**Comment by Benknightdark** [comment]
hello, @mkArtakMSFT , here is my source code Repo url
https://github.com/Benknightdark/DotnetCoreMVC-GlobalResource-test
You can try it , thanks a lot

**Comment by mkArtakMSFT** [comment]
@javiercn, can you please look into this? Thanks!

**Comment by javiercn** [comment]
@mkArtakMSFT I think @ryanbrandenburg would be a better choice to look into this one. I'm not familiar at all with localization.

**Comment by ryanbrandenburg** [comment]
The problem here isn't that you're deploying it into Docker, it's that you're deploying it into Ubuntu. The values of `System.Globalization.CultureInfo` are driven by the operating system, and even the "major" OS's don't agree on the locale codes for certain languages. The `zh` family of languages is an example of such disagreement. On Windows your values of zh-TW and zh-CN are correct, but on Ubuntu the *same languages* have the locale codes of zh-Hant-TW and zh-Hans-CN.

This leaves you with two options:
1. Do your localization work and deployments in one OS family. Both Windows or both Ubuntu, and select the locale code appropriate to that OS.
2. Use #ifdefs in your Startup.cs to select the appropriate locale code for your OS and have a pre-build task which copies differing language files so that they're available (ie you have Resource.zh-TW.resx, and make a copy of it named Resource.zh-Hant-TW.resx in the same folder).

I [modified your project](https://github.com/ryanbrandenburg/DotnetCoreMVC-GlobalResource-test/tree/rybrande/Adjust) to both simplify things a bit and demonstrate what an Ubuntu compatible localization looks like.

That should cover it, but if you still have trouble we can re-open the issue.

**Comment by Benknightdark** [comment]
@ryanbrandenburg , thanks for your help
