### ISSUE TITLE
taghelpers not working

### ISSUE THREAD

**Issue by jkotas** [aspnet/Mvc#8308]
_From @dejandjenic on August 22, 2018 13:58_

taghelpers not working correctly if project is published with lower case format of file

e.g.
project exists and its name is MYPROJ.csproj at c:\test

if published with command

dotnet publish "c:\test\myproj.csproj" -o "c:\testpub\"

dll will be created and tag helpers will not work. Generated Namespace is the same in both cases but [assembly: AssemblyTitle("myproj")] is taken from input parametar instead from csproj file.

_Copied from original issue: dotnet/coreclr#19600_

**Comment by NTaylorMullen** [comment]
@jkotas I'm unable to reproduce your issue. For example the built-in & custom TagHelpers work after publishing with lower case for me:

![image](https://user-images.githubusercontent.com/2008729/44483527-2d98ce80-a600-11e8-82a1-ab830b05b2eb.png)

Could you provide a repro app?

**Comment by jkotas** [comment]
@NTaylorMullen This issue was reported by @dejandjenic . I just moved it to the right repo.

**Comment by NTaylorMullen** [comment]
@jkotas Ahh, my apologies, read too quickly 😄, edited my above comment.

**Comment by dejandjenic** [comment]
Do you need code to reproduce issue

**Comment by NTaylorMullen** [comment]
A project that I could publish would be ideal.

**Comment by dejandjenic** [comment]
i have uploaded source code with steps to reproduce issue and my reproduced binaries
[taghelpers.zip](https://github.com/aspnet/Mvc/files/2311877/taghelpers.zip)

hope this will help

**Comment by NTaylorMullen** [comment]
Thanks @dejandjenic. The thing that I wasn't doing correctly before was not passing in the full path in lower case to the .csproj when I published (i was passing in the parent directory).

The reason why this ends up failing is because we read `@addTagHelper` statements and require that the assembly name provided in `@addTagHelper` [case sensitively matches](https://github.com/aspnet/Razor/blob/ee6f94dfd5141f3342d411ff0344d14870fd5332/src/Microsoft.AspNetCore.Razor.Language/DefaultRazorTagHelperBinderPhase.cs#L79). When you provide the project file in lower case to `dotnet publish` it ends up generating the assembly matching the original project file path provided casing instead of the files actual casing.

I'm curious, @livarcocc do you happen to know why publish uses the casing of the project file path provided rather than the project file's actual casing?

**Comment by NTaylorMullen** [comment]
> should @addTagHelper use namespace rather than assembly name

That'd be a massive breaking change if it did sadly.

**Comment by livarcocc** [comment]
@peterhuene to take a look at this.

**Comment by peterhuene** [comment]
As far as I know, there is no portable method for getting the actual case of a path on case insensitive file systems.

Still, the project file is being passed to MSBuild as an option, so I'd expect this to be an MSBuild issue to address, otherwise you'd still be able to reproduce if you bypass dotnet and use MSbuild directly.

**Comment by NTaylorMullen** [comment]
@peterhuene do you know a good MSBuild contact to reach out to?

**Comment by peterhuene** [comment]
@rainersigwald would be the one.  I edited the comment since GitHub doesn't do mention completions for mobile version.

**Comment by rainersigwald** [comment]
MSBuild just tries to read whatever's passed in, and on a case-insensitive filesystem that works. But our in-memory representation comes from the original string.

This is more relevant now, since the SDK defaults AssemblyName to `$(MSBuildProjectName)` https://github.com/dotnet/sdk/blob/ab2176b3447e3e7820b5a340408110b6d498f907/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props#L34.

We can look into normalizing to case-on-disk, but I don't know how hard that will be. Filed Microsoft/msbuild#3665 to look into it.

**Comment by NTaylorMullen** [comment]
Ah I see. Thanks everyone for the insight! @dejandjenic feel free to watch Microsoft/msbuild#3665 for updates 😄
