### ISSUE TITLE
XmlSerializerInputFormatter with iso-8859-1 encoding

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8346]
_From @rackriili on Monday, 27 August 2018 20:59:13_

Hi,
I am implementing an external interface with WebApi Core 2.0 and I must create a service that receives an XML by a Post action.

If the XML has the default encoding (UTF-8) it parse correctly to my class.
If the encoding is "iso-8859-1" the class is set to null. Unfortunatly this is the encoding.

_My controller:_
```
[HttpPost("[action]")]
public async Task<IActionResult> Notify([FromBody] Person person)
{
...
}
```

_In the startup I add the iso-8859-1 encoding to the formatter_
```
public void ConfigureServices(IServiceCollection services)
{
...
XmlSerializerInputFormatter xmlSerializerInputFormatter = new XmlSerializerInputFormatter();
xmlSerializerInputFormatter.SupportedEncodings.Add(Encoding.GetEncoding("iso-8859-1"));
services.AddMvc(options => options.InputFormatters.Add(xmlSerializerInputFormatter));
}
```

_This XML parse correctly:_
```
<?xml version="1.0" ?>
<person>
	<name>Robert</name>
	<age>30</age>
</person>
```

_This XML parse correctly too:_
```
<?xml version="1.0" encoding="utf-8" ?>
<person>
	<name>Robert</name>
	<age>30</age>
</person>
```

_But this one doesn't work:_
```
<?xml version="1.0" encoding="iso-8859-1" ?>
<person>
	<name>Robert</name>
	<age>30</age>
</person>
```
Any ideas?
Thanks

_Copied from original issue: aspnet/Home#3467_

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @rackriili.
Thank you for filing this issue. In order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by rackriili** [comment]
First of all, thank you very much!

@mkArtakMSFT, I attach a minimalist repro project that illustrates the problem:
[XmlSerializerInputFormatterTest.zip](https://github.com/aspnet/Mvc/files/2332755/XmlSerializerInputFormatterTest.zip)

I call the service from Postman. This is the code snippet generated for curl.
```
curl -X POST \
http: // localhost: 2116 / api / persons / notify \
-H 'Cache-Control: no-cache' \
-H 'Content-Type: text / xml' \
-H 'Postman-Token: 6ff4f6e0-2e96-4846-9c23-576f65554ef7' \
-d '<? xml version = "1.0" encoding = "iso-8859-1"?>
<person>
<name> Robert </ name>
<age> 30 </ age>
</ person> '
```
I get the same error if I use 'Content-Type: application / xml'


> The ModelState error is:

_The encoding in the declaration 'iso-8859-1' does not match the encoding of the document 'utf-8'._
But I don't know how fix it.
My Api is call by a legacy system, I can't change the way it call me.

**Comment by AlexejTimonin** [comment]
You can force the input formatter to always use ISO-8859-1 encoding. This is achieved by clearing all of the supported encodings before adding your encoding. Like this:

````c#
XmlSerializerInputFormatter xmlSerializerInputFormatter = new XmlSerializerInputFormatter();
xmlSerializerInputFormatter.SupportedEncondings.Clear();
xmlSerializerInputFormatter.SupportedEncodings.Add(Encoding.GetEncoding("iso-8859-1"));
services.AddMvc(options => options.InputFormatters.Add(xmlSerializerInputFormatter));
````

Now the ISO-8859-1 encoding will be used. But it does not end here. You'll receive an error in the model state stating that the XML encoding is not supported. This is because `XmlSerializerInputFormatter` uses 
`XmlDictionaryReader.CreateTextReader` which does not support the specified encoding.

The starting point for the workaround is to create you own custom input formatter that derives from `XmlSerializerInputFormatter` and override `ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)`. There create a `StreamReader` instead of `XmlDictionaryReader.CreateTextReader`.

This is an example of such custom input formatter (NOT PRODUCTION READY).
````c#
    public class CustomInputFormatter : XmlSerializerInputFormatter
    {
        public override Task<InputFormatterResult> ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
        {
            using (var reader = new StreamReader(new NonDisposableStream(context.HttpContext.Request.Body), encoding))
            {
                var serializer = GetCachedSerializer(context.ModelType);
                var result = serializer.Deserialize(reader);
                return InputFormatterResult.SuccessAsync(result);
            }
        }
    }
````

Now replace your startup with this:
````c#
var CustomXmlSerializerInputFormatter = new CustomInputFormatter();
CustomXmlSerializerInputFormatter.SupportedEncodings.Clear();
CustomXmlSerializerInputFormatter.SupportedEncodings.Add(Encoding.GetEncoding("ISO-8859-1"));
services.AddMvc(options => options.InputFormatters.Add(CustomXmlSerializerInputFormatter));
````

This will at least deserializer your Person XML. I'll let people that are smarter than me in this thread to point out in what ways my solution can blow up on you.

**Comment by ExileLee** [comment]
@AlexejTimonin 

Save my day!

thanks!

**Comment by dougbu** [comment]
Thank you all for this discussion. We're closing this issue as the questions asked here have been answered.
