### ISSUE TITLE
Parameter default value is invalid

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8357]
_From @netnr on Friday, 24 August 2018 23:47:54_

ASP.NET Core

![图片说明](https://uploadbeta.com/share-image/fU4)

Parameter "sort" default value is invalid

_Copied from original issue: aspnet/Home#3458_

**Comment by Eilon** [comment]
_From @Eilon on Monday, 27 August 2018 16:51:17_

@netnr can you provide more info about this issue and how to reproduce it? What routes does the app have, and what is the request URL?

**Comment by Eilon** [comment]
_From @netnr on Monday, 27 August 2018 23:09:14_

Perhaps my idea is that the weight of the variable default should be higher than "NULL"

**Comment by Eilon** [comment]
_From @Eilon on Tuesday, 28 August 2018 17:25:35_

@netnr we'll need more info to be able to investigate this. Can you upload a sample app to a GitHub repo so that we can inspect the code?

**Comment by Eilon** [comment]
_From @netnr on Tuesday, 28 August 2018 22:35:22_

https://github.com/netnr/test

**Comment by dougbu** [comment]
@netnr the test application is behaving as expected because MVC honours the C# semantics of optional arguments. The `sort` parameter's default value is used only when *nothing* is submitted for a parameter (your "no parameters" case), not when the submitted value is bound to `null` (your `null` and empty string cases).

For more information, please see https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/named-and-optional-arguments

**Comment by netnr** [comment]
```
Request URL:https://XXX/home/ajax?sort=
Request Method:GET
```
 **Console** 
```
method:GET   parameter-type:empty   value:isnull
```
Should not be "NULL" but empty

**Comment by netnr** [comment]
![717f0de210](https://netnr.gitee.io/gs/2018/08/30/717f0de210.png)

**Comment by dougbu** [comment]
@netnr that's also by design. There's a `ModelMetadata.ConvertEmptyStringToNull` property which defaults to `true`. If you prefer this didn't happen, add `[DisplayFormat(ConvertEmptyStringToNull = false)]` to your parameter.
