### ISSUE TITLE
Timestamp passed via RedirectToAction loses precision in target action

### ISSUE THREAD

**Issue by Eilon** [aspnet/Mvc#8383]
_From @martinmikulka on Monday, 03 September 2018 13:05:33_

Hello, I am facing a problem when calling RedirectToAction() method and passing a timestamp via parameter:

```
public IActionResult ActionOne()
{
   var timestamp = new DateTimeOffset(2018,7,25,14,16,18,120,new TimeSpan());
   return RedirectToAction("ActionTwo", new { Timestamp = timestamp });
}

public IActionResult ActionTwo(DateTimeOffset timestamp)
{
   ...
}
```

When I dump the timestamp variable inside the ActionOne:
Millisecond [int]: 120
Ticks [long]: 636681249781200000

When I dump the timestamp variable inside the ActionTwo:
Millisecond [int]: 0
Ticks [long]: 636681249780000000

The target variable has lost miliseconds precision.
Do I have to pass the timestamp in some different way or is it a bug?

Thanks, Martin

_Copied from original issue: aspnet/Home#3488_

**Comment by Eilon** [comment]
_From @martinmikulka on Tuesday, 04 September 2018 06:27:08_

I solved this problem by passing the value in milliseconds [long] instead of DateTimeOffset.

```
public IActionResult ActionOne()
{
   var timestamp = new DateTimeOffset(2018,7,25,14,16,18,120,new TimeSpan());
   return RedirectToAction("ActionTwo", new { Timestamp = timestamp.ToUnixTimeMilliseconds() });
}

public IActionResult ActionTwo(long timestamp)
{
   var ts = DateTimeOffset.FromUnixTimeMilliseconds(timestamp);
   ...
}
```

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @martinmikulka. Glad you've found a workaround.
@dougbu, can you please find out the reason for the precision to be lost? Thanks!

**Comment by dougbu** [comment]
@mkArtakMSFT the precision is lost because Routing uses `Convert.ToString(...)` and that method is not guaranteed to preserve precision. The target URI ends with the encoded form of `?Timestamp=07/25/2018 14:16:18 +00:00`. See [`TemplateBinder`](https://github.com/aspnet/Routing/blob/f9f80e3d80d14684ed2c77b1913cf4bd3c5a4692/src/Microsoft.AspNetCore.Routing/Template/TemplateBinder.cs#L278) for example.

This code provides a reasonable fidelity and special-casing the datatypes that may lose precision would cause back-compatibility problems as well as maintenance headaches. Suggest we not make changes in Routing and instead confirm the documentation is sufficient.

@martinmikulka another workaround would be to create the `string` in `ActionOne()` e.g. `new { Timestamp = timestamp.ToString("o") }`.

**Comment by mkArtakMSFT** [comment]
Thanks @dougbu.
@martinmikulka, per @dougbu's response the behavior you're observing is by design. Consider using the suggested workaround of passing the parameter as string instead.

**Comment by martinmikulka** [comment]
Ok guys, thank you for your time. m.
