### ISSUE TITLE
ViewComponents' InvokeAsync() not found if in base class (migration from 1.1.x to 2.1.x)

### ISSUE THREAD

**Issue by drauch** [aspnet/Mvc#8397]
#### Steps to reproduce (preferably a link to a GitHub repo with a repro project):

* Use a base class for a ViewComponent
* Implement the InvokeAsync in the base class (and call some abstract template method of the derived class)
* Use the ViewComponent
* Start the application
* Observe the following error:

> Could not find an 'Invoke' or 'InvokeAsync' method for the view component 'MyWebApp.ViewComponents.MyDerivedViewComponent'.

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 2.1

This is preventing us from migrating to 2.1.x - please help us soon!

**Comment by mkArtakMSFT** [comment]
@drauch, in order for us to investigate this issue, please provide a minimalistic repro project that illustrates the problem.

**Comment by drauch** [comment]
@mkArtakMSFT : Here you go, just execute the web app: https://www.dropbox.com/s/w52iqxoqsd6yne0/ViewComponentsInvokeAsyncNotFoundInBaseClass.zip?dl=0
(it's basically the web app template with a view component added)

**Comment by pranavkm** [comment]
@drauch looks like an issue with the Razor Sdk. We're fixing this in 2.2.0. For 2.1.0, there isn't a straightforward solution

1) You could avoid using inheritance in your view components
2) You could turn off Razor Sdk `RazorCompileOnBuild=false`, `RazorCompileOnPublish=false`

Fixed in https://github.com/aspnet/Razor/commit/fc86cc3ca1101d0503392a902d4336fa20f575f6

**Comment by drauch** [comment]
We've now copy & pasted an `InvokeAsync` which calls `base.ActuallyInvokeAsync()` into each view component. That's a reasonable workaround for the time.

Thanks for engaging & fixing this!
