### ISSUE TITLE
 Bug: ExpandViewLocations() resolving in parent folder

### ISSUE THREAD

**Issue by seriouz** [aspnet/Mvc#8443]
#### Is this a Bug or Feature request?:
Bug

#### Description of the problem:
In-Short: I cannot use `/../` in a custom IViewLocationExpander in a viewLocation. The file on the disk won't be resolved.

https://github.com/seriouz/DelocatedRazorViews/blob/master/src/ExtractedViewLocationExpander.cs#L14

Example App: https://github.com/seriouz/DelocatedRazorViews

#### Version of `Microsoft.AspNetCore.Mvc` or `Microsoft.AspNetCore.App` or `Microsoft.AspNetCore.All`: 2.1.2

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @seriouz.
@dougbu, can you please look into this? Thanks!

**Comment by dougbu** [comment]
@seriouz this is by design. For security reasons, web sites cannot reach outside their content root. Put another way, the `PhysicalFileProvider` constrains what is allowed and MVC can't override that.

Suggest setting the site's content root further up i.e. to a folder that contains both the web site and the extracted views.

**Comment by seriouz** [comment]
@dougbu Yeah okay. But this is only for the design time on my developer machine.

I have extracted my views into a own reusable Razor UI class library. Then i added this project as a <ProjectReference>. Everything is working fine, i see the **precompiled views** etc... But now i have the problem that the designtime is very hard because for every change on a cshtml file i have to recompile the class lib and restart the parent project. This is very annoying!
