### ISSUE TITLE
dynamic page cache bug?

### ISSUE THREAD

**Issue by TimRowe** [aspnet/Mvc#8454]
I build a mvc page (url is /home/time ) to show current time.
The code in the view is like below
`<p>@(DateTime.Now.ToLongTimeString())</p>`

But when I open a new tab in explorer (disable cache is not set), it would show the same time.
Just like the page is cached, but I can see it has sent request to the webserver.The time will change when i press the explorer reflesh button.

Any one can explain it?
Here is my test project. 
And This problem will raised only in remote server deploy(not localhost debug).
[WebApplication6.zip](https://github.com/aspnet/Mvc/files/2381635/WebApplication6.zip)

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @TimRowe.
@dougbu, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@TimRowe, have you tried to remote debug your app? Sounds like there is some kind of caching on your remote server.

**Comment by dougbu** [comment]
@TimRowe your repro Zip file contains a project that does not use `DateTime.Now` at all. Nor does it contain an action for `/home/time`. In order for us to investigate this issue, could you please provide us with a minimal repro project that illustrates the problem, preferably hosted in a GitHub repo?

Separately, what led you to the idea that MVC and not the remote hosting environment (or a proxy in front of it) is caching? Which environment are you using when deployed remotely?

**Comment by TimRowe** [comment]
@dougbu sorry, the zip is not the right, i will upload again soon.
today, I try again. I find the explorer cache the page. when I open a new tab, it load from the cache.
In my impression, dynamic pages will not be cached, is it right?

**Comment by TimRowe** [comment]
Any progress？

**Comment by dougbu** [comment]
@TimRowe I'm not seeing the behaviour you've described. The issue may be my confusion around how to reproduce it. Could you please provide more details about exactly when the problem occurs. For example, are you publishing before testing locally or specifying arguments when executing `dotnet run` et cetera?

In particular, I'm not seeing the server include `Cache-Control`, `Proxy-Connection`, or `Via` headers in the response no matter how I deploy it (Azure App Service, IIS Express from VS, standalone from VS, standalone from command line). Chrome occasionally sends a `Cache-Control: max-age=0` header when some time has passed (but that should invalidate the cache) and F12 / Network usually reports the response status as `Status Code: 200 OK (from disk cache)` which doesn't seem to mean much (because the time is updated).

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as there's been no response and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
