### ISSUE TITLE
Feedback about ASP.NET Core 2.2 preview web application template

### ISSUE THREAD

**Issue by pekspro** [aspnet/Mvc#8465]
#### Is this a Bug or Feature request?:
Feature request

#### Description of the problem:
I’ve tried the preview of ASP.NET Core 2.2 and created a new web application. I do like that it based on Bootstrap 4. But I find that the template is be too simple. I would like to see some sample pages where the most common scenarios are covered on a basic level. For instance:

* A page showing how to create an object, with post and validation. Using a real database is maybe too complicated but storing stuff in a static list will show the concept.
* A page where to search for objects, with a get request.
* A page using ajax against an API, maybe using TypeScript.
* A page with some common BootStrap controls and responsive design.
* A page describing how to change the top menu.
* A page showing how to work with localization.
* A page showing how LibMan works. Or at least having a LibMan-file in the project and reference to some documentation.

I’m not asking for a complete tutorial. But I do think it would be useful for beginners (and developers like me that never learn :-) to have a better starting point in the template. It could be a bit overwhelming to learn web development, a good template could make that easier.

I know that a lot of developers wants the template to be as simple as possible. But I think it’s better that experienced developers learn how to delete pages than that beginners need to write pages from scratch :-) If most sample code is isolated to one folder it doesn’t need to be that bad.

**Comment by mkArtakMSFT** [comment]
Thanks for your feedback, @pekspro.
@danroth27, I'll leave this to you to process.

**Comment by danroth27** [comment]
@pekspro Thanks for this feedback! It's a tricky balance to figure out how much sample code to include in the project templates so that beginners have an easy way to get started, but more experienced devs don't get frustrated with having to delete a bunch of code every time they create a project. Over the years we've heard consistent feedback the customers want a simpler template with less noise, so that's the direction we decided to go with for this release. But, we do understand that not everyone feels this way and hearing your opinion helps us get a more complete picture of what developers want.

For many of the scenarios you listed above, it sounds like you are looking for sample apps to help you learn different aspects of the framework. For samples I would recommend looking at the various [tutorials](https://docs.microsoft.com/en-us/aspnet/core/tutorials/) and topics in the docs.

**Comment by pekspro** [comment]
No problem, I just wanted to share my thoughts :-) Thanks for a quick reply!
