### ISSUE TITLE
API for specifying an IOutboundParameterTransformer needs some polish

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Mvc#8612]
I used the code here - https://github.com/aspnet/Mvc/blob/9daf5ff7a4e092b3a84c060c44148d7d5d40b5c3/test/WebSites/RoutingWebSite/Startup.cs#L25-L27 - as a template for configuring a transformer for my application. I would have expected specifying the transformer to be a property on `SelectorModel`. If that's difficult due to the design, maybe it needs a first class extension - `ActionModel.SetOutboundParameterTransformer`. Additionally, I tried setting the property value to a a type:

`action.Properties[typeof(IOutboundParameterTransformer)] = typeof(UpperCaseTransformer);` 

and it no-oped without an error or any hint on what was incorrect.

**Comment by pranavkm** [comment]
Also just happened to notice this - https://github.com/aspnet/Mvc/blob/release/2.2/src/Microsoft.AspNetCore.Mvc.RazorPages/ApplicationModels/PageRouteTransformerConvention.cs. Is there a reason there isn't an equivalent for controller actions?

**Comment by mkArtakMSFT** [comment]
@glennc , @JamesNK, @rynowak leaving this up to you to decide what should happen here.

**Comment by JamesNK** [comment]
> `ControllerRouteTokenTransformerConvention`
> Is there a reason there isn't an equivalent for controller actions?

`ControllerRouteTokenTransformerConvention `is a custom type I put together for the test site because we didn't want to test all attribute routes in the application with a transformer, just a small subset.

This is the type that the user would use - https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-2.2#use-a-parameter-transformer-to-customize-token-replacement

Setting the transformer as a property is supposed to be an internal thing that only RouteTokenTransformerConvention and MVC know about. Do you still think that should change? // @rynowak

**Comment by mkArtakMSFT** [comment]
@JamesNK, should this be closed then?

**Comment by JamesNK** [comment]
Sure. Reopen @rynowak @pranavkm if you think there is something to do here.
